import type { ServiceCategory, ServiceCategorySlug } from "./types";

export const CATEGORIES: ServiceCategory[] = [
  {
    slug: "identity-documents",
    name: "Identity & Documents",
    shortName: "Identity",
    description: "Aadhaar, PAN, Voter ID, Passport, Driving License and other national identity services.",
    icon: "IdCard",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "UIDAI / NSDL / MEA / ECI / MoRTH",
  },
  {
    slug: "income-tax-gst",
    name: "Income Tax & GST",
    shortName: "Tax & GST",
    description: "Income Tax Return filing, GST registration & returns, TDS, refunds and compliance.",
    icon: "ReceiptIndianRupee",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "CBDT / CBIC",
  },
  {
    slug: "citizenship-immigration",
    name: "Citizenship & Immigration",
    shortName: "Citizenship",
    description: "Passport, Visa, OCI, FRRO registration and citizenship services.",
    icon: "Plane",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "Ministry of External Affairs / MEA",
  },
  {
    slug: "land-property",
    name: "Land & Property",
    shortName: "Land & Property",
    description: "Land records (Bhulekh), mutation, property registration, encumbrance certificates.",
    icon: "LandPlot",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "State Revenue Departments",
  },
  {
    slug: "education-scholarships",
    name: "Education & Scholarships",
    shortName: "Education",
    description: "Board exams, entrance tests, national & state scholarships, fellowships.",
    icon: "GraduationCap",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MoE / AICTE / UGC / NCERT",
  },
  {
    slug: "health-family",
    name: "Health & Family",
    shortName: "Health",
    description: "Ayushman Bharat, CGHS, medical & disability certificates, birth/death records.",
    icon: "HeartPulse",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MoHFW / State Health Depts",
  },
  {
    slug: "employment-labour",
    name: "Employment & Labour",
    shortName: "Employment",
    description: "EPF, ESI, e-Shram, NCS, apprenticeships and labour welfare services.",
    icon: "HardHat",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MoLE / EPFO / ESIC",
  },
  {
    slug: "welfare-schemes",
    name: "Welfare Schemes",
    shortName: "Welfare",
    description: "PM-KISAN, PMAY, Ujjwala, Jan Dhan, Mudra and other central welfare schemes.",
    icon: "HandHeart",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "Various Central Ministries",
  },
  {
    slug: "business-msme",
    name: "Business & MSME",
    shortName: "Business",
    description: "Udyam, FSSAI, trade licenses, IEC, company incorporation, IP & certifications.",
    icon: "Building2",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MoMSME / MCA / FSSAI",
  },
  {
    slug: "transport-vehicles",
    name: "Transport & Vehicles",
    shortName: "Transport",
    description: "RC, Driving License, permits, vehicle tax, fitness, FASTag and PUC.",
    icon: "Car",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MoRTH / VAHAN / SARATHI",
  },
  {
    slug: "utilities",
    name: "Utilities & Connections",
    shortName: "Utilities",
    description: "Electricity, water, LPG/PNG gas, telecom and broadband connections.",
    icon: "PlugZap",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "State DISCOMs / Utilities",
  },
  {
    slug: "police-law",
    name: "Police & Law Enforcement",
    shortName: "Police",
    description: "Online FIR, Police Clearance Certificate, verifications and cyber-crime reporting.",
    icon: "ShieldCheck",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MHA / State Police",
  },
  {
    slug: "agriculture",
    name: "Agriculture & Farmer Welfare",
    shortName: "Agriculture",
    description: "Kisan Credit Card, crop insurance, soil health, e-NAM and farm subsidies.",
    icon: "Wheat",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MoA&FW / DA&FW",
  },
  {
    slug: "pensions",
    name: "Pensions",
    shortName: "Pensions",
    description: "Old-age, widow, disability pensions, NPS, EPS and family pensions.",
    icon: "PiggyBank",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MoRD / EPFO / PFRDA",
  },
  {
    slug: "elections-voting",
    name: "Elections & Voting",
    shortName: "Elections",
    description: "Voter ID, electoral roll services, objections and election complaints.",
    icon: "Vote",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "Election Commission of India",
  },
  {
    slug: "senior-citizens",
    name: "Senior Citizens",
    shortName: "Senior Citizens",
    description: "Senior citizen ID, pensions, concessions, RVY and maintenance tribunal.",
    icon: "Users",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MoSJ&E",
  },
  {
    slug: "women-child",
    name: "Women & Child Development",
    shortName: "Women & Child",
    description: "Sukanya Samriddhi, PMMVY, Beti Bachao, One Stop Centres and CARA adoption.",
    icon: "Baby",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MoWCD",
  },
  {
    slug: "certificates",
    name: "Certificates",
    shortName: "Certificates",
    description: "Caste, income, residence, birth, death, marriage, legal heir & EWS certificates.",
    icon: "ScrollText",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "State Revenue / Local Bodies",
  },
  {
    slug: "court-legal",
    name: "Court & Legal",
    shortName: "Court & Legal",
    description: "eCourts case status, judgments, e-filing, legal aid and Lok Adalat.",
    icon: "Scale",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "eCommittee / Supreme Court",
  },
  {
    slug: "defence-veterans",
    name: "Defence & Veterans",
    shortName: "Defence",
    description: "ECHS, CSD, ex-servicemen pensions, AGNIPATH and recruitment services.",
    icon: "Medal",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MoD / DESW",
  },
  {
    slug: "postal-banking",
    name: "Postal & Small Savings",
    shortName: "Postal & Savings",
    description: "India Post savings, PLI, speed post, RD/FD/NSC/KVP and postal services.",
    icon: "Mail",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "Department of Posts",
  },
  {
    slug: "rti-grievances",
    name: "RTI & Grievances",
    shortName: "RTI & Grievances",
    description: "CPGRAMS, RTI filing & appeals, PMO grievances and public grievance portals.",
    icon: "MessageSquareWarning",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "DARPG / DoPT",
  },
  {
    slug: "municipal-local",
    name: "Municipal & Local Body",
    shortName: "Municipal",
    description: "Property tax, water tax, trade license, building approvals and civic services.",
    icon: "Building",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "Urban Local Bodies",
  },
  {
    slug: "disaster-management",
    name: "Disaster Management",
    shortName: "Disaster",
    description: "NDRF, disaster relief, flood/cyclone compensation and volunteer registration.",
    icon: "Siren",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "NDMA / NDRF",
  },
  {
    slug: "tourism-culture",
    name: "Tourism & Culture",
    shortName: "Tourism",
    description: "ASI monument tickets, Incredible India, tourist guide licenses and events.",
    icon: "Camera",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MoT / ASI / MoC",
  },
  {
    slug: "environment-forests",
    name: "Environment & Forests",
    shortName: "Environment",
    description: "Forest NOC, EIA clearance, wildlife permits, tree felling & pollution consents.",
    icon: "Trees",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MoEFCC",
  },
  {
    slug: "science-tech",
    name: "Science & Technology",
    shortName: "Science & Tech",
    description: "Patents, trademarks, copyrights, research grants and innovation programs.",
    icon: "FlaskConical",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "DST / CSIR / DBT",
  },
  {
    slug: "foreign-trade",
    name: "Foreign Trade & Export",
    shortName: "Foreign Trade",
    description: "IEC, DGFT schemes, RoDTEP, EPCG, advance authorization and export inspection.",
    icon: "Ship",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "DGFT / MoC&I",
  },
  {
    slug: "cooperatives",
    name: "Cooperatives",
    shortName: "Cooperatives",
    description: "Cooperative society registration, multi-state cooperatives and PACS.",
    icon: "Handshake",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "Mo Cooperation",
  },
  {
    slug: "digital-services",
    name: "Digital & e-Governance",
    shortName: "Digital",
    description: "DigiLocker, UMANG, BharatNet, Aadhaar-mobile linking and digital literacy.",
    icon: "Smartphone",
    accent: "from-neutral-100 to-neutral-200/50 text-neutral-900 dark:from-neutral-900/50 dark:to-neutral-800/20 dark:text-neutral-100",
    ministry: "MeitY / NeGD",
  },
];

export const CATEGORY_MAP: Record<ServiceCategorySlug, ServiceCategory> = CATEGORIES.reduce(
  (acc, c) => {
    acc[c.slug] = c;
    return acc;
  },
  {} as Record<ServiceCategorySlug, ServiceCategory>
);
