// Tilak E-Seva Portal — Agriculture services catalog.
// Real Indian Government agricultural services under the Ministry of Agriculture & Farmers Welfare.
// Reference portals: pmfby.gov.in, soilhealth.dac.gov.in, pmksy.gov.in, enam.gov.in,
// pmkisan.gov.in, dac-fw.gov.in, mausam.imd.gov.in.

import type { GovernmentService } from "../types";

export const agriculture: GovernmentService[] = [
  {
    id: "kisan-credit-card-application",
    slug: "kisan-credit-card-application",
    name: "Kisan Credit Card (KCC) Application",
    category: "agriculture",
    subcategory: "Credit & Insurance",
    summary: "Apply for a Kisan Credit Card for short-term agricultural credit at 4% effective interest.",
    description:
      "The Kisan Credit Card (KCC) scheme provides farmers with short-term loans for crop production, post-harvest expenses, and farm equipment. With interest subvention of 1.5% and prompt repayment incentive of 3%, the effective interest rate is 4% p.a. KCC is now extended to animal husbandry and fisheries farmers.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DA&FW)",
    officialPortal: "PM Kisan / Bank Branch",
    officialUrl: "https://www.pmkisan.gov.in/",
    eligibility: [
      "Owner-cultivator, tenant farmer, or oral lessee",
      "Cultivatable land in own name or leased",
      "For PM-KISAN beneficiaries: eligible land records",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Land records (patta / 7-12 / khatian)",
      "Bank passbook / account details",
      "Passport-size photo",
      "KYC documents",
    ],
    fee: 0,
    feeNote: "No application fee; processing fee as per bank norms (₹0–₹500).",
    processingTime: "15–30 days from complete application",
    howToApply: [
      "Visit your bank branch (commercial / RRB / cooperative) or apply via pmkisan.gov.in Banks' KCC online portal.",
      "Fill KCC application form with land and crop details.",
      "Submit land records, Aadhaar, and bank passbook copy.",
      "Bank conducts field verification of land.",
      "Sanction letter issued; KCC card dispatched; credit limit activated.",
    ],
    serviceCharge: 110,
    popularity: 82,
    tags: ["kcc", "kisan credit card", "crop loan", "agriculture credit"],
    online: true,
  },
  {
    id: "kcc-animal-husbandry",
    slug: "kcc-animal-husbandry",
    name: "KCC for Animal Husbandry",
    category: "agriculture",
    subcategory: "Credit & Insurance",
    summary: "Get a KCC for animal husbandry — dairy, poultry, piggery, and small ruminants.",
    description:
      "The KCC scheme was extended in 2018-19 to animal husbandry farmers, providing working capital for dairy, poultry, sheep/goat, pig, and rabbit rearing. The credit limit is based on the number of animals and recurring expenses; the effective interest rate is 4% with subvention.",
    ministry: "Ministry of Fisheries, Animal Husbandry & Dairying (DAHD)",
    officialPortal: "DAHD KCC / Bank Branch",
    officialUrl: "https://ahd.ncog.gov.in/",
    eligibility: [
      "Animal husbandry farmer (dairy / poultry / etc.)",
      "No overdue KCC loan",
      "Registered with dairy cooperative (preferred)",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Bank passbook",
      "Animal ownership proof (purchase receipt / vet certificate)",
      "Dairy cooperative membership (if applicable)",
      "Land records (if land-based unit)",
    ],
    fee: 0,
    feeNote: "No application fee; loan up to ₹3 lakh at 4% effective interest.",
    processingTime: "15–30 days",
    howToApply: [
      "Visit your bank branch (commercial / RRB / cooperative).",
      "Fill KCC Animal Husbandry application form.",
      "Submit Aadhaar, animal ownership proof, and dairy membership.",
      "Bank conducts verification of livestock.",
      "Sanction issued; KCC card and credit limit activated.",
    ],
    serviceCharge: 110,
    popularity: 55,
    tags: ["kcc", "animal husbandry", "dairy", "poultry", "agriculture credit"],
    online: false,
  },
  {
    id: "kcc-fisheries",
    slug: "kcc-fisheries",
    name: "KCC for Fisheries",
    category: "agriculture",
    subcategory: "Credit & Insurance",
    summary: "Get a KCC for fisheries — inland, marine, and aquaculture farmers.",
    description:
      "The KCC scheme was extended in 2018-19 to fisheries farmers engaged in inland, marine, and aquaculture activities. Working capital covers feed, seed, fuel, and labour. The credit limit is based on operational scale; effective interest is 4% with subvention and prompt repayment incentive.",
    ministry: "Department of Fisheries (Ministry of Fisheries, Animal Husbandry & Dairying)",
    officialPortal: "Department of Fisheries KCC",
    officialUrl: "https://dof.gov.in/",
    eligibility: [
      "Fisheries farmer (inland / marine / aquaculture)",
      "Lease/ownership of pond, tank, or fishing rights",
      "No overdue KCC loan",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Bank passbook",
      "Fishing lease / ownership proof",
      "Marine fisher ID card (for marine)",
      "Aquaculture registration (if applicable)",
    ],
    fee: 0,
    feeNote: "No application fee; loan up to ₹3 lakh at 4% effective interest.",
    processingTime: "15–30 days",
    howToApply: [
      "Visit your bank branch (commercial / RRB / cooperative).",
      "Fill KCC Fisheries application form.",
      "Submit Aadhaar, fishing lease/ID, and bank passbook.",
      "Bank verifies fishing rights / pond ownership.",
      "Sanction issued; KCC card and credit limit activated.",
    ],
    serviceCharge: 110,
    popularity: 50,
    tags: ["kcc", "fisheries", "aquaculture", "fisheries credit"],
    online: false,
  },
  {
    id: "pm-fasal-bima-yojana",
    slug: "pm-fasal-bima-yojana",
    name: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    category: "agriculture",
    subcategory: "Credit & Insurance",
    summary: "Get crop insurance against natural calamities, pests, and yield loss under PMFBY.",
    description:
      "PMFBY is the flagship crop insurance scheme providing comprehensive risk cover to farmers against yield losses due to non-prevented natural calamities, pests, and diseases. Farmer premium is capped at 1.5% (Rabi), 2% (Kharif), and 5% (commercial/horticultural crops); balance is shared by Centre and State.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DA&FW)",
    officialPortal: "PMFBY Portal",
    officialUrl: "https://pmfby.gov.in/",
    eligibility: [
      "Loanee farmer: mandatory enrolment",
      "Non-loanee farmer: voluntary enrolment",
      "Cultivating notified crop in notified area",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Land records (patta / 7-12)",
      "Bank account details",
      "Sowing certificate from village revenue officer",
      "Mobile number",
    ],
    fee: 0,
    feeNote: "Premium 1.5% Rabi / 2% Kharif / 5% commercial crops of sum insured; actuarial balance by govt.",
    processingTime: "Coverage from sowing; claims paid within prescribed timelines",
    howToApply: [
      "Visit pmfby.gov.in → 'Farmer Registration'.",
      "Enter Aadhaar, land details, and crop sown.",
      "Select insurance company empanelled for your district.",
      "Pay premium online via UPI / net banking.",
      "Policy issued; intimation SMS sent; claims auto-processed on crop loss.",
    ],
    serviceCharge: 75,
    popularity: 78,
    tags: ["pmfby", "fasal bima", "crop insurance", "agriculture", "insurance"],
    online: true,
  },
  {
    id: "restructured-weather-based-crop-insurance",
    slug: "restructured-weather-based-crop-insurance",
    name: "Restructured Weather Based Crop Insurance (RWBCIS)",
    category: "agriculture",
    subcategory: "Credit & Insurance",
    summary: "Insure crops against adverse weather parameters like rainfall, temperature, humidity.",
    description:
      "RWBCIS provides insurance against deviations in weather parameters (rainfall, temperature, humidity, wind speed) that impact crop yield. Payouts are triggered automatically based on data from automatic weather stations (AWS), without need for yield-based crop cutting experiments.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DA&FW)",
    officialPortal: "PMFBY Portal (RWBCIS section)",
    officialUrl: "https://pmfby.gov.in/",
    eligibility: [
      "Loanee farmer in notified area: mandatory",
      "Non-loanee farmer: voluntary",
      "Cultivating notified crop in notified district",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Land records",
      "Bank account details",
      "Sowing certificate",
      "Mobile number",
    ],
    fee: 0,
    feeNote: "Premium 1.5% Rabi / 2% Kharif / 5% commercial crops of sum insured.",
    processingTime: "Coverage from sowing; weather-based payouts auto-triggered",
    howToApply: [
      "Visit pmfby.gov.in → 'Farmer Registration'.",
      "Choose scheme 'RWBCIS' and notified crop.",
      "Fill land and weather location details.",
      "Pay premium online.",
      "Policy issued; payouts credited to bank account automatically on weather trigger.",
    ],
    serviceCharge: 75,
    popularity: 50,
    tags: ["rwbcis", "weather insurance", "crop insurance", "pmfby"],
    online: true,
  },
  {
    id: "soil-health-card",
    slug: "soil-health-card",
    name: "Soil Health Card",
    category: "agriculture",
    subcategory: "Inputs & Extension",
    summary: "Get a Soil Health Card with nutrient status & fertiliser recommendations for your farm.",
    description:
      "The Soil Health Card (SHC) scheme provides every farmer with a periodic report of soil nutrient status (macro and micro) along with crop-wise fertiliser recommendations. SHCs are issued every 2 years free of cost and help farmers reduce input cost and improve yield through balanced fertilisation.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DA&FW)",
    officialPortal: "Soil Health Card Portal",
    officialUrl: "https://soilhealth.dac.gov.in/",
    eligibility: ["All farmers (owner / tenant / lessee)", "Land parcel with valid survey number"],
    documentsRequired: [
      "Aadhaar card",
      "Land records (patta / 7-12)",
      "Mobile number",
      "Bank passbook (optional)",
    ],
    fee: 0,
    feeNote: "Free for all farmers; sample collection and testing borne by govt.",
    processingTime: "30–90 days from sample collection",
    howToApply: [
      "Visit soilhealth.dac.gov.in → 'Farmer Login'.",
      "Register with Aadhaar and mobile number.",
      "Add land parcel with survey / khasra number.",
      "Field staff collects soil sample; barcode issued.",
      "Lab tests sample; SHC delivered to farmer online and via SMS.",
    ],
    serviceCharge: 50,
    popularity: 65,
    tags: ["soil health card", "shc", "soil testing", "fertiliser", "agriculture"],
    online: true,
  },
  {
    id: "pmksy-micro-irrigation",
    slug: "pmksy-micro-irrigation",
    name: "PMKSY Micro Irrigation (Per Drop More Crop)",
    category: "agriculture",
    subcategory: "Inputs & Extension",
    summary: "Get 55% subsidy for drip / sprinkler irrigation under PMKSY Per Drop More Crop.",
    description:
      "The Pradhan Mantri Krishi Sinchayee Yojana (PMKSY) — Per Drop More Crop component — provides 55% subsidy (45% Centre + 10% State) to small & marginal farmers for drip and sprinkler irrigation systems. The scheme improves water use efficiency and crop yield.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DA&FW)",
    officialPortal: "PMKSY Portal",
    officialUrl: "https://pmksy.gov.in/",
    eligibility: [
      "All categories of farmers (individual or group)",
      "Owns cultivable land with water source",
      "Not availed subsidy for the same system in last 7 years",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Land records",
      "Bank passbook",
      "Bank account details",
      "Land photo / sketch",
    ],
    fee: 0,
    feeNote: "Subsidy 55% (small/marginal) / 45% (others); farmer contributes balance.",
    processingTime: "60–120 days",
    howToApply: [
      "Register on pmksy.gov.in with Aadhaar.",
      "Apply for micro-irrigation under 'Per Drop More Crop'.",
      "Upload land records and select empanelled agency.",
      "Agency installs system; inspection by district officer.",
      "Subsidy credited to farmer's bank account.",
    ],
    serviceCharge: 130,
    popularity: 60,
    tags: ["pmksy", "micro irrigation", "drip", "sprinkler", "per drop more crop"],
    online: true,
  },
  {
    id: "pm-kisan-beneficiary-list-search",
    slug: "pm-kisan-beneficiary-list-search",
    name: "PM-KISAN Beneficiary List Search",
    category: "agriculture",
    subcategory: "Welfare",
    summary: "Check your PM-KISAN Samman Nidhi beneficiary status and instalment history.",
    description:
      "PM-KISAN Samman Nidhi provides income support of ₹6,000 per year to all landholding farmer families in three equal instalments. The beneficiary status portal lets farmers check their eligibility, instalment credit status, and edit land / Aadhaar / bank details. Beneficiary list is published every instalment cycle.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DA&FW)",
    officialPortal: "PM-KISAN Portal",
    officialUrl: "https://pmkisan.gov.in/",
    eligibility: [
      "Landholding farmer family with cultivable land",
      "Aadhaar linked to land records",
      "Not in exclusion categories (income tax payers, govt employees, etc.)",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Land records",
      "Mobile number",
      "Bank account details",
    ],
    fee: 0,
    feeNote: "₹6,000/year in 3 instalments of ₹2,000 each, credited directly to bank account.",
    processingTime: "Instalments every 4 months; new registrations take 30–90 days",
    howToApply: [
      "Visit pmkisan.gov.in → 'Farmers Corner' → 'Beneficiary Status'.",
      "Enter Aadhaar number or mobile number + captcha.",
      "View beneficiary record, instalments credited, and pending status.",
      "If 'Rejected', use 'Edit Name' / 'Aadhaar Errors' / 'Self Registered Farmer' to correct.",
      "CSC / Tilak Infotech can assist with correction.",
    ],
    serviceCharge: 50,
    popularity: 88,
    tags: ["pm kisan", "samman nidhi", "beneficiary", "farmer welfare", "dbt"],
    online: true,
  },
  {
    id: "tractor-subsidy",
    slug: "tractor-subsidy",
    name: "Tractor Subsidy (SMAM)",
    category: "agriculture",
    subcategory: "Machinery & Equipment",
    summary: "Get subsidy on tractor purchase under Sub-Mission on Agricultural Mechanization.",
    description:
      "Under the Sub-Mission on Agricultural Mechanization (SMAM), farmers receive subsidy (up to 25–50%, capped at ₹45,000–₹60,000) on tractor purchase up to 40 PTO HP. Custom Hiring Centres (CHCs) and Farmer Producer Organisations (FPOs) get higher subsidies for tractors and farm equipment.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DA&FW)",
    officialPortal: "SMAM / State Agriculture Portal",
    officialUrl: "https://farmmachinery.dac.gov.in/",
    eligibility: [
      "Individual farmer, FPO, or CHC",
      "Tractor up to 40 PTO HP for individual farmer",
      "Not availed tractor subsidy in last 7 years",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Land records",
      "Bank passbook",
      "Tractor invoice from empanelled OEM",
      "Quotation & ID proof",
    ],
    fee: 0,
    feeNote: "Subsidy 25–50% (varies by category & state); capped per tractor; DBT credited to bank.",
    processingTime: "60–120 days",
    howToApply: [
      "Visit farmmachinery.dac.gov.in → 'Apply for Subsidy'.",
      "Select your state and scheme (SMAM).",
      "Choose tractor model from empanelled OEM list.",
      "Purchase tractor; submit invoice & documents to state agriculture dept.",
      "Inspection done; subsidy credited via DBT.",
    ],
    serviceCharge: 140,
    popularity: 65,
    tags: ["tractor subsidy", "smam", "agricultural machinery", "farm equipment"],
    online: true,
  },
  {
    id: "seed-subsidy-distribution",
    slug: "seed-subsidy-distribution",
    name: "Seed Subsidy Distribution",
    category: "agriculture",
    subcategory: "Inputs & Extension",
    summary: "Get subsidised certified seeds of notified crops through state agriculture department.",
    description:
      "State Agriculture Departments distribute certified / truthfully labelled seeds of notified crops (paddy, wheat, pulses, oilseeds) at subsidised rates to farmers. Subsidy ranges 25–75% and is routed through Primary Agricultural Credit Societies (PACS), Krishi Vigyan Kendras, and departmental outlets.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DA&FW) & State Agriculture Dept.",
    officialPortal: "State Agriculture Department Portal",
    officialUrl: "https://agricoop.nic.in/",
    eligibility: ["Registered farmer with valid land records", "Cultivating notified crop in the season"],
    documentsRequired: [
      "Aadhaar card",
      "Land records",
      "Mobile number",
      "Bank account details",
    ],
    fee: 0,
    feeNote: "Subsidy 25–75% on MRP; farmer pays subsidised rate at distribution point.",
    processingTime: "Same day at distribution centre",
    howToApply: [
      "Visit nearest PACS / KVK / agriculture dept outlet.",
      "Submit Aadhaar and land records for verification.",
      "Select crop, variety, and quantity of seed.",
      "Pay subsidised rate (balance subsidy borne by govt).",
      "Receipt issued; seed bag with tag handed over.",
    ],
    serviceCharge: 50,
    popularity: 60,
    tags: ["seed subsidy", "certified seed", "agriculture inputs", "kharif", "rabi"],
    online: false,
  },
  {
    id: "fertilizer-subsidy-dbt",
    slug: "fertilizer-subsidy-dbt",
    name: "Fertilizer Subsidy (DBT-Bharat)",
    category: "agriculture",
    subcategory: "Inputs & Extension",
    summary: "Get fertilisers at subsidised rates via Direct Benefit Transfer under DBT Bharat.",
    description:
      "Under the DBT Fertilizers system, the subsidy on urea and P&K (phosphatic & potassic) fertilisers is transferred directly to fertiliser companies based on actual sales captured at point of sale (PoS) machines. Farmers must authenticate via Aadhaar / mobile OTP / KCC at the retailer to purchase subsidised fertiliser.",
    ministry: "Ministry of Chemicals & Fertilizers (DoF)",
    officialPortal: "DBT Fertilizers",
    officialUrl: "https://dbtfert.bharat.gov.in/",
    eligibility: ["Indian farmer with valid Aadhaar / mobile / KCC", "Purchase from registered retailer"],
    documentsRequired: [
      "Aadhaar card / mobile number / KCC",
      "Land records",
      "Bank account details (optional)",
    ],
    fee: 0,
    feeNote: "Farmer pays subsidised MRP; subsidy (₹2000+ per bag urea) paid to manufacturer by govt.",
    processingTime: "Instant sale after authentication",
    howToApply: [
      "Visit a registered fertiliser retailer with PoS device.",
      "Authenticate via Aadhaar / mobile OTP / KCC at PoS.",
      "Select quantity and grade of fertiliser.",
      "Pay subsidised MRP to retailer.",
      "Sale record synced to DBT Bharat; receipt issued.",
    ],
    serviceCharge: 30,
    popularity: 78,
    tags: ["fertiliser subsidy", "dbt", "urea", "pos", "fertilizer"],
    online: false,
  },
  {
    id: "agricultural-pumpset-connection-solar",
    slug: "agricultural-pumpset-connection-solar",
    name: "Agricultural Solar Pumpset Connection (PM-KUSUM)",
    category: "agriculture",
    subcategory: "Machinery & Equipment",
    summary: "Install a subsidised solar agricultural pumpset under PM-KUSUM Component-B/C.",
    description:
      "PM-KUSUM (Pradhan Mantri Kisan Urja Suraksha evam Utthaan Mahabhiyan) provides financial assistance of up to 60% (30% Central + 30% State) for standalone solar pumps (Component-B) and solarisation of existing grid-connected pumps (Component-C). Farmers bear ~10% of cost; remaining 30% can be loan-financed.",
    ministry: "Ministry of New and Renewable Energy (MNRE)",
    officialPortal: "PM-KUSUM Portal",
    officialUrl: "https://pmkusum.mnre.gov.in/",
    eligibility: [
      "Individual farmer with cultivable land",
      "Valid source of water (well / borewell / canal)",
      "For Component-C: existing grid-connected ag pump",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Land records",
      "Bank passbook",
      "Water source proof (borewell / well permission)",
      "Bank loan sanction (if availing loan)",
    ],
    fee: 0,
    feeNote: "Subsidy 60%; farmer contribution 10–40% (varies by state); pump size 0.5–10 HP.",
    processingTime: "60–180 days",
    howToApply: [
      "Register on pmkusum.mnre.gov.in with Aadhaar.",
      "Apply for Component B (standalone) or Component C (solarisation).",
      "Select empanelled vendor and pump capacity.",
      "Pay farmer share + loan; vendor installs pump.",
      "Inspection by DISCOM; subsidy released to vendor/farmer.",
    ],
    serviceCharge: 150,
    popularity: 60,
    tags: ["pm-kusum", "solar pump", "agriculture pump", "mnre", "renewable"],
    online: true,
  },
  {
    id: "farmers-registration-pm-kisan",
    slug: "farmers-registration-pm-kisan",
    name: "Farmers Registration (PM-KISAN New Farmer)",
    category: "agriculture",
    subcategory: "Welfare",
    summary: "Register as a new PM-KISAN beneficiary to receive ₹6,000/year income support.",
    description:
      "PM-KISAN registration is the gateway to enrolment in the PM-KISAN Samman Nidhi scheme, providing ₹6,000/year in three instalments. Farmers self-register online or via Common Service Centres (CSCs). State governments verify land records before adding to the beneficiary list.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DA&FW)",
    officialPortal: "PM-KISAN Portal",
    officialUrl: "https://pmkisan.gov.in/",
    eligibility: [
      "Landholding farmer family (own cultivable land)",
      "Not excluded (income-tax payers, govt employees, professionals, etc.)",
      "Land records in own name",
    ],
    documentsRequired: [
      "Aadhaar card (mandatory)",
      "Land records (patta / 7-12)",
      "Bank account details",
      "Mobile number",
    ],
    fee: 0,
    feeNote: "Free registration; ₹6,000/year paid via DBT to bank.",
    processingTime: "30–90 days for verification and enrolment",
    howToApply: [
      "Visit pmkisan.gov.in → 'New Farmer Registration'.",
      "Enter Aadhaar, mobile, and captcha.",
      "Fill personal, land, and bank details.",
      "Upload land record document.",
      "Submit; status updated after state verification.",
    ],
    serviceCharge: 60,
    popularity: 85,
    tags: ["pm kisan", "registration", "farmer welfare", "new farmer", "dbt"],
    online: true,
  },
  {
    id: "e-nam-trader-license",
    slug: "e-nam-trader-license",
    name: "e-NAM Trader License",
    category: "agriculture",
    subcategory: "Market & Trade",
    summary: "Get a unified trader licence to operate across e-NAM mandis in India.",
    description:
      "The National Agriculture Market (e-NAM) is an online trading platform for agricultural commodities integrating APMC mandis across India. A trader licence issued by one APMC is valid across all e-NAM mandis in participating states, enabling inter-mandi trading without separate licences.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DAC&FW)",
    officialPortal: "e-NAM Portal",
    officialUrl: "https://enam.gov.in/",
    eligibility: [
      "Indian citizen / company / partnership / FPO",
      "No criminal background",
      "Adequate financial capacity (varies by APMC)",
    ],
    documentsRequired: [
      "Aadhaar / PAN / GST certificate",
      "Address proof",
      "Bank account details",
      "Photograph",
      "Payslip / financial statement",
    ],
    fee: 1000,
    feeNote: "₹1000–₹25,000 licence fee (varies by APMC & state); annual renewal fee extra.",
    processingTime: "15–30 days",
    howToApply: [
      "Register on enam.gov.in → 'Trader Registration'.",
      "Select APMC of choice; upload KYC & financials.",
      "Pay licence fee via online mode.",
      "APMC verifies documents; licence issued.",
      "Trader can bid in any e-NAM mandi with unified login.",
    ],
    serviceCharge: 130,
    popularity: 45,
    tags: ["e-nam", "trader licence", "apmc", "agricultural market", "trading"],
    online: true,
  },
  {
    id: "e-nam-farmer-registration",
    slug: "e-nam-farmer-registration",
    name: "e-NAM Farmer Registration",
    category: "agriculture",
    subcategory: "Market & Trade",
    summary: "Register on e-NAM to sell produce online across mandis and get better prices.",
    description:
      "e-NAM farmer registration enables a farmer to sell their produce on the e-NAM platform — both at their local APMC and remotely across participating mandis. Farmers receive SMS alerts for lot auctions, real-time prices, and direct online payment to their bank account via the e-NAM payment gateway.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DAC&FW)",
    officialPortal: "e-NAM Portal",
    officialUrl: "https://enam.gov.in/",
    eligibility: ["Indian farmer with cultivable land", "Bank account in own name"],
    documentsRequired: [
      "Aadhaar card",
      "Land records",
      "Bank passbook",
      "Mobile number",
      "Passport-size photo",
    ],
    fee: 0,
    feeNote: "Free registration; mandi transaction charges as per APMC bylaws.",
    processingTime: "Same day to 7 days",
    howToApply: [
      "Visit enam.gov.in → 'Farmer Registration'.",
      "Enter Aadhaar, mobile, and bank account details.",
      "Upload land records.",
      "Visit nearest e-NAM APMC for biometric verification.",
      "Login credentials issued; farmer can bring produce for e-auction.",
    ],
    serviceCharge: 75,
    popularity: 58,
    tags: ["e-nam", "farmer registration", "apmc", "agricultural market", "e-auction"],
    online: true,
  },
  {
    id: "soil-testing-lab-application",
    slug: "soil-testing-lab-application",
    name: "Soil Testing Lab Application",
    category: "agriculture",
    subcategory: "Inputs & Extension",
    summary: "Apply to set up / use a Soil Testing Lab under Soil Health Management.",
    description:
      "Entrepreneurs, FPOs, and cooperatives can set up static or mobile Soil Testing Labs (STLs) under the Soil Health Management sub-scheme. The Centre provides up to ₹25 lakh assistance for static STLs and ₹12 lakh for mobile STLs. Farmers can also approach these labs for paid soil analysis.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DA&FW)",
    officialPortal: "Soil Health Card Portal",
    officialUrl: "https://soilhealth.dac.gov.in/",
    eligibility: [
      "Individual entrepreneurs / FPOs / cooperatives / NGOs",
      "Adequate space and equipment investment capacity",
      "Technical personnel (chemists) on board",
    ],
    documentsRequired: [
      "Aadhaar / PAN of applicant",
      "Registration certificate (for FPO/cooperative)",
      "Project report & equipment list",
      "Bank account details",
      "Premises proof",
    ],
    fee: 0,
    feeNote: "Capital subsidy 100% govt aided (govt labs) / up to ₹25 lakh for private STLs.",
    processingTime: "60–120 days",
    howToApply: [
      "Apply on soilhealth.dac.gov.in → 'STL Registration'.",
      "Submit project report and equipment details.",
      "State DAC scrutinises and recommends.",
      "Approval & sanction issued; lab commissioned.",
      "Lab linked to SHC portal for sample testing uploads.",
    ],
    serviceCharge: 140,
    popularity: 35,
    tags: ["soil testing", "stl", "soil lab", "soil health", "entrepreneur"],
    online: true,
  },
  {
    id: "kisan-call-center-18001801551",
    slug: "kisan-call-center-18001801551",
    name: "Kisan Call Center (1800-180-1551)",
    category: "agriculture",
    subcategory: "Advisory",
    summary: "Free 24x7 telephonic agricultural advisory to farmers via Kisan Call Centers.",
    description:
      "Kisan Call Centers (KCCs) provide free agricultural advisory to farmers across India via the toll-free number 1800-180-1551. Subject Matter Specialists answer queries on crops, animal husbandry, fisheries, schemes, weather, and market prices in 22 local languages. Calls are routed based on the farmer's PIN code.",
    ministry: "Ministry of Agriculture & Farmers Welfare (DA&FW)",
    officialPortal: "Kisan Call Center / KCC Portal",
    officialUrl: "https://dackkms.gov.in/",
    eligibility: ["Any Indian farmer or stakeholder", "Access to telephone"],
    documentsRequired: ["None (just a phone call)"],
    fee: 0,
    feeNote: "Completely free; toll-free from any network in India.",
    processingTime: "Immediate response",
    howToApply: [
      "Call 1800-180-1551 from any phone.",
      "Choose preferred language via IVR.",
      "Connect to Kisan Call Center Agent.",
      "Ask query — agent logs it and provides advice.",
      "SMS with summary sent to farmer's mobile; follow-up if required.",
    ],
    serviceCharge: 0,
    popularity: 55,
    tags: ["kisan call center", "1800-180-1551", "advisory", "agriculture", "toll free"],
    online: false,
  },
  {
    id: "mausam-weather-forecast-agriculture",
    slug: "mausam-weather-forecast-agriculture",
    name: "Mausam — Weather Forecast & Agromet Advisory",
    category: "agriculture",
    subcategory: "Advisory",
    summary: "Free location-specific weather forecast & agromet advisories via Mausam / Meghdoot apps.",
    description:
      "The India Meteorological Department (IMD), through its Gramin Krishi Mausam Seva (GKMS) scheme, provides location-specific weather forecasts and weekly agromet advisories to farmers. Available via the Mausam app, Meghdoot app, SMS, and KVK networks, advisories cover rainfall, temperature, wind, and crop-specific actions.",
    ministry: "Ministry of Earth Sciences (India Meteorological Department)",
    officialPortal: "Mausam / Meghdoot",
    officialUrl: "https://mausam.imd.gov.in/",
    eligibility: ["Any farmer or stakeholder in India", "Smartphone or basic mobile for SMS"],
    documentsRequired: ["Mobile number", "Location PIN code"],
    fee: 0,
    feeNote: "Free; advisories available via app, SMS, IVRS, radio, and WhatsApp.",
    processingTime: "Real-time updates; weekly bulletins",
    howToApply: [
      "Download 'Mausam' or 'Meghdoot' app from Play Store.",
      "Register with mobile number & PIN code.",
      "View current weather, 7-day forecast, and crop advisories.",
      "Subscribe to SMS alerts (free) via provider.",
      "Receive twice-weekly agromet advisory bulletin.",
    ],
    serviceCharge: 0,
    popularity: 60,
    tags: ["mausam", "meghdoot", "weather", "agromet advisory", "imd", "forecast"],
    online: true,
  },
];
