import type { GovernmentService } from "../types";

export const businessMsme: GovernmentService[] = [
  {
    id: "udyam-registration-new-msme",
    slug: "udyam-registration-new-msme",
    name: "Udyam Registration (New MSME)",
    category: "business-msme",
    subcategory: "MSME Registration",
    summary: "Register your micro, small or medium enterprise free of cost on Udyam portal.",
    description:
      "Udyam Registration is the official MSME registration process launched by the Government of India on 1 July 2020. It is fully online, free of cost, and based on Aadhaar. The Udyam Certificate enables MSMEs to avail subsidies, priority sector lending, government tenders and protection against delayed payments.",
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    officialPortal: "Udyam Registration Portal",
    officialUrl: "https://udyamregistration.gov.in/",
    eligibility: [
      "Any entity type — proprietorship, partnership, LLP, Pvt Ltd, OPC, HUF",
      "Investment in plant & machinery / equipment within MSME limits",
      "Engaged in manufacturing or services (trading-only entities excluded)",
    ],
    documentsRequired: ["Aadhaar of proprietor / authorised signatory", "PAN of entity / proprietor", "Bank account details", "Business activity & address"],
    fee: 0,
    feeNote: "Free service. Government does not charge any fee for Udyam Registration.",
    processingTime: "Instant certificate generation",
    howToApply: [
      "Visit the official Udyam Registration portal.",
      "Enter Aadhaar and name of proprietor / authorised signatory.",
      "Verify with OTP received on Aadhaar-linked mobile.",
      "Fill PAN, business, bank and activity details.",
      "Submit to receive Udyam Certificate instantly on email.",
    ],
    serviceCharge: 50,
    popularity: 92,
    tags: ["udyam", "msme", "registration", "ssi", "free"],
    online: true,
  },
  {
    id: "udyam-amendment",
    slug: "udyam-amendment",
    name: "Udyam Amendment / Detail Update",
    category: "business-msme",
    subcategory: "MSME Registration",
    summary: "Update activity, investment, address or bank details in your existing Udyam.",
    description:
      "MSMEs can amend details like plant & machinery investment, activity (manufacturing / services), office address, bank account or partner / director details on the Udyam portal. Aadhaar OTP authentication is required for changes; some changes need documentary proof upload.",
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    officialPortal: "Udyam Registration Portal",
    officialUrl: "https://udyamregistration.gov.in/AndroidApp/UpdateUdyamRegistration.aspx",
    eligibility: ["Already holds a valid Udyam Registration", "Aadhaar-linked mobile active"],
    documentsRequired: ["Udyam Registration Number (URN)", "Aadhaar", "Supporting documents for the change"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant (some changes need 1-2 days for verification)",
    howToApply: [
      "Visit the Udyam portal and click 'Update Udyam Registration'.",
      "Enter URN and Aadhaar-linked mobile OTP.",
      "Edit the required fields (address, activity, investment, bank).",
      "Upload supporting documents if changing PAN / activities.",
      "Submit and download the updated Udyam Certificate.",
    ],
    serviceCharge: 50,
    popularity: 85,
    tags: ["udyam", "amendment", "update", "msme"],
    online: true,
  },
  {
    id: "udyam-re-registration",
    slug: "udyam-re-registration",
    name: "Udyam Re-Registration",
    category: "business-msme",
    subcategory: "MSME Registration",
    summary: "Re-register on Udyam portal before expiry of earlier EM-II / UAM.",
    description:
      "Enterprises that held EM Part-II (UAN) or UAM (Udyog Aadhaar Memorandum) registration must migrate to Udyam by filing Re-Registration before 31 March 2025 (or prior expiry date). The transition preserves the original date of commencement for benefits.",
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    officialPortal: "Udyam Registration Portal",
    officialUrl: "https://udyamregistration.gov.in/AndroidApp/ForReRegistration.aspx",
    eligibility: [
      "Held valid EM Part-II or UAM earlier",
      "Not yet migrated to Udyam",
      "Continuing same business activity",
    ],
    documentsRequired: ["Earlier UAM / EM-II number", "Aadhaar of proprietor", "PAN", "Bank details"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant certificate",
    howToApply: [
      "Open 'For Re-Registration' on the Udyam portal.",
      "Enter earlier UAM / EM-II reference number and Aadhaar.",
      "Verify with OTP and confirm migration details.",
      "Update PAN, investment, bank and activity details.",
      "Submit to receive new Udyam Certificate preserving original commencement date.",
    ],
    serviceCharge: 75,
    popularity: 70,
    tags: ["udyam", "re-registration", "uam", "msme", "migration"],
    online: true,
  },
  {
    id: "fssai-basic-registration",
    slug: "fssai-basic-registration",
    name: "FSSAI Basic Registration",
    category: "business-msme",
    subcategory: "Food Safety",
    summary: "Register your small food business (up to ₹12 lakh turnover) with FSSAI.",
    description:
      "FSSAI Basic Registration is mandatory for tiny food businesses with annual turnover up to ₹12 lakh. Issued under Form A, it is valid for 1-5 years. Required for petty food manufacturers, small retailers, hawkers, and temporary stallholders.",
    ministry: "Food Safety and Standards Authority of India (FSSAI)",
    officialPortal: "FoSCoS — Food Safety Compliance System",
    officialUrl: "https://foodlicensing.fssai.gov.in/",
    eligibility: [
      "Annual turnover up to ₹12 lakh",
      "Petty food business — manufacturer / retailer / hawker / stallholder",
      "Production capacity within small scale limits",
    ],
    documentsRequired: ["Photograph of FBO", "Aadhaar of proprietor / partner", "PAN", "Address proof of business", "List of food products"],
    fee: 100,
    feeNote: "₹100 per year of validity (1 to 5 years).",
    processingTime: "7 to 30 days",
    howToApply: [
      "Register on the FoSCoS portal.",
      "Apply for Basic Registration (Form A).",
      "Fill business, product and address details.",
      "Upload Aadhaar, photo and address proof.",
      "Pay fee and download the FSSAI Registration Certificate.",
    ],
    serviceCharge: 75,
    popularity: 88,
    tags: ["fssai", "basic registration", "food", "fssc", "food safety"],
    online: true,
  },
  {
    id: "fssai-state-license",
    slug: "fssai-state-license",
    name: "FSSAI State License",
    category: "business-msme",
    subcategory: "Food Safety",
    summary: "Get FSSAI State License for food business with turnover ₹12 lakh to ₹20 crore.",
    description:
      "FSSAI State License (Form B) is required for food businesses with annual turnover between ₹12 lakh and ₹20 crore. Licence is valid for 1-5 years and covers dairy, meat, vegetable oil, storage, retail, wholesale, catering and food manufacturing units.",
    ministry: "Food Safety and Standards Authority of India (FSSAI)",
    officialPortal: "FoSCoS — Food Safety Compliance System",
    officialUrl: "https://foodlicensing.fssai.gov.in/",
    eligibility: [
      "Annual turnover ₹12 lakh to ₹20 crore",
      "Production capacity within state licence limits",
      "Manufacturing / storage / distribution / catering of food",
    ],
    documentsRequired: ["Form B application", "Aadhaar & PAN of FBO", "Constitution proof (MoA / Partnership deed)", "Address proof", "List of food products & layout plan"],
    fee: 2000,
    feeNote: "Annual licence fee ₹2,000 to ₹7,500 based on business category / capacity.",
    processingTime: "30 to 60 days",
    howToApply: [
      "Register on FoSCoS portal.",
      "Apply for State Licence (Form B).",
      "Select business category & capacity.",
      "Upload constitution proof, layout, product list & KYC.",
      "Pay licence fee; inspection conducted before grant.",
    ],
    serviceCharge: 150,
    popularity: 85,
    tags: ["fssai", "state license", "food", "form b", "food safety"],
    online: true,
  },
  {
    id: "fssai-central-license",
    slug: "fssai-central-license",
    name: "FSSAI Central License",
    category: "business-msme",
    subcategory: "Food Safety",
    summary: "Get FSSAI Central License for food business turnover above ₹20 crore.",
    description:
      "FSSAI Central License (Form B) is mandatory for large food businesses with annual turnover above ₹20 crore, importers, 100% export-oriented units, and operators in parliament / airport / seaport / railway station complexes. Valid for 1-5 years.",
    ministry: "Food Safety and Standards Authority of India (FSSAI)",
    officialPortal: "FoSCoS — Food Safety Compliance System",
    officialUrl: "https://foodlicensing.fssai.gov.in/",
    eligibility: [
      "Annual turnover above ₹20 crore",
      "Importer / exporter / operator at ports, airports, railways",
      "Dairy / meat / oil processing above central licence capacity",
    ],
    documentsRequired: ["Form B application", "Aadhaar & PAN", "Constitution documents (MoA / AoA)", "Layout & process flow plan", "NOC from local authority"],
    fee: 7500,
    feeNote: "Annual licence fee ₹7,500 to ₹17,500 based on business category / capacity.",
    processingTime: "30 to 60 days",
    howToApply: [
      "Register on FoSCoS portal.",
      "Apply for Central Licence (Form B).",
      "Select business category and capacity.",
      "Upload constitution proof, layout, NOC and product list.",
      "Inspection by Central Licensing Authority; licence issued.",
    ],
    serviceCharge: 150,
    popularity: 78,
    tags: ["fssai", "central license", "food", "importer", "food safety"],
    online: true,
  },
  {
    id: "fssai-license-renewal",
    slug: "fssai-license-renewal",
    name: "FSSAI License / Registration Renewal",
    category: "business-msme",
    subcategory: "Food Safety",
    summary: "Renew your FSSAI licence or registration before its expiry date.",
    description:
      "FSSAI licence / registration must be renewed before expiry to avoid penalty of up to ₹2 lakh per day for operating without a valid licence. Renewal application can be filed up to 180 days before expiry; the same FoSCoS portal processes both renewal and modifications.",
    ministry: "Food Safety and Standards Authority of India (FSSAI)",
    officialPortal: "FoSCoS — Food Safety Compliance System",
    officialUrl: "https://foodlicensing.fssai.gov.in/",
    eligibility: ["Existing FSSAI licence / registration nearing expiry"],
    documentsRequired: ["Existing licence / registration number", "Updated KYC", "Address proof", "Annual return (Form D1)"],
    fee: 100,
    feeNote: "Renewal fee same as original licence / registration fee.",
    processingTime: "30 to 60 days",
    howToApply: [
      "Login to FoSCoS portal.",
      "Select existing licence and click 'Renewal'.",
      "Update any changes in business / product details.",
      "Pay renewal fee for 1-5 years.",
      "Renewed licence issued and SMS / email sent.",
    ],
    serviceCharge: 75,
    popularity: 82,
    tags: ["fssai", "renewal", "food licence", "fssc", "food safety"],
    online: true,
  },
  {
    id: "trade-license-municipal",
    slug: "trade-license-municipal",
    name: "Trade License (Municipal)",
    category: "business-msme",
    subcategory: "Local Licenses",
    summary: "Get a municipal trade licence to legally operate a business within city limits.",
    description:
      "A Trade Licence is issued by the Municipal Corporation / Municipality authorising a business to operate within its jurisdiction. It ensures the business activity is permissible in the zone and complies with safety, health and noise norms. Mandatory for shops, hotels, factories, and commercial establishments.",
    ministry: "Urban Local Bodies (Municipal Corporations / Municipalities)",
    officialPortal: "State / Municipal Corporation Portal",
    officialUrl: "https://mohua.gov.in/",
    eligibility: [
      "Business operating within municipal limits",
      "Activity permitted as per local zoning bylaws",
      "Premises meets safety / health norms",
    ],
    documentsRequired: ["Address proof of premises (rent / ownership)", "PAN of proprietor / entity", "Aadhaar of applicant", "Photo of premises", "NOC from landowner (if rented)"],
    fee: 500,
    feeNote: "Fee varies by municipality and business type (₹200 to ₹5,000).",
    processingTime: "7 to 30 days",
    howToApply: [
      "Visit the Municipal Corporation / state municipal portal.",
      "Register and select 'Trade Licence Application'.",
      "Fill business, address and activity details.",
      "Upload address proof, photo, PAN & Aadhaar.",
      "Pay fee and download trade licence certificate.",
    ],
    serviceCharge: 100,
    popularity: 80,
    tags: ["trade license", "municipal", "business", "license"],
    online: true,
  },
  {
    id: "shops-establishment-msme-registration",
    slug: "shops-establishment-msme-registration",
    name: "Shops & Establishment Registration (MSME)",
    category: "business-msme",
    subcategory: "Local Licenses",
    summary: "Register your commercial establishment under state Shops & Establishments Act.",
    description:
      "Most Indian states now offer online registration of shops, hotels and commercial establishments under the state Shops & Establishments Act. The certificate is mandatory to open a current account, register on e-commerce platforms and obtain other statutory registrations. Valid for 1-5 years.",
    ministry: "State Labour Departments",
    officialPortal: "State Labour Department Portal",
    officialUrl: "https://labour.gov.in/",
    eligibility: [
      "Any shop, hotel, restaurant, theatre or commercial establishment",
      "Operating in state jurisdiction",
      "Minimum 1 employee (most states)",
    ],
    documentsRequired: ["PAN of proprietor / entity", "Address proof", "Photo of premises", "Employee details", "Photo of proprietor"],
    fee: 200,
    feeNote: "Fee varies by state and number of employees (₹100 to ₹2,000).",
    processingTime: "Instant to 7 days (varies by state)",
    howToApply: [
      "Visit the State Labour Department portal.",
      "Create establishment account with mobile / email.",
      "Fill Shop Act application with establishment & employee details.",
      "Upload address proof, photo, PAN & Aadhaar.",
      "Pay fee and download Registration Certificate.",
    ],
    serviceCharge: 100,
    popularity: 80,
    tags: ["shops", "establishment", "shop act", "registration", "msme"],
    online: true,
  },
  {
    id: "gst-suvidha-provider-onboarding",
    slug: "gst-suvidha-provider-onboarding",
    name: "GST Suvidha Provider (GSP) Services",
    category: "business-msme",
    subcategory: "Tax Compliance",
    summary: "Get GST return filing, reconciliation and API services via GST Suvidha Providers.",
    description:
      "GST Suvidha Providers (GSPs) are GSTN-approved platforms that offer APIs and applications to taxpayers / Tax Return Preparers for filing returns, reconciling data and accessing the GST system programmatically. Through GSPs and Application Service Providers (ASPs), businesses can file GSTR-1, GSTR-3B, ITC reconciliation and annual returns.",
    ministry: "Goods and Services Tax Network (GSTN)",
    officialPortal: "GST Suvidha Provider Portal",
    officialUrl: "https://www.gstn.org.in/gsp/",
    eligibility: [
      "GST-registered business requiring bulk / API based filing",
      "Tax Return Preparers / CAs / accountants serving multiple clients",
      "Tech-enabled MSMEs looking for automation",
    ],
    documentsRequired: ["GSTIN", "PAN", "Aadhaar of authorised signatory", "Authorisation letter (if ASP)"],
    fee: 0,
    feeNote: "GSP APIs free to ASPs; ASPs charge businesses ₹1,000-₹10,000 per year.",
    processingTime: "Instant onboarding with ASP",
    howToApply: [
      "Choose a GSTN-approved GSP / ASP from the official list.",
      "Register on the GSP / ASP portal with GSTIN & mobile OTP.",
      "Authorise the ASP to file returns on your behalf via GST portal.",
      "Use the ASP platform to file GSTR-1, GSTR-3B, and annual returns.",
      "Track filing status and ITC reconciliation online.",
    ],
    serviceCharge: 100,
    popularity: 70,
    tags: ["gsp", "asp", "gst", "returns", "gstn"],
    online: true,
  },
  {
    id: "iec-application",
    slug: "iec-application",
    name: "Import Export Code (IEC) Application",
    summary: "Apply for a 10-digit Import Export Code from DGFT for import/export business.",
    category: "business-msme",
    subcategory: "Foreign Trade",
    description:
      "Import Export Code (IEC) is a 10-digit unique identification number issued by the Directorate General of Foreign Trade (DGFT) under the Ministry of Commerce. It is mandatory for any business importing or exporting goods or services from / to India. The code is permanent and requires no renewal.",
    ministry: "Directorate General of Foreign Trade (DGFT), Ministry of Commerce",
    officialPortal: "DGFT Portal",
    officialUrl: "https://www.dgft.gov.in/",
    eligibility: [
      "Indian proprietorship / partnership / LLP / company",
      "PAN of proprietor / entity",
      "Bank account in name of business",
    ],
    documentsRequired: ["PAN of business / proprietor", "Aadhaar of applicant", "Bank certificate / cancelled cheque", "Address proof", "Business constitution proof"],
    fee: 500,
    feeNote: "Application fee ₹500.",
    processingTime: "1 to 2 working days (auto-approval after Aadhaar / PAN validation)",
    howToApply: [
      "Register on the DGFT portal with mobile / email.",
      "Apply for IEC under 'Services' → 'Import Export Code'.",
      "Fill PAN, bank, address and business details.",
      "Pay ₹500 fee and e-sign with Aadhaar OTP.",
      "IEC generated instantly on successful validation.",
    ],
    serviceCharge: 75,
    popularity: 85,
    tags: ["iec", "import export", "dgft", "foreign trade", "code"],
    online: true,
  },
  {
    id: "iec-modification",
    slug: "iec-modification",
    name: "IEC Modification / Update",
    category: "business-msme",
    subcategory: "Foreign Trade",
    summary: "Update address, bank or business details in your existing Import Export Code.",
    description:
      "Holders of IEC can modify details like address, bank account, branch, constitution or product profile through the DGFT portal. Some modifications require supporting documents and DGFT scrutiny; PAN-related changes are auto-processed.",
    ministry: "Directorate General of Foreign Trade (DGFT), Ministry of Commerce",
    officialPortal: "DGFT Portal",
    officialUrl: "https://www.dgft.gov.in/",
    eligibility: ["Holds a valid IEC"],
    documentsRequired: ["Existing IEC", "Aadhaar of applicant", "Supporting documents for the change"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "1 to 5 working days",
    howToApply: [
      "Login to the DGFT portal.",
      "Open 'Modify IEC' under Services.",
      "Update required fields (address, bank, branch).",
      "Upload supporting documents.",
      "Submit; modified IEC generated and emailed.",
    ],
    serviceCharge: 50,
    popularity: 60,
    tags: ["iec", "modification", "update", "dgft", "import export"],
    online: true,
  },
  {
    id: "iec-renewal",
    slug: "iec-renewal",
    name: "IEC Renewal / Annual Update",
    category: "business-msme",
    subcategory: "Foreign Trade",
    summary: "Complete mandatory annual IEC update for April-June quarter to keep it active.",
    description:
      "Although IEC is a permanent code, DGFT mandates an annual update between April and June each year to keep the IEC active. Failure to update results in deactivation of the IEC. The update is free and can be completed on the DGFT portal.",
    ministry: "Directorate General of Foreign Trade (DGFT), Ministry of Commerce",
    officialPortal: "DGFT Portal",
    officialUrl: "https://www.dgft.gov.in/",
    eligibility: ["Holds valid IEC", "Continuing import/export business"],
    documentsRequired: ["Existing IEC", "Aadhaar", "Updated business / bank details"],
    fee: 0,
    feeNote: "Free annual update.",
    processingTime: "Instant activation",
    howToApply: [
      "Login to DGFT portal between April and June.",
      "Open 'Annual IEC Update' under Services.",
      "Verify / update business, address and bank details.",
      "Submit with Aadhaar e-sign.",
      "IEC status reverts to Active immediately.",
    ],
    serviceCharge: 50,
    popularity: 55,
    tags: ["iec", "renewal", "annual update", "dgft", "import export"],
    online: true,
  },
  {
    id: "iso-9001-certification-assistance",
    slug: "iso-9001-certification-assistance",
    name: "ISO 9001:2015 Certification Assistance",
    category: "business-msme",
    subcategory: "Quality Certification",
    summary: "Get assisted end-to-end ISO 9001:2015 quality management certification.",
    description:
      "ISO 9001:2015 is the international standard for Quality Management Systems. The certification process involves gap analysis, documentation of QMS, internal audit, and certification audit by an accredited body. The certificate is valid for 3 years with annual surveillance audits.",
    ministry: "Quality Council of India (QCI) / Accredited Certification Bodies",
    officialPortal: "QCI / NABCB Portal",
    officialUrl: "https://www.qcin.org/",
    eligibility: ["Any business — manufacturing / services / trading", "Operational for at least 3 months"],
    documentsRequired: ["Business registration (Udyam / GST)", "PAN", "Quality manual & SOPs", "Internal audit records", "Process flow documents"],
    fee: 5000,
    feeNote: "Certification fee ₹5,000-₹25,000 based on number of employees & scope (varies by certification body).",
    processingTime: "15 to 45 days",
    howToApply: [
      "Engage a QCI-accredited certification body.",
      "Conduct gap analysis & prepare QMS documents.",
      "Implement QMS for at least 3 months.",
      "Stage 1 (documentation) and Stage 2 (implementation) audits.",
      "Certification issued on successful audit; valid for 3 years.",
    ],
    serviceCharge: 150,
    popularity: 65,
    tags: ["iso 9001", "qms", "certification", "quality", "qci"],
    online: false,
  },
  {
    id: "bis-isi-mark-certification",
    slug: "bis-isi-mark-certification",
    name: "BIS ISI Mark Certification",
    category: "business-msme",
    subcategory: "Quality Certification",
    summary: "Get ISI mark certification for products covered under BIS Indian Standards.",
    description:
      "Bureau of Indian Standards (BIS) grants a licence to use the ISI mark on products conforming to Indian Standards. Mandatory for many products like cement, electrical goods, food, steel etc. The licence is granted after factory inspection and sample testing.",
    ministry: "Bureau of Indian Standards (BIS)",
    officialPortal: "BIS Manak Online Portal",
    officialUrl: "https://www.manakonline.in/",
    eligibility: [
      "Manufacturing a product covered by an Indian Standard",
      "Factory with in-house testing facilities",
      "Compliance with relevant IS specifications",
    ],
    documentsRequired: ["Factory licence", "Product test reports", "QMS documents", "PAN & Aadhaar of proprietor", "Layout & process flow"],
    fee: 1000,
    feeNote: "Application fee ₹1,000; licence fee based on product / minimum fee ₹10,000 per year.",
    processingTime: "30 to 90 days",
    howToApply: [
      "Register on the BIS Manak portal.",
      "Apply for ISI licence for the relevant Indian Standard.",
      "Submit factory documents and test reports.",
      "BIS conducts factory inspection and sample drawl.",
      "Licence granted on satisfactory test & inspection.",
    ],
    serviceCharge: 150,
    popularity: 60,
    tags: ["bis", "isi mark", "indian standards", "certification", "manufacturing"],
    online: true,
  },
  {
    id: "bis-hallmarking-license",
    slug: "bis-hallmarking-license",
    name: "BIS Hallmarking Licence (Gold / Silver)",
    category: "business-msme",
    subcategory: "Quality Certification",
    summary: "Get a BIS licence to hallmark gold / silver jewellery.",
    description:
      "BIS grants recognition to jewellers and hallmarking centres to hallmark gold / silver jewellery under the BIS Act 2016. Hallmarking is mandatory for gold jewellery & artefacts. Jewellers must register with BIS; hallmarking centres are recognised separately.",
    ministry: "Bureau of Indian Standards (BIS)",
    officialPortal: "BIS Hallmarking Portal",
    officialUrl: "https://bhuvan-app1.nrsc.gov.in/hallmarking/",
    eligibility: [
      "Jeweller dealing in gold / silver jewellery",
      "Hallmarking centre with assaying equipment",
      "GST registered",
    ],
    documentsRequired: ["GST registration", "Jeweller / centre registration certificate", "PAN & Aadhaar", "Address proof", "Equipment calibration certificates"],
    fee: 1000,
    feeNote: "Registration fee ₹1,000 for jewellers; ₹25,000 for hallmarking centres.",
    processingTime: "30 to 45 days",
    howToApply: [
      "Register on the BIS Hallmarking portal.",
      "Choose Jeweller Registration or Hallmarking Centre Recognition.",
      "Submit GST, PAN and address proof.",
      "Inspection for hallmarking centres.",
      "Licence / recognition issued with unique BIS ID.",
    ],
    serviceCharge: 150,
    popularity: 55,
    tags: ["bis", "hallmarking", "gold", "silver", "jewellery"],
    online: true,
  },
  {
    id: "trademark-application-filing",
    slug: "trademark-application-filing",
    name: "Trademark Application Filing",
    category: "business-msme",
    subcategory: "Intellectual Property",
    summary: "Register your brand name, logo or tagline with the Trade Marks Registry.",
    description:
      "A trademark registration in India under the Trade Marks Act 1999 grants exclusive right to use a mark for the goods/services for which it is registered. The application is filed online via the IPIndia portal; registration is valid for 10 years (renewable).",
    ministry: "Office of the Controller General of Patents, Designs & Trade Marks (CGPDTM)",
    officialPortal: "IPIndia Trademark Portal",
    officialUrl: "https://ipindia.gov.in/trademarks.htm",
    eligibility: [
      "Any person / entity claiming to be the proprietor of the mark",
      "Mark capable of graphical representation",
      "Mark not similar to existing registered marks",
    ],
    documentsRequired: ["Logo / wordmark (if logo mark)", "Power of Attorney (Form TM-48)", "User affidavit (if claiming prior use)", "Business proof", "Applicant details"],
    fee: 4500,
    feeNote: "Government fee ₹4,500 per class per mark for individuals / startups / MSMEs; ₹9,000 for others.",
    processingTime: "6 to 24 months for registration; TM-T symbol granted in 1-2 days",
    howToApply: [
      "Conduct a public search on the IPIndia portal for similar marks.",
      "File Form TM-A online with mark, class and applicant details.",
      "Upload power of attorney and supporting documents.",
      "Pay the government fee online.",
      "Receive TM-T application number; mark examined and published in Trade Marks Journal.",
    ],
    serviceCharge: 150,
    popularity: 80,
    tags: ["trademark", "tm", "ip", "brand", "registration"],
    online: true,
  },
  {
    id: "trademark-opposition",
    slug: "trademark-opposition",
    name: "Trademark Opposition Filing",
    category: "business-msme",
    subcategory: "Intellectual Property",
    summary: "Oppose a published trademark application within 4 months of journal publication.",
    description:
      "Any person can oppose a trademark application within 4 months (extendable) of its publication in the Trade Marks Journal by filing Form TM-O with a statement of opposition. The applicant then files a counter-statement; the Registrar conducts a hearing and decides the matter.",
    ministry: "Office of the Controller General of Patents, Designs & Trade Marks (CGPDTM)",
    officialPortal: "IPIndia Trademark Portal",
    officialUrl: "https://ipindia.gov.in/trademarks.htm",
    eligibility: ["Any aggrieved person / existing trademark owner", "Filed within 4 months of journal publication"],
    documentsRequired: ["Notice of opposition (Form TM-O)", "Details of opposed mark", "Evidence by way of affidavit", "Power of Attorney"],
    fee: 1000,
    feeNote: "Government fee ₹1,000 per opposition.",
    processingTime: "18 to 36 months for decision",
    howToApply: [
      "Monitor the Trade Marks Journal for marks similar to yours.",
      "File Form TM-O notice of opposition within 4 months of publication.",
      "Pay ₹1,000 fee and upload supporting documents.",
      "Applicant files counter-statement within 2 months.",
      "Hearing conducted; Registrar passes order.",
    ],
    serviceCharge: 150,
    popularity: 45,
    tags: ["trademark", "opposition", "ip", "tm-o", "brand protection"],
    online: true,
  },
  {
    id: "patent-application-filing",
    slug: "patent-application-filing",
    name: "Patent Application Filing",
    category: "business-msme",
    subcategory: "Intellectual Property",
    summary: "File a patent for your invention with the Indian Patent Office.",
    description:
      "A patent grants exclusive rights to an invention (product or process) that is new, involves an inventive step and is industrially applicable. Filed under the Patents Act 1970, the patent is valid for 20 years from the date of filing of the application.",
    ministry: "Office of the Controller General of Patents, Designs & Trade Marks (CGPDTM)",
    officialPortal: "IPIndia Patents Portal",
    officialUrl: "https://ipindia.gov.in/patents.htm",
    eligibility: [
      "Invention is novel, non-obvious and industrially applicable",
      "Not falling in excluded categories (Section 3 & 4)",
      "Filed by true and first inventor or assignee",
    ],
    documentsRequired: ["Provisional / complete specification", "Form 1 (application)", "Form 2 (specification)", "Form 3 (foreign filing statement)", "Form 5 (inventorship)", "Form 26 (POA if agent)"],
    fee: 1600,
    feeNote: "Government fee ₹1,600 for natural persons / startups / MSMEs; higher for others.",
    processingTime: "18 to 48 months for grant",
    howToApply: [
      "Conduct a patent search on inPASS / patent office.",
      "Draft provisional / complete specification with claims.",
      "File Form 1, 2, 3, 5 and 26 online with fee.",
      "Request for examination (Form 18) within 48 months.",
      "Respond to examination objections; patent granted and published.",
    ],
    serviceCharge: 150,
    popularity: 60,
    tags: ["patent", "ip", "invention", "ipo", "registration"],
    online: true,
  },
  {
    id: "copyright-registration",
    slug: "copyright-registration",
    name: "Copyright Registration",
    category: "business-msme",
    subcategory: "Intellectual Property",
    summary: "Register your original literary, artistic, musical or software work with the Copyright Office.",
    description:
      "Copyright registration under the Copyright Act 1957 establishes a public record of ownership of original literary, dramatic, musical, artistic, cinematograph film or sound recording works (including computer programs). It is prima facie evidence in court and is valid for the lifetime of the author plus 60 years.",
    ministry: "Department of Higher Education, Ministry of Education — Copyright Office",
    officialPortal: "Copyright Office Portal",
    officialUrl: "https://copyright.gov.in/",
    eligibility: ["Author / owner of original work", "Work created in India or by an Indian citizen"],
    documentsRequired: ["Application Form XIV", "Copies of the work", "Power of Attorney (if filed through agent)", "NOC from other co-authors (if any)"],
    fee: 500,
    feeNote: "Government fee ₹500 per work (varies for artistic work ₹2,000).",
    processingTime: "6 to 12 months",
    howToApply: [
      "Register on the Copyright Office portal.",
      "File Form XIV with details of work and author.",
      "Upload copies of the work and supporting documents.",
      "Pay government fee online.",
      "Diary number issued; examination and registration certificate granted after scrutiny.",
    ],
    serviceCharge: 100,
    popularity: 55,
    tags: ["copyright", "ip", "registration", "literary", "artistic"],
    online: true,
  },
  {
    id: "design-registration",
    slug: "design-registration",
    name: "Industrial Design Registration",
    category: "business-msme",
    subcategory: "Intellectual Property",
    summary: "Register the visual design / shape of an article under the Designs Act 2000.",
    description:
      "An industrial design registration protects the visual appearance (shape, pattern, configuration, ornamentation) of an article under the Designs Act 2000. The registration is valid for 10 years, extendable by 5 years. It does not protect the technical / functional aspects.",
    ministry: "Office of the Controller General of Patents, Designs & Trade Marks (CGPDTM)",
    officialPortal: "IPIndia Designs Portal",
    officialUrl: "https://ipindia.gov.in/designs.htm",
    eligibility: [
      "Design is new / original",
      "Design appeals to the eye",
      "Not previously published in India",
    ],
    documentsRequired: ["Form 1 (application)", "Drawings / representations of design from 6 views", "Power of Attorney (Form TM-48)", "Class of article"],
    fee: 1000,
    feeNote: "Government fee ₹1,000 for natural persons / startups / MSMEs.",
    processingTime: "6 to 12 months",
    howToApply: [
      "Conduct a design search on the IPIndia portal.",
      "File Form 1 with 6 representations of the design.",
      "Pay fee and upload Form TM-48 (if filed through agent).",
      "Examination by the Designs Office.",
      "Registration certificate issued; valid for 10 years.",
    ],
    serviceCharge: 150,
    popularity: 50,
    tags: ["design", "industrial design", "ip", "registration"],
    online: true,
  },
  {
    id: "geographical-indication-registration",
    slug: "geographical-indication-registration",
    name: "Geographical Indication (GI) Registration",
    category: "business-msme",
    subcategory: "Intellectual Property",
    summary: "Register a product with GI tag based on its geographical origin (e.g. Darjeeling Tea).",
    description:
      "A Geographical Indication (GI) is a sign used on products that have a specific geographical origin and possess qualities / reputation due to that origin (e.g. Darjeeling Tea, Kancheepuram Silk). Registered under the GI of Goods (Registration & Protection) Act 1999, it is valid for 10 years (renewable).",
    ministry: "Office of the Controller General of Patents, Designs & Trade Marks (CGPDTM)",
    officialPortal: "IPIndia GI Portal",
    officialUrl: "https://ipindia.gov.in/gi.htm",
    eligibility: [
      "Any association of persons / producers / organisation representing the interest of producers",
      "Product has qualities / reputation attributable to geographical origin",
    ],
    documentsRequired: ["Form GI-1 (application)", "Statement of case", "Map of geographical area", "List of producers", "Power of Attorney"],
    fee: 5000,
    feeNote: "Application fee ₹5,000.",
    processingTime: "12 to 24 months",
    howToApply: [
      "Form an association of producers / authorised user group.",
      "File Form GI-1 with statement of case and map of area.",
      "Pay ₹5,000 fee and upload list of producers.",
      "Application examined and published in GI Journal.",
      "Registration granted if no opposition within 4 months.",
    ],
    serviceCharge: 150,
    popularity: 40,
    tags: ["gi", "geographical indication", "ip", "registration", "tag"],
    online: true,
  },
  {
    id: "company-incorporation-private-limited",
    slug: "company-incorporation-private-limited",
    name: "Private Limited Company Incorporation",
    category: "business-msme",
    subcategory: "Entity Formation",
    summary: "Incorporate a Private Limited Company with 2-200 members via SPICe+ form.",
    description:
      "A Private Limited Company is the most preferred structure for startups in India, offering limited liability, separate legal entity and easy access to funding. Incorporation is done through the SPICe+ form on the MCA portal which integrates name reservation, DIN allotment, PAN, TAN and EPFO/ESIC registration.",
    ministry: "Ministry of Corporate Affairs (MCA)",
    officialPortal: "MCA21 Portal",
    officialUrl: "https://www.mca.gov.in/",
    eligibility: [
      "Minimum 2 shareholders (max 200)",
      "Minimum 2 directors (1 must be Indian resident)",
      "No minimum capital requirement",
    ],
    documentsRequired: ["PAN & Aadhaar of directors", "DSC of subscribers", "Director's consent (DIR-2)", "Utility bill of registered office (≤2 months old)", "No-objection from owner of premises"],
    fee: 1000,
    feeNote: "Government fee varies with authorised capital (₹1,000+ for ≤₹15 lakh). Stamp duty state-specific.",
    processingTime: "2 to 7 working days",
    howToApply: [
      "Obtain DSC for proposed directors.",
      "File SPICe+ Part A for name reservation on MCA portal.",
      "Complete SPICe+ Part B with company details, subscribers and directors.",
      "Upload linked forms AGILE-PRO, INC-9, DIR-9 and stamp duty proof.",
      "Certificate of Incorporation issued with PAN, TAN, EPFO & ESIC numbers.",
    ],
    serviceCharge: 150,
    popularity: 88,
    tags: ["company", "private limited", "incorporation", "mca", "spice+"],
    online: true,
  },
  {
    id: "llp-registration",
    slug: "llp-registration",
    name: "Limited Liability Partnership (LLP) Registration",
    category: "business-msme",
    subcategory: "Entity Formation",
    summary: "Register an LLP combining benefits of partnership and limited liability company.",
    description:
      "A Limited Liability Partnership (LLP) under the LLP Act 2008 offers limited liability to partners and operational flexibility of a partnership. Registration is done via the FiLLiP form on the MCA portal. Suitable for small businesses, professionals and consulting firms.",
    ministry: "Ministry of Corporate Affairs (MCA)",
    officialPortal: "MCA21 Portal",
    officialUrl: "https://www.mca.gov.in/",
    eligibility: [
      "Minimum 2 partners (at least 1 Indian resident)",
      "Minimum 1 designated partner with DIN",
      "No minimum capital requirement",
    ],
    documentsRequired: ["PAN & Aadhaar of partners", "DSC of designated partners", "Utility bill of registered office", "NOC from premises owner", "LLP agreement (post incorporation)"],
    fee: 500,
    feeNote: "Government fee varies (₹500-₹5,000). Stamp duty state-specific.",
    processingTime: "5 to 10 working days",
    howToApply: [
      "Obtain DSC for designated partners.",
      "Reserve LLP name via RUN-LLP or FiLLiP Part A on MCA portal.",
      "File FiLLiP form with partner and registered office details.",
      "Pay fee and submit with linked forms.",
      "Certificate of Incorporation issued; file LLP Agreement within 30 days (Form 3).",
    ],
    serviceCharge: 150,
    popularity: 82,
    tags: ["llp", "limited liability partnership", "registration", "mca", "fillip"],
    online: true,
  },
  {
    id: "opc-registration",
    slug: "opc-registration",
    name: "One Person Company (OPC) Registration",
    category: "business-msme",
    subcategory: "Entity Formation",
    summary: "Incorporate a One Person Company with single shareholder and limited liability.",
    description:
      "A One Person Company (OPC) is a private limited company with only one shareholder (Indian citizen). The OPC structure offers limited liability and separate legal entity, suitable for solo entrepreneurs. Registration is via the SPICe+ form on the MCA portal.",
    ministry: "Ministry of Corporate Affairs (MCA)",
    officialPortal: "MCA21 Portal",
    officialUrl: "https://www.mca.gov.in/",
    eligibility: [
      "Single Indian citizen shareholder (natural person)",
      "Nominee director (Indian citizen)",
      "Minimum 1 director (max 15)",
    ],
    documentsRequired: ["PAN & Aadhaar of director / nominee", "DSC", "Consent of nominee (INC-3)", "Utility bill of office", "Photograph"],
    fee: 1000,
    feeNote: "Government fee ₹1,000+ (varies with authorised capital). Stamp duty state-specific.",
    processingTime: "3 to 7 working days",
    howToApply: [
      "Obtain DSC for the sole member.",
      "File SPICe+ Part A for name reservation.",
      "Complete SPICe+ Part B with director, nominee and registered office details.",
      "Upload INC-3 (nominee consent), DIR-2 and utility bill.",
      "Certificate of Incorporation issued with PAN, TAN & EPFO/ESIC.",
    ],
    serviceCharge: 150,
    popularity: 75,
    tags: ["opc", "one person company", "incorporation", "mca", "spice+"],
    online: true,
  },
  {
    id: "din-allotment",
    slug: "din-allotment",
    name: "Director Identification Number (DIN)",
    category: "business-msme",
    subcategory: "Entity Formation",
    summary: "Get a unique DIN for a person to act as director of any Indian company.",
    description:
      "Director Identification Number (DIN) is an 8-digit unique identification number allotted by the MCA to any person intending to be a director of an Indian company. DIN is obtained through SPICe+ Part B (for new companies) or Form DIR-3 for existing companies. A DIN is valid for lifetime.",
    ministry: "Ministry of Corporate Affairs (MCA)",
    officialPortal: "MCA21 Portal",
    officialUrl: "https://www.mca.gov.in/",
    eligibility: ["Indian citizen or foreign national aged 18+", "Holds valid PAN (Indians) / Passport (foreign nationals)"],
    documentsRequired: ["PAN / Passport", "Aadhaar", "Photograph", "Address proof", "Educational qualification details"],
    fee: 0,
    feeNote: "No fee for DIN allotment through SPICe+ (max 3 directors). ₹500 per DIN through DIR-3.",
    processingTime: "Instant (within SPICe+) / 1 day (DIR-3)",
    howToApply: [
      "Apply for DIN via SPICe+ Part B (for new company) or Form DIR-3 (existing company).",
      "Enter PAN / passport, Aadhaar and address details.",
      "Upload photograph and verify with Aadhaar OTP.",
      "Pay fee (if DIR-3) and submit.",
      "DIN allotted and intimated via SMS / email.",
    ],
    serviceCharge: 50,
    popularity: 70,
    tags: ["din", "director", "mca", "identification", "company"],
    online: true,
  },
  {
    id: "dsc-digital-signature-certificate",
    slug: "dsc-digital-signature-certificate",
    name: "Digital Signature Certificate (DSC)",
    category: "business-msme",
    subcategory: "Digital Identity",
    summary: "Get a Class 3 Digital Signature Certificate for e-filing with MCA, GST, Income Tax.",
    description:
      "A Class 3 Digital Signature Certificate (DSC) is required for directors / partners / professionals to digitally sign documents filed with MCA, GST, Income Tax, EPFO and Trademark Registry. DSC is issued by Certifying Authorities licensed by CCA for a validity of 1-3 years.",
    ministry: "Office of the Controller of Certifying Authorities (CCA)",
    officialPortal: "CCA India Portal",
    officialUrl: "https://www.cca.gov.in/",
    eligibility: ["Indian citizen / entity", "PAN & Aadhaar", "Mobile and email"],
    documentsRequired: ["PAN", "Aadhaar", "Photograph", "Address proof", "DSC application form"],
    fee: 1500,
    feeNote: "Cost ₹1,000-₹2,500 based on validity (1, 2 or 3 years) and token type.",
    processingTime: "1 to 3 working days",
    howToApply: [
      "Choose a CCA-licensed Certifying Authority (e.g. eMudhra, Sify, n-Code).",
      "Fill DSC application form with PAN, Aadhaar and address details.",
      "Upload documents and complete video / in-person verification.",
      "Pay fee and collect USB token (or cloud-based DSC).",
      "Install driver to use DSC for e-filing.",
    ],
    serviceCharge: 100,
    popularity: 78,
    tags: ["dsc", "digital signature", "class 3", "cca", "e-filing"],
    online: true,
  },
  {
    id: "mca21-company-filing",
    slug: "mca21-company-filing",
    name: "MCA21 Annual Company Filing (AOC-4 / MGT-7)",
    category: "business-msme",
    subcategory: "Compliance",
    summary: "File annual financials (AOC-4) and annual return (MGT-7/7A) with MCA.",
    description:
      "Every Indian company must file its audited financial statements (AOC-4) within 30 days of AGM and annual return (MGT-7 for companies, MGT-7A for OPCs / small companies) within 60 days of AGM with the MCA. Failure attracts ₹100 per day penalty per form.",
    ministry: "Ministry of Corporate Affairs (MCA)",
    officialPortal: "MCA21 Portal",
    officialUrl: "https://www.mca.gov.in/",
    eligibility: ["Active company incorporated under Companies Act 2013 / 1956"],
    documentsRequired: ["Audited Balance Sheet & P&L", "Director's Report", "AGM notice & minutes", "Auditor's report", "List of shareholders"],
    fee: 200,
    feeNote: "Filing fee based on authorised capital (₹200 to ₹600 per form).",
    processingTime: "Instant acknowledgement; approved within 1-2 days",
    howToApply: [
      "Login to MCA21 portal with valid DSC of director / professional.",
      "Pre-fill AOC-4 from XBRL / financial data.",
      "Upload audited financials, directors' report and AGM details.",
      "Pay fee; file MGT-7 / MGT-7A within 60 days of AGM.",
      "Receive challan and SRN for each form.",
    ],
    serviceCharge: 150,
    popularity: 75,
    tags: ["mca", "annual filing", "aoc-4", "mgt-7", "compliance"],
    online: true,
  },
  {
    id: "epfo-employer-registration",
    slug: "epfo-employer-registration",
    name: "EPFO Employer Establishment Registration",
    category: "business-msme",
    subcategory: "Statutory Registrations",
    summary: "Register your establishment with EPFO for PF compliance when headcount crosses 20.",
    description:
      "Every establishment employing 20 or more persons must register with EPFO under the Employees' Provident Funds & Miscellaneous Provisions Act 1952. The establishment gets a PF Establishment Code; monthly ECR is filed and PF contributions are paid online.",
    ministry: "Employees' Provident Fund Organisation (EPFO), Ministry of Labour & Employment",
    officialPortal: "EPFO Employer Portal (Shram Suvidha)",
    officialUrl: "https://www.shramsuvidha.gov.in/",
    eligibility: [
      "Establishment employing 20+ employees",
      "Covered industry / activity under Schedule I of EPF Act",
      "Voluntary registration possible for <20 employees",
    ],
    documentsRequired: ["PAN of establishment", "GST / Trade licence", "Address proof", "List of employees", "Bank details"],
    fee: 0,
    feeNote: "Free registration.",
    processingTime: "5 to 15 working days",
    howToApply: [
      "Register on the Shram Suvidha / EPFO portal.",
      "Fill establishment registration form with PAN, GST, address.",
      "Upload employee list and bank details.",
      "Submit for EPFO field office verification.",
      "PF Establishment Code allotted; ECR filing enabled.",
    ],
    serviceCharge: 100,
    popularity: 75,
    tags: ["epfo", "employer", "registration", "pf code", "establishment"],
    online: true,
  },
  {
    id: "esic-employer-registration",
    slug: "esic-employer-registration",
    name: "ESIC Employer Establishment Registration",
    category: "business-msme",
    subcategory: "Statutory Registrations",
    summary: "Register your establishment with ESIC for medical & social security of employees.",
    description:
      "Every establishment / factory employing 10 or more employees (with monthly wage up to ₹21,000) must register with ESIC under the Employees' State Insurance Act 1948. The employer gets an ESIC Code; monthly contributions are filed online for medical, sickness, maternity and disablement benefits.",
    ministry: "Employees' State Insurance Corporation (ESIC), Ministry of Labour & Employment",
    officialPortal: "ESIC Employer Portal",
    officialUrl: "https://www.esic.in/",
    eligibility: [
      "Establishment / factory employing 10+ employees (in most states)",
      "Employees drawing monthly wages up to ₹21,000",
    ],
    documentsRequired: ["PAN of establishment", "GST / Registration certificate", "Address proof", "Bank details", "List of employees"],
    fee: 0,
    feeNote: "Free registration. Employer contributes 3.25% and employee 0.75% of wages.",
    processingTime: "1 to 7 working days",
    howToApply: [
      "Register on the ESIC portal with establishment email / mobile.",
      "Fill Form-01 employer registration with PAN, GST, address.",
      "Upload employee list with wages and bank details.",
      "Generate ESIC Code Number.",
      "Add employees; file monthly return and pay contribution online.",
    ],
    serviceCharge: 100,
    popularity: 78,
    tags: ["esic", "employer", "registration", "code", "establishment"],
    online: true,
  },
  {
    id: "factory-license-msme",
    slug: "factory-license-msme",
    name: "Factory License (Factories Act)",
    category: "business-msme",
    subcategory: "Statutory Licenses",
    summary: "Get factory licence from State Factory Inspectorate under Factories Act 1948.",
    description:
      "A manufacturing premise with 10+ workers (with power) or 20+ workers (without power) requires a Factory Licence from the State Chief Inspector of Factures under the Factories Act 1948. The licence covers plan approval, safety, health and welfare compliance and is renewable periodically.",
    ministry: "State Factory Inspectorates / Directorate of Industrial Safety & Health",
    officialPortal: "State Factory Inspectorate / XGN Portal",
    officialUrl: "https://labour.gov.in/",
    eligibility: [
      "Manufacturing premise with 10+ workers (with power) / 20+ (without)",
      "Plan approved by Chief Inspector",
      "Complies with safety & welfare provisions",
    ],
    documentsRequired: ["Approved factory plan", "Stability certificate", "Form 2 application", "Building licence", "PAN & GST of entity"],
    fee: 1000,
    feeNote: "Licence fee based on installed horsepower & number of workers (state-specific).",
    processingTime: "30 to 60 days",
    howToApply: [
      "Submit Form 1 for approval of factory plan to Chief Inspector.",
      "Get plan approved and complete construction.",
      "Apply for licence in Form 2 with stability certificate.",
      "Pay licence fee online.",
      "Factory inspection conducted; licence granted on compliance.",
    ],
    serviceCharge: 150,
    popularity: 70,
    tags: ["factory license", "factories act", "manufacturing", "licence", "safety"],
    online: true,
  },
  {
    id: "pollution-control-board-consent",
    slug: "pollution-control-board-consent",
    name: "Pollution Control Board Consent (CTE / CTO)",
    category: "business-msme",
    subcategory: "Statutory Licenses",
    summary: "Get Consent to Establish (CTE) and Consent to Operate (CTO) from State PCB.",
    description:
      "Industries classified under Red / Orange / Green / White categories by CPCB must obtain Consent to Establish (CTE) before setting up and Consent to Operate (CTO) before commencing operations from the State Pollution Control Board under the Water & Air Acts. CTO is renewed periodically based on category.",
    ministry: "Central / State Pollution Control Boards",
    officialPortal: "State Pollution Control Board Portal",
    officialUrl: "https://cpcb.nic.in/",
    eligibility: [
      "Industry classified under Red / Orange / Green category",
      "Plot acquired and construction plan ready",
      "Pollution control systems designed per CPCB guidelines",
    ],
    documentsRequired: ["Industry classification proof", "Site plan & layout", "Process flow diagram", "Pollution control system design", "PAN & GST"],
    fee: 2500,
    feeNote: "Consent fee based on investment & category (₹2,500 to ₹2,00,000+).",
    processingTime: "30 to 120 days",
    howToApply: [
      "Register on State Pollution Control Board portal.",
      "Apply for CTE with industry classification, site plan and process flow.",
      "Pay consent fee; inspection by PCB officer.",
      "CTE granted; complete construction with pollution control systems.",
      "Apply for CTO before commissioning; renewal every 1-5 years.",
    ],
    serviceCharge: 150,
    popularity: 72,
    tags: ["pcb", "cte", "cto", "pollution", "consent", "environment"],
    online: true,
  },
];
