import type { GovernmentService } from "../types";

export const certificates: GovernmentService[] = [
  {
    id: "caste-certificate-sc",
    slug: "caste-certificate-sc",
    name: "Caste Certificate (SC — Scheduled Caste)",
    category: "certificates",
    subcategory: "Caste Certificates",
    summary: "Issue of Scheduled Caste (SC) caste certificate for reservations and welfare schemes.",
    description:
      "The SC Caste Certificate is issued by the State Revenue Department (Tehsildar / SDM / Mandal Revenue Officer) to persons belonging to a Scheduled Caste listed for the state. The certificate is mandatory for availing reservations in education, government jobs, scholarships, and various welfare schemes. Application is filed at the e-District portal or the Tehsil office with proof of caste.",
    ministry: "State Revenue Department / Welfare Department",
    officialPortal: "State e-District Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Person belonging to a Scheduled Caste listed for the state",
      "Permanent resident of the state",
      "Father/mother holds an SC certificate of the state (usually)",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Ration card / residence proof",
      "Caste proof of father / mother / blood relative (their SC certificate)",
      "School leaving certificate / transfer certificate",
      "Birth certificate",
      "Affidavit of caste in prescribed format",
      "Recent photograph",
    ],
    fee: 10,
    feeNote: "₹10-₹40 application fee depending on state; free for BPL.",
    processingTime: "15-30 days",
    howToApply: [
      "Visit the state e-District portal or Tehsil office.",
      "Register with Aadhaar OTP and select 'Caste Certificate (SC)' service.",
      "Fill the application form with personal, parent and caste details.",
      "Upload Aadhaar, parent's SC certificate, residence proof, photograph and affidavit.",
      "Pay the fee online; certificate is issued after revenue officer verification and dispatched by post.",
    ],
    serviceCharge: 80,
    popularity: 88,
    tags: ["caste certificate", "sc", "scheduled caste", "reservation", "e-district"],
    online: true,
  },
  {
    id: "caste-certificate-st",
    slug: "caste-certificate-st",
    name: "Caste Certificate (ST — Scheduled Tribe)",
    category: "certificates",
    subcategory: "Caste Certificates",
    summary: "Issue of Scheduled Tribe (ST) caste certificate for reservations and tribal welfare schemes.",
    description:
      "The ST Caste Certificate is issued by the State Revenue / Tribal Welfare Department to persons belonging to a Scheduled Tribe listed for the state. The certificate is mandatory for ST reservations in education, employment, scholarships, and tribal welfare schemes. Application requires proof of tribal affiliation through lineage, often verified by the Tribal Development Department.",
    ministry: "State Revenue / Tribal Welfare Department",
    officialPortal: "State e-District Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Person belonging to a Scheduled Tribe listed for the state",
      "Permanent resident of the state",
      "Tribal affiliation through lineage (father/mother)",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Ration card / residence proof",
      "ST certificate of father / mother / blood relative",
      "School leaving certificate showing tribal affiliation",
      "Birth certificate",
      "Affidavit of caste in prescribed format",
      "Recent photograph",
    ],
    fee: 10,
    feeNote: "₹10-₹40 application fee depending on state; free for BPL.",
    processingTime: "15-30 days",
    howToApply: [
      "Visit the state e-District portal or Tehsil office.",
      "Register and select 'Caste Certificate (ST)' service.",
      "Fill the application form with personal, parent and tribe details.",
      "Upload Aadhaar, parent's ST certificate, residence proof, photograph and affidavit.",
      "Pay the fee online; Tribal Welfare / Revenue Officer verifies; certificate dispatched by post.",
    ],
    serviceCharge: 80,
    popularity: 85,
    tags: ["caste certificate", "st", "scheduled tribe", "reservation", "tribal welfare"],
    online: true,
  },
  {
    id: "caste-certificate-obc",
    slug: "caste-certificate-obc",
    name: "Caste Certificate (OBC — Other Backward Class)",
    category: "certificates",
    subcategory: "Caste Certificates",
    summary: "Issue of OBC caste certificate for reservation in education and employment.",
    description:
      "The OBC Caste Certificate is issued by the State Revenue Department to persons belonging to a Backward Class listed in the state's OBC list. The certificate enables reservation in state government jobs, educational institutions and other state welfare schemes. The Central list of OBCs is maintained by the NCBC and may differ from state lists; the OBC certificate is distinct from the Non-Creamy Layer certificate required for Central jobs.",
    ministry: "State Revenue / Backward Classes Welfare Department",
    officialPortal: "State e-District Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Person belonging to a caste listed in the State OBC list",
      "Permanent resident of the state",
      "Family income within state-prescribed creamy layer limit (₹8 lakh for Central)",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Ration card / residence proof",
      "OBC certificate of father / mother / blood relative",
      "School leaving certificate",
      "Birth certificate",
      "Income certificate (for creamy layer verification)",
      "Affidavit of caste in prescribed format",
      "Recent photograph",
    ],
    fee: 10,
    feeNote: "₹10-₹40 application fee depending on state; free for BPL.",
    processingTime: "15-30 days",
    howToApply: [
      "Visit the state e-District portal or Tehsil office.",
      "Register and select 'Caste Certificate (OBC)' service.",
      "Fill the application form with personal, parent and caste details; provide income.",
      "Upload Aadhaar, parent's OBC certificate, income certificate, photograph and affidavit.",
      "Pay the fee online; certificate is issued after Revenue Officer verification and dispatched by post.",
    ],
    serviceCharge: 80,
    popularity: 90,
    tags: ["caste certificate", "obc", "backward class", "reservation", "e-district"],
    online: true,
  },
  {
    id: "obc-non-creamy-layer-certificate",
    slug: "obc-non-creamy-layer-certificate",
    name: "OBC Non-Creamy Layer Certificate",
    category: "certificates",
    subcategory: "Caste Certificates",
    summary: "Income & asset based certificate enabling OBC reservation in Central government jobs / education.",
    description:
      "The OBC Non-Creamy Layer (NCL) Certificate is required to avail OBC reservation in Central Government jobs and Central educational institutions. Issued by the District Magistrate / Competent Authority on the basis of family income and parents' service category. The creamy layer ceiling is ₹8 lakh per annum (parents' income); certain categories like Group A/Class I officers' children are excluded irrespective of income. The certificate is valid for one financial year.",
    ministry: "Ministry of Social Justice & Empowerment (NCBC)",
    officialPortal: "State e-District Portal / NCBC",
    officialUrl: "https://ncbc.nic.in/",
    eligibility: [
      "Person belonging to a caste in the Central OBC list",
      "Family income (parents) below ₹8 lakh per annum",
      "Parents not in Group A/Class I service or equivalent constitutional posts",
      "Certificate valid for one financial year; renew each year",
    ],
    documentsRequired: [
      "Aadhaar card",
      "OBC caste certificate of self / parent",
      "Income certificate (Form VIII) for current financial year",
      "PAN card of parents",
      "ITR of parents for last 3 years",
      "Service category proof of parents (if government servant)",
      "Land records / asset declaration",
      "Recent photograph",
    ],
    fee: 20,
    feeNote: "₹20-₹50 application fee; valid for one financial year only.",
    processingTime: "15-30 days",
    howToApply: [
      "Visit the state e-District portal or the office of the Competent Authority (DM/SDM/Tehsildar).",
      "Fill Form OBC-NCL with personal, parent service category and income details.",
      "Upload Aadhaar, OBC certificate, income proof, ITR, PAN of parents and asset declaration.",
      "Pay the fee online; certificate is verified by the Tehsildar and Competent Authority.",
      "Issued certificate explicitly mentions 'Non-Creamy Layer' and is valid for the FY.",
    ],
    serviceCharge: 90,
    popularity: 88,
    tags: ["obc", "non-creamy layer", "ncl", "reservation", "central government", "income"],
    online: true,
  },
  {
    id: "ews-certificate",
    slug: "ews-certificate",
    name: "EWS (Economically Weaker Section) Certificate",
    category: "certificates",
    subcategory: "Caste & Economic Certificates",
    summary: "Income & asset certificate for 10% EWS reservation in Central government jobs & education.",
    description:
      "The EWS Certificate (Income & Asset Certificate) is issued to General Category candidates whose family income is below ₹8 lakh per annum and who meet asset criteria (≤5 acre agricultural land, residential flat <1,000 sq ft, residential plot <100 sq yards in notified municipality, <200 sq yards in non-notified area). The certificate enables 10% EWS reservation in Central government jobs and Central educational institutions. Valid for one financial year.",
    ministry: "Ministry of Social Justice & Empowerment (DoPT)",
    officialPortal: "State e-District Portal",
    officialUrl: "https://persmin.gov.in/",
    eligibility: [
      "General category candidate (not covered under SC/ST/OBC reservation)",
      "Family gross annual income below ₹8 lakh",
      "Family assets within prescribed limits (agricultural land, residential property)",
      "Income includes income of self, parents, siblings below 18, spouse",
    ],
    documentsRequired: [
      "Aadhaar card",
      "PAN card of self and parents",
      "Income certificate (current FY) or ITR of parents",
      "Agricultural land records (if applicable) — Record of Rights",
      "Residential property documents (sale deed, property tax receipt)",
      "Affidavit on income and assets in prescribed format",
      "Recent photograph",
    ],
    fee: 20,
    feeNote: "₹20-₹50 application fee; valid for one financial year only.",
    processingTime: "15-30 days",
    howToApply: [
      "Visit the state e-District portal or the office of the Competent Authority (Tehsildar / SDM).",
      "Fill the EWS Income & Asset Certificate application form.",
      "Upload Aadhaar, PAN, ITR/income certificate, property records and asset affidavit.",
      "Pay the fee online; revenue officer verifies income and property records.",
      "Issued certificate explicitly mentions 'Economically Weaker Section'; valid for the current FY.",
    ],
    serviceCharge: 90,
    popularity: 86,
    tags: ["ews", "economically weaker section", "reservation", "income", "asset certificate"],
    online: true,
  },
  {
    id: "income-certificate-state",
    slug: "income-certificate-state",
    name: "Income Certificate (State)",
    category: "certificates",
    subcategory: "Economic Certificates",
    summary: "Certifies annual family income for scholarships, schemes and reservations.",
    description:
      "The Income Certificate is issued by the State Revenue Department (Tehsildar / SDM / Mandal Parishad Officer) certifying the annual family income of the applicant from all sources. The certificate is required for various Central and State schemes including scholarships (NSP), EWS reservation, OBC NCL, housing subsidies (PMAY), and BPL/AAY category. Validity is generally 6 months to 1 financial year depending on the purpose.",
    ministry: "State Revenue Department",
    officialPortal: "State e-District Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Any resident of the state",
      "Family income from all sources (salary, business, agriculture, rent, interest)",
      "Income proof for the current financial year",
    ],
    documentsRequired: [
      "Aadhaar card",
      "PAN card",
      "Salary slips (if salaried) / Form 16 / ITR",
      "Agricultural income proof (land records, sale receipts)",
      "Business income proof (GST returns, balance sheet)",
      "Affidavit of income in prescribed format",
      "Residence proof",
      "Recent photograph",
    ],
    fee: 10,
    feeNote: "₹10-₹40 application fee depending on state; free for BPL.",
    processingTime: "7-21 days",
    howToApply: [
      "Visit the state e-District portal or Tehsil office.",
      "Register and select 'Income Certificate' service.",
      "Fill the application form with personal and family income details from all sources.",
      "Upload Aadhaar, PAN, salary/ITR/business proof, income affidavit and residence proof.",
      "Pay the fee online; revenue officer verifies; certificate dispatched by post or available for download.",
    ],
    serviceCharge: 70,
    popularity: 92,
    tags: ["income certificate", "scholarship", "reservation", "e-district", "state"],
    online: true,
  },
  {
    id: "residence-domicile-certificate",
    slug: "residence-domicile-certificate",
    name: "Residence / Domicile Certificate",
    category: "certificates",
    subcategory: "Identity Certificates",
    summary: "Certifies permanent residence of a person in a particular state/UT for jobs, schemes and admissions.",
    description:
      "The Residence / Domicile Certificate is issued by the State Revenue Department to certify that a person is a permanent resident of the state/UT. The certificate is required for state government jobs, state quota admissions, state scholarships, and various welfare schemes. Domicile rules vary — typically the applicant or their parent must have resided in the state for a specified number of years (5-15 years depending on state).",
    ministry: "State Revenue Department",
    officialPortal: "State e-District Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Permanent resident of the state for the prescribed period (5-15 years)",
      "Or born in the state",
      "Or parent is a domicile of the state",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Birth certificate showing place of birth",
      "School leaving certificate / Transfer certificate",
      "Ration card / voter ID showing residence",
      "Parent's domicile certificate (if applicable)",
      "Utility bill / property documents showing residence",
      "Recent photograph",
    ],
    fee: 10,
    feeNote: "₹10-₹50 application fee depending on state.",
    processingTime: "15-30 days",
    howToApply: [
      "Visit the state e-District portal or Tehsil office.",
      "Register and select 'Residence / Domicile Certificate' service.",
      "Fill the application form with personal, residential and parent details.",
      "Upload Aadhaar, birth certificate, school TC, voter ID, residence proof and photograph.",
      "Pay the fee online; revenue officer verifies residence; certificate dispatched by post.",
    ],
    serviceCharge: 75,
    popularity: 88,
    tags: ["domicile", "residence certificate", "state", "e-district", "identity"],
    online: true,
  },
  {
    id: "birth-certificate-copy-correction",
    slug: "birth-certificate-copy-correction",
    name: "Birth Certificate Copy / Correction",
    category: "certificates",
    subcategory: "Vital Records",
    summary: "Get a duplicate copy of birth certificate or correct entries (name, parents, DOB).",
    description:
      "This service is for obtaining a duplicate certified copy of a previously registered birth certificate or for correcting entries such as the child's name, parent's name, date of birth, or place of birth. Application is filed at the Municipal Corporation / Gram Panchayat office where the birth was originally registered, or through the state's CRS (Civil Registration System) portal. Correction requires an affidavit and supporting documents.",
    ministry: "State Department of Economics & Statistics / Local Body",
    officialPortal: "CRS — Civil Registration System",
    officialUrl: "https://crsorgi.gov.in/",
    eligibility: [
      "Birth was previously registered with the local body",
      "For correction: error attributable to clerical mistake or supported by new evidence",
      "Application by the person (if adult) or parent/guardian (if minor)",
    ],
    documentsRequired: [
      "Original birth registration details (registration number / hospital record)",
      "Aadhaar card of applicant",
      "Hospital discharge summary / letter from hospital",
      "Affidavit specifying the correction required",
      "School certificate / other proof for correction",
      "Old birth certificate (for correction or copy)",
      "Photograph",
    ],
    fee: 25,
    feeNote: "₹25-₹100 for duplicate copy; ₹20-₹50 for correction depending on state.",
    processingTime: "7-21 days for copy; 30-60 days for correction",
    howToApply: [
      "Visit the office of the Registrar of Births (Municipal Corporation / Gram Panchayat) or state CRS portal.",
      "Apply for 'Duplicate Birth Certificate' or 'Correction in Birth Certificate'.",
      "Submit the registration number / hospital summary and Aadhaar.",
      "For correction, attach affidavit, supporting proof (school certificate, hospital summary) and old certificate.",
      "Fee paid; Registrar verifies; corrected certificate or duplicate dispatched within prescribed time.",
    ],
    serviceCharge: 80,
    popularity: 82,
    tags: ["birth certificate", "duplicate", "correction", "crs", "vital records"],
    online: true,
  },
  {
    id: "death-certificate-copy-correction",
    slug: "death-certificate-copy-correction",
    name: "Death Certificate Copy / Correction",
    category: "certificates",
    subcategory: "Vital Records",
    summary: "Get a duplicate copy of death certificate or correct entries (name, cause, date, place).",
    description:
      "This service is for obtaining a duplicate certified copy of a previously registered death certificate or for correcting entries such as the deceased's name, parent/spouse name, date of death, place of death, or cause of death. Application is filed at the Municipal Corporation / Gram Panchayat where the death was originally registered, or through the state's CRS portal. Correction may require a medical board's certificate if cause of death is being corrected.",
    ministry: "State Department of Economics & Statistics / Local Body",
    officialPortal: "CRS — Civil Registration System",
    officialUrl: "https://crsorgi.gov.in/",
    eligibility: [
      "Death was previously registered with the local body",
      "Application by next of kin / legal heir / authorised person",
      "For correction: error supported by documentary evidence",
    ],
    documentsRequired: [
      "Original death registration details (registration number)",
      "Aadhaar card of applicant",
      "Hospital / cremation ground certificate",
      "Affidavit specifying the correction required",
      "Medical board certificate (if cause of death correction)",
      "Old death certificate (if available)",
      "Proof of relationship with deceased",
    ],
    fee: 25,
    feeNote: "₹25-₹100 for duplicate copy; ₹20-₹50 for correction.",
    processingTime: "7-21 days for copy; 30-60 days for correction",
    howToApply: [
      "Visit the office of the Registrar of Deaths (Municipal Corporation / Gram Panchayat) or state CRS portal.",
      "Apply for 'Duplicate Death Certificate' or 'Correction in Death Certificate'.",
      "Submit the registration number and Aadhaar of applicant; relationship proof with deceased.",
      "For correction, attach affidavit, hospital/medical board certificate and old certificate.",
      "Fee paid; Registrar verifies; corrected certificate or duplicate dispatched within prescribed time.",
    ],
    serviceCharge: 80,
    popularity: 78,
    tags: ["death certificate", "duplicate", "correction", "crs", "vital records"],
    online: true,
  },
  {
    id: "marriage-registration-certificate-hindu",
    slug: "marriage-registration-certificate-hindu",
    name: "Marriage Registration Certificate (Hindu Marriage Act)",
    category: "certificates",
    subcategory: "Marriage Certificates",
    summary: "Register and obtain marriage certificate under the Hindu Marriage Act, 1955.",
    description:
      "Marriage registration under the Hindu Marriage Act, 1955 is mandatory for Hindus, Buddhists, Jains and Sikhs. The marriage is registered with the Sub-Registrar / Marriage Officer where the marriage was solemnised or where either spouse resided for at least 6 months. The application requires both spouses to appear with witnesses. The Supreme Court has held registration compulsory regardless of religion.",
    ministry: "State Department of Revenue / Local Body",
    officialPortal: "State Marriage Registration Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Both spouses are Hindus / Buddhists / Jains / Sikhs",
      "Groom aged 21+ years and bride aged 18+ years at time of marriage",
      "Marriage solemnised as per Hindu rites or court marriage",
      "Either spouse resided in the jurisdiction for 6+ months",
    ],
    documentsRequired: [
      "Aadhaar card of both spouses",
      "PAN card / Voter ID of both spouses",
      "Date of birth proof (Class 10 certificate / birth certificate)",
      "Address proof of both spouses",
      "Marriage invitation card / photograph",
      "Affidavit of marriage in prescribed format",
      "Two witnesses with Aadhaar and address proof",
      "Recent photographs of both spouses",
    ],
    fee: 100,
    feeNote: "₹100-₹500 depending on state and time of registration (late fee applies after 90 days).",
    processingTime: "7-30 days",
    howToApply: [
      "Visit the Sub-Registrar / Marriage Registration office where the marriage was solemnised or where spouses reside.",
      "Fill Form 1 (Hindu Marriage Registration) with details of both spouses and marriage.",
      "Attach Aadhaar, age proof, address proof, marriage invitation, affidavit and photographs.",
      "Both spouses and two witnesses appear before the Marriage Officer for verification.",
      "On verification, Marriage Registration Certificate is issued same day or within 7-30 days.",
    ],
    serviceCharge: 110,
    popularity: 86,
    tags: ["marriage certificate", "hindu marriage act", "registration", "sub-registrar"],
    online: true,
  },
  {
    id: "marriage-registration-certificate-special",
    slug: "marriage-registration-certificate-special",
    name: "Marriage Registration Certificate (Special Marriage Act)",
    category: "certificates",
    subcategory: "Marriage Certificates",
    summary: "Register inter-faith / civil marriage under the Special Marriage Act, 1954.",
    description:
      "Marriage registration under the Special Marriage Act, 1954 allows couples of any religion (or different religions) to marry in a civil ceremony. The procedure requires a 30-day public notice at the Marriage Officer's office, during which objections can be raised. After notice period, the marriage is solemnised in the presence of three witnesses and a marriage certificate is issued by the Marriage Officer.",
    ministry: "State Department of Revenue / Local Body",
    officialPortal: "State Marriage Registration Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Either spouse can be of any religion",
      "Groom aged 21+ years and bride aged 18+ years at time of marriage",
      "Neither spouse has a living spouse at the time of marriage",
      "Parties of unsound mind or incapable of valid consent are not eligible",
      "At least one party resided in the jurisdiction for 30+ days before notice",
    ],
    documentsRequired: [
      "Aadhaar card of both spouses",
      "PAN card / Voter ID of both spouses",
      "Date of birth proof (Class 10 certificate / birth certificate)",
      "Address proof showing 30+ days residence",
      "Affidavit of marital status (unmarried / divorced / widowed)",
      "Passport-size photographs of both spouses",
      "Three witnesses with Aadhaar and address proof",
      "Divorce decree / spouse's death certificate (if previously married)",
    ],
    fee: 150,
    feeNote: "₹150 notice fee + ₹150 solemnisation fee; state variations apply.",
    processingTime: "30-45 days (mandatory 30-day notice period)",
    howToApply: [
      "Visit the office of the Marriage Officer (SDM / ADM) where either spouse has resided for 30+ days.",
      "File Notice of Intended Marriage in the prescribed form with both spouses' details.",
      "Submit documents; the Marriage Officer publishes the notice for 30 days for objections.",
      "If no objection, both spouses and three witnesses appear on the chosen date for solemnisation.",
      "Marriage is solemnised; Marriage Certificate is issued by the Marriage Officer same day.",
    ],
    serviceCharge: 130,
    popularity: 70,
    tags: ["marriage certificate", "special marriage act", "inter-faith", "civil marriage"],
    online: true,
  },
  {
    id: "divorce-decree-copy",
    slug: "divorce-decree-copy",
    name: "Divorce Decree Certified Copy",
    category: "certificates",
    subcategory: "Court Records",
    summary: "Obtain a certified copy of the divorce decree from the Family / District Court.",
    description:
      "A certified copy of the divorce decree (also called a Divorce Judgment Copy) is required for remarriage, updating Aadhaar/pan/bank records, claim of alimony, and immigration. Application is filed at the Family Court / District Court where the divorce was granted, with the case number and year. The copy is issued under the supervision of the Registrar of the Court after payment of the prescribed fee.",
    ministry: "State High Court / Family Court",
    officialPortal: "State e-Courts / District Court",
    officialUrl: "https://districts.ecourts.gov.in/",
    eligibility: [
      "Divorce decree was passed by an Indian court",
      "Applicant is a party to the case or authorised representative",
      "Application with case number, year and court name",
    ],
    documentsRequired: [
      "Case number / CNR number of the divorce case",
      "Aadhaar card of applicant",
      "Identity of applicant as party to the case",
      "Application form for certified copy",
      "Fee payment receipt",
    ],
    fee: 50,
    feeNote: "₹50-₹200 per page depending on court; copying and certification fee extra.",
    processingTime: "5-15 working days",
    howToApply: [
      "Visit the District / Family Court where the divorce was granted, or apply via e-Courts services.",
      "File an application for 'Certified Copy of Decree' with case number, year and court.",
      "Attach Aadhaar and proof of being a party; pay the prescribed fee at the court counter.",
      "Court staff retrieves the decree record and prepares the certified copy.",
      "Certified copy with court seal and registrar signature is handed over or dispatched by post.",
    ],
    serviceCharge: 90,
    popularity: 50,
    tags: ["divorce decree", "certified copy", "court", "family court", "remarriage"],
    online: false,
  },
  {
    id: "legal-heir-certificate",
    slug: "legal-heir-certificate",
    name: "Legal Heir Certificate",
    category: "certificates",
    subcategory: "Succession & Heirship",
    summary: "Establishes relationship of legal heirs to a deceased person for transfer of utilities / bank accounts.",
    description:
      "The Legal Heir Certificate is issued by the Tahsildar / Revenue Officer of the district to identify the legal heirs of a deceased person. The certificate is required for transfer of electricity connection, LPG connection, telephone, bank accounts (small amounts), PF, pension initiation and certain property matters. It is distinct from a Succession Certificate (issued by court for movable assets without a will).",
    ministry: "State Revenue Department (Tahsildar Office)",
    officialPortal: "State e-District Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Applicant is a family member (spouse / son / daughter / parent) of the deceased",
      "Deceased was a resident of the state",
      "Death registered and death certificate available",
    ],
    documentsRequired: [
      "Death certificate of the deceased",
      "Aadhaar card of applicant and deceased",
      "Ration card showing family members",
      "Residence proof of the deceased",
      "Family genealogy affidavit",
      "No-objection from other legal heirs (if any)",
      "Recent photograph",
    ],
    fee: 20,
    feeNote: "₹20-₹50 application fee depending on state.",
    processingTime: "15-30 days",
    howToApply: [
      "Visit the Taluk / Tahsildar office or state e-District portal.",
      "Fill the Legal Heir Certificate application form with deceased's details.",
      "Attach death certificate, Aadhaar, ration card, residence proof and family genealogy affidavit.",
      "Submit; Revenue Inspector / VAO conducts inquiry at the residence.",
      "Tahsildar issues the Legal Heir Certificate listing all legal heirs.",
    ],
    serviceCharge: 90,
    popularity: 80,
    tags: ["legal heir", "heirship", "death", "succession", "revenue", "e-district"],
    online: true,
  },
  {
    id: "succession-certificate",
    slug: "succession-certificate",
    name: "Succession Certificate (Court)",
    category: "certificates",
    subcategory: "Succession & Heirship",
    summary: "Court-issued certificate for inheriting movable assets (debts, securities) of a deceased without a will.",
    description:
      "A Succession Certificate is issued by a District Court under Section 372 of the Indian Succession Act, 1925, granting authority to a successor to realise debts and securities of a deceased person who died intestate (without a will). It is required for transfer of bank deposits, shares, mutual funds, and PF when there is no nomination or will. The procedure involves a public notice and judicial inquiry.",
    ministry: "Judiciary (District Court)",
    officialPortal: "District Court / e-Courts",
    officialUrl: "https://districts.ecourts.gov.in/",
    eligibility: [
      "Deceased died intestate (without a will) leaving movable assets",
      "Applicant is a legal heir under the personal law applicable",
      "No other succession certificate granted earlier",
    ],
    documentsRequired: [
      "Death certificate of the deceased",
      "Aadhaar card of applicant",
      "Petition under Section 372 of Indian Succession Act",
      "List of assets (bank accounts, shares, mutual funds, PF)",
      "Family tree / genealogy affidavit",
      "No-objection from other legal heirs (or notice to them)",
      "Court fee stamp paper",
    ],
    fee: 500,
    feeNote: "Court fee varies by state — ad valorem on asset value (capped in many states).",
    processingTime: "5-7 months (including 45-day public notice)",
    howToApply: [
      "Engage an advocate to file a petition under Section 372 of the Indian Succession Act in District Court.",
      "Submit the petition with death certificate, list of assets, family genealogy and court fee.",
      "Court issues notice to all legal heirs and publishes notice in newspaper for 45 days.",
      "If no objection, court conducts hearing and grants the Succession Certificate.",
      "Certificate is issued in favour of the applicant to realise the listed assets.",
    ],
    serviceCharge: 150,
    popularity: 55,
    tags: ["succession certificate", "court", "intestate", "movable assets", "indian succession act"],
    online: false,
  },
  {
    id: "character-certificate-police-verification",
    slug: "character-certificate-police-verification",
    name: "Character Certificate (Police Verification)",
    category: "certificates",
    subcategory: "Police Verification",
    summary: "Police-issued character certificate for employment, visa and licensing purposes.",
    description:
      "The Character Certificate (also called Police Verification Certificate or Antecedents Certificate) is issued by the local Police Station / Superintendent of Police certifying that the holder has no criminal record. The certificate is required for certain jobs (private security, hospitality, child-related work), visa/immigration applications, firearm licences, and franchisee registrations. Application is filed at the local police station.",
    ministry: "State Police Department",
    officialPortal: "State Police / Passport Seva Portal",
    officialUrl: "https://www.police.gov.in/",
    eligibility: [
      "Resident of the police station jurisdiction for at least 1 year",
      "No criminal antecedents (or disclosed and explained)",
      "Purpose: employment, visa, licensing, etc.",
    ],
    documentsRequired: [
      "Aadhaar card",
      "PAN card",
      "Address proof (ration card, voter ID, utility bill)",
      "Recent passport-size photograph",
      "Purpose proof (offer letter, visa application, franchisee letter)",
      "Self-attested declaration of no criminal record",
    ],
    fee: 50,
    feeNote: "₹50-₹200 depending on state and purpose; free for BPL in some states.",
    processingTime: "7-21 days",
    howToApply: [
      "Visit the local Police Station / SP Office or the state police citizen portal.",
      "Fill the Character Certificate application form with personal and address details.",
      "Submit Aadhaar, address proof, photograph and purpose proof.",
      "Pay the fee; police conducts verification of antecedents and residence.",
      "On clearance, Character Certificate is issued by the SHO / SP and can be collected from the police station.",
    ],
    serviceCharge: 80,
    popularity: 75,
    tags: ["character certificate", "police verification", "antecedents", "visa", "employment"],
    online: true,
  },
  {
    id: "solvency-certificate",
    slug: "solvency-certificate",
    name: "Solvency Certificate",
    category: "certificates",
    subcategory: "Economic Certificates",
    summary: "Certifies the financial capacity / net worth of an individual for tenders and legal purposes.",
    description:
      "A Solvency Certificate is issued by the District Magistrate / SDM / Tehsildar certifying the financial solvency of an individual or firm — i.e., that they have assets worth a stated amount. The certificate is required for participation in government tenders, surety bonds, court matters, and certain licences. The valuation is based on immovable property (with encumbrance certificate), bank deposits, shares, and other liquid assets.",
    ministry: "State Revenue Department (DM / SDM / Tehsildar)",
    officialPortal: "State e-District Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Indian citizen with assets (immovable property, bank deposits, shares) worth the declared amount",
      "Resident of the issuing jurisdiction",
      "No insolvency proceedings pending",
    ],
    documentsRequired: [
      "Aadhaar card",
      "PAN card",
      "Property documents (sale deed, encumbrance certificate)",
      "Latest property tax receipts",
      "Bank statement / FD receipts",
      "Share / mutual fund statements",
      "Affidavit of solvency in prescribed format",
      "Two witnesses",
    ],
    fee: 50,
    feeNote: "₹50-₹500 depending on state and amount of solvency declared.",
    processingTime: "7-21 days",
    howToApply: [
      "Visit the SDM / Tehsildar office or state e-District portal.",
      "Fill the Solvency Certificate application form declaring the required solvency amount.",
      "Attach property documents, encumbrance certificate, bank/FD statements and affidavit of solvency.",
      "Pay the fee; revenue officer verifies property records and bank documents.",
      "Solvency Certificate is issued stating the declared financial capacity.",
    ],
    serviceCharge: 100,
    popularity: 60,
    tags: ["solvency", "financial capacity", "tender", "surety", "e-district"],
    online: true,
  },
  {
    id: "nativity-certificate",
    slug: "nativity-certificate",
    name: "Nativity Certificate",
    category: "certificates",
    subcategory: "Identity Certificates",
    summary: "Certifies that a person is native to a particular state for state-specific quotas & schemes.",
    description:
      "The Nativity Certificate is issued by the State Revenue Department (Tahsildar) certifying that the applicant is a native of that state. The certificate is required for state-specific quotas (e.g., Tamil Nadu medical admissions, Karnataka CET), state scholarships, and certain employment reservations. Nativity is established through birth in the state or parents'/grandparents' residence in the state.",
    ministry: "State Revenue Department (Tahsildar Office)",
    officialPortal: "State e-District Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Born in the state, OR",
      "Parents/grandparents were permanent residents of the state",
      "Continuous residence in the state for a prescribed period",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Birth certificate showing place of birth in the state",
      "School records (TC, SSLC / Class 10 certificate) showing study in the state",
      "Ration card / voter ID showing residence",
      "Parent's nativity certificate / birth certificate",
      "Affidavit of nativity in prescribed format",
      "Recent photograph",
    ],
    fee: 10,
    feeNote: "₹10-₹50 application fee depending on state.",
    processingTime: "15-30 days",
    howToApply: [
      "Visit the Tahsildar office or state e-District portal.",
      "Fill the Nativity Certificate application form.",
      "Attach Aadhaar, birth certificate, school records, parent's nativity / birth certificate and affidavit.",
      "Pay the fee; revenue officer verifies records.",
      "Nativity Certificate issued and dispatched by post or available for download.",
    ],
    serviceCharge: 70,
    popularity: 70,
    tags: ["nativity", "native", "state quota", "e-district", "identity"],
    online: true,
  },
  {
    id: "senior-citizen-certificate",
    slug: "senior-citizen-certificate",
    name: "Senior Citizen Certificate",
    category: "certificates",
    subcategory: "Identity Certificates",
    summary: "Government certificate proving age 60+ for senior citizen concessions in travel, tax and health.",
    description:
      "The Senior Citizen Certificate is issued by the State Revenue Department (Tahsildar / SDM) to persons aged 60 years and above. The certificate is used for availing income tax benefits (higher exemption limits), railway / air travel concessions, hospital priority queues, separate counters in banks, lower property tax in some states, and Maintenance Tribunal claims. Distinct from the Senior Citizen ID Card.",
    ministry: "State Revenue Department",
    officialPortal: "State e-District Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Age 60 years or above",
      "Resident of the state",
      "Holds valid age proof",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Age proof (Voter ID, PAN, birth certificate, school TC)",
      "Residence proof of the state",
      "Recent photograph",
      "Affidavit of age in prescribed format (if required)",
    ],
    fee: 10,
    feeNote: "₹10-₹50 application fee; free for BPL.",
    processingTime: "7-15 days",
    howToApply: [
      "Visit the Tahsildar / SDM office or state e-District portal.",
      "Fill the Senior Citizen Certificate application form with age and residence details.",
      "Upload Aadhaar, age proof (60+), residence proof and photograph.",
      "Pay the fee online; revenue officer verifies age proof.",
      "Certificate is issued and dispatched by post or available for download.",
    ],
    serviceCharge: 60,
    popularity: 78,
    tags: ["senior citizen", "certificate", "age 60", "concession", "e-district"],
    online: true,
  },
  {
    id: "disability-concession-travel-card",
    slug: "disability-concession-travel-card",
    name: "Disability Concession Travel Card",
    category: "certificates",
    subcategory: "Disability & Concession",
    summary: "Travel concession card for persons with disabilities on Indian Railways, buses and airlines.",
    description:
      "The Disability Concession Travel Card is issued by the State Social Welfare Department / Railways to persons with disabilities (40% or more) holding a valid disability certificate. The card enables 50-75% fare concession in Indian Railways (varies by disability type and class), free travel in state buses (in most states), and 50% concession on Air India flights for persons with 80%+ locomotor disability or blindness. Application requires a disability certificate from a Medical Board.",
    ministry: "Ministry of Social Justice & Empowerment (DEPwD)",
    officialPortal: "Indian Railways / State Social Welfare",
    officialUrl: "https://railwayhelp.com/",
    eligibility: [
      "Person with benchmark disability (40% or more)",
      "Holds a valid disability certificate from a Medical Board",
      "Indian citizen",
    ],
    documentsRequired: [
      "Disability certificate (40% or more) from Medical Board",
      "Aadhaar card",
      "Two recent passport-size photographs",
      "Address proof",
      "Photo ID proof",
      "Concession card application form",
    ],
    fee: 0,
    feeNote: "Free. Railways charges no fee for the concession certificate.",
    processingTime: "15-30 days",
    howToApply: [
      "Approach the State Social Welfare Office or the Divisional Railway Manager (DRM) office.",
      "Fill the Disability Travel Concession Card application form.",
      "Attach disability certificate, Aadhaar, address proof, photographs and photo ID.",
      "Submit; verification by Medical Officer of the Railways / Welfare Officer.",
      "Concession card is issued; carry the card along with photo ID during travel.",
    ],
    serviceCharge: 75,
    popularity: 65,
    tags: ["disability", "concession", "travel", "railway", "divyang", "travel card"],
    online: false,
  },
  {
    id: "income-asset-certificate-sc-st",
    slug: "income-asset-certificate-sc-st",
    name: "Income & Asset Certificate for SC / ST",
    category: "certificates",
    subcategory: "Economic Certificates",
    summary: "Combined income and asset certificate for SC/ST for educational and employment reservations.",
    description:
      "The Income & Asset Certificate for SC/ST is issued by the Competent Authority (Tahsildar / SDM) under the DoPT OM dated 21.02.2024 to enable SC/ST candidates to avail reservations in Central Government jobs and Central educational institutions. The certificate combines income and asset details and must explicitly mention 'Creamy Layer status' (Not applicable to SC/ST in pure reservation, but used for OBC within SC/ST sub-categorisation in some contexts). Valid for one financial year.",
    ministry: "Ministry of Social Justice & Empowerment / DoPT",
    officialPortal: "State e-District Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Person belonging to SC or ST category",
      "Family income and assets within prescribed limits",
      "Resident of the state",
    ],
    documentsRequired: [
      "Aadhaar card",
      "SC / ST caste certificate",
      "PAN card of self and parents",
      "ITR of parents for last 3 years",
      "Salary slips / Form 16",
      "Agricultural land records / property documents",
      "Affidavit of income and assets in prescribed format",
      "Recent photograph",
    ],
    fee: 20,
    feeNote: "₹20-₹50 application fee; valid for one financial year.",
    processingTime: "15-30 days",
    howToApply: [
      "Visit the Tahsildar / SDM office or state e-District portal.",
      "Fill the Income & Asset Certificate (SC/ST) application form.",
      "Attach Aadhaar, SC/ST certificate, PAN, ITR, salary slips, land records and asset affidavit.",
      "Pay the fee; revenue officer verifies income and property records.",
      "Certificate is issued with explicit creamy layer status and is valid for the FY.",
    ],
    serviceCharge: 90,
    popularity: 65,
    tags: ["income", "asset", "sc", "st", "reservation", "e-district"],
    online: true,
  },
  {
    id: "conversion-certificate-religion",
    slug: "conversion-certificate-religion",
    name: "Conversion Certificate (Religion)",
    category: "certificates",
    subcategory: "Religious Records",
    summary: "Certifies conversion of religion for legal records, marriage registration and inheritance matters.",
    description:
      "A Conversion Certificate is issued by the religious institution where the conversion ceremony was performed, and is registered with the local Sub-Registrar / Magistrate in some states. It is required for updating government records (Aadhaar, PAN, voter ID), marriage registration under different personal laws, and inheritance / succession under the new religion's personal law. Some states require a declaration before a Magistrate.",
    ministry: "State Religious Affairs / Revenue Department",
    officialPortal: "State e-District Portal",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Person who has converted to a new religion through a recognised ceremony",
      "Conversion done voluntarily without force or allurement",
      "Adult (18+) or with parent's consent if minor (varies by state)",
    ],
    documentsRequired: [
      "Aadhaar card",
      "PAN card",
      "Certificate of conversion from the religious institution",
      "Affidavit of conversion in prescribed format",
      "Two witnesses with Aadhaar",
      "Photograph during conversion ceremony",
      "Address proof",
    ],
    fee: 50,
    feeNote: "₹50-₹200 affidavit + state registration fee (varies).",
    processingTime: "15-30 days",
    howToApply: [
      "Obtain a Conversion Certificate from the religious institution (temple / church / mosque / gurdwara).",
      "Draft an affidavit of conversion declaring the change of religion voluntarily.",
      "Approach the Sub-Registrar / SDM office with the conversion certificate, affidavit, Aadhaar and witnesses.",
      "Pay the prescribed fee; the Magistrate verifies and registers the conversion.",
      "Conversion Certificate is issued; use to update Aadhaar, PAN, voter ID, marriage registration.",
    ],
    serviceCharge: 100,
    popularity: 35,
    tags: ["conversion", "religion", "affidavit", "sub-registrar", "personal law"],
    online: false,
  },
  {
    id: "stamp-paper-affidavit",
    slug: "stamp-paper-affidavit",
    name: "Stamp Paper Affidavit Notarisation",
    category: "certificates",
    subcategory: "Affidavit & Stamp",
    summary: "Draft and notarise affidavits on stamp paper for declarations, name change, and legal purposes.",
    description:
      "An affidavit is a written statement sworn before a Notary Public or Oath Commissioner on stamp paper of prescribed value. Common affidavits include name change, date of birth declaration, income declaration, one and the same person declaration, succession, and various other legal declarations. The stamp paper value varies by state and the type of affidavit (₹10, ₹20, ₹50, ₹100, ₹500). e-Stamp papers are available through SHCIL / Stock Holding Corporation of India.",
    ministry: "State Revenue Department (Stamps & Registration)",
    officialPortal: "SHCIL — Stock Holding Corporation of India",
    officialUrl: "https://www.shcilestamp.com/",
    eligibility: [
      "Any person above 18 years of age",
      "Of sound mind",
      "Personal knowledge of the facts being sworn",
    ],
    documentsRequired: [
      "Aadhaar card of the deponent",
      "PAN card",
      "Address proof",
      "Supporting documents for the subject of affidavit",
      "Stamp paper of prescribed value",
      "Photograph of deponent",
    ],
    fee: 100,
    feeNote: "Stamp paper ₹10-₹500 (depending on affidavit type) + notary fee ₹50-₹200.",
    processingTime: "Same day",
    howToApply: [
      "Purchase stamp paper of the prescribed value (from authorised vendor or via shcilestamp.com).",
      "Draft the affidavit with the declaration, deponent's details and notary block.",
      "Print on stamp paper and affix passport-size photograph of the deponent.",
      "Visit a Notary Public / Oath Commissioner with Aadhaar and supporting documents.",
      "Notary verifies identity and administers oath; signs and seals the affidavit. Keep original.",
    ],
    serviceCharge: 80,
    popularity: 80,
    tags: ["affidavit", "stamp paper", "notary", "declaration", "e-stamp", "shcil"],
    online: true,
  },
];
