// Tilak E-Seva Portal — Citizenship & Immigration services.
// Real Indian government services from Passport Seva (MEAPS), Bureau of
// Immigration (FRRO), OCI Services (MOIA) and the Indian e-Visa portal.

import type { GovernmentService } from "../types";

export const citizenshipImmigration: GovernmentService[] = [
  {
    id: "fresh-passport-normal",
    slug: "fresh-passport-normal",
    name: "Fresh Passport (Normal)",
    category: "citizenship-immigration",
    subcategory: "Passport",
    summary: "Apply for a fresh Indian passport under the Normal scheme.",
    description:
      "Indian citizens can apply for a fresh passport under the Normal scheme on the Passport Seva portal. The 36-page booklet costs ₹1,500 (adult) and the 60-page booklet ₹2,000. The process requires an appointment at a Passport Seva Kendra (PSK) for document verification and police verification thereafter.",
    ministry: "Ministry of External Affairs — Passport Seva (MEAPS)",
    officialPortal: "Passport Seva Portal",
    officialUrl: "https://www.passportindia.gov.in/",
    eligibility: [
      "Indian citizen by birth / registration / naturalization",
      "First-time applicant with no previous passport",
    ],
    documentsRequired: [
      "Proof of Date of Birth (birth certificate, school leaving certificate)",
      "Proof of Address (Aadhaar, utility bill, bank passbook)",
      "Proof of Identity (PAN, Aadhaar, Voter ID)",
      "Self-attested copies + originals for verification",
    ],
    fee: 1500,
    feeNote: "₹1,500 (36 pages) / ₹2,000 (60 pages) for adults; ₹1,000 for minors under 18.",
    processingTime: "30–45 days (incl. police verification)",
    howToApply: [
      "Register on passportindia.gov.in and create a login.",
      "Fill the application form and select 'Normal' scheme.",
      "Pay the fee online and schedule an appointment at a PSK.",
      "Visit PSK on the appointment date with originals + self-attested copies.",
      "Police verification follows; passport is dispatched by India Post.",
    ],
    serviceCharge: 100,
    popularity: 95,
    tags: ["passport", "fresh", "normal", "mea", "psk", "indian"],
    online: true,
  },
  {
    id: "tatkal-passport",
    slug: "tatkal-passport",
    name: "Tatkal Passport",
    category: "citizenship-immigration",
    subcategory: "Passport",
    summary: "Get a passport faster with the Tatkal scheme — 1–3 working days.",
    description:
      "Tatkal passport applications are processed on priority, with passport dispatch typically within 1–3 working days of PSK visit (subject to clear police verification). The Tatkal fee is additional to the normal passport fee — ₹1,500 for re-issue and ₹2,000 (re-issue) for fresh Tatkal.",
    ministry: "Ministry of External Affairs — Passport Seva (MEAPS)",
    officialPortal: "Passport Seva Portal",
    officialUrl: "https://www.passportindia.gov.in/",
    eligibility: [
      "Indian citizen needing urgent travel",
      "Applicants with verifiable identity / address documents",
    ],
    documentsRequired: [
      "Standard passport proofs (DOB, Address, Identity)",
      "Additional Tatkal Annexure (self-declaration)",
      "Pre-verification documents — Aadhaar / Voter ID preferred",
    ],
    fee: 3500,
    feeNote: "₹3,500 (36 pages) or ₹4,000 (60 pages) for adults = ₹1,500 normal + ₹2,000 Tatkal.",
    processingTime: "1–3 working days",
    howToApply: [
      "Register / log in at passportindia.gov.in.",
      "Fill the application and select 'Tatkal' scheme.",
      "Pay combined fee online and book PSK appointment.",
      "Visit PSK with originals + Annexures; verification is initiated same day.",
      "Police verification (post-issuance in most cases); passport dispatched in 1–3 days.",
    ],
    serviceCharge: 130,
    popularity: 90,
    tags: ["passport", "tatkal", "urgent", "mea", "psk", "fast"],
    online: true,
  },
  {
    id: "passport-renewal-re-issue",
    slug: "passport-renewal-re-issue",
    name: "Passport Renewal / Re-issue",
    category: "citizenship-immigration",
    subcategory: "Passport",
    summary: "Re-issue passport on expiry, exhaustion of pages or change in details.",
    description:
      "Passport re-issue is required when the existing passport is expiring within 1 year / expired up to 3 years ago, pages are exhausted, or details (name, spouse name, address) have changed. Application is filed on the Passport Seva portal under the 'Re-issue of Passport' category.",
    ministry: "Ministry of External Affairs — Passport Seva (MEAPS)",
    officialPortal: "Passport Seva Portal",
    officialUrl: "https://www.passportindia.gov.in/",
    eligibility: [
      "Existing Indian passport holder",
      "Passport expiring within 1 year / expired up to 3 years ago",
      "Change in personal details requiring new booklet",
    ],
    documentsRequired: [
      "Original passport (old)",
      "Self-attested copy of first and last pages",
      "Proof of new address / name change document (if applicable)",
      "Marriage certificate / divorce decree / spouse passport (if adding spouse name)",
    ],
    fee: 1500,
    feeNote: "₹1,500 (36 pages) / ₹2,000 (60 pages); Tatkal adds ₹1,500–₹2,000.",
    processingTime: "15–30 days (Normal); 1–3 days (Tatkal)",
    howToApply: [
      "Log in to passportindia.gov.in → Apply for Re-issue.",
      "Select reason (expiry / exhausted pages / change in details).",
      "Pay fee and schedule PSK appointment.",
      "Visit PSK with old passport and supporting documents.",
      "Police verification may be waived if address unchanged; new passport dispatched in 2–4 weeks.",
    ],
    serviceCharge: 100,
    popularity: 92,
    tags: ["passport", "renewal", "re-issue", "mea", "psk"],
    online: true,
  },
  {
    id: "passport-for-minors",
    slug: "passport-for-minors",
    name: "Passport for Minors",
    category: "citizenship-immigration",
    subcategory: "Passport",
    summary: "Apply for a passport for children below 18 years.",
    description:
      "Passports for minors (below 18) are issued with 5-year validity or until the child turns 18, whichever is earlier. Both parents' consent is required; Annexure D (declaration) must be signed. The fee is ₹1,000 and the booklet is 36 pages.",
    ministry: "Ministry of External Affairs — Passport Seva (MEAPS)",
    officialPortal: "Passport Seva Portal",
    officialUrl: "https://www.passportindia.gov.in/",
    eligibility: [
      "Indian citizen below 18 years",
      "Consent of both parents (or legal guardian)",
    ],
    documentsRequired: [
      "Birth certificate of minor",
      "Passports of both parents (or single parent with Annexure H)",
      "Proof of current address",
      "Annexure D (declaration of parentage)",
    ],
    fee: 1000,
    feeNote: "₹1,000 (36 pages); Tatkal ₹1,500; valid for 5 years or till age 18.",
    processingTime: "15–30 days (Normal); 1–3 days (Tatkal)",
    howToApply: [
      "Register on passportindia.gov.in with a minor's account.",
      "Apply for fresh passport and select 'Minor' category.",
      "Fill details of both parents and upload documents.",
      "Pay ₹1,000 and book PSK appointment; both parents may need to be present.",
      "Police verification often waived; passport dispatched within 2–4 weeks.",
    ],
    serviceCharge: 80,
    popularity: 80,
    tags: ["passport", "minor", "children", "mea", "psk", "infant"],
    online: true,
  },
  {
    id: "lost-damaged-passport-replacement",
    slug: "lost-damaged-passport-replacement",
    name: "Lost / Damaged Passport Replacement",
    category: "citizenship-immigration",
    subcategory: "Passport",
    summary: "Apply for a replacement passport when original is lost, stolen or damaged.",
    description:
      "If a passport is lost, stolen or damaged beyond use, the holder must file an FIR, then apply for re-issue under the 'Lost / Damaged' category. The fee is ₹3,000 (lost) or ₹3,000 (damaged) for a 36-page booklet, plus ₹2,000 Tatkal if urgent. Document verification and police verification are mandatory.",
    ministry: "Ministry of External Affairs — Passport Seva (MEAPS)",
    officialPortal: "Passport Seva Portal",
    officialUrl: "https://www.passportindia.gov.in/",
    eligibility: [
      "Indian citizen whose passport is lost / stolen / damaged",
      "FIR / Police report filed for lost/stolen cases",
    ],
    documentsRequired: [
      "Original FIR / Police acknowledgement",
      "Original damaged passport (if damaged)",
      "Proof of Identity and Address",
      "Affidavit stating how passport was lost / damaged (Annexure F)",
    ],
    fee: 3000,
    feeNote: "₹3,000 (36 pages) lost/damaged; Tatkal adds ₹2,000.",
    processingTime: "30–45 days (Normal); 1–3 days (Tatkal)",
    howToApply: [
      "File FIR at the local police station and obtain acknowledgement.",
      "Log in to passportindia.gov.in → Apply for Re-issue → Lost / Damaged.",
      "Upload FIR copy, affidavit (Annexure F) and address proof.",
      "Pay ₹3,000 + Tatkal fee if applicable; book PSK appointment.",
      "Attend PSK with originals; police verification re-confirms identity before dispatch.",
    ],
    serviceCharge: 130,
    popularity: 70,
    tags: ["passport", "lost", "damaged", "replacement", "fir", "mea"],
    online: true,
  },
  {
    id: "police-clearance-certificate",
    slug: "police-clearance-certificate",
    name: "Police Clearance Certificate (PCC)",
    category: "citizenship-immigration",
    subcategory: "Passport",
    summary: "Get a PCC for employment / long-term visa abroad.",
    description:
      "A Police Clearance Certificate (PCC) is issued to Indian passport holders who require it for emigration, employment, or long-term visa applications. It is processed only after a fresh police verification. The fee is ₹500 and the PCC is affixed on the passport or issued as a standalone certificate.",
    ministry: "Ministry of External Affairs — Passport Seva (MEAPS)",
    officialPortal: "Passport Seva Portal",
    officialUrl: "https://www.passportindia.gov.in/",
    eligibility: [
      "Indian passport holder",
      "Applied for emigration / employment / long-term visa abroad",
      "No criminal record",
    ],
    documentsRequired: [
      "Original passport",
      "Self-attested copy of first & last pages",
      "Proof of current address",
      "Letter / request from foreign employer or visa authority (if requested)",
    ],
    fee: 500,
    feeNote: "₹500 per PCC.",
    processingTime: "5–15 days after police verification",
    howToApply: [
      "Log in to passportindia.gov.in → Apply for PCC.",
      "Select the passport on which PCC is to be issued.",
      "Pay ₹500 and book PSK appointment.",
      "Visit PSK with originals; police verification initiated same day.",
      "PCC is dispatched to address or affixed in passport after verification is clear.",
    ],
    serviceCharge: 80,
    popularity: 72,
    tags: ["pcc", "police-clearance", "passport", "mea", "visa", "emigration"],
    online: true,
  },
  {
    id: "oci-card-fresh-application",
    slug: "oci-card-fresh-application",
    name: "OCI Card Fresh Application",
    category: "citizenship-immigration",
    subcategory: "OCI",
    summary: "Apply for an Overseas Citizen of India card — lifelong visa to India.",
    description:
      "The Overseas Citizen of India (OCI) card is a life-long multiple-entry visa for persons of Indian origin who have acquired foreign citizenship. The application is filed on ociservices.gov.in and processed by the Ministry of Home Affairs. The fee is USD 275 (≈ ₹23,000) for most countries.",
    ministry: "Ministry of Home Affairs — Bureau of Immigration / OCI",
    officialPortal: "OCI Services Portal",
    officialUrl: "https://ociservices.gov.in/",
    eligibility: [
      "Former citizen of India (post-26 Jan 1950)",
      "Child / grandchild of such citizen",
      "Spouse of OCI / Indian citizen (with 2-year marriage)",
      "Minor child of eligible person",
    ],
    documentsRequired: [
      "Foreign passport & current nationality proof",
      "Evidence of Indian origin (surrender certificate, old Indian passport)",
      "Naturalization certificate of foreign citizenship",
      "Marriage certificate (if spouse category)",
      "Photographs per OCI specification",
    ],
    fee: 23000,
    feeNote: "USD 275 / approx ₹23,000 (varies by country); extra $3 for OCI-Misc services.",
    processingTime: "60–90 days",
    howToApply: [
      "Register on ociservices.gov.in and complete Part A online.",
      "Upload photograph, signature and supporting documents.",
      "Print Part B and submit with originals to the Indian Mission / FRRO / outsourced VFS centre.",
      "Pay the OCI fee; application status is tracked online with the registration ID.",
      "On approval, OCI card is dispatched and lifelong visa is endorsed on the foreign passport.",
    ],
    serviceCharge: 150,
    popularity: 80,
    tags: ["oci", "overseas-citizen", "india", "visa", "home-affairs", "pio"],
    online: true,
  },
  {
    id: "oci-card-renewal",
    slug: "oci-card-renewal",
    name: "OCI Card Renewal",
    category: "citizenship-immigration",
    subcategory: "OCI",
    summary: "Renew OCI card on new passport issuance (under 20) or after age 50.",
    description:
      "OCI registration is lifelong, but the card must be re-issued once when a new passport is issued to a holder below 20 years of age, and once after completing 50 years of age. The fee is USD 25 (≈ ₹2,100) plus a small service charge and is filed via OCI-Miscellaneous services on ociservices.gov.in.",
    ministry: "Ministry of Home Affairs — Bureau of Immigration / OCI",
    officialPortal: "OCI Services Portal — OCI-Misc",
    officialUrl: "https://ociservices.gov.in/",
    eligibility: [
      "Existing OCI card holder",
      "Below 20 with new passport issued, or",
      "Completed 50 years of age, or",
      "Card damaged / personal particulars changed",
    ],
    documentsRequired: [
      "Existing OCI card copy",
      "Current foreign passport",
      "Previous passports (if any)",
      "Proof of changed particulars (if applicable)",
    ],
    fee: 2100,
    feeNote: "USD 25 (≈ ₹2,100) for renewal; service is free if only passport details changed between 21–50.",
    processingTime: "30–60 days",
    howToApply: [
      "Open ociservices.gov.in → OCI-Miscellaneous Services.",
      "Login with U-Visa / registration number and passport.",
      "Select 'Re-issue of OCI' and reason (new passport / age 50 / error).",
      "Upload documents and pay USD 25.",
      "Track status online; new OCI card dispatched after verification.",
    ],
    serviceCharge: 120,
    popularity: 65,
    tags: ["oci", "renewal", "re-issue", "home-affairs", "passport-change"],
    online: true,
  },
  {
    id: "oci-miscellaneous-service",
    slug: "oci-miscellaneous-service",
    name: "OCI Miscellaneous Service",
    category: "citizenship-immigration",
    subcategory: "OCI",
    summary: "Update details, replace lost / damaged OCI, or correct errors on OCI card.",
    description:
      "OCI-Miscellaneous services cover change of address / occupation, loss / damage of OCI card, mistake in personal particulars, and conversion of PIO to OCI. Filed on ociservices.gov.in under 'OCI-Miscellaneous Services' with fee USD 100 (≈ ₹8,300) for lost / damaged cards or USD 25 for other changes.",
    ministry: "Ministry of Home Affairs — Bureau of Immigration / OCI",
    officialPortal: "OCI Services Portal — OCI-Misc",
    officialUrl: "https://ociservices.gov.in/",
    eligibility: ["Existing OCI card holder requiring correction or replacement"],
    documentsRequired: [
      "Existing OCI card / registration number",
      "Foreign passport",
      "FIR / police report (for lost / damaged)",
      "Proof of changed particulars",
    ],
    fee: 8300,
    feeNote: "USD 100 (≈ ₹8,300) for lost/damaged; USD 25 (≈ ₹2,100) for other services.",
    processingTime: "30–60 days",
    howToApply: [
      "Visit ociservices.gov.in → OCI-Miscellaneous Services.",
      "Log in with registration number and current passport.",
      "Select service type (lost/damaged / change in particulars / PIO-OCI).",
      "Upload documents and pay applicable fee.",
      "Track with online reference number; new OCI card dispatched after verification.",
    ],
    serviceCharge: 120,
    popularity: 50,
    tags: ["oci", "miscellaneous", "correction", "replacement", "home-affairs"],
    online: true,
  },
  {
    id: "indian-e-visa-tourist",
    slug: "indian-e-visa-tourist",
    name: "Indian e-Visa (Tourist)",
    category: "citizenship-immigration",
    subcategory: "e-Visa",
    summary: "Apply for an Indian tourist e-Visa — 30 days / 1 year / 5 years.",
    description:
      "The Indian e-Tourist Visa (e-TV) is available to citizens of 170+ countries for tourism, family visits and short yoga courses. Three variants are offered: 30-day double entry, 1-year multiple entry, and 5-year multiple entry. Fee ranges from USD 25 to USD 80 depending on nationality and duration.",
    ministry: "Ministry of Home Affairs / Bureau of Immigration",
    officialPortal: "Indian e-Visa Portal",
    officialUrl: "https://indianvisaonline.gov.in/evisa/tvoa.html",
    eligibility: [
      "Citizen of an e-Visa eligible country",
      "Purpose: tourism / family visit / short yoga program",
      "Passport valid for at least 6 months from arrival",
    ],
    documentsRequired: [
      "Passport bio-data page (PDF, 10 KB–300 KB)",
      "Recent passport photograph (JPEG)",
      "Return ticket or onward journey ticket",
      "Sufficient funds proof (if asked)",
    ],
    fee: 2500,
    feeNote: "USD 25–80 (₹2,000–₹6,700) depending on duration & nationality; bank fee USD 2.5.",
    processingTime: "72 hours (most cases)",
    howToApply: [
      "Visit indianvisaonline.gov.in/evisa and click 'Apply e-Visa'.",
      "Complete Part A with passport, travel and personal details.",
      "Pay visa fee + bank charges via payment gateway.",
      "Upload passport page and photograph (Part B).",
      "Receive e-Visa by email; print and carry with passport on arrival.",
    ],
    serviceCharge: 120,
    popularity: 88,
    tags: ["e-visa", "tourist", "india", "e-tv", "tourism", "home-affairs"],
    online: true,
  },
  {
    id: "indian-e-visa-business",
    slug: "indian-e-visa-business",
    name: "Indian e-Visa (Business)",
    category: "citizenship-immigration",
    subcategory: "e-Visa",
    summary: "e-Business Visa for foreign nationals visiting India for trade / meetings.",
    description:
      "The e-Business Visa allows foreign nationals to visit India for business meetings, trade, setting up industrial ventures, technical consultations and sales / purchases. It is valid for 1 year with multiple entries, maximum 180 days continuous stay. Fee is USD 80–100 depending on nationality.",
    ministry: "Ministry of Home Affairs / Bureau of Immigration",
    officialPortal: "Indian e-Visa Portal",
    officialUrl: "https://indianvisaonline.gov.in/evisa/tvoa.html",
    eligibility: [
      "Citizen of an eligible country",
      "Purpose: business / trade / technical consultancy",
      "Passport valid 6+ months from arrival",
    ],
    documentsRequired: [
      "Passport bio-data page (PDF)",
      "Photograph (JPEG)",
      "Visiting card or letter from Indian company (PDF)",
      "Business invitation letter or contract",
    ],
    fee: 8000,
    feeNote: "USD 80–100 (≈ ₹6,700–₹8,400) depending on nationality; bank fee USD 2.5.",
    processingTime: "72 hours",
    howToApply: [
      "Open indianvisaonline.gov.in/evisa → Apply.",
      "Choose 'e-Business Visa' and fill Part A.",
      "Pay visa fee + bank charges online.",
      "Upload passport, photo and business invitation letter (Part B).",
      "Receive e-Business Visa by email; print and present at immigration on arrival.",
    ],
    serviceCharge: 130,
    popularity: 70,
    tags: ["e-visa", "business", "india", "trade", "home-affairs"],
    online: true,
  },
  {
    id: "indian-e-visa-medical",
    slug: "indian-e-visa-medical",
    name: "Indian e-Visa (Medical)",
    category: "citizenship-immigration",
    subcategory: "e-Visa",
    summary: "e-Medical Visa for foreign patients seeking treatment in India.",
    description:
      "The e-Medical Visa is issued to foreign nationals travelling to India for medical treatment in recognised / specialty hospitals. Valid for 60 days with triple entry. Up to two attendants may apply for an e-Medical Attendant Visa linked to the patient's e-Medical Visa. Fee is USD 80 (₹6,700) for most countries.",
    ministry: "Ministry of Home Affairs / Bureau of Immigration",
    officialPortal: "Indian e-Visa Portal",
    officialUrl: "https://indianvisaonline.gov.in/evisa/tvoa.html",
    eligibility: [
      "Foreign national seeking medical treatment in India",
      "Treatment at a recognised Indian hospital",
      "Passport valid 6+ months",
    ],
    documentsRequired: [
      "Passport bio-data page",
      "Photograph",
      "Letter from Indian hospital on letterhead (PDF)",
      "Estimated treatment duration and cost",
    ],
    fee: 6700,
    feeNote: "USD 80 (≈ ₹6,700); bank fee USD 2.5; valid 60 days, triple entry.",
    processingTime: "72 hours",
    howToApply: [
      "Go to indianvisaonline.gov.in/evisa → Apply.",
      "Select 'e-Medical Visa' and fill Part A.",
      "Pay visa fee online.",
      "Upload passport, photo and hospital invitation letter in Part B.",
      "Receive e-Medical Visa by email; print and present at Indian immigration.",
    ],
    serviceCharge: 120,
    popularity: 60,
    tags: ["e-visa", "medical", "india", "treatment", "hospital", "home-affairs"],
    online: true,
  },
  {
    id: "indian-e-visa-conference",
    slug: "indian-e-visa-conference",
    name: "Indian e-Visa (Conference)",
    category: "citizenship-immigration",
    subcategory: "e-Visa",
    summary: "e-Conference Visa for foreign delegates attending conferences in India.",
    description:
      "The e-Conference Visa is issued to foreign nationals attending government-approved conferences, seminars or workshops in India. Valid for 30 days with single entry. The organizer must obtain political / MHA clearance and FRO clearance before the delegate applies. Fee is USD 80 (₹6,700).",
    ministry: "Ministry of Home Affairs / Bureau of Immigration",
    officialPortal: "Indian e-Visa Portal",
    officialUrl: "https://indianvisaonline.gov.in/evisa/tvoa.html",
    eligibility: [
      "Foreign delegate attending a conference in India",
      "Conference has MHA / Political clearance and FRO clearance",
      "Passport valid 6+ months",
    ],
    documentsRequired: [
      "Passport bio-data page",
      "Photograph",
      "Invitation letter from organizer",
      "MHA & Political clearance numbers, FRO clearance",
      "Event details (dates, venue, organizer)",
    ],
    fee: 6700,
    feeNote: "USD 80 (≈ ₹6,700); bank fee USD 2.5; valid 30 days single entry.",
    processingTime: "72 hours (after organizer clearance)",
    howToApply: [
      "Organizer obtains MHA, Political and FRO clearances in advance.",
      "Delegate applies on indianvisaonline.gov.in/evisa → e-Conference Visa.",
      "Fill Part A with event clearance numbers; pay visa fee.",
      "Upload passport, photo and invitation letter.",
      "Receive e-Conference Visa by email; print and present at immigration.",
    ],
    serviceCharge: 130,
    popularity: 45,
    tags: ["e-visa", "conference", "india", "delegate", "home-affairs"],
    online: true,
  },
  {
    id: "frro-registration",
    slug: "frro-registration",
    name: "FRRO Registration",
    category: "citizenship-immigration",
    subcategory: "Foreigner Registration",
    summary: "Foreign nationals register with FRRO / FRO within 14 days of arrival.",
    description:
      "Foreign nationals (other than those from exempt countries) staying in India for more than 180 days on a long-term visa, or those on Student / Employment / Research / Medical visas, must register with the Foreigners Regional Registration Office (FRRO) within 14 days of arrival. The process is fully online via indianfrro.gov.in and is free.",
    ministry: "Ministry of Home Affairs — Bureau of Immigration",
    officialPortal: "FRRO Online Portal",
    officialUrl: "https://indianfrro.gov.in/frro/",
    eligibility: [
      "Foreign national on long-term visa (Employment / Student / Research / Medical / Entry)",
      "Staying in India > 180 days",
      "OCI holders need not register",
    ],
    documentsRequired: [
      "Passport and visa copy",
      "Recent passport photograph",
      "Proof of residence in India (rent agreement / hotel letter)",
      "Letter from employer / institution / hospital (as applicable)",
      "Undertaking / Bonafide certificate",
    ],
    fee: 0,
    feeNote: "Free if registered within 14 days; late fee USD 30 (≈ ₹2,500) in US/$-equivalent.",
    processingTime: "Same day to 7 working days",
    howToApply: [
      "Sign up on indianfrro.gov.in/frro with passport and email.",
      "Complete the registration form — Form A — with arrival, visa and address details.",
      "Upload passport, visa, photograph and residential proof.",
      "Submit and book an appointment (if physical visit required) or apply for exit permit.",
      "Residence Permit is issued online / by FRRO office; mandatory for visa extensions and exit.",
    ],
    serviceCharge: 100,
    popularity: 50,
    tags: ["frro", "foreigner-registration", "india", "home-affairs", "visa-extension"],
    online: true,
  },
];
