import type { GovernmentService } from "../types";

export const courtLegal: GovernmentService[] = [
  {
    id: "ecourts-case-status",
    slug: "ecourts-case-status",
    name: "eCourts — Case Status Search",
    category: "court-legal",
    subcategory: "Case Status",
    summary: "Check the status and hearing dates of any case in district, high or supreme courts.",
    description: "The eCourts project under the eCommittee of the Supreme Court of India provides a unified national portal to check case status, cause lists, daily orders and final judgments of all computerised district courts, High Courts and the Supreme Court. Cases can be searched by CNR number, party name, advocate name or case number.",
    ministry: "eCommittee, Supreme Court of India",
    officialPortal: "eCourts Services",
    officialUrl: "https://services.ecourts.gov.in/",
    eligibility: ["Any citizen", "Parties, advocates and litigants"],
    documentsRequired: ["Case number or CNR (Case Number Record)", "Court name / district", "Party or advocate name (optional)"],
    fee: 0,
    feeNote: "Free public service.",
    processingTime: "Instant (online search)",
    howToApply: [
      "Visit services.ecourts.gov.in.",
      "Select the court type — District, High Court or Supreme Court.",
      "Choose search by CNR, case number, party name or advocate name.",
      "Enter details and submit to view case status, next hearing date and order history.",
      "Download orders/judgments as PDF where available.",
    ],
    serviceCharge: 40,
    popularity: 82,
    tags: ["court", "case status", "ecourts", "judgment", "cnr"],
    online: true,
  },
  {
    id: "ecourts-cause-list",
    slug: "ecourts-cause-list",
    name: "eCourts — Cause List & Daily Board",
    category: "court-legal",
    subcategory: "Case Status",
    summary: "View daily cause lists of matters listed before district, High Court and Supreme Court benches.",
    description: "The eCourts portal publishes daily cause lists showing the cases listed for hearing before each bench on a given day. Advocates and litigants use it to track when their matter is to be taken up and before which judge. Cause lists are generated the previous evening and updated through the next morning.",
    ministry: "eCommittee, Supreme Court of India",
    officialPortal: "eCourts Services",
    officialUrl: "https://services.ecourts.gov.in/",
    eligibility: ["Any citizen", "Advocates and litigants"],
    documentsRequired: ["Court name / bench", "Listing date (optional)"],
    fee: 0,
    feeNote: "Free public service.",
    processingTime: "Instant (online view)",
    howToApply: [
      "Open services.ecourts.gov.in.",
      "Choose Cause List under the relevant court type.",
      "Pick the establishment, complex and court.",
      "Select the date to view the daily board.",
      "Download or print the PDF cause list for your records.",
    ],
    serviceCharge: 35,
    popularity: 60,
    tags: ["court", "cause list", "daily board", "ecourts"],
    online: true,
  },
  {
    id: "ecourts-judgment-search",
    slug: "ecourts-judgment-search",
    name: "eCourts — Judgment & Order Search",
    category: "court-legal",
    subcategory: "Case Status",
    summary: "Search final judgments and orders delivered by district and High Courts across India.",
    description: "Judgments delivered by computerised district courts, High Courts and the Supreme Court are uploaded to the eCourts repository and the Judgments Information System (JUDIS). Users can search by citation, party name, judge, date range or free text. PDF copies of judgments are freely downloadable for advocacy, research and reference.",
    ministry: "eCommittee, Supreme Court of India",
    officialPortal: "eCourts / JUDIS",
    officialUrl: "https://judgments.ecourts.gov.in/",
    eligibility: ["Any citizen", "Advocates, researchers, journalists"],
    documentsRequired: ["Party name or case number", "Court / establishment", "Approximate date range (optional)"],
    fee: 0,
    feeNote: "Free public service.",
    processingTime: "Instant (online search)",
    howToApply: [
      "Visit judgments.ecourts.gov.in.",
      "Choose District Court or High Court judgment search.",
      "Enter party name, advocate, case number or citation.",
      "Apply date filters if required and submit.",
      "Open the judgment PDF and download it for reference.",
    ],
    serviceCharge: 35,
    popularity: 58,
    tags: ["court", "judgment", "order", "judis", "ecourts"],
    online: true,
  },
  {
    id: "ecourts-order-copy-download",
    slug: "ecourts-order-copy-download",
    name: "eCourts — Certified Order Copy Download",
    category: "court-legal",
    subcategory: "Case Documents",
    summary: "Apply online and download certified copies of orders and judgments of district courts.",
    description: "Through the eCourts eServices module, litigants and advocates can apply for certified copies of orders, judgments and case filings without visiting the court copying branch. After verification by the court staff, a digitally signed copy is made available for download from the applicant's dashboard on payment of the prescribed copying fee.",
    ministry: "eCommittee, Supreme Court of India",
    officialPortal: "eCourts eServices",
    officialUrl: "https://services.ecourts.gov.in/",
    eligibility: ["Parties to the case", "Advocates on record"],
    documentsRequired: ["CNR / case number", "Date of order or judgment", "Self-attested ID proof", "Advocate code (if applied by advocate)"],
    fee: 50,
    feeNote: "Copying fee depends on number of pages (~₹2-₹5 per page); exact amount shown at checkout.",
    processingTime: "1-3 working days",
    howToApply: [
      "Register on eCourts eServices with mobile and email.",
      "Select the establishment and choose Apply for Certified Copy.",
      "Enter case number / CNR and identify the document required.",
      "Pay the prescribed copying fee online.",
      "Download the digitally signed certified copy from the dashboard once ready.",
    ],
    serviceCharge: 80,
    popularity: 55,
    tags: ["court", "certified copy", "order copy", "ecourts"],
    online: true,
  },
  {
    id: "supreme-court-case-status",
    slug: "supreme-court-case-status",
    name: "Supreme Court of India — Case Status",
    category: "court-legal",
    subcategory: "Case Status",
    summary: "Track cases pending before the Supreme Court of India by case number, diary or party name.",
    description: "The Supreme Court of India's case-status portal (main.sci.gov.in) provides real-time information on cases including case number, diary number, petitioners, respondents, advocate-on-record, last hearing date, next listing and final disposal status. Daily orders and judgments are also linked to each case record.",
    ministry: "Supreme Court of India",
    officialPortal: "Supreme Court of India",
    officialUrl: "https://main.sci.gov.in/case-status",
    eligibility: ["Any citizen", "Litigants and advocates"],
    documentsRequired: ["Case number or diary number", "Year of filing", "Party name (alternative)"],
    fee: 0,
    feeNote: "Free public service.",
    processingTime: "Instant (online search)",
    howToApply: [
      "Go to main.sci.gov.in and open Case Status.",
      "Choose search by Case Number, Diary Number, Party Name or Advocate.",
      "Enter the required details and the year.",
      "Submit to view case history and current status.",
      "Click through to download linked orders and judgments.",
    ],
    serviceCharge: 40,
    popularity: 70,
    tags: ["supreme court", "case status", "sci", "judgment"],
    online: true,
  },
  {
    id: "high-court-case-status",
    slug: "high-court-case-status",
    name: "High Court — Case Status (All High Courts)",
    category: "court-legal",
    subcategory: "Case Status",
    summary: "Check case status, cause lists and orders of any of the 25 High Courts of India.",
    description: "Each of India's 25 High Courts maintains its own case-status portal linked from the National Judicial Data Grid (NJDG). The unified entry on the eCourts portal lets citizens choose their High Court and search pending and disposed cases by case number, party name, advocate or FIR number.",
    ministry: "Respective High Court / eCommittee",
    officialPortal: "High Courts of India (via eCourts)",
    officialUrl: "https://ihc.nic.in/",
    eligibility: ["Any citizen", "Litigants and advocates"],
    documentsRequired: ["High Court name", "Case number or party name", "Year (optional)"],
    fee: 0,
    feeNote: "Free public service.",
    processingTime: "Instant (online search)",
    howToApply: [
      "Visit services.ecourts.gov.in and choose High Courts.",
      "Select the relevant High Court from the list.",
      "Pick search option — case number, party name, advocate or FIR.",
      "Submit details to view current status and next listing.",
      "Open the cause list or orders tab for additional documents.",
    ],
    serviceCharge: 40,
    popularity: 68,
    tags: ["high court", "case status", "ecourts", "njdg"],
    online: true,
  },
  {
    id: "efiling-cases-efile",
    slug: "efiling-cases-efile",
    name: "e-Filing of Cases (eFile)",
    category: "court-legal",
    subcategory: "Filing",
    summary: "File fresh cases, annexures and interlocutory applications online before Supreme, High and District Courts.",
    description: "The e-Filing system (efiling.ecourts.gov.in) is a unified electronic filing platform deployed across the Supreme Court, High Courts and district courts under the eCourts Phase III programme. Advocates and party-in-person can upload plaints, petitions, vakalatnamas and annexures, pay court fees through e-pay and receive an electronically signed case number instantly.",
    ministry: "eCommittee, Supreme Court of India",
    officialPortal: "e-Filing Courts",
    officialUrl: "https://efiling.ecourts.gov.in/",
    eligibility: ["Advocates enrolled with Bar Council of India", "Party-in-person with court permission"],
    documentsRequired: ["Signed pleadings (PDF)", "Vakalatnama / appearance memo", "Annexures and supporting documents", "e-Court fee receipt (e-pay)"],
    fee: 0,
    feeNote: "Portal is free; statutory court fee payable via e-pay as per the Court Fees Act.",
    processingTime: "Same-day registration (scrutiny later)",
    howToApply: [
      "Register on efiling.ecourts.gov.in as Advocate or Party-in-Person.",
      "Choose the court, establishment and case type.",
      "Upload pleadings, annexures and vakalatnama as signed PDFs.",
      "Pay court fee and process fee through the e-Pay integration.",
      "Submit to receive an acknowledgement and case number immediately.",
    ],
    serviceCharge: 120,
    popularity: 65,
    tags: ["efiling", "ecourts", "court fee", "filing", "petition"],
    online: true,
  },
  {
    id: "nalsa-legal-aid-application",
    slug: "nalsa-legal-aid-application",
    name: "NALSA — Free Legal Aid Application",
    category: "court-legal",
    subcategory: "Legal Aid",
    summary: "Apply for free legal aid and an empanelled lawyer through the National Legal Services Authority.",
    description: "The National Legal Services Authority (NALSA) provides free legal services to eligible persons — women, children, SC/ST, victims of trafficking, persons with disability, industrial workmen and persons earning up to the prescribed income ceiling. The Supreme Court Legal Services Committee and State Legal Services Authorities allocate empanelled advocates and meet litigation expenses of the aided person.",
    ministry: "National Legal Services Authority (NALSA)",
    officialPortal: "NALSA — Legal Services",
    officialUrl: "https://nalsa.gov.in/",
    eligibility: ["Women and children", "SC/ST candidates", "Persons with disability", "Persons in custody and victims of trafficking", "Annual income within ceiling (varies by state, ~₹3 lakh)"],
    documentsRequired: ["Aadhaar / photo ID", "Income certificate", "Caste / disability certificate (if applicable)", "Case details / FIR copy"],
    fee: 0,
    feeNote: "Completely free for eligible persons.",
    processingTime: "7-15 working days",
    howToApply: [
      "Visit nalsa.gov.in and open Online Legal Aid Application.",
      "Choose the relevant Legal Services Authority (Supreme / High / District).",
      "Fill personal details and case details.",
      "Upload eligibility proof and income certificate.",
      "Submit and track application; advocate will be allocated after verification.",
    ],
    serviceCharge: 60,
    popularity: 55,
    tags: ["legal aid", "nalsa", "free lawyer", "legal services"],
    online: true,
  },
  {
    id: "lok-adalat-registration",
    slug: "lok-adalat-registration",
    name: "Lok Adalat — Case Registration",
    category: "court-legal",
    subcategory: "Alternative Dispute Resolution",
    summary: "Refer pending or pre-litigation disputes to Lok Adalat for amicable, fast and binding settlement.",
    description: "Lok Adalats are statutory forums under the Legal Services Authorities Act, 1987 that dispose of cases through conciliation. The National Lok Adalat is held monthly; special Lok Adalats handle cheque-bounce, motor-accident and bank-recovery matters. Awards passed by Lok Adalat are deemed civil court decrees and are not appealable.",
    ministry: "National Legal Services Authority (NALSA)",
    officialPortal: "NALSA — Lok Adalat",
    officialUrl: "https://nalsa.gov.in/lok-adalat",
    eligibility: ["Any party to a pending or pre-litigation dispute", "Both parties must consent to reference"],
    documentsRequired: ["Case number (if pending)", "ID proof of parties", "Underlying document / agreement in dispute", "Written consent of both parties"],
    fee: 0,
    feeNote: "Free; no court fee is levied on Lok Adalat references.",
    processingTime: "Same day disposal",
    howToApply: [
      "Approach the nearest Legal Services Authority or apply via NALSA online.",
      "Submit application with case details and consent of both parties.",
      "Authority lists the matter before the next Lok Adalat bench.",
      "Both parties present their case; bench facilitates settlement.",
      "Receive the Lok Adalat Award, which is final and binding.",
    ],
    serviceCharge: 75,
    popularity: 50,
    tags: ["lok adalat", "alternative dispute", "nalsa", "settlement"],
    online: true,
  },
  {
    id: "mcpc-mediation-application",
    slug: "mcpc-mediation-application",
    name: "Mediation Application (MCPC)",
    category: "court-legal",
    subcategory: "Alternative Dispute Resolution",
    summary: "Refer civil, family and commercial disputes to mediation through the Mediation and Conciliation Project Committee.",
    description: "The Mediation and Conciliation Project Committee (MCPC) of the Supreme Court of India runs court-annexed mediation centres across districts and High Courts. Parties can opt for mediation at any stage of a proceeding; settlement agreements are referred back to the referring court for recording as a decree. The Mediation Act, 2023 now statutorily recognises mediated settlements.",
    ministry: "Mediation and Conciliation Project Committee, Supreme Court",
    officialPortal: "MCPC India",
    officialUrl: "https://mcpc.gov.in/",
    eligibility: ["Parties to civil, commercial or family disputes", "Court-referred or pre-litigation references"],
    documentsRequired: ["Case details / application", "ID proof of parties", "Underlying agreement or plaint", "Consent of parties"],
    fee: 0,
    feeNote: "Court-referred mediation is free for first 3 sessions; private mediation fees apply beyond that.",
    processingTime: "60 days (extendable by 30 days)",
    howToApply: [
      "Approach the Mediation Centre at your district court or visit mcpc.gov.in.",
      "File a mediation application with consent of both parties.",
      "Centre allots a mediator and schedules sessions.",
      "Parties attend sessions; settlement is reduced to writing if reached.",
      "Settlement is filed before the referring court and recorded as a decree.",
    ],
    serviceCharge: 90,
    popularity: 42,
    tags: ["mediation", "mcpc", "adr", "conciliation", "supreme court"],
    online: true,
  },
  {
    id: "court-fee-estamp-payment",
    slug: "court-fee-estamp-payment",
    name: "Court Fee Payment — e-Stamp (SHCIL)",
    category: "court-legal",
    subcategory: "Court Fee",
    summary: "Purchase e-stamp papers online for paying court fees and document registration charges.",
    description: "Stock Holding Corporation of India Limited (SHCIL) is the Central Record Keeping Agency for e-stamps under the Indian Stamp Act. Citizens, advocates and companies can purchase e-stamps of any denomination online or at authorised collection centres; the e-stamp certificate carries a unique certificate number and QR code verifiable on the SHCIL portal.",
    ministry: "Ministry of Finance / SHCIL",
    officialPortal: "SHCIL e-Stamp",
    officialUrl: "https://www.shcilestamp.com/",
    eligibility: ["Any citizen or entity requiring stamped documents"],
    documentsRequired: ["PAN / Aadhaar", "Purpose of stamp (court fee, agreement, affidavit)", "Party details and denomination"],
    fee: 100,
    feeNote: "Denomination value paid as per Indian Stamp Act schedule; portal service charge ₹10-₹25 extra.",
    processingTime: "Instant",
    howToApply: [
      "Open shcilestamp.com and choose Online e-Stamp.",
      "Select the state and denomination required.",
      "Fill first party, second party and article description.",
      "Pay online through net-banking / UPI / card.",
      "Download the e-stamp certificate with unique certificate number.",
    ],
    serviceCharge: 50,
    popularity: 60,
    tags: ["court fee", "e-stamp", "shcil", "stamp paper"],
    online: true,
  },
  {
    id: "notary-registration",
    slug: "notary-registration",
    name: "Notary Registration & Appointment",
    category: "court-legal",
    subcategory: "Legal Professionals",
    summary: "Apply for the post of Notary Public under the Notaries Act, 1952 and renew the certificate of practice.",
    description: "The Department of Legal Affairs, Ministry of Law & Justice appoints Notaries Public under the Notaries Act, 1952 for a term of five years. Advocates with at least 10 years of practice (or 7 years for SC/ST/women) are eligible to apply. Notaries are authorised to attest, authenticate and certify documents and to administer oaths.",
    ministry: "Department of Legal Affairs, Ministry of Law & Justice",
    officialPortal: "Notaries Cell",
    officialUrl: "https://legalaffairs.gov.in/notaries",
    eligibility: ["Advocate with 10 years of practice (7 years for SC/ST/women)", "Indian citizen of good character"],
    documentsRequired: ["Bar Council enrolment certificate", "Proof of practice (10 years)", "Aadhaar / PAN", "Two character certificates from advocates"],
    fee: 1000,
    feeNote: "Application fee ₹1,000; renewal ₹500.",
    processingTime: "3-6 months",
    howToApply: [
      "Register on the Notaries portal of Department of Legal Affairs.",
      "Fill Form I application for appointment as Notary.",
      "Upload Bar Council certificate, practice proof and ID.",
      "Pay ₹1,000 fee online and submit.",
      "On approval by the Central Government, receive Certificate of Practice.",
    ],
    serviceCharge: 150,
    popularity: 35,
    tags: ["notary", "attestation", "legal affairs", "law ministry"],
    online: true,
  },
  {
    id: "oath-commissioner-appointment",
    slug: "oath-commissioner-appointment",
    name: "Oath Commissioner Appointment",
    category: "court-legal",
    subcategory: "Legal Professionals",
    summary: "Apply for the post of Oath Commissioner / Commissioner for Oaths in district courts.",
    description: "Oath Commissioners (also called Commissioners for Oaths) are appointed by the District & Sessions Judge to administer oaths and affirmations on affidavits filed in courts. Eligibility requires enrolment as an advocate with the State Bar Council, typically with 2-3 years standing at the Bar. The appointment is renewed periodically by the High Court or District Court.",
    ministry: "Respective High Court / District Court",
    officialPortal: "District Court (Oath Commissioners)",
    officialUrl: "https://districts.ecourts.gov.in/",
    eligibility: ["Advocate enrolled with State Bar Council", "Minimum 2-3 years practice (varies by state)"],
    documentsRequired: ["Bar Council enrolment certificate", "Practice certificate", "Aadhaar / PAN", "Character certificate"],
    fee: 500,
    feeNote: "Application fee ~₹500 (varies by High Court rules).",
    processingTime: "1-3 months",
    howToApply: [
      "Visit the District Court administrative wing or its website.",
      "Obtain and fill the Oath Commissioner application form.",
      "Attach Bar Council certificate, practice proof and ID.",
      "Pay the application fee at the court counter.",
      "On approval by the District Judge, take the oath of office and receive the commission.",
    ],
    serviceCharge: 100,
    popularity: 30,
    tags: ["oath commissioner", "affidavit", "commissioner", "district court"],
    online: false,
  },
  {
    id: "legal-services-authority-complaint",
    slug: "legal-services-authority-complaint",
    name: "Legal Services Authority — Grievance Complaint",
    category: "court-legal",
    subcategory: "Legal Aid",
    summary: "File a grievance against denial of legal aid or against an empanelled advocate before SLSA / DLSA.",
    description: "Beneficiaries of free legal aid can file grievances before the State Legal Services Authority (SLSA) or District Legal Services Authority (DLSA) if aid is denied, delayed or if the empanelled advocate is not performing. The complaint can also be lodged online through the NALSA grievance portal for time-bound redress.",
    ministry: "National Legal Services Authority (NALSA)",
    officialPortal: "NALSA Grievance Redressal",
    officialUrl: "https://nalsa.gov.in/grievance-redressal",
    eligibility: ["Beneficiaries of legal aid", "Any aggrieved litigant"],
    documentsRequired: ["Legal aid application / registration number", "Grievance description", "Supporting correspondence", "ID proof"],
    fee: 0,
    feeNote: "Free public service.",
    processingTime: "30 working days",
    howToApply: [
      "Visit the NALSA Grievance Redressal portal.",
      "Register with mobile number and OTP.",
      "Choose the type of grievance — denial of aid, advocate inaction, etc.",
      "Upload supporting documents and submit.",
      "Track status online; authority issues a reasoned order on closure.",
    ],
    serviceCharge: 50,
    popularity: 38,
    tags: ["legal aid", "grievance", "nalsa", "slsa", "dlsa"],
    online: true,
  },
];
