import type { GovernmentService } from "../types";

export const defenceVeterans: GovernmentService[] = [
  {
    id: "echs-polyclinic-registration",
    slug: "echs-polyclinic-registration",
    name: "ECHS Polyclinic Registration",
    category: "defence-veterans",
    subcategory: "Healthcare",
    summary: "Register at an Ex-Servicemen Contributory Health Scheme polyclinic for OPD and referral treatment.",
    description: "The Ex-Servicemen Contributory Health Scheme (ECHS) operates 428 polyclinics across India providing free OPD, investigation and inpatient referral services to ex-servicemen and their dependants. Beneficiaries must register at the parent polyclinic nearest to their residence to avail cashless treatment at empanelled hospitals.",
    ministry: "Department of Ex-Servicemen Welfare, Ministry of Defence",
    officialPortal: "ECHS",
    officialUrl: "https://echs.gov.in/",
    eligibility: ["Ex-servicemen drawing pension", "Widows of ex-servicemen", "Dependant parents, spouse and children"],
    documentsRequired: ["ECHS card / 16-digit temporary ID", "Discharge book / PPO", "Aadhaar of beneficiary", "Address proof"],
    fee: 0,
    feeNote: "Free for ECHS members.",
    processingTime: "1-3 working days",
    howToApply: [
      "Visit the nearest ECHS polyclinic with discharge book and ECHS card.",
      "Fill the polyclinic registration form available at the reception.",
      "Submit Aadhaar and address proof for self and dependants.",
      "Biometric capture done at the polyclinic counter.",
      "Collect the polyclinic registration slip; begin availing OPD services.",
    ],
    serviceCharge: 50,
    popularity: 70,
    tags: ["echs", "ex-servicemen", "health", "polyclinic", "defence"],
    online: false,
  },
  {
    id: "echs-new-card-application",
    slug: "echs-new-card-application",
    name: "ECHS New Card Application",
    category: "defence-veterans",
    subcategory: "Healthcare",
    summary: "Apply for a new ECHS 64 KB smart card for self and dependants after retirement from the Armed Forces.",
    description: "On retirement, service personnel and their dependants must apply for the ECHS 64 KB smart card to access cashless healthcare at ECHS polyclinics and empanelled hospitals. Online application is done through the ECHS portal with biometric authentication at the record-keeping polyclinic. Replacement of lost or damaged cards is also done through the same module.",
    ministry: "Department of Ex-Servicemen Welfare, Ministry of Defence",
    officialPortal: "ECHS Online Application",
    officialUrl: "https://echs.gov.in/",
    eligibility: ["Retiring / retired service personnel", "Widows of ex-servicemen", "Dependant family members"],
    documentsRequired: ["Discharge book / PPO", "Aadhaar of self and dependants", "PAN card", "Passport-size photographs", "Relationship proof for dependants"],
    fee: 135,
    feeNote: "₹135 for 64 KB card; ₹207 for dual dependant card. Free for widows and gallantry award winners.",
    processingTime: "30-60 days",
    howToApply: [
      "Register on apps.echs.gov.in with service number and DOB.",
      "Fill the new smart card application and add dependants.",
      "Upload discharge book, PPO and Aadhaar of all members.",
      "Pay the card fee online or generate challan for bank deposit.",
      "Visit the polyclinic for biometric capture; collect card after SMS intimation.",
    ],
    serviceCharge: 100,
    popularity: 72,
    tags: ["echs", "smart card", "ex-servicemen", "health", "defence"],
    online: true,
  },
  {
    id: "csd-canteen-smart-card",
    slug: "csd-canteen-smart-card",
    name: "CSD Canteen Smart Card Application",
    category: "defence-veterans",
    subcategory: "Welfare",
    summary: "Apply for the Canteen Stores Department smart card for grocery and liquor at unit-run canteens.",
    description: "The Canteen Stores Department (CSD) under the Ministry of Defence runs unit-run canteens (URCs) supplying groceries, household goods and liquor to serving and retired defence personnel at concessional rates. Beneficiaries require a 64 KB Ration Card (smart card) linked to their UIDAI Aadhaar for purchases; the card has monthly and annual monetary entitlements.",
    ministry: "Department of Ex-Servicemen Welfare / CSD",
    officialPortal: "CSD India",
    officialUrl: "https://csdindia.gov.in/",
    eligibility: ["Serving personnel", "Ex-servicemen drawing pension", "Widows of defence personnel"],
    documentsRequired: ["Discharge book / service certificate", "PPO", "Aadhaar", "Photograph", "URC introduction letter"],
    fee: 135,
    feeNote: "₹135 for primary card; ₹45 for add-on dependant card.",
    processingTime: "30-90 days",
    howToApply: [
      "Collect the smart card application form from your URC.",
      "Fill the form and attach discharge book, PPO and Aadhaar copies.",
      "Submit at the URC along with two photographs.",
      "Pay ₹135 fee at the URC counter.",
      "Collect the smart card after SMS intimation; activate at the URC biometric terminal.",
    ],
    serviceCharge: 90,
    popularity: 75,
    tags: ["csd", "canteen", "smart card", "ex-servicemen", "defence"],
    online: false,
  },
  {
    id: "echs-online-application",
    slug: "echs-online-application",
    name: "ECHS Online Membership Application",
    category: "defence-veterans",
    subcategory: "Healthcare",
    summary: "Apply for ECHS membership online before retirement for seamless transition from service medicare.",
    description: "Serving defence personnel within 6 months of retirement can apply for ECHS membership online through the ECHS portal so the smart card is ready by the date of retirement. The application integrates with PCDA (Pension) for verification of pension and with UIDAI for Aadhaar authentication of all dependants.",
    ministry: "Department of Ex-Servicemen Welfare, Ministry of Defence",
    officialPortal: "ECHS Online Application",
    officialUrl: "https://apps.echs.gov.in/",
    eligibility: ["Serving personnel within 6 months of retirement", "Pre-retirement enrolment recommended"],
    documentsRequired: ["Service number and date of retirement", "Aadhaar of self and dependants", "PPO / service pension certificate", "Dependant relationship proofs"],
    fee: 135,
    feeNote: "₹135 smart card fee per primary member.",
    processingTime: "30-45 days",
    howToApply: [
      "Go to apps.echs.gov.in and click New Registration.",
      "Enter service number, date of birth and date of retirement.",
      "Add dependants with their Aadhaar numbers.",
      "Upload documents and pay the card fee online.",
      "Visit polyclinic for biometric; card is dispatched to the polyclinic.",
    ],
    serviceCharge: 110,
    popularity: 65,
    tags: ["echs", "membership", "pre-retirement", "ex-servicemen", "health"],
    online: true,
  },
  {
    id: "ex-servicemen-widow-pension-application",
    slug: "ex-servicemen-widow-pension-application",
    name: "Ex-Servicemen Widow Pension Application",
    category: "defence-veterans",
    subcategory: "Pension",
    summary: "Apply for ordinary / special family pension as a widow of an ex-serviceman through PCDA (Pension).",
    description: "Widows of ex-servicemen are entitled to Ordinary Family Pension or Special Family Pension (in case of death attributable to service) under the Pension Regulations of the three Services. The pension is sanctioned by PCDA (Pension), Allahabad and paid through the Treasury or SPARSH portal after verification of death and marriage certificates.",
    ministry: "Department of Ex-Servicemen Welfare / PCDA (Pension)",
    officialPortal: "PCDA Pension / SPARSH",
    officialUrl: "https://pcdapension.nic.in/",
    eligibility: ["Widow of ex-servicemen", "Unmarried daughter below 25 (in absence of widow)", "Dependant parents (in specified cases)"],
    documentsRequired: ["Death certificate of ex-serviceman", "Marriage certificate", "PPO of deceased", "Aadhaar of widow", "Bank passbook"],
    fee: 0,
    feeNote: "Free; no application fee.",
    processingTime: "2-6 months",
    howToApply: [
      "Collect the family pension claim form from the Zila Sainik Board or download from pcdapension.nic.in.",
      "Fill the form and attach death certificate, marriage proof and PPO.",
      "Submit to the Record Office / Zila Sainik Welfare Office for verification.",
      "Forwarded to PCDA (Pension) for sanction through SPARSH.",
      "Pension is credited to the widow's bank account after PPO issuance.",
    ],
    serviceCharge: 120,
    popularity: 55,
    tags: ["widow pension", "ex-servicemen", "family pension", "pcda", "sparsh"],
    online: true,
  },
  {
    id: "war-widow-pension",
    slug: "war-widow-pension",
    name: "War Widow Pension",
    category: "defence-veterans",
    subcategory: "Pension",
    summary: "Enhanced pension and monetary allowances for widows of battle casualties and martyred soldiers.",
    description: "Widows of personnel killed in action or attributable to military operations receive Special Family Pension at enhanced rates, plus lump-sum ex-gratia and monetary allowances from the Ministry of Defence and State governments. The scheme is administered by PCDA (Pension) and the respective KSB / Rajya Sainik Boards.",
    ministry: "Ministry of Defence / Department of Ex-Servicemen Welfare",
    officialPortal: "PCDA Pension / KSB",
    officialUrl: "https://ksb.gov.in/",
    eligibility: ["Widows of battle casualties", "Widows of personnel dying in military operations attributable to service"],
    documentsRequired: ["Casualty / battle casualty certificate", "Death certificate", "PPO of deceased", "Marriage certificate", "Aadhaar"],
    fee: 0,
    feeNote: "Free.",
    processingTime: "3-6 months",
    howToApply: [
      "Approach the Unit / Record Office immediately on casualty.",
      "Submit casualty certificate and family details for family pension sanction.",
      "KSB / ZSB forwards the case to PCDA (Pension) for enhanced pension.",
      "Apply for ex-gratia and State government relief through ZSB.",
      "Receive special family pension and allowances through bank / SPARSH.",
    ],
    serviceCharge: 120,
    popularity: 48,
    tags: ["war widow", "martyr", "special family pension", "ksb", "defence"],
    online: false,
  },
  {
    id: "gallantry-award-pension",
    slug: "gallantry-award-pension",
    name: "Gallantry Award Pension",
    category: "defence-veterans",
    subcategory: "Pension",
    summary: "Lifelong monetary allowance for recipients of PVC, MVC, VrC and other gallantry awards.",
    description: "Recipients of gallantry awards — Param Vir Chakra (PVC), Maha Vir Chakra (MVC), Vir Chakra (VrC), Sena / Nao Sena / Vayu Sena Medal (Gallantry) and Mention-in-Despatches — receive a monthly monetary allowance sanctioned by the Ministry of Defence. The allowance continues for life and is doubled for awardees of PVC, MVC and VrC.",
    ministry: "Ministry of Defence",
    officialPortal: "Gallantry Awards Portal",
    officialUrl: "https://www.gallantryawards.gov.in/",
    eligibility: ["Living recipients of PVC, MVC, VrC and other gallantry awards", "Widows of deceased awardees"],
    documentsRequired: ["Gallantry award citation / gazette notification", "PPO / service document", "Aadhaar", "Bank passbook"],
    fee: 0,
    feeNote: "Free.",
    processingTime: "1-3 months",
    howToApply: [
      "Submit the gallantry award gazette notification to the Record Office.",
      "Record Office forwards the case to PCDA (Pension) for monetary allowance.",
      "PCDA sanctions the allowance through SPARSH or PPO amendment.",
      "Allowance is credited monthly to the awardee's bank account.",
      "Notify PCDA of any change in bank or address to avoid delay.",
    ],
    serviceCharge: 80,
    popularity: 40,
    tags: ["gallantry", "pvc", "mvc", "vrc", "pension", "defence"],
    online: false,
  },
  {
    id: "reservist-pension",
    slug: "reservist-pension",
    name: "Reservist Pension",
    category: "defence-veterans",
    subcategory: "Pension",
    summary: "Pension for reservist personnel embodied for service and discharged after qualifying period.",
    description: "Reservists of the Indian Army, Navy and Air Force who are embodied for service and complete the qualifying pensionary service are entitled to reservist pension under the Pension Regulations. The pension is sanctioned by PCDA (Pension) and paid through SPARSH / treasury after verification of service records by the respective Record Office.",
    ministry: "Department of Ex-Servicemen Welfare / PCDA (Pension)",
    officialPortal: "PCDA Pension",
    officialUrl: "https://pcdapension.nic.in/",
    eligibility: ["Reservists embodied for qualifying service", "Discharged with pensionary benefits"],
    documentsRequired: ["Service record / embodiment certificate", "Discharge book", "Aadhaar", "Bank passbook"],
    fee: 0,
    feeNote: "Free.",
    processingTime: "3-6 months",
    howToApply: [
      "Apply through the parent Record Office with service and embodiment certificates.",
      "Record Office initiates pension claim with PCDA (Pension).",
      "PCDA verifies and sanctions pension through SPARSH.",
      "Receive PPO and monthly pension in bank account.",
      "Submit life certificate annually to keep pension alive.",
    ],
    serviceCharge: 100,
    popularity: 32,
    tags: ["reservist", "pension", "pcda", "sparsh", "defence"],
    online: false,
  },
  {
    id: "agnipath-agniveer-army",
    slug: "agnipath-agniveer-army",
    name: "AGNIPATH — Agniveer (Indian Army)",
    category: "defence-veterans",
    subcategory: "Recruitment",
    summary: "Online enrolment as Agniveer in the Indian Army under the AGNIPATH scheme (4-year engagement).",
    description: "The AGNIPATH scheme, launched in 2022, enrolls youth as Agniveers in the Indian Army for a 4-year engagement period. Recruitment is conducted centrally through the Indian Army recruitment portal with online Common Entrance Exam (CEE), physical fitness test, physical measurement test and medical examination at designated AROs.",
    ministry: "Ministry of Defence / Indian Army",
    officialPortal: "Join Indian Army",
    officialUrl: "https://joinindianarmy.nic.in/",
    eligibility: ["Age 17.5-21 years", "Class 10 / 12 pass as per trade", "Indian citizen", "Unmarried male (some trades open to females)"],
    documentsRequired: ["Class 10 / 12 marksheet", "Aadhaar", "PAN", "Caste / domicile certificate", "Photographs"],
    fee: 250,
    feeNote: "Online application fee ₹250 (non-refundable).",
    processingTime: "6-12 months",
    howToApply: [
      "Register on joinindianarmy.nic.in with Aadhaar and mobile.",
      "Fill the Agniveer application for the desired trade (GD, Clerk, Tech, Tradesman).",
      "Pay ₹250 application fee online.",
      "Download admit card for the Common Entrance Exam (CEE).",
      "Appear for CEE, then physical and medical tests at ARO; join training on selection.",
    ],
    serviceCharge: 80,
    popularity: 78,
    tags: ["agnipath", "agniveer", "indian army", "recruitment", "defence"],
    online: true,
  },
  {
    id: "agnipath-agniveer-navy",
    slug: "agnipath-agniveer-navy",
    name: "AGNIPATH — Agniveer (Indian Navy)",
    category: "defence-veterans",
    subcategory: "Recruitment",
    summary: "Apply for Agniveer (SSR / MR) entry in the Indian Navy under the AGNIPATH scheme.",
    description: "The Indian Navy enrolls Agniveers for Senior Secondary Recruit (SSR) and Matric Recruit (MR) trades under the AGNIPATH scheme for a 4-year engagement. Applications are invited twice a year through joinindiannavy.gov.in with online CEE, PFT, physical measurement and medical examination at INS Chilka.",
    ministry: "Ministry of Defence / Indian Navy",
    officialPortal: "Join Indian Navy",
    officialUrl: "https://www.joinindiannavy.gov.in/",
    eligibility: ["Age 17.5-21 years", "10+2 with Physics & Maths for SSR; Class 10 for MR", "Unmarried male & female Indian citizens"],
    documentsRequired: ["10+2 marksheet (SSR) / Class 10 (MR)", "Aadhaar", "PAN", "Domicile certificate", "Photograph"],
    fee: 250,
    feeNote: "Application fee ₹250.",
    processingTime: "6-12 months",
    howToApply: [
      "Register on joinindiannavy.gov.in.",
      "Choose SSR or MR entry and fill application form.",
      "Pay ₹250 fee online.",
      "Download CEE admit card and appear for the online exam.",
      "Qualified candidates attend PFT & medical at INS Chilka; join training on selection.",
    ],
    serviceCharge: 80,
    popularity: 70,
    tags: ["agnipath", "agniveer", "indian navy", "ssr", "mr", "recruitment"],
    online: true,
  },
  {
    id: "agnipath-agniveer-airforce",
    slug: "agnipath-agniveer-airforce",
    name: "AGNIPATH — Agniveer (Indian Air Force)",
    category: "defence-veterans",
    subcategory: "Recruitment",
    summary: "Apply for Agniveer Vayu entry in the Indian Air Force under the AGNIPATH scheme.",
    description: "The Indian Air Force enrolls Agniveer Vayu (Non-Combatant and Combatant trades) under the AGNIPATH scheme for a 4-year engagement. Recruitment is conducted through the online Agniveer Vayu Intake portal on indianairforce.nic.in with an online test, physical fitness test, adaptability test and medical examination.",
    ministry: "Ministry of Defence / Indian Air Force",
    officialPortal: "Indian Air Force — Agniveer Vayu",
    officialUrl: "https://agnipathvayu.cdac.in/",
    eligibility: ["Age 17.5-21 years", "10+2 / Diploma (Science) for combatant; Class 10 for non-combatant", "Unmarried male & female Indian citizens"],
    documentsRequired: ["10+2 marksheet / Diploma certificate", "Aadhaar", "PAN", "Domicile certificate", "Photograph"],
    fee: 250,
    feeNote: "Application fee ₹250.",
    processingTime: "6-12 months",
    howToApply: [
      "Register on agnipathvayu.cdac.in.",
      "Fill the Agniveer Vayu application for the relevant intake.",
      "Pay ₹250 fee online and download admit card.",
      "Appear for online test (English, Physics, Maths / Reasoning).",
      "Qualified candidates undergo PFT, adaptability test and medical; join training on selection.",
    ],
    serviceCharge: 80,
    popularity: 72,
    tags: ["agnipath", "agniveer vayu", "indian air force", "recruitment", "defence"],
    online: true,
  },
  {
    id: "indian-army-recruitment-jco-or",
    slug: "indian-army-recruitment-jco-or",
    name: "Indian Army Recruitment — JCO / OR (Regular)",
    category: "defence-veterans",
    subcategory: "Recruitment",
    summary: "Apply for regular recruitment of Junior Commissioned Officers and Other Ranks in the Indian Army.",
    description: "Regular recruitment of Junior Commissioned Officers (JCO) and Other Ranks (OR) into the Indian Army is conducted through Army Recruitment Offices (AROs) under the aegis of Army Headquarters. Online applications are invited for trades such as Soldier GD, Clerk, Technical, Tradesman, Nursing Assistant and JCO Religious Teacher.",
    ministry: "Ministry of Defence / Indian Army",
    officialPortal: "Join Indian Army",
    officialUrl: "https://joinindianarmy.nic.in/",
    eligibility: ["Age 17.5-23 years (varies by trade)", "Class 8 / 10 / 12 / Diploma / Graduate as per trade", "Indian citizen", "Meets physical & medical standards"],
    documentsRequired: ["Class 10 / 12 marksheet", "Aadhaar", "PAN", "Domicile / caste certificate", "Photographs"],
    fee: 0,
    feeNote: "Application is free; recruitment is conducted through open rallies.",
    processingTime: "6-12 months",
    howToApply: [
      "Register on joinindianarmy.nic.in with Aadhaar.",
      "Fill the online application for the desired trade and ARO.",
      "Download admit card for the Army Rally / CEE.",
      "Attend the rally for physical, medical and CEE.",
      "Selected candidates receive joining letter for training.",
    ],
    serviceCharge: 80,
    popularity: 76,
    tags: ["indian army", "jco", "or", "rally", "recruitment", "soldier"],
    online: true,
  },
  {
    id: "ncc-enrollment",
    slug: "ncc-enrollment",
    name: "NCC Enrollment",
    category: "defence-veterans",
    subcategory: "Youth & Cadets",
    summary: "Enroll as a cadet in the National Cadet Corps (Army / Navy / Air Wing) through your school or college.",
    description: "The National Cadet Corps (NCC) is the youth wing of the Indian Armed Forces, enrolling school (Junior Division, Class 8-10) and college (Senior Division, Class 11 onwards) students as cadets. Training is conducted in Army, Navy and Air Wings with annual camps, the 'B' and 'C' certificate examinations and quota benefits in defence recruitment.",
    ministry: "Ministry of Defence",
    officialPortal: "National Cadet Corps",
    officialUrl: "https://nccindia.nic.in/",
    eligibility: ["School students of Class 8-10 (JD/JW)", "College students of Class 11+ (SD/SW)", "Indian citizen", "Meets medical fitness"],
    documentsRequired: ["School / college ID", "Aadhaar", "Medical fitness certificate", "Photographs", "Parental consent"],
    fee: 0,
    feeNote: "Free enrollment; nominal camp fee ~₹50-₹100 per camp.",
    processingTime: "30 days",
    howToApply: [
      "Contact the NCC in-charge (ANO) at your school or college.",
      "Fill the NCC enrollment form (Form 1 / 2).",
      "Attach school ID, Aadhaar and parental consent.",
      "Undergo a basic medical check-up at the unit.",
      "Begin attending NCC parades and training as enrolled cadet.",
    ],
    serviceCharge: 40,
    popularity: 50,
    tags: ["ncc", "cadet", "youth", "defence", "school"],
    online: false,
  },
  {
    id: "veer-nari-scheme",
    slug: "veer-nari-scheme",
    name: "Veer Nari Scheme",
    category: "defence-veterans",
    subcategory: "Welfare",
    summary: "Welfare and rehabilitation scheme for widows of martyred defence personnel.",
    description: "The Veer Nari scheme, run through Kendriya Sainik Board (KSB) and Zila Sainik Boards, provides widows of martyred defence personnel with enhanced family pension, reservation in CGHS / ECHS, education quota for children, employment reservation in Group C & D posts and preference in allotment of LIG / MIG houses by central and state agencies.",
    ministry: "Department of Ex-Servicemen Welfare / Kendriya Sainik Board",
    officialPortal: "Kendriya Sainik Board",
    officialUrl: "https://ksb.gov.in/",
    eligibility: ["Widows of battle casualties and martyrs", "Widows of personnel dying attributable to service"],
    documentsRequired: ["Casualty certificate", "Death certificate", "PPO / family pension order", "Aadhaar of widow", "Marriage certificate"],
    fee: 0,
    feeNote: "Free.",
    processingTime: "1-3 months for registration; benefits ongoing",
    howToApply: [
      "Approach the Zila Sainik Welfare Office with casualty and death certificates.",
      "Register as Veer Nari and obtain the Veer Nari identity card.",
      "Apply for enhanced family pension through PCDA (Pension).",
      "Submit children's school / college details for education benefits.",
      "Approach employment exchange for reservation in Group C / D posts.",
    ],
    serviceCharge: 100,
    popularity: 45,
    tags: ["veer nari", "widow", "martyr", "ksb", "welfare", "defence"],
    online: false,
  },
];
