import type { GovernmentService } from "../types";

export const educationScholarships: GovernmentService[] = [
  {
    id: "cbse-class-10-exam-registration",
    slug: "cbse-class-10-exam-registration",
    name: "CBSE Class 10 Board Exam Registration",
    category: "education-scholarships",
    subcategory: "Board Exams",
    summary: "Annual registration for Class 10 (Secondary) CBSE Board Examination.",
    description:
      "Central Board of Secondary Education (CBSE) conducts the All India Secondary School Examination (Class 10) every year. Schools register regular students through the CBSE Pariksha Sangam / e-Pareeksha portal; private candidates register themselves for the board exam.",
    ministry: "Ministry of Education (CBSE)",
    officialPortal: "CBSE Pariksha Sangam",
    officialUrl: "https://www.cbse.gov.in/",
    eligibility: [
      "Student of CBSE-affiliated school (regular) or private candidate",
      "Has passed Class 9 from a recognised school",
      "Meets minimum attendance requirement",
    ],
    documentsRequired: [
      "Class 9 pass certificate / report card",
      "Aadhaar of student",
      "School ID / affiliation details",
      "Caste / category certificate (if reservation availed)",
      "Recent passport-size photograph",
    ],
    fee: 1500,
    feeNote:
      "Registration ₹1,500 (India, 5 subjects); ₹300 per additional subject; ₹10,000+ for exam centres abroad.",
    processingTime: "Registration window: Sep–Oct; exams in Feb–Mar",
    howToApply: [
      "School logs in to the CBSE Pariksha Sangam portal.",
      "Fill student details, subjects and Aadhaar.",
      "Upload photographs and category certificates.",
      "Pay the registration fee online.",
      "Download confirmation page and admit card later.",
    ],
    serviceCharge: 60,
    popularity: 85,
    tags: ["cbse", "class 10", "board exam", "secondary", "registration"],
    online: true,
  },
  {
    id: "cbse-class-12-exam-registration",
    slug: "cbse-class-12-exam-registration",
    name: "CBSE Class 12 Board Exam Registration",
    category: "education-scholarships",
    subcategory: "Board Exams",
    summary: "Annual registration for Class 12 (Senior School Certificate) CBSE Board Examination.",
    description:
      "CBSE conducts the All India Senior School Certificate Examination (Class 12) for Science, Commerce and Arts streams. Registration is done by schools through the CBSE portal; private candidates can also register for select subjects.",
    ministry: "Ministry of Education (CBSE)",
    officialPortal: "CBSE Pariksha Sangam",
    officialUrl: "https://www.cbse.gov.in/",
    eligibility: ["Student of CBSE-affiliated school who has passed Class 11", "Private candidate eligible for select subjects"],
    documentsRequired: [
      "Class 11 pass certificate",
      "Class 10 pass certificate",
      "Aadhaar of student",
      "Subject / stream choice list",
      "Category certificate if applicable",
    ],
    fee: 1500,
    feeNote:
      "Registration ₹1,500 (India, 5 subjects); ₹300 per additional subject; ₹10,000+ for abroad centres.",
    processingTime: "Registration Aug–Oct; exams in Feb–Mar",
    howToApply: [
      "School admin logs in to CBSE Pariksha Sangam.",
      "Enter student & subject details for Class 12.",
      "Upload documents and photographs.",
      "Pay registration fee online.",
      "Generate confirmation page; download admit card later.",
    ],
    serviceCharge: 60,
    popularity: 86,
    tags: ["cbse", "class 12", "board exam", "senior secondary", "registration"],
    online: true,
  },
  {
    id: "icse-isc-board-registration",
    slug: "icse-isc-board-registration",
    name: "ICSE / ISC Board Registration",
    category: "education-scholarships",
    subcategory: "Board Exams",
    summary: "Register for ICSE (Class 10) or ISC (Class 12) examination conducted by CISCE.",
    description:
      "The Council for the Indian School Certificate Examinations (CISCE) conducts the ICSE (Class 10) and ISC (Class 12) examinations. Affiliated schools register students through the CISCE Careers portal for the annual board examinations.",
    ministry: "Ministry of Education (CISCE)",
    officialPortal: "CISCE Careers Portal",
    officialUrl: "https://www.cisce.org/",
    eligibility: ["Student of a CISCE-affiliated school", "Has passed the previous class with required attendance"],
    documentsRequired: ["Previous class pass certificate", "Aadhaar of student", "School enrolment details", "Subject choices", "Category certificate if applicable"],
    fee: 2800,
    feeNote: "ICSE registration ₹2,000–₹2,500; ISC ₹2,500–₹3,000 plus per-subject exam fee.",
    processingTime: "Registration window: Aug–Oct; exams Feb–Apr",
    howToApply: [
      "School logs in to the CISCE Careers portal.",
      "Fill student details and subject choices.",
      "Upload photographs and documents.",
      "Pay registration fee online.",
      "Download hall tickets before the exam.",
    ],
    serviceCharge: 70,
    popularity: 60,
    tags: ["icse", "isc", "cisce", "board exam", "registration"],
    online: true,
  },
  {
    id: "nios-secondary-admission",
    slug: "nios-secondary-admission",
    name: "NIOS Admission (Secondary – Class 10)",
    category: "education-scholarships",
    subcategory: "Open Schooling",
    summary: "Take admission in NIOS Secondary (Class 10) equivalent programme through open schooling.",
    description:
      "The National Institute of Open Schooling (NIOS) offers Secondary (Class 10) education equivalent to CBSE, designed for school dropouts, working learners and those who cannot attend regular school. Admissions open twice a year (April & October sessions).",
    ministry: "Ministry of Education (NIOS)",
    officialPortal: "NIOS Student Portal",
    officialUrl: "https://nos.org/",
    eligibility: [
      "Minimum 14 years of age",
      "Class 8 pass (or self-certified able to attempt Class 10)",
      "Indian citizen or overseas citizen of India",
    ],
    documentsRequired: ["Class 8 marksheet (if available)", "Aadhaar / valid ID", "Date of birth proof", "Recent photograph", "Category certificate if applicable"],
    fee: 580,
    feeNote:
      "₹200 registration + ₹480 (5 subjects); ₹180 per extra theory + ₹100 per practical; SC/ST/Ex-Servicemen/PwD get fee concession.",
    processingTime: "Admission confirmation in 4–6 weeks; exams in Apr–May & Oct–Nov",
    howToApply: [
      "Register on the NIOS online admission portal.",
      "Choose stream (Stream 1 for regular admissions).",
      "Select 5 subjects and 1 language minimum.",
      "Upload documents and photograph.",
      "Pay fee online and download identity card.",
    ],
    serviceCharge: 80,
    popularity: 58,
    tags: ["nios", "secondary", "class 10", "open schooling", "admission"],
    online: true,
  },
  {
    id: "nios-senior-secondary-admission",
    slug: "nios-senior-secondary-admission",
    name: "NIOS Admission (Senior Secondary – Class 12)",
    category: "education-scholarships",
    subcategory: "Open Schooling",
    summary: "Take admission in NIOS Senior Secondary (Class 12) equivalent programme.",
    description:
      "NIOS Senior Secondary (Class 12) is recognised equivalent to CBSE / CISCE for higher education and employment. Students choose subjects from Science, Commerce and Humanities streams; admissions are conducted twice a year.",
    ministry: "Ministry of Education (NIOS)",
    officialPortal: "NIOS Student Portal",
    officialUrl: "https://nos.org/",
    eligibility: ["Class 10 / Secondary pass from a recognised board", "Minimum 15 years of age"],
    documentsRequired: ["Class 10 pass certificate", "Aadhaar / valid ID", "Recent photograph", "Category certificate if applicable"],
    fee: 680,
    feeNote:
      "₹200 registration + ₹600 (5 subjects); ₹180 per extra theory + ₹100 per practical; fee concessions for SC/ST/PwD/Ex-Servicemen.",
    processingTime: "Admission confirmation 4–6 weeks; exams Apr–May & Oct–Nov",
    howToApply: [
      "Register on the NIOS online admission portal.",
      "Select Senior Secondary and stream.",
      "Choose minimum 5 subjects including 1 language.",
      "Upload documents and pay fee online.",
      "Receive study material and identity card.",
    ],
    serviceCharge: 80,
    popularity: 55,
    tags: ["nios", "senior secondary", "class 12", "open schooling", "admission"],
    online: true,
  },
  {
    id: "national-scholarship-portal-application",
    slug: "national-scholarship-portal-application",
    name: "National Scholarship Portal (NSP) Application",
    category: "education-scholarships",
    subcategory: "Scholarships",
    summary: "Single window to apply for 100+ central & state scholarships (pre- & post-matric).",
    description:
      "The National Scholarship Portal (NSP) is the official single-window platform for scholarships from Central Ministries, State Governments and UGC/AICTE. Students apply, track and receive scholarships directly into their bank accounts through DBT.",
    ministry: "Ministry of Education (NSP)",
    officialPortal: "National Scholarship Portal",
    officialUrl: "https://scholarships.gov.in/",
    eligibility: ["Students studying in India in recognised institutions", "Family income within scheme limits", "Category / merit as per each scheme"],
    documentsRequired: ["Aadhaar", "Bank passbook / account details", "Income certificate", "Caste certificate (if applicable)", "Previous class marksheet", "Bonafide / institution verification"],
    fee: 0,
    feeNote: "Free to apply on NSP.",
    processingTime: "Verification & disbursal: 2–6 months",
    howToApply: [
      "Register on scholarships.gov.in with Aadhaar / OTR.",
      "Complete student profile & academic details.",
      "Select the eligible scholarship scheme(s).",
      "Upload documents and submit application.",
      "Institute verifies online; disbursal via DBT.",
    ],
    serviceCharge: 50,
    popularity: 90,
    tags: ["nsp", "scholarship", "dbt", "education", "central"],
    online: true,
  },
  {
    id: "pre-matric-scholarship-sc",
    slug: "pre-matric-scholarship-sc",
    name: "Pre-Matric Scholarship for SC Students",
    category: "education-scholarships",
    subcategory: "Pre-Matric Scholarships",
    summary: "Scholarship for Scheduled Caste students studying in Classes 1 to 10.",
    description:
      "The Ministry of Social Justice & Empowerment provides Pre-Matric Scholarship to SC students to reduce dropout rates at the pre-matric stage. The scholarship includes a maintenance allowance, book grant and ad-hoc grant, credited through DBT.",
    ministry: "Ministry of Social Justice & Empowerment",
    officialPortal: "National Scholarship Portal",
    officialUrl: "https://scholarships.gov.in/",
    eligibility: ["SC category student in Class 1–10", "Family income up to ₹2.5 lakh per annum", "Studying in recognised institution"],
    documentsRequired: ["Caste certificate (SC)", "Income certificate", "Aadhaar", "Bonafide certificate", "Bank passbook"],
    fee: 0,
    feeNote: "Free to apply; scholarship amounts ₹350–₹950 per month + book grant.",
    processingTime: "2–6 months after verification",
    howToApply: [
      "Register / login on scholarships.gov.in.",
      "Select 'Pre-Matric Scholarship for SC'.",
      "Fill academic, family and bank details.",
      "Upload caste, income and bonafide certificates.",
      "Submit and get institute verification done.",
    ],
    serviceCharge: 50,
    popularity: 75,
    tags: ["pre matric", "sc", "scholarship", "social justice"],
    online: true,
  },
  {
    id: "pre-matric-scholarship-st",
    slug: "pre-matric-scholarship-st",
    name: "Pre-Matric Scholarship for ST Students",
    category: "education-scholarships",
    subcategory: "Pre-Matric Scholarships",
    summary: "Scholarship for Scheduled Tribe students studying in Classes 1 to 10.",
    description:
      "The Ministry of Tribal Affairs administers Pre-Matric Scholarship for ST students, particularly those in Classes 9 & 10, to support their schooling. The scholarship includes maintenance, book and ad-hoc grants disbursed through DBT.",
    ministry: "Ministry of Tribal Affairs",
    officialPortal: "National Scholarship Portal",
    officialUrl: "https://scholarships.gov.in/",
    eligibility: ["ST category student in Class 1–10", "Family income up to ₹2.5 lakh per annum", "Studying in recognised institution"],
    documentsRequired: ["Caste certificate (ST)", "Income certificate", "Aadhaar", "Bonafide certificate", "Bank passbook"],
    fee: 0,
    feeNote: "Free to apply; scholarship ₹350–₹950 per month + book grant.",
    processingTime: "2–6 months after verification",
    howToApply: [
      "Register on NSP with Aadhaar.",
      "Choose Pre-Matric Scholarship for ST.",
      "Fill academic & family income details.",
      "Upload caste, income and bonafide certificates.",
      "Submit and get institute verification.",
    ],
    serviceCharge: 50,
    popularity: 70,
    tags: ["pre matric", "st", "scholarship", "tribal affairs"],
    online: true,
  },
  {
    id: "pre-matric-scholarship-obc",
    slug: "pre-matric-scholarship-obc",
    name: "Pre-Matric Scholarship for OBC Students",
    category: "education-scholarships",
    subcategory: "Pre-Matric Scholarships",
    summary: "Scholarship for OBC / EBC / Denotified students in Classes 1 to 10.",
    description:
      "The Ministry of Social Justice & Empowerment provides Pre-Matric Scholarship to OBC, EBC and Denotified Tribal students to encourage their continued education at the pre-matric level. The scholarship includes a maintenance allowance and ad-hoc grant.",
    ministry: "Ministry of Social Justice & Empowerment",
    officialPortal: "National Scholarship Portal",
    officialUrl: "https://scholarships.gov.in/",
    eligibility: ["OBC / EBC / DNT student in Class 1–10", "Family income up to ₹2.5 lakh per annum"],
    documentsRequired: ["Caste certificate (OBC/EBC/DNT)", "Income certificate", "Aadhaar", "Bonafide certificate", "Bank passbook"],
    fee: 0,
    feeNote: "Free to apply; scholarship amount varies by class and boarding/day scholar.",
    processingTime: "2–6 months after verification",
    howToApply: [
      "Register on NSP.",
      "Select Pre-Matric Scholarship for OBC.",
      "Provide academic & income details.",
      "Upload caste, income and bonafide documents.",
      "Submit and complete institute verification.",
    ],
    serviceCharge: 50,
    popularity: 65,
    tags: ["pre matric", "obc", "ebc", "scholarship", "social justice"],
    online: true,
  },
  {
    id: "post-matric-scholarship-sc",
    slug: "post-matric-scholarship-sc",
    name: "Post-Matric Scholarship for SC Students",
    category: "education-scholarships",
    subcategory: "Post-Matric Scholarships",
    summary: "Scholarship for SC students studying at post-matric (Class 11 to PhD) level.",
    description:
      "The Ministry of Social Justice & Empowerment's Post-Matric Scholarship for SC students supports higher education. It covers maintenance, non-refundable compulsory fees and study tour charges. Disbursal is through DBT directly to the student's bank account.",
    ministry: "Ministry of Social Justice & Empowerment",
    officialPortal: "National Scholarship Portal",
    officialUrl: "https://scholarships.gov.in/",
    eligibility: ["SC student in Class 11 / 12 / UG / PG / professional course", "Family income up to ₹2.5 lakh per annum"],
    documentsRequired: ["Caste certificate (SC)", "Income certificate", "Aadhaar", "Previous class marksheet", "Bonafide / fee receipt", "Bank passbook"],
    fee: 0,
    feeNote: "Free to apply; maintenance ₹350–₹1,200 per month + tuition fee reimbursement.",
    processingTime: "2–6 months",
    howToApply: [
      "Login to NSP with OTR / Aadhaar.",
      "Choose Post-Matric Scholarship for SC.",
      "Fill academic and bank details.",
      "Upload caste, income & bonafide certificates.",
      "Submit and complete institute verification.",
    ],
    serviceCharge: 50,
    popularity: 80,
    tags: ["post matric", "sc", "scholarship", "higher education"],
    online: true,
  },
  {
    id: "post-matric-scholarship-st",
    slug: "post-matric-scholarship-st",
    name: "Post-Matric Scholarship for ST Students",
    category: "education-scholarships",
    subcategory: "Post-Matric Scholarships",
    summary: "Scholarship for ST students pursuing post-matric courses.",
    description:
      "The Ministry of Tribal Affairs provides Post-Matric Scholarship to ST students for higher education. The scholarship covers maintenance, compulsory non-refundable fees and additional allowances for students with disabilities.",
    ministry: "Ministry of Tribal Affairs",
    officialPortal: "National Scholarship Portal",
    officialUrl: "https://scholarships.gov.in/",
    eligibility: ["ST student in Class 11 and above", "Family income up to ₹2.5 lakh per annum"],
    documentsRequired: ["Caste certificate (ST)", "Income certificate", "Aadhaar", "Previous marksheet", "Bonafide / fee receipt", "Bank passbook"],
    fee: 0,
    feeNote: "Free to apply; maintenance ₹350–₹1,200 per month + fee reimbursement.",
    processingTime: "2–6 months",
    howToApply: [
      "Register on NSP.",
      "Select Post-Matric Scholarship for ST.",
      "Fill academic and income details.",
      "Upload supporting documents.",
      "Submit for institute verification.",
    ],
    serviceCharge: 50,
    popularity: 75,
    tags: ["post matric", "st", "scholarship", "tribal affairs"],
    online: true,
  },
  {
    id: "post-matric-scholarship-obc",
    slug: "post-matric-scholarship-obc",
    name: "Post-Matric Scholarship for OBC Students",
    category: "education-scholarships",
    subcategory: "Post-Matric Scholarships",
    summary: "Scholarship for OBC students pursuing post-matric courses.",
    description:
      "The Ministry of Social Justice & Empowerment provides Post-Matric Scholarship to OBC students to support their higher education. The scheme offers maintenance allowance and reimbursement of compulsory non-refundable fees for eligible courses.",
    ministry: "Ministry of Social Justice & Empowerment",
    officialPortal: "National Scholarship Portal",
    officialUrl: "https://scholarships.gov.in/",
    eligibility: ["OBC student in Class 11 and above", "Family income up to ₹1.5 lakh (or ₹3 lakh in some states) per annum"],
    documentsRequired: ["OBC certificate (non-creamy layer)", "Income certificate", "Aadhaar", "Previous marksheet", "Bonafide / fee receipt", "Bank passbook"],
    fee: 0,
    feeNote: "Free to apply; maintenance ₹350–₹750 per month + fee reimbursement.",
    processingTime: "2–6 months",
    howToApply: [
      "Register on NSP.",
      "Choose Post-Matric Scholarship for OBC.",
      "Fill academic, income and bank details.",
      "Upload caste, income and bonafide documents.",
      "Submit and complete institute verification.",
    ],
    serviceCharge: 50,
    popularity: 70,
    tags: ["post matric", "obc", "scholarship", "social justice"],
    online: true,
  },
  {
    id: "post-matric-scholarship-minorities",
    slug: "post-matric-scholarship-minorities",
    name: "Post-Matric Scholarship for Minorities",
    category: "education-scholarships",
    subcategory: "Post-Matric Scholarships",
    summary: "Scholarship for students from minority communities in post-matric courses.",
    description:
      "The Ministry of Minority Affairs offers Pre/Post-Matric Scholarships to students belonging to notified minorities (Muslims, Christians, Sikhs, Buddhists, Parsis and Jains). The Post-Matric scheme provides maintenance allowance and course fee assistance.",
    ministry: "Ministry of Minority Affairs",
    officialPortal: "National Scholarship Portal",
    officialUrl: "https://scholarships.gov.in/",
    eligibility: ["Minority community student in Class 11 and above", "Family income up to ₹2 lakh per annum", "Minimum 50% marks in previous exam"],
    documentsRequired: ["Minority community certificate", "Income certificate", "Previous marksheet (≥50%)", "Aadhaar", "Bonafide certificate", "Bank passbook"],
    fee: 0,
    feeNote: "Free to apply; maintenance ₹820–₹1,070 per month + course fee up to ₹20,000.",
    processingTime: "2–6 months",
    howToApply: [
      "Register on NSP.",
      "Select Post-Matric Scholarship for Minorities.",
      "Fill academic, family and bank details.",
      "Upload community, income and bonafide documents.",
      "Submit and complete institute verification.",
    ],
    serviceCharge: 50,
    popularity: 68,
    tags: ["post matric", "minorities", "scholarship", "minority affairs"],
    online: true,
  },
  {
    id: "means-cum-merit-scholarship",
    slug: "means-cum-merit-scholarship",
    name: "Means-cum-Merit Scholarship",
    category: "education-scholarships",
    subcategory: "Scholarships",
    summary: "Income-linked merit scholarship for school students on NSP.",
    description:
      "Means-cum-Merit Scholarships are offered by central ministries and several states to academically bright students from low-income families. The scheme helps reduce dropout rates at secondary and senior secondary level by providing annual financial support.",
    ministry: "Ministry of Education / State Governments",
    officialPortal: "National Scholarship Portal",
    officialUrl: "https://scholarships.gov.in/",
    eligibility: ["Class 9–12 student", "Family income within scheme limit (typically ₹1.5 lakh)", "Minimum 50–55% in previous class"],
    documentsRequired: ["Income certificate", "Previous marksheet", "Aadhaar", "Bonafide certificate", "Bank passbook"],
    fee: 0,
    feeNote: "Free to apply; award ₹6,000–₹12,000 per annum.",
    processingTime: "2–6 months",
    howToApply: [
      "Register / login on NSP.",
      "Choose Means-cum-Merit Scholarship scheme.",
      "Fill academic and family income details.",
      "Upload income certificate and marksheet.",
      "Submit for verification.",
    ],
    serviceCharge: 50,
    popularity: 60,
    tags: ["means cum merit", "scholarship", "school"],
    online: true,
  },
  {
    id: "nmms-national-means-cum-merit",
    slug: "nmms-national-means-cum-merit",
    name: "National Means-cum-Merit Scholarship (NMMS)",
    category: "education-scholarships",
    subcategory: "Scholarships",
    summary: "Central scholarship for Class 8 students to continue education in Classes 9–12.",
    description:
      "NMMS is a centrally sponsored scheme awarded through a national-level exam conducted by SCERTs / State Education Departments, coordinated by NCERT. Selected students receive ₹12,000 per year from Class 9 to 12 to prevent dropouts.",
    ministry: "Ministry of Education (NCERT / SCERTs)",
    officialPortal: "NMMS Portal (SCERT / NIC)",
    officialUrl: "https://dsel.education.gov.in/nmms",
    eligibility: ["Class 8 regular student in govt / govt-aided school", "Family income up to ₹3.5 lakh per annum", "Minimum 55% in Class 7 (50% for SC/ST)"],
    documentsRequired: ["Class 7 marksheet", "Income certificate", "Caste certificate if applicable", "Aadhaar", "Bonafide certificate"],
    fee: 0,
    feeNote: "Free to apply; exam fee ₹0; scholarship ₹12,000 per year for 4 years.",
    processingTime: "Exam in Nov; result in Feb–Mar",
    howToApply: [
      "Visit the SCERT / state NMMS portal.",
      "Register with Aadhaar & school details.",
      "Fill application and upload documents.",
      "Download admit card for the NMMS exam.",
      "Selected students receive scholarship through DBT.",
    ],
    serviceCharge: 60,
    popularity: 62,
    tags: ["nmms", "ncert", "scert", "scholarship", "class 8"],
    online: true,
  },
  {
    id: "aicte-pragati-scholarship-girls",
    slug: "aicte-pragati-scholarship-girls",
    name: "AICTE Pragati Scholarship (Girls)",
    category: "education-scholarships",
    subcategory: "AICTE Schemes",
    summary: "Scholarship for girl students in 1st year of technical diploma / degree.",
    description:
      "AICTE's Pragati Scheme supports two girls per family with ₹50,000 per year for tuition and ₹3,000 contingency for pursuing technical diploma or degree courses. Up to 10,000 scholarships are awarded annually on merit-cum-means basis.",
    ministry: "Ministry of Education (AICTE)",
    officialPortal: "AICTE Pragati Portal",
    officialUrl: "https://www.aicte-india.org/",
    eligibility: ["Girl student admitted to 1st year of technical diploma / degree (AICTE approved)", "Family income up to ₹8 lakh per annum", "Maximum 2 girls per family"],
    documentsRequired: ["Aadhaar", "Income certificate", "Admission proof / bonafide", "Previous class marksheet", "Bank passbook", "Caste / DNT certificate if applicable"],
    fee: 0,
    feeNote: "Free to apply; award ₹50,000 tuition + ₹3,000 contingency per year.",
    processingTime: "1–3 months after application window",
    howToApply: [
      "Register on the AICTE Pragati scholarship portal.",
      "Fill academic, income and bank details.",
      "Upload Aadhaar, income certificate and bonafide.",
      "Submit before the deadline (usually Oct–Nov).",
      "Selected students receive award through DBT.",
    ],
    serviceCharge: 60,
    popularity: 65,
    tags: ["aicte", "pragati", "girls", "scholarship", "technical education"],
    online: true,
  },
  {
    id: "aicte-saksham-scholarship-divyang",
    slug: "aicte-saksham-scholarship-divyang",
    name: "AICTE Saksham Scholarship (Divyang)",
    category: "education-scholarships",
    subcategory: "AICTE Schemes",
    summary: "Scholarship for specially-abled students in technical diploma / degree.",
    description:
      "AICTE Saksham Scheme supports Divyang (differently-abled) students admitted to 1st year of AICTE-approved technical diploma / degree with ₹50,000 tuition + ₹2,000 contingency per year. Up to 1,000 scholarships are awarded annually.",
    ministry: "Ministry of Education (AICTE)",
    officialPortal: "AICTE Saksham Portal",
    officialUrl: "https://www.aicte-india.org/",
    eligibility: ["Divyang student with ≥40% disability", "Admitted to AICTE-approved diploma / degree", "Family income up to ₹8 lakh per annum"],
    documentsRequired: ["Disability certificate (≥40%)", "Aadhaar", "Income certificate", "Admission proof", "Bank passbook"],
    fee: 0,
    feeNote: "Free to apply; award ₹50,000 tuition + ₹2,000 contingency per year.",
    processingTime: "1–3 months",
    howToApply: [
      "Register on the AICTE Saksham portal.",
      "Provide disability and academic details.",
      "Upload disability certificate, income and bonafide.",
      "Submit application online.",
      "Award disbursed through DBT.",
    ],
    serviceCharge: 60,
    popularity: 45,
    tags: ["aicte", "saksham", "divyang", "disability", "scholarship"],
    online: true,
  },
  {
    id: "aicte-pg-scholarship",
    slug: "aicte-pg-scholarship",
    name: "AICTE PG Scholarship (GATE / GPAT qualified)",
    category: "education-scholarships",
    subcategory: "AICTE Schemes",
    summary: "Monthly stipend for GATE / GPAT qualified ME / M.Pharm students.",
    description:
      "AICTE provides ₹12,400 per month for 24 months to GATE / GPAT qualified students pursuing full-time ME / M.Tech / M.Pharm in AICTE-approved institutions. The scholarship is credited through DBT and the institute verifies attendance every semester.",
    ministry: "Ministry of Education (AICTE)",
    officialPortal: "AICTE PG Scholarship Portal",
    officialUrl: "https://www.aicte-india.org/",
    eligibility: ["Valid GATE / GPAT score", "Admitted to full-time ME / M.Tech / M.Pharm in AICTE-approved institute", "Indian national"],
    documentsRequired: ["GATE / GPAT scorecard", "Admission / allotment letter", "Aadhaar", "Bank passbook", "Bonafide certificate"],
    fee: 0,
    feeNote: "Free to apply; award ₹12,400 per month for 24 months.",
    processingTime: "1–2 months after verification",
    howToApply: [
      "Register on the AICTE PG Scholarship portal.",
      "Enter GATE / GPAT details and admission info.",
      "Upload scorecard, admission letter and bank details.",
      "Institute verifies attendance online.",
      "Stipend is credited monthly through DBT.",
    ],
    serviceCharge: 60,
    popularity: 55,
    tags: ["aicte", "pg scholarship", "gate", "gpat", "stipend"],
    online: true,
  },
  {
    id: "ugc-jrf-net-fellowship",
    slug: "ugc-jrf-net-fellowship",
    name: "UGC JRF / NET Fellowship",
    category: "education-scholarships",
    subcategory: "Fellowships",
    summary: "Junior Research Fellowship for NET-qualified candidates pursuing PhD.",
    description:
      "The National Testing Agency (NTA) conducts UGC-NET twice a year. Top rank holders qualify for Junior Research Fellowship (JRF), receiving ₹37,000 (JRF) and ₹42,000 (SRF) per month plus contingency grant for 5 years to pursue research / PhD in Indian universities.",
    ministry: "University Grants Commission (UGC) / NTA",
    officialPortal: "NTA UGC-NET",
    officialUrl: "https://ugcnet.nta.ac.in/",
    eligibility: ["Master's degree with ≥55% (50% for reserved)", "Age ≤30 years for JRF (relaxation for reserved)"],
    documentsRequired: ["Master's degree / marksheet", "Category certificate (if applicable)", "Aadhaar", "Photograph & signature"],
    fee: 1150,
    feeNote:
      "NTA NET fee: ₹1,150 (Gen), ₹600 (OBC/EWS), ₹325 (SC/ST/PwD/Transgender).",
    processingTime: "Exam Jun & Dec; fellowship activation in 3–6 months after admission",
    howToApply: [
      "Register on ugcnet.nta.ac.in when notification is issued.",
      "Fill application form with subject choice.",
      "Upload photograph, signature and category certificate.",
      "Pay fee online and download confirmation page.",
      "Appear for the exam; qualify JRF cutoff for fellowship.",
    ],
    serviceCharge: 80,
    popularity: 60,
    tags: ["ugc", "jrf", "net", "fellowship", "research", "phd"],
    online: true,
  },
  {
    id: "ugc-manf-minority-fellowship",
    slug: "ugc-manf-minority-fellowship",
    name: "UGC MANF (Maulana Azad National Fellowship)",
    category: "education-scholarships",
    subcategory: "Fellowships",
    summary: "Fellowship for minority students pursuing M.Phil / PhD.",
    description:
      "The Maulana Azad National Fellowship (MANF), earlier by UGC and now coordinated via NSP, provides fellowship to minority community students pursuing full-time M.Phil / PhD. The fellowship covers JRF / SRF rates plus contingency and escorts allowance for PwD.",
    ministry: "Ministry of Minority Affairs (via UGC)",
    officialPortal: "National Scholarship Portal",
    officialUrl: "https://scholarships.gov.in/",
    eligibility: ["Minority community student", "Admitted to full-time M.Phil / PhD", "Family income up to ₹6 lakh per annum", "Qualified NET / equivalent or admitted without NET as per rules"],
    documentsRequired: ["Minority community certificate", "Income certificate", "M.Phil / PhD admission proof", "NET / GATE scorecard", "Aadhaar", "Bank passbook"],
    fee: 0,
    feeNote: "Free to apply; fellowship ₹37,000–₹42,000 per month + contingency.",
    processingTime: "3–6 months after verification",
    howToApply: [
      "Register on NSP when MANF scheme is open.",
      "Fill academic and fellowship-related details.",
      "Upload minority, income and admission documents.",
      "Submit and complete institute verification.",
      "Fellowship credited via DBT.",
    ],
    serviceCharge: 70,
    popularity: 45,
    tags: ["manf", "ugc", "minority", "fellowship", "mphil", "phd"],
    online: true,
  },
  {
    id: "ishan-uday-ne-region",
    slug: "ishan-uday-ne-region",
    name: "Ishan Uday Scholarship (NE Region)",
    category: "education-scholarships",
    subcategory: "Fellowships",
    summary: "Special scholarship for students of North-East India in UG / PG courses.",
    description:
      "Ishan Uday is a UGC scheme offering ₹5,440 (general courses) and ₹7,800 (technical / professional / medical courses) per month for students from the North-Eastern states pursuing UG / PG in recognised institutions across India.",
    ministry: "Ministry of Education (UGC)",
    officialPortal: "National Scholarship Portal",
    officialUrl: "https://scholarships.gov.in/",
    eligibility: ["Domicile of NER (8 NE states including Sikkim)", "Admitted to UG / PG after Class 12", "Family income up to ₹4.5 lakh per annum"],
    documentsRequired: ["Domicile certificate of NE state", "Income certificate", "Admission proof", "Previous marksheet", "Aadhaar", "Bank passbook"],
    fee: 0,
    feeNote: "Free to apply; award ₹5,440 / ₹7,800 per month for 2–5 years.",
    processingTime: "2–4 months",
    howToApply: [
      "Register on NSP and choose Ishan Uday scheme.",
      "Fill domicile, academic and bank details.",
      "Upload domicile, income and admission certificates.",
      "Submit and complete institute verification.",
      "Scholarship credited through DBT.",
    ],
    serviceCharge: 60,
    popularity: 40,
    tags: ["ishan uday", "ugc", "northeast", "scholarship"],
    online: true,
  },
  {
    id: "pm-scholarship-ex-servicemen",
    slug: "pm-scholarship-ex-servicemen",
    name: "PM Scholarship Scheme (Ex-Servicemen / Coast Guard)",
    category: "education-scholarships",
    subcategory: "Scholarships",
    summary: "Scholarship for wards of Ex-Servicemen / Coast Guard pursuing professional courses.",
    description:
      "The Prime Minister's Scholarship Scheme (PMSS) is administered by the Kendriya Sainik Board under the Department of Ex-Servicemen Welfare. It supports wards and widows of Ex-Servicemen / Coast Guard personnel pursuing professional degree courses (medical, engineering, dental, MBA, MCA, etc.) with ₹2,500–₹3,000 per month.",
    ministry: "Ministry of Defence (DESW / KSB)",
    officialPortal: "Kendriya Sainik Board Portal",
    officialUrl: "https://ksb.gov.in/",
    eligibility: [
      "Ward / widow of Ex-Serviceman / Coast Guard (with disability ≥50% or deceased)",
      "Pursuing 1st year professional degree (medical, dental, engineering, B.Tech, BAMS, BHMS, MBA, MCA, etc.)",
      "Not availing any other scholarship >₹1,000/month",
    ],
    documentsRequired: ["ESM / Coast Guard discharge book", "PPO / service pension certificate", "Aadhaar", "Bank passbook", "Admission proof / bonafide", "Previous marksheet"],
    fee: 0,
    feeNote: "Free to apply; ₹2,500/month (boys) and ₹3,000/month (girls) for 1–5 years.",
    processingTime: "2–4 months after application window",
    howToApply: [
      "Register on the KSB portal (ksb.gov.in).",
      "Apply for PMSS during the Jul–Oct window.",
      "Upload ESM details, PPO and admission proof.",
      "Submit and complete Zila Sainik Board verification.",
      "Selected candidates receive scholarship through DBT.",
    ],
    serviceCharge: 70,
    popularity: 40,
    tags: ["pm scholarship", "ex servicemen", "ksb", "defence", "scholarship"],
    online: true,
  },
  {
    id: "cbse-swami-vivekananda-single-girl-child",
    slug: "cbse-swami-vivekananda-single-girl-child",
    name: "SWAMI VIVEKANANDA Single Girl Child Scholarship",
    category: "education-scholarships",
    subcategory: "Scholarships",
    summary: "CBSE scholarship for the only girl child of parents studying in Class 11 & 12.",
    description:
      "CBSE's Swami Vivekananda Scholarship provides ₹500 per month for two years to a single girl child (the only child of parents) studying in Class 11 & 12 in CBSE-affiliated schools. The aim is to recognise and support the education of the single girl child.",
    ministry: "Ministry of Education (CBSE)",
    officialPortal: "CBSE Scholarship Portal",
    officialUrl: "https://www.cbse.gov.in/",
    eligibility: ["Single girl child (only child) of parents", "Studying in Class 11 / 12 in CBSE school", "Indian national", "Secured ≥60% in Class 10 CBSE exam"],
    documentsRequired: ["Class 10 marksheet (CBSE)", "Affidavit of single girl child", "Aadhaar / bonafide certificate", "Bank passbook", "Joint affidavit by parents"],
    fee: 0,
    feeNote: "Free to apply; award ₹500/month for 2 years (max ₹12,000).",
    processingTime: "2–3 months after application window",
    howToApply: [
      "Register on the CBSE scholarship portal.",
      "Select Swami Vivekananda Single Girl Child Scholarship.",
      "Fill academic and bank details.",
      "Upload marksheet and single girl child affidavit.",
      "Submit before deadline; award via DBT.",
    ],
    serviceCharge: 50,
    popularity: 38,
    tags: ["cbse", "swami vivekananda", "single girl child", "scholarship"],
    online: true,
  },
  {
    id: "neet-ug-application",
    slug: "neet-ug-application",
    name: "NEET UG Application",
    category: "education-scholarships",
    subcategory: "Entrance Exams",
    summary: "Apply for the National Eligibility cum Entrance Test (NEET-UG) for MBBS / BDS.",
    description:
      "The National Testing Agency (NTA) conducts NEET-UG annually for admission to MBBS, BDS, AYUSH, BSc Nursing and other medical courses. The single entrance test is mandatory for all medical aspirants across India.",
    ministry: "Ministry of Health & Family Welfare (NTA)",
    officialPortal: "NTA NEET",
    officialUrl: "https://neet.nta.nic.in/",
    eligibility: ["Class 12 pass / appearing with Physics, Chemistry, Biology/Biotech", "Minimum 50% (40% reserved) in PCB", "Age ≥17 years on Dec 31 of admission year"],
    documentsRequired: ["Class 10 & 12 marksheet / certificate", "Aadhaar", "Category certificate if applicable", "PwD certificate if applicable", "Photograph, signature & thumb impression"],
    fee: 1700,
    feeNote: "₹1,700 (Gen), ₹1,600 (OBC/EWS), ₹1,000 (SC/ST/PwD/Transgender).",
    processingTime: "Exam in May; result in Jun",
    howToApply: [
      "Register on neet.nta.nic.in when notification opens.",
      "Fill application form with personal & academic details.",
      "Upload photograph, signature and category certificate.",
      "Pay fee online and download confirmation page.",
      "Download admit card a few weeks before the exam.",
    ],
    serviceCharge: 70,
    popularity: 92,
    tags: ["neet", "mbbs", "bds", "medical", "nta", "entrance exam"],
    online: true,
  },
  {
    id: "jee-main-application",
    slug: "jee-main-application",
    name: "JEE Main Application",
    category: "education-scholarships",
    subcategory: "Entrance Exams",
    summary: "Apply for JEE Main — engineering entrance for NITs, IIITs, CFTIs.",
    description:
      "JEE Main is conducted by NTA four times a year (Session 1 & 2) for admission to undergraduate engineering (B.E./B.Tech) and architecture (B.Arch / B.Plan) courses in NITs, IIITs, CFTIs and as a qualifier for JEE Advanced.",
    ministry: "Ministry of Education (NTA)",
    officialPortal: "NTA JEE Main",
    officialUrl: "https://jeemain.nta.ac.in/",
    eligibility: ["Class 12 pass / appearing with Physics & Mathematics", "Minimum 75% (65% reserved) in Class 12 for NITs", "Born on/after 1 Oct 1999 (relaxation for reserved)"],
    documentsRequired: ["Class 10 & 12 marksheet", "Aadhaar", "Category certificate if applicable", "PwD certificate if applicable", "Photograph & signature"],
    fee: 1000,
    feeNote: "₹1,000 (Gen/OBC, single paper, single session), ₹800 (SC/ST/PwD/Female); both papers / both sessions extra.",
    processingTime: "Sessions in Jan–Apr; result after each session",
    howToApply: [
      "Register on jeemain.nta.ac.in.",
      "Fill personal, academic and exam centre details.",
      "Upload photograph, signature and certificates.",
      "Pay fee online via net banking / UPI / card.",
      "Download confirmation page; admit card later.",
    ],
    serviceCharge: 70,
    popularity: 90,
    tags: ["jee main", "engineering", "nit", "iit", "nta", "entrance exam"],
    online: true,
  },
  {
    id: "jee-advanced-application",
    slug: "jee-advanced-application",
    name: "JEE Advanced Application",
    category: "education-scholarships",
    subcategory: "Entrance Exams",
    summary: "Apply for JEE Advanced — entrance to undergraduate programmes at IITs.",
    description:
      "JEE Advanced is conducted by one of the IITs (on rotational basis under JAB) for admission to B.Tech / B.Arch programmes at the 23 IITs. Only the top 2.5 lakh JEE Main qualifiers are eligible to register.",
    ministry: "Ministry of Education (IIT-JAB)",
    officialPortal: "JEE Advanced",
    officialUrl: "https://jeeadv.ac.in/",
    eligibility: [
      "Top 2.5 lakh rankers in JEE Main (B.E./B.Tech paper)",
      "Class 12 pass with minimum 75% (65% reserved) or top 20 percentile",
      "Maximum 2 attempts in 2 consecutive years",
    ],
    documentsRequired: ["JEE Main scorecard / rank", "Class 12 marksheet", "Aadhaar / passport", "Category certificate if applicable", "Photograph & signature"],
    fee: 2900,
    feeNote: "₹2,900 (Gen/OBC/EWS), ₹1,450 (SC/ST/PwD/Female); SAARC candidates USD 90, non-SAARC USD 180.",
    processingTime: "Exam in May; result in Jun",
    howToApply: [
      "Visit jeeadv.ac.in and register with JEE Main roll no.",
      "Fill personal and academic details.",
      "Choose exam centres and language preference.",
      "Pay fee online and download confirmation page.",
      "Download admit card before the exam.",
    ],
    serviceCharge: 80,
    popularity: 78,
    tags: ["jee advanced", "iit", "engineering", "entrance exam"],
    online: true,
  },
  {
    id: "cat-application",
    slug: "cat-application",
    name: "CAT Application (Common Admission Test)",
    category: "education-scholarships",
    subcategory: "Entrance Exams",
    summary: "Apply for the Common Admission Test for admission to IIMs & 1,000+ B-schools.",
    description:
      "CAT is conducted by one of the older IIMs on rotational basis for admission to the Post Graduate Programme in Management (MBA / PGDM) at IIMs and over 1,000 participating B-schools across India.",
    ministry: "Ministry of Education (IIMs)",
    officialPortal: "CAT (IIM)",
    officialUrl: "https://iimcat.ac.in/",
    eligibility: ["Bachelor's degree with ≥50% (45% reserved) or equivalent CGPA", "Final year graduation students eligible"],
    documentsRequired: ["Bachelor's degree / marksheet", "Aadhaar", "Category certificate if applicable", "PwD certificate if applicable", "Photograph & signature"],
    fee: 2500,
    feeNote: "₹2,500 (Gen/OBC/EWS), ₹1,250 (SC/ST/PwD).",
    processingTime: "Exam in Nov; result in Jan",
    howToApply: [
      "Register on iimcat.ac.in when notification opens.",
      "Fill personal, academic and work-experience details.",
      "Select 6 preferred IIMs / test cities.",
      "Pay fee online and download confirmation page.",
      "Download admit card in October.",
    ],
    serviceCharge: 80,
    popularity: 75,
    tags: ["cat", "iim", "mba", "management", "entrance exam"],
    online: true,
  },
  {
    id: "clat-application",
    slug: "clat-application",
    name: "CLAT Application (Common Law Admission Test)",
    category: "education-scholarships",
    subcategory: "Entrance Exams",
    summary: "Apply for CLAT — national entrance for admission to NLUs.",
    description:
      "CLAT is a centralised national-level entrance test conducted by the Consortium of NLUs for admission to 5-year integrated LLB (UG) and 1-year LLM (PG) programmes at the 24 National Law Universities.",
    ministry: "Ministry of Education (Consortium of NLUs)",
    officialPortal: "Consortium of NLUs",
    officialUrl: "https://consortiumofnlus.ac.in/",
    eligibility: ["Class 12 pass with ≥45% (40% reserved) for UG LLB", "LLB degree with ≥50% (45% reserved) for PG LLM", "No upper age limit for UG"],
    documentsRequired: ["Class 10 & 12 marksheet / certificate", "Aadhaar", "Category certificate if applicable", "PwD / BPL certificate if applicable", "Photograph & signature"],
    fee: 4000,
    feeNote: "₹4,000 (Gen/OBC/PwD/NRI/PIO/OCI), ₹3,500 (SC/ST/BPL).",
    processingTime: "Exam in Dec; result in Jan",
    howToApply: [
      "Register on consortiumofnlus.ac.in.",
      "Fill personal & academic details.",
      "Choose exam centres and NLU preferences.",
      "Pay fee online and download confirmation page.",
      "Download admit card before the exam.",
    ],
    serviceCharge: 70,
    popularity: 60,
    tags: ["clat", "law", "nlu", "entrance exam"],
    online: true,
  },
  {
    id: "gate-application",
    slug: "gate-application",
    name: "GATE Application (Graduate Aptitude Test in Engineering)",
    category: "education-scholarships",
    subcategory: "Entrance Exams",
    summary: "Apply for GATE — entrance for M.Tech / ME / PSUs recruitment.",
    description:
      "GATE is conducted jointly by IISc Bangalore and 7 IITs on rotational basis for admission to postgraduate engineering programmes (M.E./M.Tech/PhD) and direct recruitment by several PSUs. Score is valid for 3 years.",
    ministry: "Ministry of Education (IISc / IITs)",
    officialPortal: "GATE Online Application Processing System (GOAPS)",
    officialUrl: "https://gate.iitk.ac.in/",
    eligibility: ["Bachelor's degree in Engineering / Tech / Architecture (4+ years) OR", "Master's degree in Science / Maths / Statistics / Computer Applications", "3rd year+ students also eligible"],
    documentsRequired: ["Degree / marksheet of qualifying exam", "Aadhaar / valid ID", "Category certificate if applicable", "PwD certificate if applicable", "Photograph & signature"],
    fee: 1900,
    feeNote: "₹1,900 (Gen/OBC/EWS), ₹950 (SC/ST/PwD/Female) if applied within deadline; ₹2,900 / ₹1,450 late fee.",
    processingTime: "Exam in Feb; result in Mar",
    howToApply: [
      "Register on GOAPS portal of organising IIT / IISc.",
      "Fill personal, academic and exam paper details.",
      "Upload photograph, signature and certificates.",
      "Pay fee online before the deadline.",
      "Download admit card in January.",
    ],
    serviceCharge: 70,
    popularity: 70,
    tags: ["gate", "mtech", "engineering", "psu", "entrance exam"],
    online: true,
  },
  {
    id: "cuet-ug-application",
    slug: "cuet-ug-application",
    name: "CUET UG Application",
    category: "education-scholarships",
    subcategory: "Entrance Exams",
    summary: "Apply for Common University Entrance Test (UG) for central universities.",
    description:
      "CUET (UG) is conducted by NTA for admission to undergraduate programmes in 45+ central, state, deemed and private universities including DU, JNU, BHU, etc. It offers 61 subjects and 33 languages to choose from.",
    ministry: "Ministry of Education (NTA)",
    officialPortal: "CUET (UG) Samarth",
    officialUrl: "https://cuet.samarth.ac.in/",
    eligibility: ["Class 12 pass / appearing from a recognised board", "Specific subject eligibility as per chosen university / programme"],
    documentsRequired: ["Class 10 & 12 marksheet", "Aadhaar", "Category certificate if applicable", "PwD certificate if applicable", "Photograph & signature"],
    fee: 1000,
    feeNote:
      "₹1,000 (Gen, 3 subjects), ₹900 (OBC/EWS), ₹800 (SC/ST/PwD/TG); ₹400 / ₹375 / ₹350 per additional subject.",
    processingTime: "Exam in May–Jun; result in Jul",
    howToApply: [
      "Register on cuet.samarth.ac.in.",
      "Fill personal, academic and subject choices.",
      "Select participating universities and programmes.",
      "Pay fee online and download confirmation.",
      "Download admit card before the exam.",
    ],
    serviceCharge: 70,
    popularity: 80,
    tags: ["cuet", "ug", "central university", "nta", "entrance exam"],
    online: true,
  },
  {
    id: "cuet-pg-application",
    slug: "cuet-pg-application",
    name: "CUET PG Application",
    category: "education-scholarships",
    subcategory: "Entrance Exams",
    summary: "Apply for Common University Entrance Test (PG) for postgraduate admissions.",
    description:
      "CUET (PG) is conducted by NTA for admission to PG programmes in central, state, deemed and private universities. The exam has 100 questions in the chosen subject and is computer-based.",
    ministry: "Ministry of Education (NTA)",
    officialPortal: "CUET PG (NTA)",
    officialUrl: "https://cuet.ntaonline.in/",
    eligibility: ["Bachelor's degree pass / appearing from a recognised university", "Subject eligibility as per chosen PG programme"],
    documentsRequired: ["Bachelor's degree / marksheet", "Aadhaar", "Category certificate if applicable", "PwD certificate if applicable", "Photograph & signature"],
    fee: 1200,
    feeNote: "₹1,200 (Gen, 1 paper), ₹1,000 (OBC/EWS-Gen), ₹900 (SC/ST/TG/PwD); ₹600 / ₹500 extra per additional paper.",
    processingTime: "Exam in Mar–Apr; result in Apr–May",
    howToApply: [
      "Register on cuet.ntaonline.in.",
      "Fill personal, academic and subject choices.",
      "Select universities and programmes.",
      "Pay fee online.",
      "Download admit card before the exam.",
    ],
    serviceCharge: 70,
    popularity: 70,
    tags: ["cuet pg", "postgraduate", "central university", "nta", "entrance exam"],
    online: true,
  },
  {
    id: "upsc-civil-services-application",
    slug: "upsc-civil-services-application",
    name: "UPSC Civil Services (CSE) Application",
    category: "education-scholarships",
    subcategory: "Entrance Exams",
    summary: "Apply for UPSC Civil Services Examination (IAS, IPS, IFS, etc.).",
    description:
      "The Civil Services Examination (CSE) is conducted by the Union Public Service Commission in three stages — Prelims, Mains and Interview — for selection to IAS, IPS, IFS and other Group A & B central services. It is among the most competitive exams in India.",
    ministry: "Union Public Service Commission",
    officialPortal: "UPSC Online",
    officialUrl: "https://www.upsc.gov.in/",
    eligibility: [
      "Indian citizen (for IAS / IPS); certain services open to Nepal / Bhutan citizens",
      "Graduate from a recognised university",
      "Age 21–32 years (relaxation: SC/ST +5, OBC +3, PwD +10)",
      "Maximum 6 attempts (relaxation for reserved)",
    ],
    documentsRequired: ["Graduation certificate / marksheet", "Aadhaar / valid photo ID", "Category certificate if applicable", "PwD / Ex-Servicemen certificate if applicable", "Photograph & signature"],
    fee: 100,
    feeNote: "₹100 (Gen/OBC) for Prelims; no fee for SC/ST/PwD/Female. Mains fee ₹200 (Gen/OBC) extra.",
    processingTime: "Prelims in May; Mains in Sep; Interview in Jan–Apr",
    howToApply: [
      "Register on upsconline.nic.in / upsc.gov.in.",
      "Fill Part I (personal, academic, optional subject).",
      "Complete Part II (fee payment, photo, signature, ID).",
      "Submit before the deadline (usually Feb–Mar).",
      "Download e-Admit card a few weeks before the exam.",
    ],
    serviceCharge: 100,
    popularity: 88,
    tags: ["upsc", "civil services", "ias", "ips", "exam", "prelims"],
    online: true,
  },
];
