import type { GovernmentService } from "../types";

export const electionsVoting: GovernmentService[] = [
  {
    id: "voter-form-6-new-registration",
    slug: "voter-form-6-new-registration",
    name: "Voter ID New Registration (Form 6)",
    category: "elections-voting",
    subcategory: "Voter Registration",
    summary: "First-time voter registration for Indian citizens aged 18 years and above using Form 6.",
    description:
      "Form 6 is the application for inclusion of a name in the electoral roll for the first time. Any Indian citizen who has attained 18 years of age as on 1st January, 1st April, 1st July or 1st October of the qualifying year can apply online through the Voter Portal or NVSP. The application is verified by the Booth Level Officer (BLO) and the Electoral Registration Officer (ERO) issues the EPIC card.",
    ministry: "Election Commission of India",
    officialPortal: "Voter Portal / NVSP",
    officialUrl: "https://voterportal.eci.gov.in/",
    eligibility: [
      "Indian citizen",
      "Age 18 years or above as on qualifying date (1st Jan/Apr/Jul/Oct)",
      "Ordinarily resident at the address given in the application",
      "Not already enrolled in any other constituency",
    ],
    documentsRequired: [
      "Aadhaar card (for identity verification)",
      "One documentary proof of address (Passport / Bank passbook / Utility bill / Rent agreement)",
      "One documentary proof of age (Birth certificate / Class 10 marksheet / PAN / Driving Licence)",
      "Recent passport-size photograph",
      "Form 6 (online form on Voter Portal)",
    ],
    fee: 0,
    feeNote: "Free. EPIC dispatched by speed post after approval.",
    processingTime: "30-45 days from application",
    howToApply: [
      "Register on voterportal.eci.gov.in using mobile number and email.",
      "Login and select 'New Registration for General Electors' → Form 6.",
      "Fill personal details, address and constituency; upload photograph, age proof and address proof.",
      "Submit the form and note the application ID for tracking.",
      "BLO visits the address for physical verification; ERO approves and EPIC is dispatched by post.",
    ],
    serviceCharge: 70,
    popularity: 88,
    tags: ["voter id", "epic", "form 6", "election", "eci", "registration"],
    online: true,
  },
  {
    id: "voter-form-8-correction",
    slug: "voter-form-8-correction",
    name: "Voter ID Correction / Modification (Form 8)",
    category: "elections-voting",
    subcategory: "Voter Registration",
    summary: "Correct details such as name, photograph, age, DOB, address or gender on the Electoral Roll.",
    description:
      "Form 8 is used by an already enrolled voter to correct entries in the electoral roll relating to name, photograph, age, date of birth, address, EPIC number, gender, or name of relative. The application can be filed online through the Voter Portal or NVSP, and the corrected EPIC is issued free of charge after ERO verification.",
    ministry: "Election Commission of India",
    officialPortal: "Voter Portal / NVSP",
    officialUrl: "https://voterportal.eci.gov.in/",
    eligibility: [
      "Already enrolled voter with an active EPIC",
      "Error in existing entry on the electoral roll",
      "Application filed in the same constituency where the voter is enrolled",
    ],
    documentsRequired: [
      "Existing EPIC number",
      "Aadhaar card",
      "Supporting document for the correction (e.g., corrected name proof, new photo, address proof)",
      "Recent passport-size photograph (if photo correction)",
      "Form 8 (online form)",
    ],
    fee: 0,
    feeNote: "Free. Corrected EPIC issued post-approval.",
    processingTime: "30-45 days",
    howToApply: [
      "Login to voterportal.eci.gov.in and select 'Correction of Entries' → Form 8.",
      "Enter EPIC number and verify existing details auto-fetched from electoral roll.",
      "Select fields to correct and upload supporting documents for each correction.",
      "Submit and note the application ID; BLO conducts verification if required.",
      "ERO approves the correction; corrected EPIC is dispatched by post.",
    ],
    serviceCharge: 60,
    popularity: 85,
    tags: ["voter id", "epic", "form 8", "correction", "eci", "election"],
    online: true,
  },
  {
    id: "voter-form-8a-address-transfer",
    slug: "voter-form-8a-address-transfer",
    name: "Voter ID Address Transfer Within Constituency (Form 8A)",
    category: "elections-voting",
    subcategory: "Voter Registration",
    summary: "Transfer voter entry to a new address within the same Assembly Constituency.",
    description:
      "Form 8A is used when a voter shifts residence within the same Assembly Constituency and wants the electoral roll entry updated with the new address. For shifting to a different constituency, Form 6 (new registration) with deletion from old constituency via Form 7 is required. The corrected EPIC is dispatched after ERO approval.",
    ministry: "Election Commission of India",
    officialPortal: "Voter Portal / NVSP",
    officialUrl: "https://voterportal.eci.gov.in/",
    eligibility: [
      "Already enrolled voter with an EPIC",
      "New residence is within the same Assembly Constituency",
      "Not shifting to a different constituency (use Form 6 + Form 7 instead)",
    ],
    documentsRequired: [
      "Existing EPIC number",
      "Aadhaar card",
      "Proof of new address (Bank passbook / Utility bill / Rent agreement / Passport)",
      "Form 8A (online form)",
    ],
    fee: 0,
    feeNote: "Free. Address updated on the same EPIC.",
    processingTime: "30-45 days",
    howToApply: [
      "Login to voterportal.eci.gov.in and select 'Transposition of Entry' → Form 8A.",
      "Enter EPIC and verify existing address details.",
      "Provide the new address within the same AC and upload address proof.",
      "Submit the form; BLO verifies the new address.",
      "ERO updates the electoral roll; the same EPIC is valid with the new address.",
    ],
    serviceCharge: 55,
    popularity: 80,
    tags: ["voter id", "form 8a", "address transfer", "eci", "election"],
    online: true,
  },
  {
    id: "voter-form-7-deletion-objection",
    slug: "voter-form-7-deletion-objection",
    name: "Voter ID Deletion / Objection (Form 7)",
    category: "elections-voting",
    subcategory: "Voter Registration",
    summary: "Object to or seek deletion of a name from the electoral roll (death, shifting, duplicate entry).",
    description:
      "Form 7 is used to object to inclusion of a name in the electoral roll or to seek deletion of an entry on grounds such as death of the voter, shifting to another constituency, or duplicate enrollment. Any citizen can file an objection; the ERO conducts an inquiry before ordering deletion. The form is available online on the Voter Portal and NVSP.",
    ministry: "Election Commission of India",
    officialPortal: "Voter Portal / NVSP",
    officialUrl: "https://voterportal.eci.gov.in/",
    eligibility: [
      "Objector is a citizen of India",
      "Objector is a resident of the same constituency (or family member for death case)",
      "Ground for deletion: death, shifting to another constituency, duplicate entry, or non-residence",
    ],
    documentsRequired: [
      "EPIC number of the person whose name is sought to be deleted",
      "Aadhaar of the objector",
      "Death certificate (if deletion on death)",
      "Proof of shifting / duplicate enrollment (if applicable)",
      "Form 7 (online form)",
    ],
    fee: 0,
    feeNote: "Free. ERO gives a reasonable opportunity of being heard to the affected person.",
    processingTime: "30-60 days (with notice period to affected person)",
    howToApply: [
      "Login to voterportal.eci.gov.in and select 'Objection / Deletion' → Form 7.",
      "Enter EPIC of the person to be deleted and the ground for deletion.",
      "Upload supporting documents (death certificate / proof of shifting / etc.).",
      "Submit; ERO issues notice to the affected person and conducts inquiry.",
      "On finding the objection valid, ERO orders deletion from the electoral roll.",
    ],
    serviceCharge: 50,
    popularity: 60,
    tags: ["voter id", "form 7", "deletion", "objection", "eci", "election"],
    online: true,
  },
  {
    id: "voter-form-6a-overseas-registration",
    slug: "voter-form-6a-overseas-registration",
    name: "Overseas Voter Registration (Form 6A)",
    category: "elections-voting",
    subcategory: "Voter Registration",
    summary: "Register as an overseas (NRI) elector at the Indian residence address mentioned in passport.",
    description:
      "Form 6A allows a citizen of India who has not acquired citizenship of any other country and is residing abroad for employment, education or other purposes to be enrolled as an overseas elector at the Indian address mentioned in the passport. Once enrolled, the NRI can vote in person at the polling station on election day; proxy/postal ballot is not yet enabled for them.",
    ministry: "Election Commission of India",
    officialPortal: "Voter Portal / NVSP",
    officialUrl: "https://voterportal.eci.gov.in/",
    eligibility: [
      "Indian citizen who has not acquired citizenship of any other country",
      "Currently residing abroad for employment/education/business",
      "Holds a valid Indian passport",
      "Passport mentions an Indian address",
    ],
    documentsRequired: [
      "Indian Passport (valid)",
      "Aadhaar card (if available)",
      "Recent passport-size photograph",
      "Form 6A (online form)",
      "Self-attested copy of passport pages with VISA/Residence permit",
    ],
    fee: 0,
    feeNote: "Free. EPIC marked 'Overseas Elector' dispatched to Indian address.",
    processingTime: "30-45 days",
    howToApply: [
      "Register on voterportal.eci.gov.in and select 'New Registration for Overseas Electors' → Form 6A.",
      "Fill in passport details, Indian address mentioned in passport and current foreign address.",
      "Upload passport copy, photograph and visa/residence permit pages.",
      "Submit the form; the ERO of the constituency mentioned in passport verifies.",
      "On approval, EPIC marked 'Overseas Elector' is issued; voting only in person at the polling station.",
    ],
    serviceCharge: 90,
    popularity: 55,
    tags: ["voter id", "nri", "overseas", "form 6a", "eci", "election"],
    online: true,
  },
  {
    id: "eci-electoral-roll-search",
    slug: "eci-electoral-roll-search",
    name: "Electoral Roll Search (Elector Search)",
    category: "elections-voting",
    subcategory: "Electoral Information",
    summary: "Search your name on the national electoral roll by EPIC, mobile or personal details.",
    description:
      "The Election Commission's electoralsearch.in portal lets any citizen verify whether their name appears on the electoral roll. Search can be done using EPIC number, mobile number, or personal details (name, age, state, constituency, father/husband name). This is essential before every election since deletion of names by error is common.",
    ministry: "Election Commission of India",
    officialPortal: "Elector Search",
    officialUrl: "https://electoralsearch.in/",
    eligibility: [
      "Any citizen wanting to verify enrollment status",
      "Should have either EPIC number or basic personal details",
    ],
    documentsRequired: [
      "EPIC number or mobile number or name + state details",
      "No documents required for search",
    ],
    fee: 0,
    feeNote: "Free lookup service.",
    processingTime: "Instant",
    howToApply: [
      "Visit electoralsearch.in or use the Voter Helpline App.",
      "Choose 'Search by EPIC' or 'Search by Details' option.",
      "Enter EPIC + State OR Name + Father/Husband Name + Age + State + District Constituency.",
      "Complete the captcha and click Search.",
      "View enrollment status, polling station, AC/PC details and BLO contact.",
    ],
    serviceCharge: 25,
    popularity: 86,
    tags: ["voter id", "electoral roll", "search", "eci", "epic", "election"],
    online: true,
  },
  {
    id: "know-your-polling-station",
    slug: "know-your-polling-station",
    name: "Know Your Polling Station",
    category: "elections-voting",
    subcategory: "Electoral Information",
    summary: "Locate your polling station using EPIC number or address via the Voter Portal.",
    description:
      "The Election Commission's 'Know Your Polling Station' service on voterportal.eci.gov.in helps a voter identify the exact polling station assigned to their residence. Voters can search by EPIC number or by address to view the polling station name, address and a Google Maps location link. This is essential for first-time voters and after each delimitation.",
    ministry: "Election Commission of India",
    officialPortal: "Voter Portal",
    officialUrl: "https://voterportal.eci.gov.in/",
    eligibility: [
      "Registered voter with valid EPIC",
      "Or citizen wanting to find a polling station for a given address",
    ],
    documentsRequired: [
      "EPIC number (preferred)",
      "Or address details (State, District, AC, Locality)",
    ],
    fee: 0,
    feeNote: "Free lookup service.",
    processingTime: "Instant",
    howToApply: [
      "Visit voterportal.eci.gov.in and select 'Know Your Polling Station'.",
      "Enter EPIC number and State, or fill address (State, District, AC).",
      "Complete the captcha and click Search.",
      "View polling station name, full address and Google Maps navigation link.",
      "Save the location for use on election day.",
    ],
    serviceCharge: 25,
    popularity: 82,
    tags: ["polling station", "eci", "epic", "election", "voting"],
    online: true,
  },
  {
    id: "voter-helpline-app-download",
    slug: "voter-helpline-app-download",
    name: "Voter Helpline App (Download & Services)",
    category: "elections-voting",
    subcategory: "Electoral Information",
    summary: "Download the ECI Voter Helpline App for voter registration, search and complaint services.",
    description:
      "The Voter Helpline App is the official mobile app of the Election Commission of India available on Android and iOS. It provides a single interface for voter registration (Forms 6, 6A, 7, 8, 8A), electoral roll search, Know Your Polling Station, candidate affidavits, election results and grievance filing via cVIGIL. The app is free to download from Google Play Store and Apple App Store.",
    ministry: "Election Commission of India",
    officialPortal: "Voter Helpline App",
    officialUrl: "https://voterportal.eci.gov.in/",
    eligibility: [
      "Indian citizen with a smartphone",
      "Android 5.0+ or iOS 11.0+",
      "Active mobile number for OTP registration",
    ],
    documentsRequired: [
      "Active mobile number",
      "Smartphone with internet",
    ],
    fee: 0,
    feeNote: "Free app. Standard data charges may apply for download.",
    processingTime: "Instant download and registration",
    howToApply: [
      "Open Google Play Store or Apple App Store on your smartphone.",
      "Search for 'Voter Helpline' by Election Commission of India.",
      "Tap Install/Get to download the app (~30 MB).",
      "Open the app and register using your mobile number with OTP.",
      "Use the dashboard to access voter registration, electoral roll search and complaint services.",
    ],
    serviceCharge: 25,
    popularity: 78,
    tags: ["voter", "eci", "mobile app", "election", "voter helpline"],
    online: true,
  },
  {
    id: "voter-e-epic-download",
    slug: "voter-e-epic-download",
    name: "Voter e-EPIC Download",
    category: "elections-voting",
    subcategory: "Electoral Information",
    summary: "Download a digital, password-protected Voter ID card (e-EPIC) from the Voter Portal.",
    description:
      "The e-EPIC (Electronic Electoral Photo Identity Card) is a secure, non-editable PDF version of the EPIC card. It can be downloaded free of cost from voterportal.eci.gov.in by all general electors whose mobile number is registered with the Electoral Roll. The PDF is password-protected (default password: first 4 letters of name in capital + birth year) and can be stored in DigiLocker.",
    ministry: "Election Commission of India",
    officialPortal: "Voter Portal",
    officialUrl: "https://voterportal.eci.gov.in/",
    eligibility: [
      "Registered voter with EPIC number",
      "Mobile number linked with the electoral roll entry",
      "All general electors, service electors and overseas electors",
    ],
    documentsRequired: [
      "EPIC number",
      "Registered mobile number for OTP",
    ],
    fee: 0,
    feeNote: "Free download. PDF is password protected.",
    processingTime: "Instant download",
    howToApply: [
      "Login to voterportal.eci.gov.in with mobile/email and password.",
      "Click 'e-EPIC Download' under the Services menu.",
      "Verify EPIC number and request OTP on registered mobile.",
      "Enter OTP; the e-EPIC PDF is generated and downloaded.",
      "Open the PDF with password: first 4 letters of name in CAPS + birth year (e.g., RAHU1998).",
    ],
    serviceCharge: 40,
    popularity: 84,
    tags: ["voter id", "e-epic", "digital", "eci", "election", "download"],
    online: true,
  },
  {
    id: "candidate-affidavit-search",
    slug: "candidate-affidavit-search",
    name: "Candidate Affidavit Search",
    category: "elections-voting",
    subcategory: "Election Transparency",
    summary: "View affidavits filed by candidates declaring assets, liabilities, education and criminal cases.",
    description:
      "Every candidate contesting a Parliament or State Assembly election is required to file an affidavit (Form 26) declaring their assets, liabilities, educational qualifications and pending criminal cases. The Election Commission publishes these affidavits on its Affidavit portal so voters can make an informed choice. Search is possible by candidate name, constituency, year and election type.",
    ministry: "Election Commission of India",
    officialPortal: "ECI Affidavits",
    officialUrl: "https://affidavit.eci.gov.in/",
    eligibility: [
      "Open to all citizens",
      "No registration required",
    ],
    documentsRequired: [
      "No documents required",
      "Optional: candidate name or constituency for search",
    ],
    fee: 0,
    feeNote: "Free public service.",
    processingTime: "Instant",
    howToApply: [
      "Visit affidavit.eci.gov.in.",
      "Select Election Type (Parliament / Assembly / By-election) and Year.",
      "Choose State and Constituency, or search by candidate name.",
      "View the list of candidates with their party affiliation.",
      "Click on a candidate to download/view the affidavit PDF (assets, liabilities, education, criminal cases).",
    ],
    serviceCharge: 25,
    popularity: 70,
    tags: ["candidate", "affidavit", "transparency", "eci", "election"],
    online: true,
  },
  {
    id: "political-party-registration",
    slug: "political-party-registration",
    name: "Political Party Registration (Section 29A RPA)",
    category: "elections-voting",
    subcategory: "Political Parties",
    summary: "Register a new political party with the Election Commission of India under Section 29A of RPA, 1951.",
    description:
      "An association of individuals seeking registration as a political party under Section 29A of the Representation of the People Act, 1951 must apply to the Election Commission of India within 30 days of formation. The application is made in the prescribed format along with a copy of the party memorandum, rules, and a demand draft of ₹10,000. Registered parties can later seek recognition as State/National party based on poll performance.",
    ministry: "Election Commission of India",
    officialPortal: "Election Commission of India — Political Parties",
    officialUrl: "https://www.eci.gov.in/political-parties",
    eligibility: [
      "Association of individuals with a distinct name and symbol",
      "Memorandum of rules and regulations complying with the Constitution and RPA",
      "Application within 30 days of formation",
      "Minimum 100 registered electors as members",
    ],
    documentsRequired: [
      "Application in prescribed format under Section 29A",
      "Memorandum of Association and Rules of the party",
      "List of office-bearers and members (minimum 100 electors)",
      "Demand draft of ₹10,000 in favour of 'Secretary, Election Commission of India'",
      "Party flag and symbol proposal",
      "Affidavits of office-bearers",
    ],
    fee: 10000,
    feeNote: "₹10,000 application fee via demand draft.",
    processingTime: "6-12 months",
    howToApply: [
      "Draft the Memorandum and Rules of the party complying with Constitution and RPA.",
      "Collect 100+ member affidavits from registered electors.",
      "Prepare the Section 29A application and obtain a ₹10,000 DD favouring 'Secretary, ECI'.",
      "Submit the application to the Election Commission of India, Nirvachan Sadan, New Delhi.",
      "ECI publishes the application in two national dailies for objections; on no objection, registration is granted.",
    ],
    serviceCharge: 150,
    popularity: 35,
    tags: ["political party", "registration", "section 29a", "rpa", "eci", "election"],
    online: false,
  },
  {
    id: "election-complaint-cvigil",
    slug: "election-complaint-cvigil",
    name: "Election Complaint (cVIGIL App)",
    category: "elections-voting",
    subcategory: "Election Grievance",
    summary: "Report Model Code of Conduct violations during elections using the cVIGIL app with photo/video proof.",
    description:
      "cVIGIL ('Citizens Vigilance') is the Election Commission's app that allows any citizen to report violations of the Model Code of Conduct (MCC) such as bribery, freebies, hate speech, defacement of property, illegal banners, or liquor distribution during the election period. The complaint with geo-tagged photo/video is forwarded to the Returning Officer for action within 100 minutes.",
    ministry: "Election Commission of India",
    officialPortal: "cVIGIL App",
    officialUrl: "https://cvigil.eci.gov.in/",
    eligibility: [
      "Any citizen aged 18+ years",
      "Android/iOS smartphone with camera and GPS",
      "Active mobile number for OTP",
      "Complaint during MCC period (election notification to polling day)",
    ],
    documentsRequired: [
      "Photo/video of the violation (live capture in app, not gallery upload)",
      "Geo-location enabled",
      "Mobile number for OTP",
    ],
    fee: 0,
    feeNote: "Free. Identity of complainant is kept confidential.",
    processingTime: "Action within 100 minutes of complaint",
    howToApply: [
      "Download the cVIGIL app from Google Play Store or Apple App Store.",
      "Register with mobile number and OTP.",
      "Tap the camera icon to capture a photo or video of the violation.",
      "Select the violation category (MCC violation / Paid news / Expenditure) and add description.",
      "Submit; track complaint status via the app; Returning Officer takes action and updates within 100 minutes.",
    ],
    serviceCharge: 25,
    popularity: 75,
    tags: ["cvigil", "mcc", "complaint", "eci", "election", "grievance"],
    online: true,
  },
];
