import type { GovernmentService } from "../types";

export const employmentLabour: GovernmentService[] = [
  {
    id: "epf-uan-activation",
    slug: "epf-uan-activation",
    name: "EPF UAN Activation & Account Creation",
    category: "employment-labour",
    subcategory: "Provident Fund",
    summary: "Activate your Universal Account Number (UAN) to access EPF services online.",
    description:
      "The Universal Account Number (UAN) is a 12-digit identifier issued by EPFO that stays with an employee throughout their career. Activating UAN enables access to PF balance, passbook, withdrawal, transfer and KYC updates online via the EPFO member portal.",
    ministry: "Employees' Provident Fund Organisation (EPFO), Ministry of Labour & Employment",
    officialPortal: "EPFO Member e-Sewa Portal",
    officialUrl: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/",
    eligibility: ["Salaried employee with EPF deduction", "Must have a UAN allotted by employer"],
    documentsRequired: ["UAN", "Aadhaar number", "Mobile number linked to Aadhaar", "Bank account details"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant (online activation)",
    howToApply: [
      "Visit the EPFO Member e-Sewa portal.",
      "Click 'Activate UAN' under the Important Links section.",
      "Enter UAN, Aadhaar, name, mobile and email, then verify with OTP.",
      "Set a username and password to access the member portal.",
      "Login to download passbook, file claims and update KYC.",
    ],
    serviceCharge: 50,
    popularity: 90,
    tags: ["epf", "uan", "provident fund", "epfo", "salary"],
    online: true,
  },
  {
    id: "epf-withdrawal-form-19",
    slug: "epf-withdrawal-form-19",
    name: "EPF Final Withdrawal (Form 19)",
    category: "employment-labour",
    subcategory: "Provident Fund",
    summary: "Withdraw your full EPF balance after leaving the job or retirement.",
    description:
      "Form 19 is used to claim the final PF accumulation when an employee leaves service, retires, or remains unemployed for more than two months. The claim is filed entirely online through the EPFO member portal and the amount is credited to the seeded bank account.",
    ministry: "Employees' Provident Fund Organisation (EPFO), Ministry of Labour & Employment",
    officialPortal: "EPFO Member e-Sewa Portal",
    officialUrl: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/",
    eligibility: [
      "Member has left employment or retired",
      "Unemployed for more than 2 months (for full withdrawal)",
      "UAN activated and KYC (Aadhaar, bank, PAN) seeded",
    ],
    documentsRequired: ["UAN", "Aadhaar", "PAN", "Bank account proof", "Cancelled cheque"],
    fee: 0,
    feeNote: "Free service. TDS may apply if service < 5 years and PAN not linked.",
    processingTime: "3 to 7 working days (online)",
    howToApply: [
      "Login to the EPFO Member e-Sewa portal using UAN and password.",
      "Go to 'Claim (Form-31, 19 & 10C)' under the Online Services tab.",
      "Verify KYC details and enter bank account information.",
      "Select 'Form 19' for final PF withdrawal and enter the amount.",
      "Authenticate with Aadhaar OTP and submit the claim.",
    ],
    serviceCharge: 75,
    popularity: 92,
    tags: ["epf", "form 19", "withdrawal", "epfo", "provident fund"],
    online: true,
  },
  {
    id: "epf-transfer-form-13",
    slug: "epf-transfer-form-13",
    name: "EPF Account Transfer (Form 13)",
    category: "employment-labour",
    subcategory: "Provident Fund",
    summary: "Transfer your EPF balance from previous employer to new employer when changing jobs.",
    description:
      "Form 13 enables an EPF member to transfer the accumulated balance from the previous EPF account to the new employer's account. The online transfer can be claimed by either the previous or current employer based on KYC attestation, and is tracked through the OTCP portal.",
    ministry: "Employees' Provident Fund Organisation (EPFO), Ministry of Labour & Employment",
    officialPortal: "EPFO Member e-Sewa Portal",
    officialUrl: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/",
    eligibility: [
      "Member must have an active UAN with Aadhaar verified",
      "Both previous and current PF accounts linked to same UAN",
      "Currently employed with EPF deduction",
    ],
    documentsRequired: ["UAN", "Previous PF member ID", "Current PF member ID", "Aadhaar"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "10 to 25 working days",
    howToApply: [
      "Login to EPFO Member e-Sewa portal.",
      "Open 'One Member - One EPF Account (Transfer Request)' under Online Services.",
      "Select previous and current member IDs and verify personal details.",
      "Choose attestation mode (previous or current employer).",
      "Submit and download Form 13 printable PDF for employer attestation.",
    ],
    serviceCharge: 75,
    popularity: 85,
    tags: ["epf", "form 13", "transfer", "job change", "epfo"],
    online: true,
  },
  {
    id: "epf-advance-form-31",
    slug: "epf-advance-form-31",
    name: "EPF Advance / Partial Withdrawal (Form 31)",
    category: "employment-labour",
    subcategory: "Provident Fund",
    summary: "Withdraw EPF partially for housing, marriage, illness or education without quitting job.",
    description:
      "Form 31 allows members to take a non-refundable advance from their EPF for specific purposes such as purchase/construction of house, repayment of home loan, marriage of self/children, medical treatment, or education. Eligibility and quantum depend on years of service and reason.",
    ministry: "Employees' Provident Fund Organisation (EPFO), Ministry of Labour & Employment",
    officialPortal: "EPFO Member e-Sewa Portal",
    officialUrl: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/",
    eligibility: [
      "Active EPF member with completed years of service as per reason",
      "UAN and KYC (Aadhaar, bank, PAN) seeded",
      "Purpose meets EPFO scheme conditions",
    ],
    documentsRequired: ["UAN", "Aadhaar", "Bank details", "Purpose proof (e.g. sale agreement, medical certificate)"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "3 to 7 working days",
    howToApply: [
      "Login to EPFO Member e-Sewa portal.",
      "Go to 'Claim (Form-31, 19 & 10C)' under Online Services.",
      "Select Form 31 and choose the purpose of advance.",
      "Enter the advance amount and upload supporting documents.",
      "Authenticate with Aadhaar OTP and submit.",
    ],
    serviceCharge: 75,
    popularity: 88,
    tags: ["epf", "form 31", "advance", "partial withdrawal", "epfo"],
    online: true,
  },
  {
    id: "epf-passbook-download",
    slug: "epf-passbook-download",
    name: "EPF Passbook Download",
    category: "employment-labour",
    subcategory: "Provident Fund",
    summary: "Download your EPF passbook showing monthly contributions and interest.",
    description:
      "The EPF passbook is a digital statement showing month-wise employee, employer and pension contributions along with interest credited annually. It is updated monthly after the employer files the ECR and can be downloaded as a PDF for any linked member ID.",
    ministry: "Employees' Provident Fund Organisation (EPFO), Ministry of Labour & Employment",
    officialPortal: "EPFO Member Passbook Portal",
    officialUrl: "https://passbook.epfindia.gov.in/MemberPassBook/Login.jsp",
    eligibility: ["Active EPF member with UAN activated", "KYC (Aadhaar) verified"],
    documentsRequired: ["UAN", "Password / OTP"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant download",
    howToApply: [
      "Visit the EPFO Member Passbook portal.",
      "Login with UAN, password and captcha.",
      "Select the member ID from the dropdown.",
      "Click 'Download Passbook' to get a PDF copy.",
      "View month-wise contributions and interest.",
    ],
    serviceCharge: 40,
    popularity: 87,
    tags: ["epf", "passbook", "statement", "epfo", "balance"],
    online: true,
  },
  {
    id: "epf-kyc-update",
    slug: "epf-kyc-update",
    name: "EPF KYC Update (Aadhaar / Bank / PAN)",
    category: "employment-labour",
    subcategory: "Provident Fund",
    summary: "Seed or update Aadhaar, bank and PAN against your UAN for seamless claims.",
    description:
      "KYC details including Aadhaar, bank account and PAN must be linked to UAN to enable online claims and avoid TDS deduction. Members can self-update KYC using Aadhaar OTP authentication; the employer then digitally approves the changes.",
    ministry: "Employees' Provident Fund Organisation (EPFO), Ministry of Labour & Employment",
    officialPortal: "EPFO Member e-Sewa Portal",
    officialUrl: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/",
    eligibility: ["Active UAN", "Mobile linked to Aadhaar"],
    documentsRequired: ["UAN", "Aadhaar", "Bank account number & IFSC", "PAN"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant (after employer approval)",
    howToApply: [
      "Login to EPFO Member e-Sewa portal.",
      "Open 'KYC' under the Manage tab.",
      "Select document type (Aadhaar / Bank / PAN) and enter details.",
      "Authenticate using Aadhaar OTP.",
      "Await employer digital approval; status reflects in 'KYC Pending'.",
    ],
    serviceCharge: 50,
    popularity: 84,
    tags: ["epf", "kyc", "aadhaar seeding", "epfo", "uan"],
    online: true,
  },
  {
    id: "epf-nomination-form-2",
    slug: "epf-nomination-form-2",
    name: "EPF Nomination (Form 2)",
    category: "employment-labour",
    subcategory: "Provident Fund",
    summary: "File Form 2 to declare nominee(s) for EPF, EPS and EDLI balances.",
    description:
      "Form 2 is the statutory nomination form under EPF Scheme where a member declares one or more nominees who will receive the EPF/EPS/EDLI corpus in case of death. The form is filed online through the member portal and digitally signed by the member.",
    ministry: "Employees' Provident Fund Organisation (EPFO), Ministry of Labour & Employment",
    officialPortal: "EPFO Member e-Sewa Portal",
    officialUrl: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/",
    eligibility: ["Active EPF member with UAN", "Aadhaar verified"],
    documentsRequired: ["UAN", "Nominee details (name, relation, DOB, Aadhaar)", "Photograph of nominee (optional)"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant on submission",
    howToApply: [
      "Login to EPFO Member e-Sewa portal.",
      "Open 'E-Nomination' under Manage tab.",
      "Add family member details with Aadhaar and relationship.",
      "Allocate percentage share to each nominee (total 100%).",
      "Authenticate with Aadhaar OTP to submit e-nomination.",
    ],
    serviceCharge: 50,
    popularity: 70,
    tags: ["epf", "form 2", "nomination", "nominee", "epfo"],
    online: true,
  },
  {
    id: "epf-e-nomination",
    slug: "epf-e-nomination",
    name: "EPF e-Nomination (Digital)",
    category: "employment-labour",
    subcategory: "Provident Fund",
    summary: "File paperless e-nomination using Aadhaar e-Sign to secure EPF corpus for family.",
    description:
      "EPFO's e-Nomination facility allows members to digitally file nominations without any paperwork using Aadhaar-based e-Sign. The e-nomination is instantly registered with EPFO and removes the need to submit physical Form 2 to the employer.",
    ministry: "Employees' Provident Fund Organisation (EPFO), Ministry of Labour & Employment",
    officialPortal: "EPFO Member e-Sewa Portal",
    officialUrl: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/",
    eligibility: ["Active EPF member", "Aadhaar seeded against UAN", "Mobile linked to Aadhaar"],
    documentsRequired: ["UAN", "Aadhaar", "Family member Aadhaar details"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Login to EPFO Member e-Sewa portal.",
      "Click 'E-Nomination' under Manage.",
      "Proceed for Aadhaar authentication.",
      "Add nominee(s) and share percentage.",
      "E-sign with OTP and confirm submission.",
    ],
    serviceCharge: 50,
    popularity: 72,
    tags: ["epf", "e-nomination", "digital", "epfo", "nominee"],
    online: true,
  },
  {
    id: "eps-pension-claim-form-10d",
    slug: "eps-pension-claim-form-10d",
    name: "EPS Pension Claim (Form 10D)",
    category: "employment-labour",
    subcategory: "Pension",
    summary: "Claim monthly pension under the Employees' Pension Scheme 1995.",
    description:
      "Form 10D is filed by a member (or nominee/family member in case of death) to start monthly pension under EPS 1995. Pension starts after the member completes 10 years of eligible service and attains age 58 (or 50 for reduced pension).",
    ministry: "Employees' Provident Fund Organisation (EPFO), Ministry of Labour & Employment",
    officialPortal: "EPFO Member e-Sewa Portal",
    officialUrl: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/",
    eligibility: [
      "Completed 10 years of eligible service",
      "Age 58 for full pension (50 for reduced pension)",
      "UAN active and KYC verified",
    ],
    documentsRequired: ["UAN", "Aadhaar", "Bank account details", "Date of joining & exit proof", "Family details (if applicable)"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "20 to 30 days",
    howToApply: [
      "Login to EPFO Member e-Sewa portal.",
      "Go to 'Claim (Form-31, 19 & 10C & 10D)' under Online Services.",
      "Select Form 10D and verify KYC.",
      "Enter pension payment bank account and family details.",
      "Authenticate with Aadhaar OTP and submit.",
    ],
    serviceCharge: 100,
    popularity: 75,
    tags: ["eps", "pension", "form 10d", "epfo", "employee pension"],
    online: true,
  },
  {
    id: "edli-claim-form-20-5if",
    slug: "edli-claim-form-20-5if",
    name: "EDLI Death Benefit Claim (Form 20 / 5IF)",
    category: "employment-labour",
    subcategory: "Insurance",
    summary: "Claim life insurance benefit under EDLI in case of death of EPF member.",
    description:
      "Form 20 and Form 5IF are filed by the nominee/legal heir to claim the EDLI (Employees' Deposit Linked Insurance) benefit payable on the death of an active EPF member. The benefit equals 35 times the average monthly wage of last 12 months, subject to a maximum.",
    ministry: "Employees' Provident Fund Organisation (EPFO), Ministry of Labour & Employment",
    officialPortal: "EPFO Member e-Sewa Portal",
    officialUrl: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/",
    eligibility: [
      "Member was in active EPF employment at time of death",
      "Claimant is nominee/legal heir",
      "Death occurred within 180 days of exit",
    ],
    documentsRequired: ["Death certificate", "Member UAN", "Nominee Aadhaar", "Bank details of claimant", "Guardian certificate (if applicable)"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "15 to 30 days",
    howToApply: [
      "Login to EPFO portal as nominee / claimant.",
      "File Form 20 for EPF withdrawal and Form 5IF for EDLI.",
      "Upload death certificate and nominee KYC.",
      "Submit employer attestation or self-attest if Aadhaar-verified.",
      "Track claim status in claim history.",
    ],
    serviceCharge: 150,
    popularity: 55,
    tags: ["edli", "form 20", "form 5if", "death benefit", "epfo", "insurance"],
    online: true,
  },
  {
    id: "pension-withdrawal-form-10c",
    slug: "pension-withdrawal-form-10c",
    name: "EPS Withdrawal Benefit (Form 10C)",
    category: "employment-labour",
    subcategory: "Pension",
    summary: "Withdraw pension corpus when service is less than 10 years and you leave the job.",
    description:
      "Form 10C is used to claim the EPS withdrawal benefit (pension fund) when a member exits before completing 10 years of eligible service, or to claim Scheme Certificate for preserving pensionable service. The amount is credited to the bank account seeded against UAN.",
    ministry: "Employees' Provident Fund Organisation (EPFO), Ministry of Labour & Employment",
    officialPortal: "EPFO Member e-Sewa Portal",
    officialUrl: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/",
    eligibility: [
      "Service less than 10 years",
      "Member has left employment",
      "UAN active with KYC verified",
    ],
    documentsRequired: ["UAN", "Aadhaar", "PAN", "Bank details", "Date of joining and exit"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "3 to 7 working days",
    howToApply: [
      "Login to EPFO Member e-Sewa portal.",
      "Open 'Claim (Form-31, 19 & 10C)' under Online Services.",
      "Select Form 10C for withdrawal or scheme certificate.",
      "Verify KYC, enter amount and bank account.",
      "Authenticate with Aadhaar OTP to submit.",
    ],
    serviceCharge: 75,
    popularity: 78,
    tags: ["eps", "form 10c", "withdrawal", "pension", "epfo"],
    online: true,
  },
  {
    id: "eshram-worker-registration",
    slug: "eshram-worker-registration",
    name: "e-SHRAM Unorganised Worker Registration",
    category: "employment-labour",
    subcategory: "Unorganised Sector",
    summary: "Register as an unorganised worker on the national e-SHRAM portal to get accident cover.",
    description:
      "e-SHRAM is the national database of unorganised workers launched by the Ministry of Labour & Employment. Registered workers receive a ₹2 lakh accidental insurance cover under PMSBY and become eligible for various welfare schemes routed through states.",
    ministry: "Ministry of Labour & Employment",
    officialPortal: "e-SHRAM Portal",
    officialUrl: "https://eshram.gov.in/",
    eligibility: [
      "Age between 16 and 59 years",
      "Unorganised sector worker (not a regular EPF/ESIC member)",
      "Indian citizen with valid Aadhaar",
    ],
    documentsRequired: ["Aadhaar", "Mobile linked to Aadhaar", "Bank account"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant (e-SHRAM card generated)",
    howToApply: [
      "Visit the e-SHRAM portal.",
      "Click 'Register on e-SHRAM' and enter Aadhaar-linked mobile.",
      "Verify Aadhaar with OTP.",
      "Fill occupation, income, family and bank details.",
      "Submit to receive the e-SHRAM card with UAN.",
    ],
    serviceCharge: 50,
    popularity: 86,
    tags: ["eshram", "unorganised worker", "labour", "accident insurance", "moole"],
    online: true,
  },
  {
    id: "bocw-worker-registration",
    slug: "bocw-worker-registration",
    name: "Building & Other Construction Worker (BOCW) Registration",
    category: "employment-labour",
    subcategory: "Welfare Boards",
    summary: "Register as a construction worker with the state BOCW Welfare Board for benefits.",
    description:
      "The Building and Other Construction Workers Welfare Cess Act mandates state boards to register workers engaged in building and construction. Registered workers get accident relief, pension, maternity benefit, education aid for children and housing assistance from the welfare fund.",
    ministry: "State Labour Departments / BOCW Welfare Boards",
    officialPortal: "State BOCW Welfare Board Portals",
    officialUrl: "https://labour.gov.in/webcbo/",
    eligibility: [
      "Age 18 to 60 years",
      "Engaged in building / construction work for at least 90 days in past 1 year",
      "Not covered under EPF/ESIC as regular employee",
    ],
    documentsRequired: ["Aadhaar", "Photograph", "Age proof", "Bank passbook", "Employer certificate / engagement proof"],
    fee: 25,
    feeNote: "Annual renewal fee ₹25 to ₹50 (varies by state).",
    processingTime: "30 to 45 days",
    howToApply: [
      "Visit your state BOCW Welfare Board portal or e-District centre.",
      "Create an account and complete BOCW registration form.",
      "Upload Aadhaar, photo and engagement proof.",
      "Pay the registration fee (if applicable).",
      "Visit the labour office for physical verification and receive BOCW ID card.",
    ],
    serviceCharge: 100,
    popularity: 65,
    tags: ["bocw", "construction worker", "welfare board", "labour"],
    online: true,
  },
  {
    id: "beedi-worker-registration",
    slug: "beedi-worker-registration",
    name: "Beedi Worker Welfare Registration",
    category: "employment-labour",
    subcategory: "Welfare Boards",
    summary: "Register as a beedi roller with the Labour Ministry's Beedi Workers Welfare Fund.",
    description:
      "Beedi workers engaged in rolling beedis for at least 60 days in a year can register with the Office of the Welfare Commissioner for Beedi & Cine Workers. Registered members receive health insurance (RSBY), maternity benefit, education scholarship, housing aid and pension under the Beedi Workers Welfare Fund Act 1976.",
    ministry: "Ministry of Labour & Employment — Welfare Commissioner for Beedi Workers",
    officialPortal: "Beedi Workers Welfare Fund Portal",
    officialUrl: "https://labour.gov.in/division/welfare-commissioner-beedi-workers-0",
    eligibility: [
      "Engaged in beedi rolling for minimum 60 days in preceding year",
      "Income below ₹10,000 per month (worker category)",
      "Not working in organised sector",
    ],
    documentsRequired: ["Aadhaar", "Employer certificate of beedi rolling", "Photograph", "Bank account", "Income certificate"],
    fee: 0,
    feeNote: "Free registration.",
    processingTime: "30 to 60 days",
    howToApply: [
      "Approach the nearest Office of the Welfare Commissioner for Beedi Workers.",
      "Submit Form A (registration) with employer's certificate.",
      "Attach Aadhaar, photo and bank account details.",
      "Field verification is conducted by the Labour Officer.",
      "Identity card (B-Pass Book) is issued on approval.",
    ],
    serviceCharge: 120,
    popularity: 45,
    tags: ["beedi", "welfare fund", "labour", "beedi roller"],
    online: false,
  },
  {
    id: "mine-worker-registration",
    slug: "mine-worker-registration",
    name: "Mine Worker Welfare Registration",
    category: "employment-labour",
    subcategory: "Welfare Boards",
    summary: "Register with the Labour Ministry for mine workers' welfare schemes.",
    description:
      "Mineworkers employed in mines are registered under the Mines Act 1952 and the Mines Welfare Fund. Members get medical aid through the Mines Board of Health, educational scholarships, housing assistance and rehabilitation benefits for occupational diseases.",
    ministry: "Ministry of Labour & Employment — Directorate General of Mines Safety (DGMS)",
    officialPortal: "DGMS Mines Welfare Portal",
    officialUrl: "https://dgms.gov.in/",
    eligibility: [
      "Employed in a mine notified under the Mines Act 1952",
      "Holds a valid appointment letter from mine owner",
      "Age 18 years and above",
    ],
    documentsRequired: ["Aadhaar", "Appointment letter from mine owner", "Photograph", "Bank account", "Medical fitness certificate"],
    fee: 0,
    feeNote: "Free registration.",
    processingTime: "30 to 60 days",
    howToApply: [
      "Approach the mine management for the Form-A registration.",
      "Submit Form A with DGMS regional office.",
      "Attach appointment letter, Aadhaar, photo and bank account.",
      "Medical fitness verified by DGMS-approved centre.",
      "Receive Mine Worker Welfare Identity Card.",
    ],
    serviceCharge: 120,
    popularity: 40,
    tags: ["mines", "welfare", "labour", "dgms", "mine worker"],
    online: false,
  },
  {
    id: "ncs-jobseeker-registration",
    slug: "ncs-jobseeker-registration",
    name: "National Career Service (NCS) Job Seeker Registration",
    category: "employment-labour",
    subcategory: "Employment Exchange",
    summary: "Register as a job seeker on NCS to access jobs, career counselling and skilling.",
    description:
      "The National Career Service is a digital platform by the Ministry of Labour & Employment connecting job seekers with employers. Registered job seekers get access to job fairs, career counselling, online courses, and skill verification by registered employers across India.",
    ministry: "Ministry of Labour & Employment — Directorate General of Employment",
    officialPortal: "National Career Service Portal",
    officialUrl: "https://www.ncs.gov.in/",
    eligibility: [
      "Indian citizen aged 14 years and above",
      "Looking for job, internship or skill upgradation",
      "Valid mobile number and email",
    ],
    documentsRequired: ["Aadhaar (optional)", "Educational qualifications", "Resume", "Mobile number", "Email"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant registration",
    howToApply: [
      "Visit the NCS portal and click 'Sign Up'.",
      "Choose 'Job Seeker' and enter email, mobile and password.",
      "Fill personal, educational and experience details.",
      "Upload resume and select preferred job categories.",
      "Receive NCS job seeker ID and access job matches.",
    ],
    serviceCharge: 50,
    popularity: 78,
    tags: ["ncs", "job seeker", "employment exchange", "career", "jobs"],
    online: true,
  },
  {
    id: "ncs-employer-registration",
    slug: "ncs-employer-registration",
    name: "NCS Employer Registration",
    category: "employment-labour",
    subcategory: "Employment Exchange",
    summary: "Register your organisation on NCS to post jobs and access candidate database.",
    description:
      "Employers can register on the National Career Service portal to post vacancies, conduct walk-in interviews and job fairs, and shortlist candidates from the national database. Registration is verified by the nearest Employment Exchange before activation.",
    ministry: "Ministry of Labour & Employment — Directorate General of Employment",
    officialPortal: "National Career Service Portal",
    officialUrl: "https://www.ncs.gov.in/",
    eligibility: [
      "Registered business entity (Pvt Ltd, LLP, Proprietorship, NGO, Govt Dept)",
      "Active PAN and GST (where applicable)",
      "Authorised signatory with Aadhaar",
    ],
    documentsRequired: ["PAN of organisation", "GST certificate", "Incorporation / registration certificate", "Aadhaar of signatory", "Organisation email"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "2 to 5 working days (post verification)",
    howToApply: [
      "Visit the NCS portal and click 'Sign Up as Employer'.",
      "Enter organisation details, PAN and GST.",
      "Upload incorporation certificate and signatory Aadhaar.",
      "Submit for Employment Exchange verification.",
      "On approval, post jobs and access candidate database.",
    ],
    serviceCharge: 100,
    popularity: 60,
    tags: ["ncs", "employer", "hiring", "recruitment", "jobs"],
    online: true,
  },
  {
    id: "apprenticeship-registration-naps",
    slug: "apprenticeship-registration-naps",
    name: "Apprenticeship Registration (NAPS)",
    category: "employment-labour",
    subcategory: "Skilling",
    summary: "Register as an apprentice under the National Apprenticeship Promotion Scheme.",
    description:
      "The National Apprenticeship Promotion Scheme (NAPS) by the Ministry of Skill Development promotes apprenticeship training in industry. Candidates register on the apprenticeship portal to be matched with establishments for practical training of 6 months to 3 years with stipend support.",
    ministry: "Ministry of Skill Development and Entrepreneurship",
    officialPortal: "Apprenticeship India Portal",
    officialUrl: "https://www.apprenticeshipindia.org/",
    eligibility: [
      "Age 14 years and above (18+ for hazardous occupations)",
      "Passed Class 5 / 8 / 10 / 12 / ITI / Diploma / Degree",
      "Indian citizen",
    ],
    documentsRequired: ["Aadhaar", "Educational certificates", "Caste / category certificate (if applicable)", "Bank account", "Photograph"],
    fee: 0,
    feeNote: "Free registration.",
    processingTime: "5 to 10 working days for establishment approval",
    howToApply: [
      "Visit the Apprenticeship India portal.",
      "Register as a candidate with email and mobile.",
      "Complete profile with educational qualifications.",
      "Search and apply to apprenticeship opportunities.",
      "Establishment approves and contract is registered with RDAT.",
    ],
    serviceCharge: 75,
    popularity: 70,
    tags: ["naps", "apprenticeship", "skill", "training", "stipend"],
    online: true,
  },
  {
    id: "gratuity-claim",
    slug: "gratuity-claim",
    name: "Gratuity Claim (Form I)",
    category: "employment-labour",
    subcategory: "Statutory Benefits",
    summary: "Claim payment of gratuity after completing 5 years of continuous service.",
    description:
      "Under the Payment of Gratuity Act 1972, employees who have completed 5 years of continuous service (or 4 years 240 days as per courts) with an establishment of 10+ employees are entitled to gratuity. Form I is filed with the employer; payment must be made within 30 days of becoming payable.",
    ministry: "Ministry of Labour & Employment — Labour Commissioner",
    officialPortal: "Labour Commissioner / PGMS Portal",
    officialUrl: "https://labour.gov.in/",
    eligibility: [
      "Completed 5 years continuous service (or 4 yrs 240 days)",
      "Superannuation, resignation, death or disablement",
      "Establishment covered under Payment of Gratuity Act",
    ],
    documentsRequired: ["Form I (claim form)", "Resignation/retirement letter", "Bank details", "Aadhaar", "Service certificate"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "30 days from claim submission",
    howToApply: [
      "Download Form I from the Labour Ministry portal.",
      "Fill in personal, service and bank details.",
      "Submit to the employer with self-attested documents.",
      "Employer processes payment within 30 days.",
      "If not paid, file a claim with the Controlling Authority.",
    ],
    serviceCharge: 100,
    popularity: 65,
    tags: ["gratuity", "form i", "retirement", "labour", "statutory"],
    online: false,
  },
  {
    id: "maternity-benefit-claim",
    slug: "maternity-benefit-claim",
    name: "Maternity Benefit Claim",
    category: "employment-labour",
    subcategory: "Statutory Benefits",
    summary: "Claim paid maternity leave of 26 weeks under the Maternity Benefit Act.",
    description:
      "The Maternity Benefit (Amendment) Act 2017 provides 26 weeks of paid maternity leave for the first two children and 12 weeks thereafter. Eligible female employees not covered by ESIC can claim maternity benefit from the employer by submitting Form 1 along with medical proof.",
    ministry: "Ministry of Labour & Employment — Labour Commissioner",
    officialPortal: "Labour Commissioner Portal",
    officialUrl: "https://labour.gov.in/",
    eligibility: [
      "Female employee who has worked 80 days in past 12 months",
      "Establishment with 10+ employees",
      "Not covered under ESIC for the relevant period",
    ],
    documentsRequired: ["Form 1 (maternity benefit claim)", "Medical certificate of pregnancy", "Salary proof", "Bank details", "Aadhaar"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Within 48 hours of submission (per Act)",
    howToApply: [
      "Notify the employer in writing about the pregnancy.",
      "Submit Form 1 with medical certificate to employer.",
      "Employer pays maternity benefit in advance in instalments.",
      "Submit Form 5 (post-natal) on return to work.",
      "File complaint with Labour Inspector if denied.",
    ],
    serviceCharge: 100,
    popularity: 60,
    tags: ["maternity", "women", "leave", "labour", "statutory"],
    online: false,
  },
  {
    id: "minimum-wage-compliance",
    slug: "minimum-wage-compliance",
    name: "Minimum Wage Compliance Certificate",
    category: "employment-labour",
    subcategory: "Compliance",
    summary: "Verify and obtain compliance certificate for Minimum Wages Act 1948.",
    description:
      "The Minimum Wages Act 1948 requires every employer to pay wages not less than the rate notified by the Central or State Government for scheduled employments. A compliance certificate is issued by the Labour Department after inspection of wage registers, muster rolls and payment proof.",
    ministry: "Ministry of Labour & Employment / State Labour Departments",
    officialPortal: "Labour Department Portal",
    officialUrl: "https://labour.gov.in/",
    eligibility: [
      "Establishment engaged in any scheduled employment",
      "Employer maintaining wage register (Form X) and muster roll (Form V)",
      "Complied with all wage revisions notified",
    ],
    documentsRequired: ["Wage register (Form X)", "Muster roll (Form V)", "Salary payment proof", "PF & ESI records", "Licence / registration"],
    fee: 100,
    feeNote: "Inspection / processing fee varies by state.",
    processingTime: "15 to 30 days",
    howToApply: [
      "Maintain wage register and muster roll as per state rules.",
      "Apply for inspection at the nearest Labour Office.",
      "Submit Form X, Form V and salary proof to the Inspector.",
      "Inspection conducted and observations recorded.",
      "Compliance Certificate issued on satisfactory verification.",
    ],
    serviceCharge: 150,
    popularity: 50,
    tags: ["minimum wages", "compliance", "labour", "wages", "employer"],
    online: false,
  },
  {
    id: "contract-labour-registration",
    slug: "contract-labour-registration",
    name: "Contract Labour Registration (Form I)",
    category: "employment-labour",
    subcategory: "Licensing",
    summary: "Register your establishment or contractor under the Contract Labour (R&A) Act 1970.",
    description:
      "Every establishment employing 50 or more contract labourers and every contractor supplying 20 or more workers must register under the Contract Labour (Regulation & Abolition) Act 1970. Form I (Principal Employer) and Form IV (Contractor Licence) are filed with the registering officer.",
    ministry: "Ministry of Labour & Employment / State Labour Departments",
    officialPortal: "State Labour Department / Shram Suvidha Portal",
    officialUrl: "https://efs.upsdc.gov.in/",
    eligibility: [
      "Establishment employing 50 or more contract labourers",
      "Contractor deploying 20 or more workers",
      "Engaged in activity covered under the Act",
    ],
    documentsRequired: ["Form I / Form IV", "PAN of establishment / contractor", "GST certificate", "Address proof", "List of contractors / employees"],
    fee: 500,
    feeNote: "Registration fee based on number of contract workers (varies by state).",
    processingTime: "30 days",
    howToApply: [
      "Register on the State Labour Department portal or Shram Suvidha.",
      "Fill Form I (principal employer) or Form IV (contractor licence).",
      "Upload PAN, GST and establishment documents.",
      "Pay the prescribed registration fee online.",
      "Receive Certificate of Registration / Licence valid for the specified period.",
    ],
    serviceCharge: 150,
    popularity: 55,
    tags: ["contract labour", "registration", "licence", "form i", "labour"],
    online: true,
  },
  {
    id: "trade-union-registration",
    slug: "trade-union-registration",
    name: "Trade Union Registration",
    category: "employment-labour",
    subcategory: "Registration",
    summary: "Register a trade union under the Trade Unions Act 1926.",
    description:
      "Any group of 7 or more workers can form a trade union and register it under the Trade Unions Act 1926 with the Registrar of Trade Unions. Registered unions get legal protection, can collect membership fees, and act as bargaining agents for workers.",
    ministry: "Ministry of Labour & Employment / State Registrars of Trade Unions",
    officialPortal: "State Labour Department Portal",
    officialUrl: "https://labour.gov.in/",
    eligibility: [
      "At least 7 members subscribing to the rules",
      "At least 10% or 100 (whichever is less) of workers engaged in establishment as members",
      "Not already registered as a union under same name",
    ],
    documentsRequired: ["Form A (application)", "Statement of office bearers", "Rules of the union", "Receipt of fee payment", "List of members"],
    fee: 100,
    feeNote: "Registration fee ₹100 plus ₹2 per member (varies by state).",
    processingTime: "30 to 60 days",
    howToApply: [
      "Form a union with at least 7 subscribing members and elect office bearers.",
      "Draft rules of the union as required by the Act.",
      "File Form A with the Registrar of Trade Unions along with rules.",
      "Pay the prescribed registration fee.",
      "Registrar issues Certificate of Registration after scrutiny.",
    ],
    serviceCharge: 150,
    popularity: 35,
    tags: ["trade union", "registration", "labour", "workers", "union"],
    online: false,
  },
  {
    id: "inter-state-migrant-worker-licence",
    slug: "inter-state-migrant-worker-licence",
    name: "Inter-State Migrant Worker Licence (ISMW)",
    category: "employment-labour",
    subcategory: "Licensing",
    summary: "Obtain licence as a contractor for inter-state migrant workers.",
    description:
      "Under the Inter-State Migrant Workmen (Regulation of Employment & Conditions of Service) Act 1979, every contractor who recruits or supplies 5 or more inter-state migrant workers must obtain a licence from the registering authority of the home state.",
    ministry: "Ministry of Labour & Employment / State Labour Departments",
    officialPortal: "State Labour Department Portal",
    officialUrl: "https://labour.gov.in/",
    eligibility: [
      "Contractor supplying 5 or more inter-state migrant workmen",
      "Establishment employing such workers through a contractor",
      "Holds valid Contract Labour Licence",
    ],
    documentsRequired: ["Form IV (licence application)", "PAN & GST of contractor", "Establishment registration certificate", "List of migrant workers", "Wage & displacement allowance proof"],
    fee: 500,
    feeNote: "Licence fee based on number of migrant workers.",
    processingTime: "30 to 45 days",
    howToApply: [
      "Apply to the Licensing Officer of the home state.",
      "Submit Form IV with establishment and contractor details.",
      "Upload list of inter-state migrant workers.",
      "Pay the licence fee based on number of workers.",
      "Receive Licence valid for 1 year (renewable).",
    ],
    serviceCharge: 150,
    popularity: 30,
    tags: ["ismw", "migrant", "licence", "labour", "inter-state"],
    online: true,
  },
  {
    id: "factories-act-licence",
    slug: "factories-act-licence",
    name: "Factories Act Licence & Approval of Plans",
    category: "employment-labour",
    subcategory: "Licensing",
    summary: "Get factory plan approval and licence under the Factories Act 1948.",
    description:
      "Any manufacturing premise with 10+ workers (with power) or 20+ workers (without power) requires approval of factory plan and licence from the Chief Inspector of Factures under the Factories Act 1948. The licence ensures compliance with safety, health and welfare provisions.",
    ministry: "State Factory Inspectorates / Directorate of Industrial Safety & Health",
    officialPortal: "State Factory Inspectorate Portal",
    officialUrl: "https://labour.gov.in/",
    eligibility: [
      "Manufacturing premise with 10+ workers using power, or 20+ without power",
      "Plan approved by Chief Inspector",
      "Complies with safety, health and welfare provisions",
    ],
    documentsRequired: ["Form 2 (licence application)", "Approved factory plan", "Stability certificate", "Building licence", "Solvency / fee receipt"],
    fee: 1000,
    feeNote: "Licence fee based on installed horsepower & number of workers (varies by state).",
    processingTime: "30 to 90 days",
    howToApply: [
      "Submit Form 1 for approval of factory plan to Chief Inspector.",
      "Get plan approved and complete construction as per plan.",
      "Apply for licence in Form 2 with stability certificate.",
      "Inspection conducted by Factory Inspector.",
      "Licence granted on compliance with the Act.",
    ],
    serviceCharge: 150,
    popularity: 50,
    tags: ["factories act", "licence", "manufacturing", "safety", "labour"],
    online: true,
  },
  {
    id: "shops-establishment-registration",
    slug: "shops-establishment-registration",
    name: "Shops & Establishment Registration",
    category: "employment-labour",
    subcategory: "Registration",
    summary: "Register your shop, commercial establishment or hotel under the state Shops Act.",
    description:
      "The Shops and Establishments Act (state-specific, e.g. Bombay Shop Act, Delhi Shop Act) regulates working conditions, hours, leave, holidays and wages of employees in shops, hotels, restaurants and commercial establishments. Most states now offer online registration with instant certificate issuance.",
    ministry: "State Labour Departments / Municipal Corporations",
    officialPortal: "State Labour Department / e-District Portal",
    officialUrl: "https://labour.gov.in/",
    eligibility: [
      "Any shop or commercial establishment with employees",
      "Hotel, restaurant, theatre or place of amusement",
      "Most states have no minimum employee threshold",
    ],
    documentsRequired: ["PAN of establishment / proprietor", "Address proof (rent agreement / utility bill)", "Photo of premises", "Employee details", "Photo of proprietor / partners"],
    fee: 200,
    feeNote: "Fee varies by state (₹100 to ₹2,000 based on number of employees).",
    processingTime: "Instant to 7 days (varies by state)",
    howToApply: [
      "Visit the State Labour Department or municipal portal.",
      "Create an establishment account with mobile and email.",
      "Fill the Shop Act application with establishment details.",
      "Upload address proof, photo and employee details.",
      "Pay the fee and download the Registration Certificate.",
    ],
    serviceCharge: 100,
    popularity: 80,
    tags: ["shops", "establishment", "registration", "shop act", "labour"],
    online: true,
  },
];
