import type { GovernmentService } from "../types";

export const healthFamily: GovernmentService[] = [
  {
    id: "ayushman-bharat-pmjay-card",
    slug: "ayushman-bharat-pmjay-card",
    name: "Ayushman Bharat (PMJAY) Card",
    category: "health-family",
    subcategory: "Health Insurance",
    summary: "Get a ₹5 lakh per year health cover card under PM-JAY for cashless treatment.",
    description:
      "The Pradhan Mantri Jan Arogya Yojana (PM-JAY) provides a health cover of up to ₹5 lakh per family per year for secondary and tertiary care hospitalisation. Eligible families identified through SECC 2011 receive an Ayushman Card enabling cashless treatment at any empanelled public or private hospital across India.",
    ministry: "Ministry of Health & Family Welfare (NHA)",
    officialPortal: "PM-JAY",
    officialUrl: "https://pmjay.gov.in/",
    eligibility: [
      "Families identified under SECC 2011 database (priority households)",
      "Eligible categories vary for rural & urban areas (e.g. SC/ST, landless labour, rag-pickers, etc.)",
      "Senior citizens ≥70 years are now covered regardless of category",
    ],
    documentsRequired: ["Aadhaar", "Ration card", "Mobile number linked with Aadhaar", "Family ID / SECC details"],
    fee: 0,
    feeNote: "PM-JAY card and treatment are completely free for beneficiaries.",
    processingTime: "Instant to 7 days for card activation",
    howToApply: [
      "Visit the nearest CSC / empanelled hospital or pmjay.gov.in.",
      "Verify eligibility using Aadhaar / mobile / Ration card.",
      "Visit the Ayushman Mitra desk at an empanelled hospital.",
      "Biometric authentication and KYC done at the desk.",
      "Ayushman Card is generated; cashless treatment can be availed immediately.",
    ],
    serviceCharge: 50,
    popularity: 92,
    tags: ["ayushman bharat", "pmjay", "health insurance", "cashless", "5 lakh"],
    online: true,
  },
  {
    id: "cghs-card-central-govt-health-scheme",
    slug: "cghs-card-central-govt-health-scheme",
    name: "CGHS Card (Central Govt Health Scheme)",
    category: "health-family",
    subcategory: "Health Insurance",
    summary: "Get a CGHS plastic card / e-card for cashless OPD & IPD at CGHS wellness centres.",
    description:
      "The Central Government Health Scheme (CGHS) provides comprehensive healthcare — OPD, IPD, specialist consultation, investigations and medicines — to central government employees, pensioners, MPs, judges and their dependants through CGHS Wellness Centres and empanelled private hospitals.",
    ministry: "Ministry of Health & Family Welfare (CGHS)",
    officialPortal: "CGHS",
    officialUrl: "https://cghs.nic.in/",
    eligibility: [
      "Serving / retired Central Govt employees, MPs, ex-MPs, Judges, Freedom Fighters, accredited journalists",
      "Pensioners drawing pension from central civil estimates",
      "Delhi Police personnel in specified categories",
    ],
    documentsRequired: ["PPO / salary slip", "Aadhaar", "Photograph", "Dependent certificates", "Last pay certificate"],
    fee: 1000,
    feeNote:
      "Pensioner subscription ₹225–₹1,000 per month based on pay level; serving employees have it deducted from salary. Lifetime option available.",
    processingTime: "7–15 days for plastic card; e-card instant",
    howToApply: [
      "Visit cghs.nic.in and click 'Beneficiary Login'.",
      "Register with PPO / employee ID and Aadhaar.",
      "Fill application form and upload documents.",
      "Pay subscription fee online (one-time / yearly / lifetime).",
      "Download temporary CGHS card; plastic card dispatched by post.",
    ],
    serviceCharge: 80,
    popularity: 60,
    tags: ["cghs", "central government", "health", "pensioner", "wellness centre"],
    online: true,
  },
  {
    id: "echs-card-ex-servicemen",
    slug: "echs-card-ex-servicemen",
    name: "ECHS Card (Ex-Servicemen Contributory Health Scheme)",
    category: "health-family",
    subcategory: "Health Insurance",
    summary: "Get an ECHS smart card for cashless healthcare for Ex-Servicemen & dependants.",
    description:
      "ECHS is a contributory health scheme of the Ministry of Defence for Ex-Servicemen (ESM) and their dependants. It provides cashless OPD, IPD, specialist and emergency care through a network of 426 polyclinics and empanelled private hospitals across India.",
    ministry: "Ministry of Defence (Department of Ex-Servicemen Welfare)",
    officialPortal: "ECHS",
    officialUrl: "https://echs.gov.in/",
    eligibility: [
      "Ex-Servicemen (ESM) drawing pension / service pension",
      "Spouse, dependent children, parents (specified categories)",
      "Widows of ESM are also eligible",
    ],
    documentsRequired: ["ESM discharge book / PPO", "Aadhaar", "Photographs of all dependants", "Disability / pension documents", "Dependent certificates"],
    fee: 0,
    feeNote:
      "Initial contribution paid at discharge (₹1,800 for JCO/OR, ₹5,400 for Officers); thereafter free. Replacement card ₹100.",
    processingTime: "3–7 working days",
    howToApply: [
      "Visit the nearest ECHS polyclinic or Stn HQ.",
      "Fill ECHS application Form 10 / 10A.",
      "Submit PPO, discharge book and dependent documents.",
      "Biometric capture and issuance of 32-bit smart card.",
      "Card activated at parent polyclinic; empanelled hospitals verified online.",
    ],
    serviceCharge: 90,
    popularity: 55,
    tags: ["echs", "ex servicemen", "defence", "veteran", "health"],
    online: true,
  },
  {
    id: "medical-fitness-certificate-form-1a",
    slug: "medical-fitness-certificate-form-1a",
    name: "Medical Fitness Certificate (Form 1A for Driving License)",
    category: "health-family",
    subcategory: "Medical Certificates",
    summary: "Get the Form 1A medical fitness certificate required for Driving License.",
    description:
      "Form 1A is the medical fitness certificate prescribed under the Central Motor Vehicles Rules, 1989. It is mandatory for applicants above 40 years renewing / applying for a Driving License, for Transport Vehicle (commercial) licenses, and for international driving permits. The certificate is issued by a registered medical practitioner after a physical & eyesight examination.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Sewa",
    officialUrl: "https://parivahan.gov.in/",
    eligibility: [
      "Driving License applicant above 40 years",
      "Transport vehicle (commercial) license applicants",
      "International Driving Permit applicants",
    ],
    documentsRequired: ["Aadhaar / photo ID", "Existing DL (for renewal)", "Passport-size photograph", "Old Form 1A if renewing"],
    fee: 200,
    feeNote: "No government fee; doctor's consultation fee ₹100–₹500 typically.",
    processingTime: "Same day",
    howToApply: [
      "Visit a registered medical practitioner (RMP) or govt dispensary.",
      "Request Form 1A medical fitness examination.",
      "Doctor checks eyesight, BP, general fitness and signs the form.",
      "Get the form attested and stamped.",
      "Upload the scanned Form 1A on the Parivahan portal while applying / renewing DL.",
    ],
    serviceCharge: 50,
    popularity: 70,
    tags: ["form 1a", "medical fitness", "driving license", "parivahan"],
    online: true,
  },
  {
    id: "disability-certificate",
    slug: "disability-certificate",
    name: "Disability Certificate (UDID)",
    category: "health-family",
    subcategory: "Medical Certificates",
    summary: "Apply for a Unique Disability ID (UDID) card with disability assessment.",
    description:
      "The Department of Empowerment of Persons with Disabilities (DEPwD) issues the Unique Disability ID (UDID) card through authorised Medical Boards. The certificate specifies the type and percentage of disability (≥40% for certification) and is the basis for availing reservations, pensions, scholarships and assistive devices.",
    ministry: "Ministry of Social Justice & Empowerment (DEPwD)",
    officialPortal: "UDID / Swavlamban Card",
    officialUrl: "https://www.swavlambancard.gov.in/",
    eligibility: ["Person with ≥40% benchmark disability as per RPwD Act 2016", "Indian citizen", "Disability of a notified type"],
    documentsRequired: ["Aadhaar", "Photograph", "Proof of residence", "Medical reports / diagnosis", "Disability assessment by Medical Board"],
    fee: 0,
    feeNote: "Free to apply; Medical Board assessment may have nominal hospital fee.",
    processingTime: "15–30 days after Medical Board assessment",
    howToApply: [
      "Register on swavlambancard.gov.in.",
      "Fill personal and disability details.",
      "Upload Aadhaar, photo and medical reports.",
      "Visit the Medical Board on the assigned date for assessment.",
      "UDID card and certificate generated and dispatched.",
    ],
    serviceCharge: 80,
    popularity: 55,
    tags: ["udid", "disability certificate", "swavlamban", "depwd", "pwpd"],
    online: true,
  },
  {
    id: "blood-donation-registration-eraktkosh",
    slug: "blood-donation-registration-eraktkosh",
    name: "Blood Donation Registration (e-Raktkosh)",
    category: "health-family",
    subcategory: "Blood & Organ Donation",
    summary: "Register as a blood donor and find / request blood through e-Raktkosh.",
    description:
      "e-Raktkosh is the centralised web-based blood bank management system of the Ministry of Health & Family Welfare. Citizens can register as donors, locate nearby blood banks, check blood stock availability and raise requests for specific blood groups.",
    ministry: "Ministry of Health & Family Welfare",
    officialPortal: "e-Raktkosh",
    officialUrl: "https://www.eraktkosh.in/",
    eligibility: [
      "Donor between 18–65 years",
      "Weight ≥50 kg, Hb ≥12.5 g/dL",
      "Free from infections and chronic diseases as per Drug Authority guidelines",
    ],
    documentsRequired: ["Aadhaar / photo ID", "Donor registration form", "Medical history (self-declaration)"],
    fee: 0,
    feeNote: "Free service; blood is donated voluntarily without payment.",
    processingTime: "Instant registration; donation slot per appointment",
    howToApply: [
      "Visit eraktkosh.in and register as a donor.",
      "Choose a nearby registered blood bank.",
      "Book a donation appointment slot.",
      "Visit blood bank, undergo screening & donate.",
      "Receive donor card and digital certificate of donation.",
    ],
    serviceCharge: 30,
    popularity: 45,
    tags: ["blood donation", "e raktkosh", "donor", "blood bank"],
    online: true,
  },
  {
    id: "organ-donor-registry-notto",
    slug: "organ-donor-registry-notto",
    name: "Organ Donor Registry (NOTTO)",
    category: "health-family",
    subcategory: "Blood & Organ Donation",
    summary: "Pledge to donate organs after death through the National Organ & Tissue Transplant Organisation.",
    description:
      "NOTTO, under the Ministry of Health & Family Welfare, maintains the National Register of organ donors. Pledging is voluntary and indicates intent to donate organs after brain death; family consent is still required at the time of donation.",
    ministry: "Ministry of Health & Family Welfare (NOTTO)",
    officialPortal: "NOTTO",
    officialUrl: "https://notto.mohfw.gov.in/",
    eligibility: ["Any Indian citizen above 18 years", "Of sound mind", "Voluntary willingness to donate"],
    documentsRequired: ["Aadhaar / photo ID", "Photograph", "Donor pledge form (online)"],
    fee: 0,
    feeNote: "Free to register; donor card issued at no cost.",
    processingTime: "Instant digital card",
    howToApply: [
      "Visit notto.mohfw.gov.in and click 'Pledge Now'.",
      "Register with personal details and Aadhaar.",
      "Choose organs / tissues you wish to donate.",
      "Submit the pledge and download the organ donor card.",
      "Carry the donor card and inform family of your wish.",
    ],
    serviceCharge: 30,
    popularity: 40,
    tags: ["notto", "organ donation", "donor card", "transplant"],
    online: true,
  },
  {
    id: "covid-19-vaccination-certificate",
    slug: "covid-19-vaccination-certificate",
    name: "COVID-19 Vaccination Certificate",
    category: "health-family",
    subcategory: "Vaccination",
    summary: "Download your COVID-19 vaccination certificate from CoWIN / Aarogya Setu.",
    description:
      "After each dose of COVID-19 vaccine, a digitally signed vaccination certificate is generated on the CoWIN portal. The certificate includes beneficiary details, vaccine name, batch number, vaccination date and a secure QR code for verification.",
    ministry: "Ministry of Health & Family Welfare (CoWIN)",
    officialPortal: "CoWIN / Aarogya Setu",
    officialUrl: "https://www.cowin.gov.in/",
    eligibility: ["Anyone who has received one or more doses of COVID-19 vaccine in India", "Beneficiary registered on CoWIN"],
    documentsRequired: ["Mobile number used during registration", "Beneficiary Reference ID (13-digit)"],
    fee: 0,
    feeNote: "Free at government centres; ₹250 at private centres (currently free for all adults under govt programme).",
    processingTime: "Instant (within hours of vaccination)",
    howToApply: [
      "Visit cowin.gov.in and click 'Download Certificate'.",
      "Enter the mobile number used during vaccination.",
      "Verify with OTP.",
      "Select the beneficiary name.",
      "Download the certificate PDF with QR code.",
    ],
    serviceCharge: 25,
    popularity: 75,
    tags: ["covid", "vaccination", "certificate", "cowin", "aarogya setu"],
    online: true,
  },
  {
    id: "cowin-vaccination-appointment",
    slug: "cowin-vaccination-appointment",
    name: "CoWIN Vaccination Appointment",
    category: "health-family",
    subcategory: "Vaccination",
    summary: "Book a vaccination slot at a nearby government or private centre via CoWIN.",
    description:
      "CoWIN is the digital platform for COVID-19 (and select routine) vaccination. Citizens can register beneficiaries, search by PIN code / district, view available vaccine and slots, and book appointments at empanelled vaccination centres across India.",
    ministry: "Ministry of Health & Family Welfare",
    officialPortal: "CoWIN",
    officialUrl: "https://www.cowin.gov.in/",
    eligibility: ["All citizens eligible for the applicable vaccine / dose", "Valid mobile number and photo ID"],
    documentsRequired: ["Aadhaar / PAN / Driving License / Passport", "Mobile number"],
    fee: 0,
    feeNote: "Free at government centres; private centre fees as notified.",
    processingTime: "Same day or scheduled slot",
    howToApply: [
      "Register / login on cowin.gov.in with mobile OTP.",
      "Add beneficiary with photo ID details.",
      "Search by PIN / district for available centres & slots.",
      "Book a slot and download appointment slip.",
      "Visit centre with ID for vaccination.",
    ],
    serviceCharge: 35,
    popularity: 70,
    tags: ["cowin", "vaccination", "appointment", "slot", "covid"],
    online: true,
  },
  {
    id: "death-certificate-registration",
    slug: "death-certificate-registration",
    name: "Death Certificate Registration",
    category: "health-family",
    subcategory: "Vital Records",
    summary: "Register a death and obtain a certified copy of the Death Certificate.",
    description:
      "Registration of every death is mandatory under the Registration of Births & Deaths (RBD) Act, 1969. The Civil Registrar (municipality / panchayat) issues the Death Certificate, which is required for inheritance, pension, insurance, bank account closure and other legal purposes.",
    ministry: "Ministry of Home Affairs (Registrar General of India) / State Governments",
    officialPortal: "Civil Registration System (CRS)",
    officialUrl: "https://crsorgi.gov.in/",
    eligibility: [
      "Any death occurring in India must be registered within 21 days",
      "Head of household / nearest relative / medical institution in-charge can report",
    ],
    documentsRequired: [
      "Medical certificate of cause of death (Form 4)",
      "Aadhaar of deceased & informant",
      "Address proof",
      "Ration card / other ID of deceased",
    ],
    fee: 2,
    feeNote:
      "Free within 21 days; ₹2 (after 21 days, within 30); ₹5 (after 30 days, within 1 year); ₹10 (after 1 year, with magistrate order).",
    processingTime: "7–21 days",
    howToApply: [
      "Visit crsorgi.gov.in or your municipal / panchayat portal.",
      "Register the death with date, place & cause.",
      "Upload medical certificate and ID of deceased.",
      "Submit to the local Registrar (Births & Deaths).",
      "Collect certified Death Certificate after verification.",
    ],
    serviceCharge: 50,
    popularity: 85,
    tags: ["death certificate", "vital records", "crsorgi", "registration"],
    online: true,
  },
  {
    id: "birth-certificate-registration",
    slug: "birth-certificate-registration",
    name: "Birth Certificate Registration",
    category: "health-family",
    subcategory: "Vital Records",
    summary: "Register a birth and obtain the official Birth Certificate.",
    description:
      "Registration of every birth is mandatory under the RBD Act, 1969. The Birth Certificate, issued by the local Registrar (municipality / panchayat), is the first legal identity document of a child and is required for school admission, Aadhaar, passport and other services.",
    ministry: "Ministry of Home Affairs (Registrar General of India) / State Governments",
    officialPortal: "Civil Registration System (CRS)",
    officialUrl: "https://crsorgi.gov.in/",
    eligibility: ["Every birth in India must be registered within 21 days", "Parent / guardian / hospital reports the birth"],
    documentsRequired: ["Hospital discharge / birth record", "Aadhaar of parents", "Marriage certificate of parents", "Address proof"],
    fee: 2,
    feeNote:
      "Free within 21 days; ₹2 (21–30 days); ₹5 (30 days–1 year); ₹10 (after 1 year with magistrate order).",
    processingTime: "7–21 days",
    howToApply: [
      "Visit crsorgi.gov.in or your municipal citizen portal.",
      "Register the birth with date, place, parents' details.",
      "Upload hospital record and parents' Aadhaar.",
      "Submit to the local Registrar.",
      "Collect the certified Birth Certificate after verification.",
    ],
    serviceCharge: 50,
    popularity: 95,
    tags: ["birth certificate", "vital records", "crsorgi", "registration"],
    online: true,
  },
  {
    id: "still-birth-certificate",
    slug: "still-birth-certificate",
    name: "Still Birth Certificate Registration",
    category: "health-family",
    subcategory: "Vital Records",
    summary: "Register a still birth and obtain a Still Birth Certificate.",
    description:
      "Still births (foetal death at ≥20 weeks gestation or ≥500g weight) must be registered under the RBD Act, 1969. The Medical Practitioner or institution reports the still birth, and the Registrar issues a Still Birth Certificate, which is used for medical records, maternity benefits and statistics.",
    ministry: "Ministry of Home Affairs (Registrar General of India) / State Governments",
    officialPortal: "Civil Registration System (CRS)",
    officialUrl: "https://crsorgi.gov.in/",
    eligibility: ["Any still birth occurring in a hospital or at home must be registered", "Institutional authority or parent reports"],
    documentsRequired: ["Medical certificate of still birth (Form 4A)", "Hospital record", "Aadhaar of mother", "Address proof"],
    fee: 2,
    feeNote:
      "Free within 21 days; late registration fees apply later (₹2–₹10).",
    processingTime: "7–21 days",
    howToApply: [
      "Visit crsorgi.gov.in or municipal registrar office.",
      "Fill the still birth registration form.",
      "Upload medical certificate (Form 4A) and hospital record.",
      "Submit to the Registrar (Births & Deaths).",
      "Collect the Still Birth Certificate after verification.",
    ],
    serviceCharge: 50,
    popularity: 30,
    tags: ["still birth", "vital records", "crsorgi", "registration"],
    online: true,
  },
  {
    id: "drug-license-retail-pharmacy",
    slug: "drug-license-retail-pharmacy",
    name: "Drug License (Retail Pharmacy)",
    category: "health-family",
    subcategory: "Drug & Pharmacy Licenses",
    summary: "Obtain a retail drug licence to sell allopathic medicines to consumers.",
    description:
      "A Retail Drug License (Form 20/21) issued by the State Drug Controller under the Drugs & Cosmetics Act, 1940 is mandatory to operate a retail pharmacy. The licence requires a qualified pharmacist (D.Pharm / B.Pharm) and premises meeting statutory storage conditions.",
    ministry: "Ministry of Health & Family Welfare (CDSCO / State FDA)",
    officialPortal: "CDSCO / State FDA Portals",
    officialUrl: "https://cdsco.gov.in/",
    eligibility: [
      "Registered pharmacist (Pharmacy Council) or partnership / company with pharmacist",
      "Premises ≥10 sq.m with required storage",
      "Compliance with Good Pharmacy Practice",
    ],
    documentsRequired: ["Pharmacist registration certificate", "Premises proof / rental agreement", "Constitution of firm (partnership deed / MOA)", "Affidavit of pharmacist", "Layout & storage plan", "Aadhaar of applicant"],
    fee: 3000,
    feeNote: "State-wise ₹3,000–₹15,000 for fresh retail licence; renewal at 50%–100%.",
    processingTime: "30–60 days",
    howToApply: [
      "Apply on the State Drugs Control / FDA online portal.",
      "Upload Form 19/20/21 and supporting documents.",
      "Pay licence fee online.",
      "Inspection of premises by Drug Inspector.",
      "Grant of retail drug licence (Form 20/21) by State Licensing Authority.",
    ],
    serviceCharge: 120,
    popularity: 50,
    tags: ["drug license", "retail pharmacy", "form 20", "form 21", "cdsco"],
    online: true,
  },
  {
    id: "drug-license-wholesale",
    slug: "drug-license-wholesale",
    name: "Drug License (Wholesale)",
    category: "health-family",
    subcategory: "Drug & Pharmacy Licenses",
    summary: "Obtain a wholesale drug licence to sell medicines to retailers & institutions.",
    description:
      "A Wholesale Drug License (Form 20B/21B) issued by the State Drug Controller allows sale of drugs to retailers, hospitals and other licensees (not direct to consumers). It is required for distributors, stockists and C&F agents in the pharmaceutical supply chain.",
    ministry: "Ministry of Health & Family Welfare (CDSCO / State FDA)",
    officialPortal: "CDSCO / State FDA Portals",
    officialUrl: "https://cdsco.gov.in/",
    eligibility: ["Partnership / company / LLP with a competent technical person (B.Pharm / D.Pharm / graduate in science with experience)", "Storage premises meeting statutory requirements"],
    documentsRequired: ["Constitution deed / MOA & AOA", "Competent person qualification & registration", "Premises proof", "Storage plan & cold chain if applicable", "Aadhaar of directors / partners"],
    fee: 3000,
    feeNote: "₹3,000–₹15,000 depending on state; renewal as notified.",
    processingTime: "30–60 days",
    howToApply: [
      "Apply on the State Drugs Control / FDA portal.",
      "Submit Form 20B/21B with supporting documents.",
      "Pay licence fee online.",
      "Inspection of premises by Drug Inspector.",
      "Grant of wholesale drug licence by Licensing Authority.",
    ],
    serviceCharge: 120,
    popularity: 45,
    tags: ["drug license", "wholesale", "form 20b", "form 21b", "cdsco"],
    online: true,
  },
  {
    id: "clinical-establishment-registration",
    slug: "clinical-establishment-registration",
    name: "Clinical Establishment Registration",
    category: "health-family",
    subcategory: "Medical Facility Licenses",
    summary: "Register a clinical establishment (clinic / hospital / diagnostic centre) under CE Act.",
    description:
      "Under the Clinical Establishments (Registration & Regulation) Act, 2010, every clinical establishment in the adopting states / UTs must be registered with the State / District Registering Authority. The National Council prescribes Minimum Standards for care, infrastructure and records.",
    ministry: "Ministry of Health & Family Welfare (National Council for Clinical Establishments)",
    officialPortal: "Clinical Establishments Portal",
    officialUrl: "https://clinicalestablishments.gov.in/",
    eligibility: [
      "Any clinical establishment — hospital, clinic, nursing home, diagnostic lab, physiotherapy centre",
      "Operated by a registered medical practitioner (Modern / AYUSH)",
      "Meets Minimum Standards prescribed by National Council",
    ],
    documentsRequired: ["Constitution / ownership proof", "Qualification & MCI/SMC registration of doctor(s)", "Premises / occupancy proof", "Fire & biomedical waste NOC", "List of equipment & services", "Aadhaar of owner"],
    fee: 500,
    feeNote:
      "Provisional registration free; permanent registration ₹500–₹5,000 based on bed strength & state.",
    processingTime: "30–45 days (permanent); provisional instant",
    howToApply: [
      "Register on clinicalestablishments.gov.in / state portal.",
      "Fill the application form with establishment details.",
      "Upload ownership, doctor registration and NOC documents.",
      "Pay registration fee online.",
      "Inspection & grant of Certificate of Registration (5-year validity).",
    ],
    serviceCharge: 130,
    popularity: 40,
    tags: ["clinical establishment", "hospital registration", "ce act", "clinic"],
    online: true,
  },
  {
    id: "nursing-home-registration",
    slug: "nursing-home-registration",
    name: "Nursing Home Registration",
    category: "health-family",
    subcategory: "Medical Facility Licenses",
    summary: "Register a private nursing home with the state health department.",
    description:
      "State laws (e.g. Bombay Nursing Homes Registration Act, Delhi Nursing Homes Registration Act) require every private nursing home to be registered with the State Directorate of Health Services. The licence is renewable and subject to infrastructure, staffing and safety norms.",
    ministry: "State Health Departments",
    officialPortal: "State Health Dept Portals",
    officialUrl: "https://www.mohfw.gov.in/",
    eligibility: [
      "Owned / operated by a registered medical practitioner",
      "Adequate nursing & support staff",
      "Fire safety, biomedical waste & pollution control compliance",
    ],
    documentsRequired: ["MCI / State Medical Council registration of owner doctor", "Nursing staff registrations (INC)", "Premises & fire safety NOC", "Biomedical waste agreement", "Equipment list", "Aadhaar of owner"],
    fee: 3000,
    feeNote: "₹1,000–₹10,000 depending on bed strength & state; renewal every 1–5 years.",
    processingTime: "30–60 days",
    howToApply: [
      "Apply on the State Directorate of Health Services portal.",
      "Submit application with required documents and fee.",
      "Inspection of premises by health officer.",
      "Grant of registration certificate.",
      "Renew periodically as notified.",
    ],
    serviceCharge: 120,
    popularity: 38,
    tags: ["nursing home", "registration", "health department", "private hospital"],
    online: true,
  },
  {
    id: "medical-council-registration-nmc-smc",
    slug: "medical-council-registration-nmc-smc",
    name: "Medical Council Registration (NMC / SMC)",
    category: "health-family",
    subcategory: "Medical Profession",
    summary: "Register with the National / State Medical Council to practise as a doctor.",
    description:
      "The National Medical Commission (NMC) and State Medical Councils register medical graduates under the NMC Act, 2019. Permanent Registration is mandatory to practise modern medicine in India. The register also enables medical professionals to issue medical certificates and prescribe scheduled drugs.",
    ministry: "Ministry of Health & Family Welfare (NMC) / State Medical Councils",
    officialPortal: "National Medical Commission",
    officialUrl: "https://nmc.org.in/",
    eligibility: ["MBBS graduate from an NMC-recognised medical college (India / abroad with FMGE)", "Completed compulsory rotatory internship", "Indian citizen or OCitizen of India"],
    documentsRequired: ["MBBS degree certificate", "Internship completion certificate", "FMGE pass certificate (for foreign graduates)", "Aadhaar", "Photograph", "Character certificate"],
    fee: 3000,
    feeNote: "NMC registration ~₹3,000–₹5,000 (one-time) + state council annual / renewal fees ₹1,000–₹3,000.",
    processingTime: "30–90 days",
    howToApply: [
      "Register on the NMC / State Medical Council portal.",
      "Fill the registration form with qualification details.",
      "Upload MBBS degree, internship and ID documents.",
      "Pay registration fee online.",
      "Receive Permanent Registration Certificate and unique RMP number.",
    ],
    serviceCharge: 100,
    popularity: 55,
    tags: ["medical council", "nmc", "smc", "doctor registration", "rmp"],
    online: true,
  },
  {
    id: "pcpndt-registration",
    slug: "pcpndt-registration",
    name: "PCPNDT Registration (Genetic Clinic / Ultrasound Centre)",
    category: "health-family",
    subcategory: "Medical Facility Licenses",
    summary: "Register a genetic clinic / ultrasound centre under the PCPNDT Act.",
    description:
      "The Pre-Conception & Pre-Natal Diagnostic Techniques (PCPNDT) Act, 1994 mandates registration of every genetic clinic, ultrasound clinic, imaging centre or facility using prenatal diagnostic techniques. The aim is to prevent sex determination and female foeticide.",
    ministry: "Ministry of Health & Family Welfare (State Appropriate Authorities)",
    officialPortal: "State Health Dept PCPNDT Portals",
    officialUrl: "https://pndt.maharashtra.gov.in/",
    eligibility: [
      "Medical practitioner with MD / DMRD / equivalent in radiology or sonology",
      "Registered medical qualification from MCI / NMC",
      "Equipment certified by AERB",
    ],
    documentsRequired: ["MCI / NMC registration of doctor", "Equipment invoice & AERB certification", "Premises proof", "Constitution of clinic", "Affidavit of compliance with PCPNDT Act"],
    fee: 12000,
    feeNote: "₹3,000–₹25,000 based on number of machines & state; renewal every 5 years.",
    processingTime: "45–90 days",
    howToApply: [
      "Apply on the State Appropriate Authority (PCPNDT) portal.",
      "Submit Form A with clinic and equipment details.",
      "Upload doctor registration, AERB certificate and NOC.",
      "Pay registration fee online.",
      "Inspection & grant of certificate of registration (5-year validity).",
    ],
    serviceCharge: 130,
    popularity: 32,
    tags: ["pcpndt", "ultrasound", "genetic clinic", "registration", "radiology"],
    online: true,
  },
  {
    id: "surrogacy-registration",
    slug: "surrogacy-registration",
    name: "Surrogacy Clinic / Centre Registration",
    category: "health-family",
    subcategory: "Medical Facility Licenses",
    summary: "Register a surrogacy clinic under the Surrogacy (Regulation) Act, 2021.",
    description:
      "The Surrogacy (Regulation) Act, 2021 prohibits commercial surrogacy and allows only altruistic surrogacy for eligible intending couples. Surrogacy clinics must be registered with the State Medical Board / National Surrogacy Board and maintain statutory records.",
    ministry: "Ministry of Health & Family Welfare (National Surrogacy Board)",
    officialPortal: "State Health Dept Surrogacy Portals",
    officialUrl: "https://www.mohfw.gov.in/",
    eligibility: [
      "Clinic attached to IVF / ART facility",
      "Run by qualified medical specialists (gynaecology / embryology)",
      "Compliance with infrastructure & record-keeping norms",
    ],
    documentsRequired: ["MCI / NMC registration of medical director", "IVF / ART lab certification", "Premises & equipment proof", "Standard Operating Procedures", "Affidavit of compliance"],
    fee: 10000,
    feeNote: "₹10,000 registration fee (approx); renewal as notified by State Board.",
    processingTime: "60–90 days",
    howToApply: [
      "Apply to the State Medical Board / Surrogacy Board.",
      "Submit Form with clinic, equipment and staff details.",
      "Upload IVF lab certification and doctor registrations.",
      "Pay registration fee.",
      "Inspection & grant of registration certificate.",
    ],
    serviceCharge: 140,
    popularity: 25,
    tags: ["surrogacy", "ivf", "registration", "art clinic"],
    online: true,
  },
  {
    id: "mental-health-establishment-registration",
    slug: "mental-health-establishment-registration",
    name: "Mental Health Establishment Registration",
    category: "health-family",
    subcategory: "Medical Facility Licenses",
    summary: "Register a mental health establishment under the Mental Healthcare Act, 2017.",
    description:
      "Under the Mental Healthcare Act, 2017, every mental health establishment (psychiatric hospital, de-addiction centre, rehabilitation home) must be registered with the State Mental Health Authority. The registration ensures minimum standards of care, patient rights and prohibition of chaining / cruel treatment.",
    ministry: "Ministry of Health & Family Welfare (Central / State Mental Health Authority)",
    officialPortal: "State Mental Health Authority Portals",
    officialUrl: "https://www.mohfw.gov.in/",
    eligibility: ["Operated by a qualified psychiatrist (MD / DPM)", "Meets Minimum Standards of Mental Health Establishment", "Compliance with patient rights & records"],
    documentsRequired: ["Psychiatrist qualification & registration", "Premises & infrastructure proof", "List of staff (psychologist, social worker, nurses)", "Fire & safety NOC", "Standard operating procedures"],
    fee: 5000,
    feeNote: "₹5,000–₹25,000 based on bed strength & state; renewable periodically.",
    processingTime: "60–90 days",
    howToApply: [
      "Apply on the State Mental Health Authority portal.",
      "Submit application with establishment details.",
      "Upload psychiatrist qualification and infrastructure documents.",
      "Pay registration fee online.",
      "Inspection & grant of registration certificate.",
    ],
    serviceCharge: 130,
    popularity: 28,
    tags: ["mental health", "psychiatric", "registration", "mha", "mental healthcare act"],
    online: true,
  },
  {
    id: "vaccine-adverse-event-reporting",
    slug: "vaccine-adverse-event-reporting",
    name: "Vaccine Adverse Event Reporting (AEFI)",
    category: "health-family",
    subcategory: "Pharmacovigilance",
    summary: "Report Adverse Events Following Immunisation (AEFI) to the national surveillance system.",
    description:
      "The National AEFI Surveillance System under the Immunisation Division of the Ministry of Health & Family Welfare monitors adverse events following immunisation. Healthcare providers and citizens can report AEFI online or via the PIB / NCC-PvPI for review by the National AEFI Committee.",
    ministry: "Ministry of Health & Family Welfare (Immunisation Division)",
    officialPortal: "AEFI Surveillance / PvPI",
    officialUrl: "https://cdsco.gov.in/",
    eligibility: ["Healthcare providers administering vaccines", "Citizens who have experienced an adverse event post-vaccination"],
    documentsRequired: ["Vaccine name, batch & manufacturer", "Date & site of vaccination", "Patient details (age, sex)", "Adverse event description & onset time", "Reporter contact"],
    fee: 0,
    feeNote: "Free public-health reporting; no fee.",
    processingTime: "Acknowledgement 48 hrs; investigation per severity",
    howToApply: [
      "Visit the AEFI / PvPI portal or CDSCO Pharmacovigilance portal.",
      "Fill the AEFI reporting form (Form 1) with vaccine & event details.",
      "Upload supporting medical records.",
      "Submit online; receive acknowledgement with unique ID.",
      "Concerned District Immunisation Officer investigates serious cases.",
    ],
    serviceCharge: 30,
    popularity: 25,
    tags: ["aefi", "adverse event", "vaccine", "pharmacovigilance", "pvpi"],
    online: true,
  },
  {
    id: "blood-bank-license",
    slug: "blood-bank-license",
    name: "Blood Bank License (CDSCO)",
    category: "health-family",
    subcategory: "Drug & Pharmacy Licenses",
    summary: "Obtain a licence to operate a blood bank under the Drugs & Cosmetics Act.",
    description:
      "A Blood Bank License (Form 27-C) is issued by the Central Licence Approving Authority (CDSCO) after inspection of premises, staff, equipment and Standard Operating Procedures. Blood banks must also be registered on the e-Raktkosh network for inventory management.",
    ministry: "Ministry of Health & Family Welfare (CDSCO)",
    officialPortal: "CDSCO Online Services (SUGAM)",
    officialUrl: "https://cdsco.gov.in/",
    eligibility: [
      "Operated by a registered medical practitioner with transfusion medicine qualification",
      "Medical Officer trained in blood bank operations",
      "Adequate technical staff (LT, nurses) & infrastructure",
      "Compliance with Drugs & Cosmetics Rules and NACO guidelines",
    ],
    documentsRequired: ["MCI / NMC registration of medical officer", "Premises proof / layout", "Equipment list & calibration certificates", "Standard Operating Procedures", "Biomedical waste agreement", "Aadhaar of applicant"],
    fee: 50000,
    feeNote: "Fresh licence ~₹50,000; inspection & other charges extra; renewal every 2–3 years.",
    processingTime: "90–180 days",
    howToApply: [
      "Register on the CDSCO SUGAM portal.",
      "Submit Form 27-C with blood bank details.",
      "Upload medical officer qualification, equipment list and SOPs.",
      "Pay licence fee online.",
      "Inspection by CDSCO / State FDA team; grant of licence.",
    ],
    serviceCharge: 150,
    popularity: 30,
    tags: ["blood bank", "license", "cdsco", "form 27c", "transfusion"],
    online: true,
  },
];
