// Tilak E-Seva Portal — Identity & Documents services.
// Real Indian government services from UIDAI, NSDL/Protean, UTIITSL, NVSP,
// eMudhra (CCA), DigiLocker, BBPS.

import type { GovernmentService } from "../types";

export const identityDocuments: GovernmentService[] = [
  {
    id: "aadhaar-enrollment",
    slug: "aadhaar-enrollment",
    name: "Aadhaar Enrollment",
    category: "identity-documents",
    subcategory: "Aadhaar",
    summary: "Get a new 12-digit Aadhaar number from UIDAI.",
    description:
      "Aadhaar is a 12-digit unique identity number issued by UIDAI to residents of India. Enrollment captures demographic and biometric (fingerprints, iris, photo) data. It is free of cost and serves as proof of identity and address across the country.",
    ministry: "Unique Identification Authority of India (UIDAI)",
    officialPortal: "UIDAI — myAadhaar",
    officialUrl: "https://myaadhaar.uidai.gov.in/",
    eligibility: [
      "Indian resident",
      "Any age (including children via Baal Aadhaar)",
      "Must not already hold an Aadhaar",
    ],
    documentsRequired: [
      "Proof of Identity (POI) — e.g. PAN, Passport, Voter ID",
      "Proof of Address (POA) — e.g. bank passbook, utility bill",
      "Proof of Date of Birth (DOB) — e.g. birth certificate, SSC certificate",
    ],
    fee: 0,
    feeNote: "Free at all UIDAI enrollment centers.",
    processingTime: "Up to 90 days",
    howToApply: [
      "Book an appointment online at myaadhaar.uidai.gov.in or visit a nearby Aadhaar Seva Kendra.",
      "Carry original identity, address and date-of-birth proof documents.",
      "At the center, demographic details are entered and biometrics (fingerprints, iris, photograph) captured.",
      "Receive an acknowledgement slip with a 28-digit Enrollment ID (EID).",
      "Track status online with EID; Aadhaar is delivered by post within 90 days.",
    ],
    serviceCharge: 50,
    popularity: 98,
    tags: ["aadhaar", "uidai", "identity", "biometric", "uid"],
    online: true,
  },
  {
    id: "aadhaar-demographic-update",
    slug: "aadhaar-demographic-update",
    name: "Aadhaar Demographic Update",
    category: "identity-documents",
    subcategory: "Aadhaar",
    summary: "Update your name, address, DOB, gender, email or mobile on Aadhaar.",
    description:
      "UIDAI allows residents to update demographic details — name, address, date of birth, gender, mobile number and email — online via myAadhaar or at an Aadhaar Seva Kendra. The first three updates after enrollment are free; subsequent updates carry a ₹50 fee.",
    ministry: "Unique Identification Authority of India (UIDAI)",
    officialPortal: "UIDAI — myAadhaar",
    officialUrl: "https://myaadhaar.uidai.gov.in/",
    eligibility: [
      "Existing Aadhaar holder",
      "Must have a mobile number linked for OTP authentication",
    ],
    documentsRequired: [
      "Existing Aadhaar number",
      "Valid Proof of Identity / Address / DOB depending on field updated",
      "Registered mobile number for OTP",
    ],
    fee: 50,
    feeNote: "First 3 demographic updates in lifetime are free; ₹50 thereafter (GST included).",
    processingTime: "7–30 days",
    howToApply: [
      "Log in to myaadhaar.uidai.gov.in with Aadhaar number and OTP.",
      "Choose 'Update Demographic Data' and select fields to update.",
      "Upload scanned supporting documents (POI/POA/DOB).",
      "Pay ₹50 fee online (if beyond free quota) and submit request.",
      "Track status with the Update Request Number (URN); new Aadhaar e-copy is available after approval.",
    ],
    serviceCharge: 60,
    popularity: 92,
    tags: ["aadhaar", "uidai", "update", "demographic", "name", "address"],
    online: true,
  },
  {
    id: "aadhaar-biometric-update",
    slug: "aadhaar-biometric-update",
    name: "Aadhaar Biometric Update",
    category: "identity-documents",
    subcategory: "Aadhaar",
    summary: "Update fingerprints, iris or photograph on Aadhaar at a Seva Kendra.",
    description:
      "Biometric updates — fingerprints, iris scans and photograph — must be done in person at an Aadhaar Seva Kendra as they require live capture. Children at age 5 and 15 must mandatorily update biometrics. Fee is ₹100 per biometric update request.",
    ministry: "Unique Identification Authority of India (UIDAI)",
    officialPortal: "UIDAI — Aadhaar Seva Kendra",
    officialUrl: "https://myaadhaar.uidai.gov.in/",
    eligibility: [
      "Existing Aadhaar holder",
      "Children completing age 5 or 15 (mandatory update)",
      "Anyone with faded fingerprints or iris failure",
    ],
    documentsRequired: [
      "Existing Aadhaar number / acknowledgment",
      "Proof of Identity",
      "Registered mobile number for OTP",
    ],
    fee: 100,
    feeNote: "₹100 (GST inclusive) per biometric update request.",
    processingTime: "7–30 days",
    howToApply: [
      "Book a slot at an Aadhaar Seva Kendra via myaadhaar.uidai.gov.in.",
      "Visit the center on the appointment date with original Aadhaar.",
      "Authenticate with OTP and request biometric update.",
      "Fingerprints, iris and photograph are re-captured.",
      "Use the URN to track status online; updated Aadhaar is delivered within 30 days.",
    ],
    serviceCharge: 75,
    popularity: 85,
    tags: ["aadhaar", "biometric", "fingerprint", "iris", "uidai"],
    online: false,
  },
  {
    id: "aadhaar-mobile-number-update",
    slug: "aadhaar-mobile-number-update",
    name: "Aadhaar Mobile Number Update",
    category: "identity-documents",
    subcategory: "Aadhaar",
    summary: "Link or change the mobile number connected to your Aadhaar.",
    description:
      "Mobile number updates require in-person verification at an Aadhaar Seva Kendra because of the OTP-based authentication ecosystem. Without a linked mobile number, residents cannot use most online UIDAI services. The fee is ₹50 per update request.",
    ministry: "Unique Identification Authority of India (UIDAI)",
    officialPortal: "UIDAI — Aadhaar Seva Kendra",
    officialUrl: "https://myaadhaar.uidai.gov.in/",
    eligibility: ["Existing Aadhaar holder", "Owner of the mobile number to be linked"],
    documentsRequired: ["Existing Aadhaar number", "Proof of Identity", "Mobile handset for OTP"],
    fee: 50,
    feeNote: "₹50 (GST inclusive) per mobile update request.",
    processingTime: "Up to 7 days for activation",
    howToApply: [
      "Book an appointment at an Aadhaar Seva Kendra via myaadhaar.uidai.gov.in.",
      "Visit the center with original Aadhaar and Proof of Identity.",
      "Request mobile number addition or update at the counter.",
      "Verify with OTP sent to the new number.",
      "Acknowledgement slip with URN is issued; mobile is active within 7 days.",
    ],
    serviceCharge: 50,
    popularity: 90,
    tags: ["aadhaar", "mobile", "otp", "uidai", "phone-linking"],
    online: false,
  },
  {
    id: "aadhaar-pvc-card-order",
    slug: "aadhaar-pvc-card-order",
    name: "Aadhaar PVC Card Order",
    category: "identity-documents",
    subcategory: "Aadhaar",
    summary: "Order a durable PVC Aadhaar card delivered to your address.",
    description:
      "UIDAI offers a pocket-sized PVC Aadhaar card with security features like guilloché pattern, ghost image and QR code. Any resident can order it online using Aadhaar or Virtual ID. The fee is ₹50 (inclusive of taxes and Speed Post delivery).",
    ministry: "Unique Identification Authority of India (UIDAI)",
    officialPortal: "UIDAI — Order Aadhaar PVC Card",
    officialUrl: "https://myaadhaar.uidai.gov.in/orderAadhaarPVC",
    eligibility: ["Existing Aadhaar holder", "Mobile or alternate mobile number linked for OTP"],
    documentsRequired: ["Aadhaar number or 16-digit Virtual ID (VID)", "Registered mobile for OTP"],
    fee: 50,
    feeNote: "₹50 (GST inclusive) including Speed Post delivery.",
    processingTime: "3–15 working days",
    howToApply: [
      "Open myaadhaar.uidai.gov.in/orderAadhaarPVC.",
      "Enter Aadhaar / VID, captcha, and verify with OTP.",
      "Confirm the security code on screen.",
      "Pay ₹50 online via UPI / card / net-banking.",
      "Track delivery via India Post using the AWB number on the acknowledgment slip.",
    ],
    serviceCharge: 40,
    popularity: 80,
    tags: ["aadhaar", "pvc", "card", "uidai", "delivery"],
    online: true,
  },
  {
    id: "aadhaar-lock-unlock-biometrics",
    slug: "aadhaar-lock-unlock-biometrics",
    name: "Aadhaar Lock/Unlock Biometrics",
    category: "identity-documents",
    subcategory: "Aadhaar",
    summary: "Secure your Aadhaar biometrics by locking them when not in use.",
    description:
      "UIDAI's Biometric Locking feature lets residents lock their fingerprints and iris data to prevent misuse. Once locked, biometric authentication fails until unlocked by the resident. The service is free and can be managed entirely from the myAadhaar app or website.",
    ministry: "Unique Identification Authority of India (UIDAI)",
    officialPortal: "UIDAI — Lock/Unlock Biometrics",
    officialUrl: "https://myaadhaar.uidai.gov.in/lockUnlockBiometric",
    eligibility: ["Existing Aadhaar holder", "Mobile number linked for OTP"],
    documentsRequired: ["Aadhaar number / VID", "Registered mobile number"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Log in to myaadhaar.uidai.gov.in with Aadhaar and OTP.",
      "Navigate to 'Lock/Unlock Biometrics'.",
      "Verify your identity with a second OTP.",
      "Choose Lock to disable biometric authentication.",
      "To re-enable, use Unlock from the same dashboard — temporary unlock is also available.",
    ],
    serviceCharge: 25,
    popularity: 60,
    tags: ["aadhaar", "biometric", "lock", "security", "uidai"],
    online: true,
  },
  {
    id: "virtual-id-generation",
    slug: "virtual-id-generation",
    name: "Virtual ID (VID) Generation",
    category: "identity-documents",
    subcategory: "Aadhaar",
    summary: "Generate a 16-digit temporary Virtual ID instead of sharing Aadhaar.",
    description:
      "VID is a temporary, revocable 16-digit number mapped to the Aadhaar number. It can be used in place of Aadhaar for authentication and e-KYC, protecting the resident's actual Aadhaar number. A new VID can be generated any time; the older one expires.",
    ministry: "Unique Identification Authority of India (UIDAI)",
    officialPortal: "UIDAI — Generate VID",
    officialUrl: "https://myaadhaar.uidai.gov.in/generateOrRetrieveVID",
    eligibility: ["Existing Aadhaar holder", "Mobile number linked for OTP"],
    documentsRequired: ["Aadhaar number", "Registered mobile number"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Visit myaadhaar.uidai.gov.in/generateOrRetrieveVID.",
      "Enter Aadhaar number and captcha.",
      "Verify with OTP sent to the registered mobile.",
      "Choose 'Generate New VID' — a fresh 16-digit VID is displayed.",
      "Use the VID for e-KYC; retrieve it later with the same flow.",
    ],
    serviceCharge: 25,
    popularity: 55,
    tags: ["aadhaar", "vid", "privacy", "ekyc", "uidai"],
    online: true,
  },
  {
    id: "masked-aadhaar-download",
    slug: "masked-aadhaar-download",
    name: "Masked Aadhaar Download",
    category: "identity-documents",
    subcategory: "Aadhaar",
    summary: "Download Aadhaar with first 8 digits hidden for safer sharing.",
    description:
      "A masked Aadhaar e-copy displays only the last 4 digits of the Aadhaar number, hiding the first 8 for privacy. It is a valid proof of identity for most non-banking KYC uses. The password-protected PDF can be downloaded free from the UIDAI portal.",
    ministry: "Unique Identification Authority of India (UIDAI)",
    officialPortal: "UIDAI — Download Aadhaar",
    officialUrl: "https://myaadhaar.uidai.gov.in/downloadAadhaar",
    eligibility: ["Existing Aadhaar holder", "Mobile number linked for OTP"],
    documentsRequired: ["Aadhaar number or VID", "Registered mobile number"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Go to myaadhaar.uidai.gov.in/downloadAadhaar.",
      "Enter Aadhaar / VID and captcha, then choose 'Masked Aadhaar'.",
      "Verify with OTP (or TOTP via mAadhaar app).",
      "Download the password-protected PDF (password = first 4 letters of name in CAPS + birth year).",
      "Use the masked copy where full Aadhaar is not mandatory.",
    ],
    serviceCharge: 25,
    popularity: 70,
    tags: ["aadhaar", "masked", "download", "ekyc", "uidai"],
    online: true,
  },
  {
    id: "aadhaar-pan-linking",
    slug: "aadhaar-pan-linking",
    name: "Aadhaar-PAN Linking",
    category: "identity-documents",
    subcategory: "Aadhaar",
    summary: "Link your PAN with Aadhaar — mandatory for valid PAN.",
    description:
      "The Income Tax Department mandates linking of PAN with Aadhaar; unlinked PANs are rendered 'inoperative' for most financial transactions. Linking is free if done before the deadline; a ₹1,000 fee applies for late linking under Section 234H.",
    ministry: "Central Board of Direct Taxes (CBDT)",
    officialPortal: "Income Tax e-Filing — Link Aadhaar",
    officialUrl: "https://eportal.incometax.gov.in/iec/foservices/",
    eligibility: ["Indian resident with PAN", "Aadhaar holder", "Mobile linked to Aadhaar for OTP"],
    documentsRequired: ["PAN number", "Aadhaar number", "Name exactly as on Aadhaar"],
    fee: 1000,
    feeNote: "₹1,000 late-linking fee under Section 234H (free if linked before deadline).",
    processingTime: "Instant to 72 hours",
    howToApply: [
      "Log in to eportal.incometax.gov.in with PAN.",
      "Navigate to Profile → Link Aadhaar.",
      "Verify Aadhaar details and confirm name match.",
      "Pay ₹1,000 challan if late, then authenticate via Aadhaar OTP.",
      "Confirmation SMS is sent once linking is successful.",
    ],
    serviceCharge: 75,
    popularity: 95,
    tags: ["aadhaar", "pan", "linking", "incometax", "234h"],
    online: true,
  },
  {
    id: "aadhaar-authentication-history",
    slug: "aadhaar-authentication-history",
    name: "Aadhaar Authentication History",
    category: "identity-documents",
    subcategory: "Aadhaar",
    summary: "View the last 50 Aadhaar authentication transactions.",
    description:
      "UIDAI lets residents view up to 50 of their most recent authentication transactions, including e-KYC, biometric and OTP authentications. This helps detect unauthorized use of Aadhaar. The service is free and instantly available via the myAadhaar portal.",
    ministry: "Unique Identification Authority of India (UIDAI)",
    officialPortal: "UIDAI — Authentication History",
    officialUrl: "https://myaadhaar.uidai.gov.in/checkAadhaarAuthHistory",
    eligibility: ["Existing Aadhaar holder", "Mobile number linked for OTP"],
    documentsRequired: ["Aadhaar number / VID", "Registered mobile number"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Open myaadhaar.uidai.gov.in/checkAadhaarAuthHistory.",
      "Enter Aadhaar / VID, captcha and OTP.",
      "Select the authentication type and date range (up to 6 months).",
      "Enter the security code sent by SMS.",
      "View the list of authentications with date, time, requesting entity and modality.",
    ],
    serviceCharge: 25,
    popularity: 50,
    tags: ["aadhaar", "authentication", "history", "audit", "uidai"],
    online: true,
  },
  {
    id: "pan-card-new-application-form-49a",
    slug: "pan-card-new-application-form-49a",
    name: "PAN Card New Application (Form 49A)",
    category: "identity-documents",
    subcategory: "PAN",
    summary: "Apply for a new Permanent Account Number (PAN) — Indian citizens.",
    description:
      "Form 49A is the application for a new PAN by Indian citizens, companies and entities formed in India. Applications can be made online via NSDL (Protean) or UTIITSL. The fee is ₹107 for a physical PAN card and ₹72 for an e-PAN only.",
    ministry: "Income Tax Department / NSDL (Protean)",
    officialPortal: "Protean (NSDL) — PAN Online",
    officialUrl: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    eligibility: [
      "Indian citizen, entity or company",
      "Never allotted a PAN before",
      "Aged 18+ for individual applications (minors via guardian)",
    ],
    documentsRequired: [
      "Proof of Identity (Passport, Aadhaar, Voter ID etc.)",
      "Proof of Address (Aadhaar, utility bill, bank statement)",
      "Proof of Date of Birth (birth certificate, school certificate)",
      "Photograph (passport size, scanned)",
    ],
    fee: 107,
    feeNote: "₹107 physical PAN (incl. taxes); ₹72 e-PAN only; ₹1,017 for physical PAN outside India.",
    processingTime: "15–20 working days (e-PAN in ~72 hours)",
    howToApply: [
      "Visit onlineservices.nsdl.com and select 'New PAN — Form 49A'.",
      "Fill in personal details, parents' details and AO code.",
      "Upload photograph, signature and supporting documents.",
      "Pay ₹107 (physical) or ₹72 (e-PAN) online.",
      "Track status with the 15-digit acknowledgement number; physical card is delivered by India Post.",
    ],
    serviceCharge: 80,
    popularity: 96,
    tags: ["pan", "nsdl", "protean", "form49a", "income-tax", "identity"],
    online: true,
  },
  {
    id: "pan-card-correction",
    slug: "pan-card-correction",
    name: "PAN Card Correction",
    category: "identity-documents",
    subcategory: "PAN",
    summary: "Correct name, DOB, address, photo or signature on your PAN.",
    description:
      "Existing PAN holders can request changes or corrections to their PAN data — name, date of birth, address, photograph, signature, parentage — via NSDL/UTIITSL. The fee is ₹107 for a corrected physical PAN card and ₹72 for an e-PAN correction.",
    ministry: "Income Tax Department / NSDL (Protean)",
    officialPortal: "Protean (NSDL) — PAN Correction",
    officialUrl: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    eligibility: ["Existing PAN holder", "Supporting documents that justify the change"],
    documentsRequired: [
      "Existing PAN number",
      "Proof of Identity, Address and DOB (with corrected values)",
      "Documentary proof for the change (e.g. gazette notification for name change)",
    ],
    fee: 107,
    feeNote: "₹107 physical corrected PAN; ₹72 e-PAN only.",
    processingTime: "15–20 working days",
    howToApply: [
      "Open onlineservices.nsdl.com and choose 'Changes/Correction in PAN'.",
      "Select fields to be corrected and fill in new values.",
      "Upload supporting documents and proof of the change.",
      "Pay ₹107 / ₹72 online and submit.",
      "Track status with acknowledgement number; corrected PAN delivered within 20 days.",
    ],
    serviceCharge: 90,
    popularity: 88,
    tags: ["pan", "correction", "nsdl", "protean", "update"],
    online: true,
  },
  {
    id: "pan-for-foreign-citizens-form-49aa",
    slug: "pan-for-foreign-citizens-form-49aa",
    name: "PAN for Foreign Citizens (Form 49AA)",
    category: "identity-documents",
    subcategory: "PAN",
    summary: "Apply for an Indian PAN — foreign citizens and entities.",
    description:
      "Form 49AA is used by foreign citizens and entities incorporated outside India to obtain an Indian PAN, often required for investments, business or tax compliance. Applications are filed via NSDL (Protean). The fee is ₹1,017 for physical delivery abroad and ₹944 for e-PAN only.",
    ministry: "Income Tax Department / NSDL (Protean)",
    officialPortal: "Protean (NSDL) — Form 49AA",
    officialUrl: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    eligibility: [
      "Non-Indian citizen or entity incorporated outside India",
      "Required for Indian tax, business or investment purposes",
    ],
    documentsRequired: [
      "Passport (mandatory for foreign individuals)",
      "Proof of Address outside India",
      "Proof of Identity and Date of Birth",
      "Country of citizenship / incorporation proof",
    ],
    fee: 1017,
    feeNote: "₹1,017 for physical PAN delivered abroad; ₹944 for e-PAN only.",
    processingTime: "20–30 working days",
    howToApply: [
      "Visit onlineservices.nsdl.com and select Form 49AA.",
      "Fill personal/entity details, country of citizenship, AO code.",
      "Upload passport, address proof and identity documents.",
      "Pay ₹1,017 / ₹944 online via international card or NRO bank transfer.",
      "Track with acknowledgement number; PAN is couriered abroad.",
    ],
    serviceCharge: 120,
    popularity: 65,
    tags: ["pan", "form49aa", "foreign", "nri", "nsdl", "protean"],
    online: true,
  },
  {
    id: "pan-aadhaar-link-status-check",
    slug: "pan-aadhaar-link-status-check",
    name: "PAN-Aadhaar Link Status Check",
    category: "identity-documents",
    subcategory: "PAN",
    summary: "Verify whether your PAN is linked with Aadhaar and operative.",
    description:
      "The Income Tax Department provides a free public utility to check the link status between PAN and Aadhaar. Unlinked PANs are marked 'inoperative' and cannot be quoted for specified transactions. The check requires only PAN and Aadhaar numbers — no login needed.",
    ministry: "Central Board of Direct Taxes (CBDT)",
    officialPortal: "Income Tax e-Filing — Link Status",
    officialUrl: "https://eportal.incometax.gov.in/iec/foservices/",
    eligibility: ["Holders of both PAN and Aadhaar"],
    documentsRequired: ["PAN number", "Aadhaar number", "Registered mobile / name"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Visit the 'Link Aadhaar' utility on eportal.incometax.gov.in.",
      "Choose 'Check Link Status' from the menu.",
      "Enter PAN, Aadhaar number and captcha.",
      "View status — Linked / Not Linked / Inoperative.",
      "If not linked, follow the on-screen prompt to complete linking.",
    ],
    serviceCharge: 25,
    popularity: 92,
    tags: ["pan", "aadhaar", "status", "link", "incometax"],
    online: true,
  },
  {
    id: "e-pan-download",
    slug: "e-pan-download",
    name: "e-PAN Download",
    category: "identity-documents",
    subcategory: "PAN",
    summary: "Download a digital PDF copy of your PAN instantly.",
    description:
      "NSDL (Protean) and UTIITSL allow PAN holders to download a digitally signed e-PAN in PDF format. It is legally equivalent to the physical PAN card and accepted for most KYC purposes. Download is free for recently issued PANs (within 30 days); ₹8.80 otherwise.",
    ministry: "Income Tax Department / NSDL (Protean) / UTIITSL",
    officialPortal: "NSDL e-PAN / UTIITSL e-PAN",
    officialUrl: "https://www.onlineservices.nsdl.com/paam/ReprintEPAN.html",
    eligibility: ["Existing PAN holder", "Mobile or email linked for OTP"],
    documentsRequired: ["PAN number", "Registered mobile / email for OTP"],
    fee: 8,
    feeNote: "Free within 30 days of allotment; ₹8.80 (GST incl.) for subsequent downloads.",
    processingTime: "Instant",
    howToApply: [
      "Go to onlineservices.nsdl.com/paam/ReprintEPAN.html.",
      "Enter PAN, captcha and Aadhaar (if linked).",
      "Authenticate via OTP on registered mobile / email.",
      "Pay ₹8.80 if applicable.",
      "Download the password-protected e-PAN PDF (password = date of birth in DDMMYYYY).",
    ],
    serviceCharge: 30,
    popularity: 90,
    tags: ["pan", "e-pan", "download", "nsdl", "utiitsl", "digital"],
    online: true,
  },
  {
    id: "tan-registration",
    slug: "tan-registration",
    name: "TAN Registration",
    category: "identity-documents",
    subcategory: "TAN",
    summary: "Get a Tax Deduction Account Number (TAN) for TDS compliance.",
    description:
      "TAN is a 10-digit alphanumeric number mandatory for anyone responsible for deducting/collecting tax at source (TDS/TCS). Issued by NSDL (Protean) on behalf of the Income Tax Department. The application fee is ₹65 (₹71.50 with GST) for Indian applicants.",
    ministry: "Income Tax Department / NSDL (Protean)",
    officialPortal: "Protean (NSDL) — TAN Online",
    officialUrl: "https://www.tin-nsdl.com/services/tan/tan-index.html",
    eligibility: [
      "Any person / entity required to deduct TDS or collect TCS",
      "Employers, companies, firms, deductors",
    ],
    documentsRequired: [
      "Proof of Identity (PAN of applicant)",
      "Proof of Address of deductor entity",
      "Demand draft if offline (in favour of 'Protean – TAN')",
    ],
    fee: 65,
    feeNote: "₹65 + GST = ₹71.50 for Indian applicants; ₹761 for dispatch outside India.",
    processingTime: "7–10 working days",
    howToApply: [
      "Visit tin-nsdl.com and choose 'Online TAN Application — Form 49B'.",
      "Fill entity details, deductor category and AO code.",
      "Pay ₹71.50 online (or via DD for offline).",
      "Receive 14-digit acknowledgement number for tracking.",
      "TAN allotment letter is dispatched by NSDL within 10 days.",
    ],
    serviceCharge: 90,
    popularity: 70,
    tags: ["tan", "tds", "nsdl", "protean", "income-tax", "form49b"],
    online: true,
  },
  {
    id: "voter-id-epic-new-registration",
    slug: "voter-id-epic-new-registration",
    name: "Voter ID (EPIC) New Registration",
    category: "identity-documents",
    subcategory: "Voter ID",
    summary: "Register as a new voter and get an EPIC card via Form 6.",
    description:
      "Form 6 on the Voter Helpline app or voters.eci.gov.in is used by first-time voters and new residents to enrol in the electoral roll. After verification by the Booth Level Officer, an Elector's Photo Identity Card (EPIC) is issued free of cost by the Election Commission of India.",
    ministry: "Election Commission of India (ECI)",
    officialPortal: "ECI — Voter Helpline / NVSP",
    officialUrl: "https://voters.eci.gov.in/",
    eligibility: [
      "Indian citizen",
      "Aged 18+ as on the qualifying date (1 Jan / 1 Apr / 1 Jul / 1 Oct)",
      "Ordinarily resident at the address given",
    ],
    documentsRequired: [
      "Aadhaar number (for demographic verification)",
      "Proof of Address (latest utility bill, bank passbook, etc.)",
      "Passport-size photograph",
      "Proof of Age (Class 10 certificate, birth certificate, PAN)",
    ],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "30–45 days",
    howToApply: [
      "Log in at voters.eci.gov.in or open the Voter Helpline app.",
      "Choose Form 6 — New Voter Registration.",
      "Fill personal, address and family details; link Aadhaar.",
      "Upload photo, age and address proofs.",
      "Submit and note the Application ID; BLO visits for verification before EPIC is issued.",
    ],
    serviceCharge: 50,
    popularity: 90,
    tags: ["voter-id", "epic", "eci", "form6", "election", "identity"],
    online: true,
  },
  {
    id: "voter-id-correction",
    slug: "voter-id-correction",
    name: "Voter ID Correction",
    category: "identity-documents",
    subcategory: "Voter ID",
    summary: "Correct name, address, photo or DOB on your Voter ID (Form 8).",
    description:
      "Form 8 is used to correct entries — name, photograph, age, address, gender or EPIC number — on the electoral roll. It can also be used to mark a Person with Disability (PwD) or shift within the same constituency. The Election Commission processes corrections free of charge.",
    ministry: "Election Commission of India (ECI)",
    officialPortal: "ECI — NVSP Form 8",
    officialUrl: "https://voters.eci.gov.in/",
    eligibility: ["Existing Voter ID holder listed on the electoral roll"],
    documentsRequired: [
      "Existing EPIC number",
      "Documentary proof of the correct entry (e.g. Aadhaar for name/address)",
      "Recent passport-size photograph",
    ],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "30–45 days",
    howToApply: [
      "Log in to voters.eci.gov.in with mobile OTP.",
      "Choose Form 8 — Correction of Entries.",
      "Select fields to correct and enter new values.",
      "Upload supporting proof and recent photo.",
      "Submit and track via Application ID; corrected EPIC is delivered by post.",
    ],
    serviceCharge: 50,
    popularity: 82,
    tags: ["voter-id", "correction", "form8", "eci", "nvsp"],
    online: true,
  },
  {
    id: "voter-id-duplicate-lost",
    slug: "voter-id-duplicate-lost",
    name: "Voter ID Duplicate (Lost)",
    category: "identity-documents",
    subcategory: "Voter ID",
    summary: "Get a replacement Voter ID card for one lost or destroyed.",
    description:
      "Voters whose EPIC card is lost, stolen or destroyed can apply for a duplicate via Form EPIC-002 on the NVSP portal. A nominal fee of ₹25 is payable (varies by state) and a replacement card is dispatched after verification of the existing electoral roll entry.",
    ministry: "Election Commission of India (ECI)",
    officialPortal: "ECI — NVSP Duplicate EPIC",
    officialUrl: "https://voters.eci.gov.in/",
    eligibility: [
      "Existing voter on electoral roll",
      "Original EPIC lost, destroyed or unusable",
    ],
    documentsRequired: [
      "Existing EPIC number (if known)",
      "Copy of FIR in case of theft",
      "Proof of Address and Identity",
      "Passport-size photograph",
    ],
    fee: 25,
    feeNote: "₹25 nominal fee (varies by state).",
    processingTime: "30–45 days",
    howToApply: [
      "Log in to voters.eci.gov.in with mobile OTP.",
      "Choose 'Replacement EPIC' (Form EPIC-002).",
      "Provide original EPIC number and reason for replacement.",
      "Upload FIR (if stolen) and identity proofs; pay ₹25 fee.",
      "Track with Application ID; new EPIC is delivered to the registered address.",
    ],
    serviceCharge: 40,
    popularity: 65,
    tags: ["voter-id", "duplicate", "lost", "nvsp", "eci", "epic"],
    online: true,
  },
  {
    id: "electoral-roll-search",
    slug: "electoral-roll-search",
    name: "Electoral Roll Search",
    category: "identity-documents",
    subcategory: "Voter ID",
    summary: "Check your name, polling booth and details on the electoral roll.",
    description:
      "The Election Commission's electoralsearch.in service lets citizens verify if their name is on the voter list, view their polling station and download voter slip. A simple search by EPIC number or by name and address returns details free of charge.",
    ministry: "Election Commission of India (ECI)",
    officialPortal: "ECI — Electoral Roll Search",
    officialUrl: "https://electoralsearch.eci.gov.in/",
    eligibility: ["Any citizen registered (or seeking registration) as a voter"],
    documentsRequired: ["EPIC number or full name + age + address + state"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Open electoralsearch.eci.gov.in.",
      "Search by EPIC number, or by Name + Father/Husband name + Age + State + District.",
      "Enter captcha and submit.",
      "View your voter record, polling station and assembly/parliamentary constituency.",
      "Download or print the voter slip if needed.",
    ],
    serviceCharge: 25,
    popularity: 78,
    tags: ["voter-id", "electoral-roll", "search", "eci", "voter-list"],
    online: true,
  },
  {
    id: "dsc-class-2",
    slug: "dsc-class-2",
    name: "Digital Signature Certificate (DSC) Class 2",
    category: "identity-documents",
    subcategory: "Digital Signature",
    summary: "Class 2 DSC for income-tax e-filing, GST and MCA filings.",
    description:
      "Class 2 Digital Signature Certificates are issued by Certifying Authorities licensed by the Controller of Certifying Authorities (CCA). They are used for e-filing of income tax returns, GST submissions, MCA filings and PF/ESI portals. Validity is 1–3 years and issuance requires Aadhaar e-KYC or paper verification.",
    ministry: "Controller of Certifying Authorities (CCA), MeitY",
    officialPortal: "eMudhra / (n)Code / Sify / Capricorn",
    officialUrl: "https://www.emudhradigital.com/",
    eligibility: [
      "Indian individual or entity",
      "PAN and Aadhaar (for individuals)",
      "Required for tax, MCA or GST filings",
    ],
    documentsRequired: [
      "PAN card copy",
      "Aadhaar copy (for e-KYC based issuance)",
      "Passport-size photograph",
      "For organizations: GST / COI / PAN of entity",
    ],
    fee: 1500,
    feeNote: "₹1,500–₹2,500 for 2 years depending on issuing authority and USB token.",
    processingTime: "1–3 working days",
    howToApply: [
      "Visit a licensed Certifying Authority (eMudhra, (n)Code, Sify, Capricorn).",
      "Choose Class 2 DSC and validity (1–3 years).",
      "Complete Aadhaar e-KYC video verification or submit paper form.",
      "Pay ₹1,500+ and upload documents.",
      "DSC is issued on a USB token or downloaded with a password-protected file.",
    ],
    serviceCharge: 100,
    popularity: 60,
    tags: ["dsc", "digital-signature", "class2", "cca", "mca", "gst"],
    online: true,
  },
  {
    id: "dsc-class-3",
    slug: "dsc-class-3",
    name: "DSC Class 3",
    category: "identity-documents",
    subcategory: "Digital Signature",
    summary: "High-assurance Class 3 DSC for e-tendering and e-procurement.",
    description:
      "Class 3 DSC is the highest assurance digital signature in India, mandatory for e-tendering, e-procurement, IRCTC and trademark filings. Issued only after in-person or video verification of identity. Valid for 1–3 years and delivered on a FIPS-certified USB token.",
    ministry: "Controller of Certifying Authorities (CCA), MeitY",
    officialPortal: "eMudhra / (n)Code / Sify / Capricorn",
    officialUrl: "https://www.emudhradigital.com/",
    eligibility: [
      "Indian individual or authorized representative of an organization",
      "Required for e-tendering / e-procurement participation",
      "PAN and Aadhaar (individuals)",
    ],
    documentsRequired: [
      "PAN card",
      "Aadhaar / Passport (photo ID)",
      "Passport-size photograph",
      "Authorization letter (for organization)",
      "GST / COI / MSME certificate of entity",
    ],
    fee: 2500,
    feeNote: "₹2,500–₹3,500 (incl. USB token) for 2 years; varies by authority.",
    processingTime: "2–5 working days",
    howToApply: [
      "Choose a CCA-licensed authority (eMudhra, Sify, (n)Code, Capricorn).",
      "Select Class 3 DSC — Signing, Encryption or Combo.",
      "Complete video verification and submit documents.",
      "Pay ₹2,500+ online.",
      "Receive FIPS-certified USB token with the DSC installed, along with installation guide.",
    ],
    serviceCharge: 130,
    popularity: 55,
    tags: ["dsc", "class3", "e-tendering", "digital-signature", "cca", "encryption"],
    online: true,
  },
  {
    id: "e-sign-service",
    slug: "e-sign-service",
    name: "e-Sign Service",
    category: "identity-documents",
    subcategory: "Digital Signature",
    summary: "Aadhaar-based e-Sign of PDF documents — free, instant, legally valid.",
    description:
      "e-Sign is an online electronic signature service that lets Aadhaar holders sign documents using their Aadhaar e-KYC. It is legally valid under the IT Act 2000 and is offered by CCA-licensed ESPs (eMudhra, CDAC, (n)Code). It is free for individuals for low-volume use.",
    ministry: "Controller of Certifying Authorities (CCA), MeitY",
    officialPortal: "eMudhra e-Sign / CDAC e-Sign",
    officialUrl: "https://www.emudhradigital.com/e-sign.php",
    eligibility: ["Aadhaar holder with linked mobile", "Mobile number active for OTP"],
    documentsRequired: ["Aadhaar number / VID", "Registered mobile for OTP", "PDF to sign"],
    fee: 0,
    feeNote: "Free for individuals; ESPs charge enterprises per signature.",
    processingTime: "Instant",
    howToApply: [
      "Open the document on a portal that supports e-Sign (DigiLocker, MCA, GST).",
      "Click 'e-Sign' and enter Aadhaar number.",
      "Authenticate with OTP or biometric.",
      "e-Sign ESP applies a digital signature to the PDF.",
      "Download the signed, tamper-evident PDF immediately.",
    ],
    serviceCharge: 25,
    popularity: 60,
    tags: ["esign", "aadhaar", "digital-signature", "cca", "electronic-signature"],
    online: true,
  },
  {
    id: "digilocker-account",
    slug: "digilocker-account",
    name: "DigiLocker Account",
    category: "identity-documents",
    subcategory: "Digital Services",
    summary: "Create a free DigiLocker wallet for government-issued documents.",
    description:
      "DigiLocker is a flagship digital wallet under Digital India where citizens can store government-issued documents — Aadhaar, PAN, driving licence, vehicle RC, Class 10/12 marksheets — that are legally valid under the IT Act. Account creation is free with Aadhaar-based authentication.",
    ministry: "National e-Governance Division (NeGD), MeitY",
    officialPortal: "DigiLocker",
    officialUrl: "https://www.digilocker.gov.in/",
    eligibility: ["Indian resident", "Aadhaar holder", "Mobile number linked for OTP"],
    documentsRequired: ["Aadhaar number", "Registered mobile for OTP"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Visit digilocker.gov.in or download the DigiLocker app.",
      "Sign up with mobile number and verify via OTP.",
      "Enter Aadhaar number and complete OTP / biometric authentication.",
      "Set a 6-digit security PIN for the account.",
      "Browse 'Issued Documents' to fetch documents from partner issuers (UIDAI, CBSE, MoRTH etc.).",
    ],
    serviceCharge: 25,
    popularity: 88,
    tags: ["digilocker", "digital-india", "wallet", "documents", "negd", "meity"],
    online: true,
  },
  {
    id: "bharat-bill-payment-identity",
    slug: "bharat-bill-payment-identity",
    name: "Bharat Bill Payment (BBPS) — KYC & Onboarding",
    category: "identity-documents",
    subcategory: "Digital Services",
    summary: "Onboard as a BBPS agent / customer after identity verification.",
    description:
      "Bharat Bill Payment System (BBPS), operated by NPCI, is an interoperable platform for paying utility bills (electricity, water, gas, telecom, etc.). Agents and Customer Organisations must complete NPCI-defined KYC onboarding before activation. End-customers can pay bills without KYC; agents require PAN, Aadhaar and bank verification.",
    ministry: "National Payments Corporation of India (NPCI) / RBI",
    officialPortal: "NPCI — Bharat BillPay",
    officialUrl: "https://www.npci.org.in/what-we-do/bbps/bbps-overview",
    eligibility: [
      "Indian citizen or entity",
      "PAN and Aadhaar (for individual agents)",
      "Current account for agent / biller onboarding",
    ],
    documentsRequired: [
      "PAN card",
      "Aadhaar for e-KYC",
      "Bank account proof (cancelled cheque / passbook)",
      "For entities: COI, GST, MSME / shop-establishment certificate",
    ],
    fee: 0,
    feeNote: "Free for end-customers; agent onboarding fee varies by BBPOU (₹0–₹2,500).",
    processingTime: "3–10 working days for agent onboarding",
    howToApply: [
      "Identify a BBPOU (Bill Payment Operating Unit) like BillDesk, Razorpay, Paytm.",
      "Submit the agent / biller onboarding form with KYC documents.",
      "Complete Aadhaar e-KYC and bank account verification.",
      "NPCI approves the agent code after due diligence.",
      "Receive agent credentials to operate on the BBPS network.",
    ],
    serviceCharge: 100,
    popularity: 55,
    tags: ["bbps", "npci", "bills", "kyc", "agent", "payments"],
    online: true,
  },
];
