// Tilak E-Seva Portal — Income Tax & GST services.
// Real Indian government services from Income Tax e-Filing Portal,
// GST Portal, TRACES, NSDL (Protean) and TIN.

import type { GovernmentService } from "../types";

export const incomeTaxGst: GovernmentService[] = [
  {
    id: "itr-1-sahaj-filing",
    slug: "itr-1-sahaj-filing",
    name: "ITR-1 (Sahaj) Filing",
    category: "income-tax-gst",
    subcategory: "Income Tax Return",
    summary: "File ITR-1 (Sahaj) for salaried individuals with income up to ₹50 lakh.",
    description:
      "ITR-1 Sahaj is the simplified return for resident individuals having income from salary, one house property, other sources and agricultural income up to ₹5,000. Total income must not exceed ₹50 lakh. Filing is free on the Income Tax e-Filing portal; Tilak charges only for assisted filing.",
    ministry: "Central Board of Direct Taxes (CBDT)",
    officialPortal: "Income Tax e-Filing Portal",
    officialUrl: "https://eportal.incometax.gov.in/iec/foservices/",
    eligibility: [
      "Resident individual (other than not ordinarily resident)",
      "Total income ≤ ₹50 lakh",
      "Income from salary / one house property / other sources / agricultural ≤ ₹5,000",
    ],
    documentsRequired: [
      "PAN and Aadhaar (linked)",
      "Form 16 from employer",
      "Bank interest statements / Form 16A",
      "Investment proofs (80C, 80D, etc.)",
    ],
    fee: 0,
    feeNote: "Free on the Income Tax portal; Tilak assisted charge applies separately.",
    processingTime: "Immediate acknowledgement; refund in 7–60 days",
    howToApply: [
      "Log in to eportal.incometax.gov.in with PAN and password.",
      "Go to e-File → Income Tax Return → File Income Tax Return.",
      "Select AY 2025-26 and ITR-1, then choose Online mode.",
      "Pre-fill salary, house property, other income; verify deductions.",
      "Pay self-assessment tax if due, e-Verify with Aadhaar OTP and download ITR-V.",
    ],
    serviceCharge: 199,
    popularity: 96,
    tags: ["itr", "itr-1", "sahaj", "income-tax", "salary", "return"],
    online: true,
  },
  {
    id: "itr-2-filing",
    slug: "itr-2-filing",
    name: "ITR-2 Filing",
    category: "income-tax-gst",
    subcategory: "Income Tax Return",
    summary: "File ITR-2 for individuals/HUFs with capital gains, foreign assets or business income excluded.",
    description:
      "ITR-2 is for individuals and HUFs not carrying on business or profession, but with income from capital gains, more than one house property, foreign assets or income above ₹50 lakh. It must be filed online on the Income Tax e-Filing portal within the due date to avoid penalties.",
    ministry: "Central Board of Direct Taxes (CBDT)",
    officialPortal: "Income Tax e-Filing Portal",
    officialUrl: "https://eportal.incometax.gov.in/iec/foservices/",
    eligibility: [
      "Individual or HUF",
      "No income from business or profession",
      "Has capital gains, foreign income/assets, or income > ₹50 lakh",
    ],
    documentsRequired: [
      "PAN and Aadhaar",
      "Form 16 / 16A / 26AS / AIS",
      "Capital gains statements from broker / mutual fund",
      "Foreign asset details (if any)",
    ],
    fee: 0,
    feeNote: "Free on the portal; Tilak assisted charge applies separately.",
    processingTime: "Immediate acknowledgement; refund in 7–90 days",
    howToApply: [
      "Log in to the e-Filing portal and choose File ITR → ITR-2.",
      "Import pre-filled data and review income schedules.",
      "Add capital gains (Schedule CG), house property (Schedule HP) and foreign assets (Schedule FA).",
      "Compute tax, pay self-assessment tax if any, and submit return.",
      "e-Verify via Aadhaar OTP, Net Banking or by posting signed ITR-V to CPC Bengaluru.",
    ],
    serviceCharge: 399,
    popularity: 80,
    tags: ["itr", "itr-2", "income-tax", "capital-gains", "huf", "foreign-assets"],
    online: true,
  },
  {
    id: "itr-3-filing",
    slug: "itr-3-filing",
    name: "ITR-3 Filing",
    category: "income-tax-gst",
    subcategory: "Income Tax Return",
    summary: "File ITR-3 for individuals/HUFs carrying on a business or profession.",
    description:
      "ITR-3 applies to individuals and HUFs with income from a proprietary business or profession. It requires details of profit & loss, balance sheet, and depreciation as per the Income Tax Act. Partnership firms and LLPs also file the related ITR-5.",
    ministry: "Central Board of Direct Taxes (CBDT)",
    officialPortal: "Income Tax e-Filing Portal",
    officialUrl: "https://eportal.incometax.gov.in/iec/foservices/",
    eligibility: [
      "Individual / HUF running a proprietary business or profession",
      "Has income from profession (doctor, CA, lawyer) or business",
      "Partner in a firm (with share of profit)",
    ],
    documentsRequired: [
      "PAN and Aadhaar",
      "Books of account / P&L / Balance Sheet",
      "GST returns reconciliation",
      "Form 26AS and AIS / TIS",
      "Tax audit report (if applicable under 44AB)",
    ],
    fee: 0,
    feeNote: "Free on the portal; Tilak assisted charge applies separately.",
    processingTime: "Immediate acknowledgement; refund in 30–90 days",
    howToApply: [
      "Log in to eportal.incometax.gov.in and choose ITR-3.",
      "Pre-fill personal data and import business income from books.",
      "Fill Schedules BP (business), P&L, BS, and depreciation.",
      "Upload tax audit report (3CA-3CD / 3CB-3CD) if turnover exceeds threshold.",
      "Submit, pay tax due, and e-Verify using Aadhaar OTP or DSC.",
    ],
    serviceCharge: 499,
    popularity: 75,
    tags: ["itr", "itr-3", "business", "profession", "income-tax", "tax-audit"],
    online: true,
  },
  {
    id: "itr-4-sugam-filing",
    slug: "itr-4-sugam-filing",
    name: "ITR-4 (Sugam) Filing",
    category: "income-tax-gst",
    subcategory: "Income Tax Return",
    summary: "File ITR-4 Sugam under presumptive taxation (Sections 44AD/44ADA/44AE).",
    description:
      "ITR-4 Sugam is for individuals, HUFs and partnerships (other than LLPs) opting for presumptive taxation. Under 44AD, business turnover up to ₹2 crore is taxed at 8% / 6%; under 44ADA, professional income up to ₹50 lakh is taxed at 50% of gross receipts.",
    ministry: "Central Board of Direct Taxes (CBDT)",
    officialPortal: "Income Tax e-Filing Portal",
    officialUrl: "https://eportal.incometax.gov.in/iec/foservices/",
    eligibility: [
      "Resident individual / HUF / Partnership firm (not LLP)",
      "Business turnover ≤ ₹2 crore (44AD) or professional receipts ≤ ₹50 lakh (44ADA)",
      "Aggregate interest from deposits ≤ ₹50 lakh in FY 2024-25",
    ],
    documentsRequired: [
      "PAN and Aadhaar",
      "Gross receipts / turnover summary",
      "Bank interest statements",
      "Form 26AS / AIS",
    ],
    fee: 0,
    feeNote: "Free on the portal; Tilak assisted charge applies separately.",
    processingTime: "Immediate acknowledgement; refund in 7–60 days",
    howToApply: [
      "Log in to the e-Filing portal and select ITR-4 (Sugam).",
      "Opt for presumptive scheme (44AD / 44ADA / 44AE).",
      "Enter gross receipts, deemed profit and bank interest.",
      "Confirm deductions under Chapter VI-A.",
      "Pay tax due, submit and e-Verify with Aadhaar OTP.",
    ],
    serviceCharge: 299,
    popularity: 82,
    tags: ["itr", "itr-4", "sugam", "presumptive", "44ad", "44ada"],
    online: true,
  },
  {
    id: "itr-for-nri",
    slug: "itr-for-nri",
    name: "ITR for NRI",
    category: "income-tax-gst",
    subcategory: "Income Tax Return",
    summary: "Income tax return filing for Non-Resident Indians.",
    description:
      "NRIs must file ITR-2 or ITR-3 if their Indian income exceeds the basic exemption limit (₹2.5 lakh / ₹3 lakh) or to claim TDS refunds on rental, capital gains or interest income. Special schedules capture DTAA relief, foreign currency conversion and Schedule FA.",
    ministry: "Central Board of Direct Taxes (CBDT)",
    officialPortal: "Income Tax e-Filing Portal",
    officialUrl: "https://eportal.incometax.gov.in/iec/foservices/",
    eligibility: [
      "Non-Resident Indian (NRI) as per Income Tax Act",
      "Indian income exceeds exemption limit, or",
      "Wishes to claim refund of TDS deducted in India",
    ],
    documentsRequired: [
      "PAN and Aadhaar / passport (if available)",
      "Form 26AS and AIS (Indian TDS)",
      "TRC (Tax Residency Certificate) of foreign country for DTAA",
      "Foreign bank account details for refund",
    ],
    fee: 0,
    feeNote: "Free on the portal; Tilak assisted charge applies separately.",
    processingTime: "Refund in 30–120 days for NRIs",
    howToApply: [
      "Log in with PAN; if NRI without Indian mobile, update international number first.",
      "File ITR-2 / ITR-3 based on income type.",
      "Convert foreign income to INR at SBI TT buying rate on receipt date.",
      "Claim DTAA relief with TRC and Form 10F.",
      "Submit, pay tax if any, and e-Verify via DSC or by posting signed ITR-V.",
    ],
    serviceCharge: 499,
    popularity: 65,
    tags: ["itr", "nri", "non-resident", "dtaa", "income-tax", "refund"],
    online: true,
  },
  {
    id: "income-tax-refund-status",
    slug: "income-tax-refund-status",
    name: "Income Tax Refund Status",
    category: "income-tax-gst",
    subcategory: "Refunds & Status",
    summary: "Check status of your income tax refund for any assessment year.",
    description:
      "The Income Tax Department provides a free utility to track the status of refunds — issued, in process, adjusted or failed — using PAN and the relevant Assessment Year. Refunds are credited to the bank account pre-validated on the e-Filing portal.",
    ministry: "Central Board of Direct Taxes (CBDT)",
    officialPortal: "Income Tax e-Filing — Refund Status",
    officialUrl: "https://eportal.incometax.gov.in/iec/foservices/",
    eligibility: ["PAN holder who has filed ITR for the relevant AY"],
    documentsRequired: ["PAN", "Assessment Year", "Mobile for OTP"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Log in to eportal.incometax.gov.in.",
      "Navigate to e-File → Income Tax Return → Refund Status.",
      "Select the relevant Assessment Year.",
      "View status — Refund Issued / Adjusted / In Process / Failed.",
      "If failed, pre-validate bank account and re-issue request under 'Refund Reissue Request'.",
    ],
    serviceCharge: 25,
    popularity: 90,
    tags: ["refund", "income-tax", "status", "itr", "cbd"],
    online: true,
  },
  {
    id: "advance-tax-payment",
    slug: "advance-tax-payment",
    name: "Advance Tax Payment",
    category: "income-tax-gst",
    subcategory: "Tax Payments",
    summary: "Pay advance tax in 4 instalments (15%, 45%, 75%, 100%).",
    description:
      "Advance tax is payable by individuals and businesses if estimated tax liability for the year exceeds ₹10,000 after TDS. It is paid in 4 instalments — 15% by 15 Jun, 45% by 15 Sep, 75% by 15 Dec and 100% by 15 Mar — via Challan 280 on the Income Tax Portal or NSDL.",
    ministry: "Central Board of Direct Taxes (CBDT)",
    officialPortal: "Income Tax Portal — e-Pay Tax",
    officialUrl: "https://eportal.incometax.gov.in/iec/foservices/",
    eligibility: [
      "Estimated tax liability after TDS exceeds ₹10,000 in the FY",
      "Senior citizens (60+ without business income) are exempt",
    ],
    documentsRequired: ["PAN", "Assessment Year / Financial Year", "Bank account with net-banking"],
    fee: 0,
    feeNote: "No fee; interest under Sections 234B / 234C applies on default.",
    processingTime: "Instant (challan generated immediately)",
    howToApply: [
      "Log in to eportal.incometax.gov.in → e-File → e-Pay Tax.",
      "Choose Challan 280 and select 'Advance Tax' (100).",
      "Enter PAN, AY and estimated amount.",
      "Pay via net-banking / UPI / debit card.",
      "Download Challan 280 receipt with CIN for ITR filing.",
    ],
    serviceCharge: 50,
    popularity: 78,
    tags: ["advance-tax", "challan-280", "cbd", "income-tax", "payment"],
    online: true,
  },
  {
    id: "self-assessment-tax-challan-280",
    slug: "self-assessment-tax-challan-280",
    name: "Self-Assessment Tax (Challan 280)",
    category: "income-tax-gst",
    subcategory: "Tax Payments",
    summary: "Pay self-assessment tax before filing your ITR using Challan 280.",
    description:
      "Self-assessment tax under Section 140A is the balance tax payable after accounting for TDS, TCS and advance tax, before filing the return. It is paid using Challan 280 (Code 300) on the Income Tax portal or NSDL. The challan must be quoted in the ITR.",
    ministry: "Central Board of Direct Taxes (CBDT)",
    officialPortal: "Income Tax Portal / NSDL (Protean) — e-Pay Tax",
    officialUrl: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    eligibility: [
      "PAN holder",
      "Tax due after TDS / advance tax while filing ITR",
    ],
    documentsRequired: ["PAN", "Assessment Year", "Bank account"],
    fee: 0,
    feeNote: "No fee; interest under Section 234A may apply if filed after due date.",
    processingTime: "Instant",
    howToApply: [
      "Visit eportal.incometax.gov.in → e-Pay Tax or NSDL Tax Payment.",
      "Select Challan 280 → 'Self-Assessment Tax' (300).",
      "Enter PAN, AY, address and amount.",
      "Pay via net-banking / UPI / card.",
      "Save the challan with CIN; enter its BSR + serial number in your ITR.",
    ],
    serviceCharge: 50,
    popularity: 85,
    tags: ["self-assessment-tax", "challan-280", "income-tax", "cbd", "tax-payment"],
    online: true,
  },
  {
    id: "tds-return-filing",
    slug: "tds-return-filing",
    name: "TDS Return Filing (24Q / 26Q / 27Q)",
    category: "income-tax-gst",
    subcategory: "TDS / TCS",
    summary: "File quarterly TDS returns — 24Q (salary), 26Q (non-salary), 27Q (non-resident).",
    description:
      "Deductors must file quarterly TDS returns via TRACES using RPU/FVU utility or directly on the e-Filing portal. Form 24Q covers salary TDS, 26Q covers non-salary payments to residents, and 27Q covers payments to non-residents. Late filing attracts ₹200/day fee under Section 234E.",
    ministry: "Central Board of Direct Taxes (CBDT) / TRACES",
    officialPortal: "TRACES",
    officialUrl: "https://www.tdscpc.gov.in/",
    eligibility: ["TAN holder who has deducted TDS in the quarter", "Deductor — employer, company, firm"],
    documentsRequired: [
      "TAN",
      "PAN of all deductees",
      "Challan details (BSR, serial no, amount)",
      "Section under which TDS deducted",
    ],
    fee: 0,
    feeNote: "Free on TRACES; ₹200/day late fee under Section 234E plus penalty up to ₹1 lakh.",
    processingTime: "Acknowledgement in 24 hours",
    howToApply: [
      "Download RPU/FVU from traces.e-TDS-TCS or use the e-Filing portal directly.",
      "Prepare the .txt file with deductee-wise details and challans.",
      "Validate with FVU and upload the .fvu file on TRACES / e-Filing portal.",
      "Receive provisional receipt (PRN) on acceptance.",
      "File correction returns (C1/C2/C3/C4/C5/C9) if defaults are flagged.",
    ],
    serviceCharge: 150,
    popularity: 70,
    tags: ["tds", "24q", "26q", "27q", "traces", "tan", "quarterly"],
    online: true,
  },
  {
    id: "form-16-download",
    slug: "form-16-download",
    name: "Form 16 Download",
    category: "income-tax-gst",
    subcategory: "Forms & Statements",
    summary: "Download Form 16 / 16A TDS certificate from TRACES.",
    description:
      "Form 16 is the annual TDS certificate issued by employers (Part A from TRACES + Part B from employer). Form 16A is for non-salary TDS. Deductors must download these from TRACES; deductees can view them in their AIS / Form 26AS and request copies from the deductor.",
    ministry: "Central Board of Direct Taxes (CBDT) / TRACES",
    officialPortal: "TRACES",
    officialUrl: "https://www.tdscpc.gov.in/",
    eligibility: ["Deductor with TAN", "Employee / deductee whose TDS has been deducted"],
    documentsRequired: ["TAN (deductor)", "PAN of deductee", "Quarter and financial year"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant download",
    howToApply: [
      "Log in to traces.tdscpc.gov.in as Deductor.",
      "Go to 'Downloads → Form 16 / 16A'.",
      "Search by PAN and quarter; generate request.",
      "Download the zip protected with TRACES password.",
      "Issue to deductees within 15 days of TDS return due date.",
    ],
    serviceCharge: 50,
    popularity: 88,
    tags: ["form16", "form16a", "tds", "traces", "certificate", "salary"],
    online: true,
  },
  {
    id: "form-26as-download",
    slug: "form-26as-download",
    name: "Form 26AS Download",
    category: "income-tax-gst",
    subcategory: "Forms & Statements",
    summary: "Download annual tax credit statement (Form 26AS) for your PAN.",
    description:
      "Form 26AS is the consolidated annual tax statement showing TDS/TCS, advance tax, self-assessment tax, refund and high-value transactions against a PAN. It is auto-generated from TRACES and is critical for accurate ITR filing. Download is free from the e-Filing portal.",
    ministry: "Central Board of Direct Taxes (CBDT) / TRACES",
    officialPortal: "Income Tax e-Filing / TRACES",
    officialUrl: "https://eportal.incometax.gov.in/iec/foservices/",
    eligibility: ["PAN holder with tax deducted/collected or refund"],
    documentsRequired: ["PAN", "e-Filing login", "Mobile for OTP"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant download",
    howToApply: [
      "Log in to eportal.incometax.gov.in.",
      "Go to e-File → Income Tax Forms → View Form 26AS.",
      "Confirm PAN and select the relevant AY.",
      "Choose PDF or Excel / SFT view.",
      "Open PDF (password = DOB in DDMMYYYY); reconcile with AIS before filing ITR.",
    ],
    serviceCharge: 25,
    popularity: 90,
    tags: ["26as", "tax-credit", "traces", "tds", "income-tax", "statement"],
    online: true,
  },
  {
    id: "ais-tis-download",
    slug: "ais-tis-download",
    name: "AIS / TIS Download",
    category: "income-tax-gst",
    subcategory: "Forms & Statements",
    summary: "Download Annual Information Statement & Taxpayer Information Summary.",
    description:
      "AIS (Annual Information Statement) and TIS (Taxpayer Information Summary) replaced the old Form 26AS for broader reporting — covering SFT transactions, dividends, interest, mutual fund trades, foreign remittances and TDS/TCS. Both are free to download from the e-Filing portal and feed pre-filled ITR data.",
    ministry: "Central Board of Direct Taxes (CBDT)",
    officialPortal: "Income Tax e-Filing — AIS",
    officialUrl: "https://eportal.incometax.gov.in/iec/foservices/",
    eligibility: ["PAN holder", "Registered on e-Filing portal"],
    documentsRequired: ["PAN", "e-Filing login", "Mobile for OTP"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant download",
    howToApply: [
      "Log in to eportal.incometax.gov.in.",
      "Go to Services → Annual Information Statement (AIS).",
      "Choose the relevant FY; view AIS or TIS tab.",
      "Download PDF (password = DOB in DDMMYYYY) or CSV.",
      "Submit feedback on any incorrect entry directly from AIS.",
    ],
    serviceCharge: 25,
    popularity: 85,
    tags: ["ais", "tis", "annual-information-statement", "income-tax", "sft"],
    online: true,
  },
  {
    id: "tan-registration-income-tax",
    slug: "tan-registration-income-tax",
    name: "TAN Registration (TRACES)",
    category: "income-tax-gst",
    subcategory: "TDS / TCS",
    summary: "Register TAN on TRACES and Income Tax e-Filing for TDS compliance.",
    description:
      "Once a TAN is allotted, the deductor must register it on TRACES and the Income Tax e-Filing portal to file TDS returns, download Form 16/16A, view defaults and apply for corrections. Registration requires TAN, registered mobile and the deductor's PAN.",
    ministry: "Central Board of Direct Taxes (CBDT) / TRACES",
    officialPortal: "TRACES",
    officialUrl: "https://www.tdscpc.gov.in/",
    eligibility: ["TAN holder", "Deductor (employer, firm, company)"],
    documentsRequired: ["TAN", "PAN of deductor", "Registered mobile / email"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Open traces.tdscpc.gov.in → 'Register as Deductor'.",
      "Enter TAN, PAN and captcha.",
      "Verify via OTP on registered mobile/email.",
      "Set user ID, password and security questions.",
      "Log in to file TDS returns and download certificates.",
    ],
    serviceCharge: 60,
    popularity: 60,
    tags: ["tan", "traces", "registration", "tds", "deductor"],
    online: true,
  },
  {
    id: "gst-registration-regular",
    slug: "gst-registration-regular",
    name: "GST Registration (Regular)",
    category: "income-tax-gst",
    subcategory: "GST Registration",
    summary: "Apply for Regular GSTIN for businesses crossing the turnover threshold.",
    description:
      "Regular GST registration is mandatory for businesses whose aggregate turnover exceeds ₹40 lakh (goods) / ₹20 lakh (services), or for inter-state suppliers, e-commerce operators and certain notified categories. Application is filed free on the GST Portal using Form GST REG-01.",
    ministry: "Central Board of Indirect Taxes & Customs (CBIC)",
    officialPortal: "GST Portal",
    officialUrl: "https://www.gst.gov.in/",
    eligibility: [
      "Turnover > ₹40 lakh (goods) / ₹20 lakh (services)",
      "Inter-state supplier of goods/services",
      "E-commerce operator / supplier via e-commerce",
      "Casual / non-resident taxable person",
    ],
    documentsRequired: [
      "PAN of business",
      "Aadhaar of promoters / partners",
      "Proof of business address (electricity bill, rent agreement)",
      "Bank statement / cancelled cheque",
      "Digital Signature Certificate (DSC) or e-Sign",
    ],
    fee: 0,
    feeNote: "Free on GST portal.",
    processingTime: "7 working days",
    howToApply: [
      "Go to gst.gov.in → Services → Registration → New Registration.",
      "Fill Part-A with PAN, state, business details; receive Temporary Reference Number (TRN).",
      "Log in with TRN and OTP; complete Part-B with business address, goods/services, bank details.",
      "Upload documents and digitally sign with DSC / e-Sign / EVC.",
      "Track application status; receive GSTIN and Certificate of Registration via email.",
    ],
    serviceCharge: 100,
    popularity: 92,
    tags: ["gst", "registration", "regular", "gstin", "cbic", "form-reg-01"],
    online: true,
  },
  {
    id: "gst-registration-composition",
    slug: "gst-registration-composition",
    name: "GST Registration (Composition)",
    category: "income-tax-gst",
    subcategory: "GST Registration",
    summary: "Opt for the Composition Scheme — lower tax, simpler returns.",
    description:
      "The Composition Scheme under Section 10 allows small taxpayers (turnover up to ₹1.5 crore / ₹75 lakh for services) to pay tax at a flat rate (1% for traders, 2% manufacturers, 5% restaurants) and file only GSTR-4 annually. It is optional and applied via Form GST REG-01 + Form CMP-02.",
    ministry: "Central Board of Indirect Taxes & Customs (CBIC)",
    officialPortal: "GST Portal",
    officialUrl: "https://www.gst.gov.in/",
    eligibility: [
      "Aggregate turnover ≤ ₹1.5 crore (goods) / ₹75 lakh (services or mixed)",
      "Not engaged in inter-state outward supplies",
      "Not a manufacturer of ice-cream, pan masala, tobacco",
      "Not a service provider (other than restaurant)",
    ],
    documentsRequired: [
      "PAN of business",
      "Aadhaar of proprietor",
      "Proof of business address",
      "Bank account details",
    ],
    fee: 0,
    feeNote: "Free on GST portal; tax paid quarterly via CMP-08.",
    processingTime: "7 working days",
    howToApply: [
      "Apply for regular GST registration via Form GST REG-01.",
      "After GSTIN allotment, file Form CMP-02 to opt for Composition.",
      "Declare stock details in Form ITC-03 if migrating from regular scheme.",
      "Pay tax quarterly via Form CMP-08 and file GSTR-4 annually.",
      "Cannot collect tax from customers or issue tax invoices.",
    ],
    serviceCharge: 100,
    popularity: 70,
    tags: ["gst", "composition", "composition-scheme", "cbic", "small-business"],
    online: true,
  },
  {
    id: "gstr-1-filing",
    slug: "gstr-1-filing",
    name: "GSTR-1 Filing",
    category: "income-tax-gst",
    subcategory: "GST Returns",
    summary: "File monthly / quarterly GSTR-1 — outward supplies of goods / services.",
    description:
      "GSTR-1 is the return for outward supplies — sales invoices, debit/credit notes, exports, advance receipts — filed by every regular registered taxpayer. Monthly filers (turnover > ₹5 crore) file by the 11th; QRMP scheme taxpayers file by the 13th of next month.",
    ministry: "Central Board of Indirect Taxes & Customs (CBIC)",
    officialPortal: "GST Portal",
    officialUrl: "https://www.gst.gov.in/",
    eligibility: ["Regular GST registered taxpayer", "QRMP scheme taxpayer (turnover ≤ ₹5 crore)"],
    documentsRequired: ["GSTIN", "Sales invoices / e-invoices", "HSN/SAC summary", "DSC or EVC"],
    fee: 0,
    feeNote: "Free on GST portal; late fee ₹50/day (₹20/day nil return).",
    processingTime: "Instant acknowledgement",
    howToApply: [
      "Log in to gst.gov.in → Services → Returns → Returns Dashboard.",
      "Select FY and period; open GSTR-1.",
      "Upload B2B, B2C, Export, CDNR, HSN summaries; or use JSON upload.",
      "Validate and compute liabilities; preview summary.",
      "File with DSC / EVC and download acknowledgement.",
    ],
    serviceCharge: 100,
    popularity: 88,
    tags: ["gstr-1", "gst", "outward-supplies", "returns", "cbic", "qrmp"],
    online: true,
  },
  {
    id: "gstr-3b-filing",
    slug: "gstr-3b-filing",
    name: "GSTR-3B Filing",
    category: "income-tax-gst",
    subcategory: "GST Returns",
    summary: "File monthly summary return GSTR-3B and pay net GST liability.",
    description:
      "GSTR-3B is the monthly summary return in which taxpayers declare total outward and inward supplies, claim Input Tax Credit (ITC) and pay net tax (CGST + SGST + IGST + Cess). Due date is the 20th (or 22nd/24th for QRMP). Late fee is ₹50/day (₹20/day nil return).",
    ministry: "Central Board of Indirect Taxes & Customs (CBIC)",
    officialPortal: "GST Portal",
    officialUrl: "https://www.gst.gov.in/",
    eligibility: ["Regular GST registered taxpayer", "QRMP scheme taxpayer"],
    documentsRequired: ["GSTIN", "GSTR-1 / IFF data", "ITC ledger & cash ledger", "DSC or EVC"],
    fee: 0,
    feeNote: "Free on portal; late fee ₹50/day (₹20/day for nil return).",
    processingTime: "Instant acknowledgement",
    howToApply: [
      "Log in to gst.gov.in → Returns Dashboard → GSTR-3B.",
      "Confirm auto-populated values from GSTR-2B (ITC) and GSTR-1 (output tax).",
      "Enter reverse charge, ineligible ITC and outward supplies if any.",
      "Offset liability from ITC ledger, then cash ledger for balance.",
      "File with DSC / EVC; download filed return and receipt.",
    ],
    serviceCharge: 100,
    popularity: 90,
    tags: ["gstr-3b", "gst", "monthly-return", "itc", "cbic"],
    online: true,
  },
  {
    id: "gstr-9-annual-return",
    slug: "gstr-9-annual-return",
    name: "GSTR-9 Annual Return",
    category: "income-tax-gst",
    subcategory: "GST Returns",
    summary: "File annual consolidated GSTR-9 for regular GST taxpayers.",
    description:
      "GSTR-9 is the annual return consolidating all monthly/quarterly returns of a regular taxpayer. Mandatory for taxpayers with turnover > ₹2 crore; smaller taxpayers may opt out via GSTR-9C waiver. Due date is 31 December of the following financial year.",
    ministry: "Central Board of Indirect Taxes & Customs (CBIC)",
    officialPortal: "GST Portal",
    officialUrl: "https://www.gst.gov.in/",
    eligibility: [
      "Regular GST registered taxpayer",
      "Aggregate annual turnover > ₹2 crore",
    ],
    documentsRequired: [
      "GSTIN",
      "Monthly GSTR-1 and GSTR-3B for the FY",
      "HSN summary and ITC reconciliation",
      "DSC or EVC",
    ],
    fee: 0,
    feeNote: "Free on portal; late fee capped based on turnover.",
    processingTime: "Instant acknowledgement",
    howToApply: [
      "Log in to gst.gov.in → Services → Returns → Annual Return.",
      "Select the FY and open GSTR-9.",
      "Review auto-drafted values in Parts II–VI from monthly returns.",
      "Reconcile ITC, HSN and outward supplies; enter manual adjustments if any.",
      "File with DSC / EVC; download acknowledgement.",
    ],
    serviceCharge: 150,
    popularity: 65,
    tags: ["gstr-9", "annual-return", "gst", "cbic", "reconciliation"],
    online: true,
  },
  {
    id: "gst-e-invoice",
    slug: "gst-e-invoice",
    name: "GST e-Invoice",
    category: "income-tax-gst",
    subcategory: "GST Compliance",
    summary: "Generate IRN and QR code for B2B invoices above the turnover threshold.",
    description:
      "GST e-Invoicing is mandatory for businesses with aggregate turnover > ₹5 crore (notified in stages). Taxpayers must report B2B invoices to the Invoice Registration Portal (IRP), which returns a 64-character Invoice Reference Number (IRN) and a signed QR code — without which an invoice is invalid.",
    ministry: "Central Board of Indirect Taxes & Customs (CBIC) / GSTN / NIC",
    officialPortal: "GST e-Invoice Portal (IRP)",
    officialUrl: "https://einvoice1.gst.gov.in/",
    eligibility: [
      "GST registered taxpayer with turnover > ₹5 crore (per latest threshold)",
      "Issues B2B invoices, export invoices or deemed exports",
    ],
    documentsRequired: ["GSTIN", "Invoice JSON per schema", "Digital signature (for API)"],
    fee: 0,
    feeNote: "Free on IRP portal.",
    processingTime: "Instant (IRN generated in seconds)",
    howToApply: [
      "Register on einvoice1.gst.gov.in with GSTIN and OTP.",
      "Choose mode — web, offline utility, Excel utility, or API.",
      "Upload invoice JSON; system validates with GST registry.",
      "Receive IRN, QR code and digitally signed invoice in PDF.",
      "Report to IRP within 30 days of invoice date (from 1 Nov 2023).",
    ],
    serviceCharge: 100,
    popularity: 75,
    tags: ["e-invoice", "irn", "gst", "cbic", "b2b", "qr-code"],
    online: true,
  },
  {
    id: "gst-e-way-bill",
    slug: "gst-e-way-bill",
    name: "GST e-Way Bill",
    category: "income-tax-gst",
    subcategory: "GST Compliance",
    summary: "Generate e-Way Bill for movement of goods exceeding ₹50,000 in value.",
    description:
      "An e-Way Bill is required for the movement of goods where the consignment value exceeds ₹50,000 (inter-state) and certain intra-state movements. It is generated on the NIC e-Way Bill portal using Part-A (invoice details) and Part-B (transport details) and is valid for 1 day per 200 km.",
    ministry: "Central Board of Indirect Taxes & Customs (CBIC) / NIC",
    officialPortal: "NIC e-Way Bill Portal",
    officialUrl: "https://ewaybillgst.gov.in/",
    eligibility: [
      "GST registered supplier / recipient / transporter",
      "Consignment value > ₹50,000",
    ],
    documentsRequired: ["GSTIN / Transporter ID", "Invoice / challan", "Transport mode & vehicle number"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Log in to ewaybillgst.gov.in with GSTIN.",
      "Choose 'Generate New' → fill Part A (supplier, recipient, goods, HSN, value).",
      "Fill Part B (vehicle number / transport doc) before movement begins.",
      "System generates EWB number and QR code.",
      "Share the EWB with the transporter; cancel within 24 hours if unused.",
    ],
    serviceCharge: 50,
    popularity: 80,
    tags: ["e-way-bill", "gst", "transport", "cbic", "nic", "goods-movement"],
    online: true,
  },
  {
    id: "gst-refund-application",
    slug: "gst-refund-application",
    name: "GST Refund Application",
    category: "income-tax-gst",
    subcategory: "GST Compliance",
    summary: "Claim GST refund — exports, inverted duty, excess cash, ITC accumulation.",
    description:
      "GST refunds can be claimed for export of goods/services with/without payment of tax, inverted duty structure, accumulation of ITC, excess cash in electronic cash ledger, deemed exports and for international tourists. Filed via Form RFD-01 on the GST portal within 2 years of relevant date.",
    ministry: "Central Board of Indirect Taxes & Customs (CBIC)",
    officialPortal: "GST Portal",
    officialUrl: "https://www.gst.gov.in/",
    eligibility: [
      "GST registered taxpayer",
      "Refund arises from exports / inverted duty / excess cash / ITC accumulation",
    ],
    documentsRequired: [
      "GSTIN",
      "Statement 1 / 2 / 3 as applicable",
      "Shipping bill / LUT for exports",
      "Bank account pre-validated on portal",
    ],
    fee: 0,
    feeNote: "Free on portal; interest @6% p.a. on delayed refund beyond 60 days.",
    processingTime: "15–60 days",
    howToApply: [
      "Log in to gst.gov.in → Services → Refunds → Application.",
      "Select refund type (export, inverted duty, excess balance, etc.).",
      "System auto-funds the electronic credit/cash ledger statement.",
      "Upload supporting documents; ARN is generated on submission.",
      "Track status; refund credited to validated bank account after RFD-06 / RFD-08.",
    ],
    serviceCharge: 150,
    popularity: 65,
    tags: ["gst-refund", "rfd-01", "gst", "cbic", "export", "itc"],
    online: true,
  },
  {
    id: "ldc-lower-deduction-certificate",
    slug: "ldc-lower-deduction-certificate",
    name: "LDC Lower Deduction Certificate (Form 13)",
    category: "income-tax-gst",
    subcategory: "TDS / TCS",
    summary: "Apply for lower / nil TDS deduction certificate under Section 197.",
    description:
      "A deductee can apply to the Jurisdictional Assessing Officer (JAO) via Form 13 for a Lower Deduction Certificate (LDC) under Section 197 where the regular TDS rate would cause hardship. Once granted, the deductor quotes the certificate number to deduct TDS at the lower / nil rate specified.",
    ministry: "Central Board of Direct Taxes (CBDT)",
    officialPortal: "Income Tax e-Filing — Form 13",
    officialUrl: "https://eportal.incometax.gov.in/iec/foservices/",
    eligibility: [
      "PAN holder receiving contract / professional / interest / commission payments",
      "Estimated total income below taxable limit, or lower rate justified",
    ],
    documentsRequired: [
      "PAN, latest ITR and computation",
      "Project / contract details and TDS projected",
      "Bank statements, balance sheet",
      "Audit report if applicable",
    ],
    fee: 0,
    feeNote: "Free on portal; certificate validity specified by JAO.",
    processingTime: "30–90 days",
    howToApply: [
      "Log in to eportal.incometax.gov.in → e-File → Income Tax Forms → Form 13.",
      "Select section (197 / 206C(9)) and the relevant deductor type.",
      "Fill deductor details, nature of payment and projected income/TDS.",
      "Upload supporting documents and submit to JAO.",
      "On approval, certificate number is auto-shared with TRACES; deductor quotes it in TDS return.",
    ],
    serviceCharge: 150,
    popularity: 55,
    tags: ["ldc", "form13", "section197", "tds", "lower-deduction", "income-tax"],
    online: true,
  },
];
