import type { GovernmentService } from "../types";

export const landProperty: GovernmentService[] = [
  {
    id: "land-records-search",
    slug: "land-records-search",
    name: "Land Records Search (Bhulekh)",
    category: "land-property",
    subcategory: "Land Records",
    summary: "View and download digital land records (Khasra, Khatauni, Jamabandi) online.",
    description:
      "The Digital India Land Records Modernization Programme (DILRMP) computerised land records across states. Citizens can access Khasra, Khatauni, Jamabandi, mutation status and property cards online through the state Bhulekh portal.",
    ministry: "Department of Land Resources (State Revenue Departments)",
    officialPortal: "Bhulekh State Portals",
    officialUrl: "https://bhulekh.gov.in/",
    eligibility: ["Any citizen", "Landowner or authorised person for certified copies"],
    documentsRequired: ["Khasra / survey number", "Name of the owner", "District, tehsil, village details"],
    fee: 0,
    feeNote: "Viewing is free; certified copy charges vary by state (₹10–₹50 per page).",
    processingTime: "Instant (online view)",
    howToApply: [
      "Visit your state's Bhulekh portal (e.g. upbhulekh.gov.in, bhulekh.mahabhumi.gov.in).",
      "Select district, tehsil and village.",
      "Enter Khasra number or owner name to search records.",
      "View the record online or download a digital copy.",
      "For certified copy, apply at the tehsildar office or state e-district portal.",
    ],
    serviceCharge: 40,
    popularity: 80,
    tags: ["bhulekh", "land records", "khasra", "khatauni", "jamabandi"],
    online: true,
  },
  {
    id: "property-mutation-dakhil-kharij",
    slug: "property-mutation-dakhil-kharij",
    name: "Property Mutation (Dakhil Kharij)",
    category: "land-property",
    subcategory: "Mutation",
    summary: "Transfer ownership of property in revenue records after sale, gift or inheritance.",
    description:
      "Mutation or Dakhil Kharij is the process of updating revenue records when ownership changes due to sale, gift, will, inheritance or court decree. After verification by the Revenue Officer (Tehsildar/Patwari), the new owner's name is reflected in the Khatauni and Khasra.",
    ministry: "State Revenue Departments",
    officialPortal: "State e-District / Revenue Portals",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: ["New owner after registered sale deed / gift / inheritance", "Legal heir with succession documents"],
    documentsRequired: [
      "Registered sale deed / gift deed / will",
      "Original title deed",
      "Latest Khatauni / Jamabandi",
      "Aadhaar card of applicant",
      "Indemnity bond and affidavit",
    ],
    fee: 100,
    feeNote: "Mutation fee varies by state — typically ₹100–₹500; copying charges extra.",
    processingTime: "15–45 days",
    howToApply: [
      "Visit the state e-District or Revenue department portal.",
      "Login and select 'Mutation (Dakhil Kharij)' service.",
      "Fill mutation application with Khasra / plot details.",
      "Upload registered deed, Khatauni, Aadhaar and affidavit.",
      "Pay mutation fee and note the application number.",
      "Patwari/Tehsildar verifies and publishes notice; mutation entry is made after objection period.",
    ],
    serviceCharge: 90,
    popularity: 75,
    tags: ["dakhil kharij", "mutation", "land transfer", "revenue records"],
    online: true,
  },
  {
    id: "property-registration",
    slug: "property-registration",
    name: "Property Registration (Sale Deed)",
    category: "land-property",
    subcategory: "Registration",
    summary: "Register sale deed, gift deed, lease or mortgage at the Sub-Registrar office.",
    description:
      "Registration of immovable property transfer is mandatory under the Registration Act, 1908. The deed is executed before the Sub-Registrar of Assurances after paying stamp duty and registration charges, and an encumbrance check is done before the transaction.",
    ministry: "State Registration & Stamps Department (Inspector General of Registration)",
    officialPortal: "State IGR Portals",
    officialUrl: "https://igrs.gov.in/",
    eligibility: ["Buyer and seller of immovable property", "Must be of sound mind and competent to contract"],
    documentsRequired: [
      "Previous sale deed / title document",
      "Encumbrance Certificate (recent)",
      "Property tax paid receipts",
      "Aadhaar & PAN of both parties",
      "e-Stamp / challan for stamp duty",
      "NOC from society / authority if applicable",
    ],
    fee: 30000,
    feeNote:
      "Stamp duty 4–8% of property value (state-wise) + 1% registration fee. Example shown is approximate for a mid-value property.",
    processingTime: "Same day (after appointment)",
    howToApply: [
      "Login to the state IGR portal and create a deed draft.",
      "Determine stamp duty and registration fee via the online calculator.",
      "Purchase e-Stamp from SHCIL (shcilestamp.com) for the stamp value.",
      "Book an appointment at the Sub-Registrar office (SRO).",
      "Both parties visit SRO with originals for biometric verification and execution.",
      "Receive the registered deed and indexed copy the same or next working day.",
    ],
    serviceCharge: 150,
    popularity: 78,
    tags: ["property registration", "sale deed", "sub registrar", "stamp duty"],
    online: true,
  },
  {
    id: "encumbrance-certificate",
    slug: "encumbrance-certificate",
    name: "Encumbrance Certificate (EC)",
    category: "land-property",
    subcategory: "Certificates",
    summary: "Obtain EC certifying that a property is free from any monetary or legal liability.",
    description:
      "An Encumbrance Certificate (EC) is issued by the Sub-Registrar showing all transactions registered against a property for a specified period. It is mandatory for selling property, obtaining loans, and verifying clear title before purchase.",
    ministry: "State Registration & Stamps Department",
    officialPortal: "State IGR Portals",
    officialUrl: "https://igrs.gov.in/",
    eligibility: ["Any property owner or authorised buyer", "Property must be registered in the SRO records"],
    documentsRequired: [
      "Copy of sale deed / title document",
      "Property address and survey number",
      "Aadhaar of applicant",
      "Period for which EC is required",
    ],
    fee: 100,
    feeNote: "Search fee per year approx. ₹20–₹100; certified EC ₹100–₹500 depending on state.",
    processingTime: "2–7 working days",
    howToApply: [
      "Open the state IGR portal (e.g. registration.ihm_kel.com, igrsodisha.gov.in).",
      "Choose 'Encumbrance Certificate' service.",
      "Enter SRO, document number, period and property details.",
      "Pay search + certificate fee online.",
      "Download digitally signed EC after officer approval.",
    ],
    serviceCharge: 60,
    popularity: 70,
    tags: ["encumbrance certificate", "ec", "title search", "property"],
    online: true,
  },
  {
    id: "property-card-urban",
    slug: "property-card-urban",
    name: "Property Card (Urban)",
    category: "land-property",
    subcategory: "Land Records",
    summary: "View and download the urban property card showing ownership and area details.",
    description:
      "A Property Card is the official record of ownership for urban properties, issued by the city survey office / revenue department under DILRMP. It contains the property number, area, owner name and mutation history, and is accepted as proof of title in urban areas.",
    ministry: "State Revenue / City Survey Department",
    officialPortal: "DILRMP / State City Survey Portals",
    officialUrl: "https://dilrmp.gov.in/",
    eligibility: ["Owner of urban property", "Authorised legal heir"],
    documentsRequired: ["Property number / survey number", "Owner name", "Old property card (if any)"],
    fee: 50,
    feeNote: "Free view; certified property card ₹50–₹200 based on state.",
    processingTime: "Instant (view) / 3–7 days (certified)",
    howToApply: [
      "Visit the state property card portal (e.g. mumbai city survey portal).",
      "Select city, ward and property / CTS number.",
      "Verify owner name and view the property card.",
      "Apply for a certified copy if required and pay the fee.",
      "Collect certified copy from the City Survey Office.",
    ],
    serviceCharge: 50,
    popularity: 55,
    tags: ["property card", "urban", "city survey", "ownership"],
    online: true,
  },
  {
    id: "khata-khatauni-download",
    slug: "khata-khatauni-download",
    name: "Khata / Khatauni Download",
    category: "land-property",
    subcategory: "Land Records",
    summary: "Download Khatauni showing all owners of a plot as per revenue records.",
    description:
      "Khatauni is the register of all persons recorded as owners or cultivators of a particular plot. Maintained by the Patwari and computerised on Bhulekh portals, it lists Khasra numbers, owners and their shares, and is the primary proof of ownership for agricultural land.",
    ministry: "State Revenue Departments",
    officialPortal: "Bhulekh State Portals",
    officialUrl: "https://bhulekh.gov.in/",
    eligibility: ["Any citizen for view", "Landowner for certified copy"],
    documentsRequired: ["Khasra / Khata number", "District, tehsil, village", "Owner name"],
    fee: 15,
    feeNote: "Online download is free; certified copy ₹15–₹50 per page.",
    processingTime: "Instant (download)",
    howToApply: [
      "Open the state Bhulekh portal.",
      "Select district, tehsil and village.",
      "Choose Khata / Khatauni option.",
      "Enter Khata number or owner name.",
      "View and download the digital Khatauni copy.",
    ],
    serviceCharge: 35,
    popularity: 65,
    tags: ["khata", "khatauni", "bhulekh", "land records"],
    online: true,
  },
  {
    id: "khasra-details",
    slug: "khasra-details",
    name: "Khasra Details",
    category: "land-property",
    subcategory: "Land Records",
    summary: "View plot-wise Khasra details including area, ownership and crop information.",
    description:
      "Khasra is the plot-wise record maintained by the Patwari at the village level. It contains field number, area, land type, ownership shares and crops sown, and forms the basis of the Khatauni. Khasra details are now available online for most states under DILRMP.",
    ministry: "State Revenue Departments",
    officialPortal: "Bhulekh State Portals",
    officialUrl: "https://bhulekh.gov.in/",
    eligibility: ["Any citizen", "Landowner for certified copy"],
    documentsRequired: ["Khasra / survey number", "Village name", "Tehsil & district"],
    fee: 0,
    feeNote: "Viewing is free; certified copy ₹15–₹50.",
    processingTime: "Instant",
    howToApply: [
      "Visit the state Bhulekh portal.",
      "Select district, tehsil and village.",
      "Choose Khasra search option.",
      "Enter Khasra number or owner name.",
      "View and download the Khasra record.",
    ],
    serviceCharge: 35,
    popularity: 60,
    tags: ["khasra", "plot details", "bhulekh", "land records"],
    online: true,
  },
  {
    id: "jamabandi-fard",
    slug: "jamabandi-fard",
    name: "Jamabandi (Fard)",
    category: "land-property",
    subcategory: "Land Records",
    summary: "Get the Jamabandi (record of rights) / Fard for any plot in Punjab, Haryana & Rajasthan.",
    description:
      "Jamabandi is the Record of Rights (ROR) prepared every five years by the Patwari, showing ownership, cultivation and tenancy details. Also called Fard in parts of North India, it is the most authentic document of title for agricultural land in these states.",
    ministry: "State Revenue Departments (Punjab, Haryana, Rajasthan, HP)",
    officialPortal: "Jamabandi / State Revenue Portals",
    officialUrl: "https://jamabandi.nic.in/",
    eligibility: ["Any citizen for view", "Landowner or authorised person for certified copy"],
    documentsRequired: ["Khasra / Khewat number", "Village, tehsil, district", "Owner name"],
    fee: 50,
    feeNote: "View free; certified Nakal ₹30–₹100.",
    processingTime: "Instant (online) / 2–5 days (certified)",
    howToApply: [
      "Visit jamabandi.nic.in or the relevant state portal.",
      "Select district, tehsil and village.",
      "Enter Khewat / Khasra / owner name.",
      "View the Jamabandi online.",
      "Apply for certified Nakal at the Patwari / Tehsil office if needed.",
    ],
    serviceCharge: 40,
    popularity: 58,
    tags: ["jamabandi", "fard", "record of rights", "ror", "punjab", "haryana"],
    online: true,
  },
  {
    id: "mutation-status-check",
    slug: "mutation-status-check",
    name: "Mutation Status Check",
    category: "land-property",
    subcategory: "Mutation",
    summary: "Track the status of a pending land mutation (Dakhil Kharij) application.",
    description:
      "Citizens who have applied for mutation of land can check the current status — pending, verified, rejected or completed — online. The mutation register entry, patwari report and tehsildar order are tracked through the state revenue portal or e-District application.",
    ministry: "State Revenue Departments",
    officialPortal: "State e-District / Revenue Portals",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: ["Applicant who filed mutation", "Authorised representative with application ID"],
    documentsRequired: ["Mutation application number", "Aadhaar of applicant"],
    fee: 0,
    feeNote: "Free online status check.",
    processingTime: "Instant",
    howToApply: [
      "Open the state e-District / Revenue portal.",
      "Click 'Mutation Status' or 'Track Application'.",
      "Enter application number and captcha.",
      "View current stage: patwari report, tehsildar order, pending objection, completed.",
      "Download acknowledgement or order as applicable.",
    ],
    serviceCharge: 25,
    popularity: 55,
    tags: ["mutation status", "dakhil kharij status", "track application"],
    online: true,
  },
  {
    id: "bhu-naksha-cadastral-map",
    slug: "bhu-naksha-cadastral-map",
    name: "Bhu Naksha (Cadastral Map)",
    category: "land-property",
    subcategory: "Land Records",
    summary: "View and download the cadastral map (Bhu Naksha) of any village plot.",
    description:
      "Bhu Naksha is the digital cadastral map of village land parcels showing plot boundaries, Khasra numbers and areas. Maintained by the National Informatics Centre under DILRMP, it integrates with Bhulekh records and is used to verify boundaries and prevent encroachment.",
    ministry: "Department of Land Resources (NIC)",
    officialPortal: "Bhu Naksha",
    officialUrl: "https://bhunaksha.gov.in/",
    eligibility: ["Any citizen", "Landowner for certified print"],
    documentsRequired: ["Khasra number", "Village name", "District and tehsil"],
    fee: 0,
    feeNote: "Free online view and PDF download.",
    processingTime: "Instant",
    howToApply: [
      "Open bhunaksha.gov.in and select the state.",
      "Choose district, tehsil and village.",
      "Click on the plot or search by Khasra number.",
      "View plot boundary, area and adjoining parcels.",
      "Download the Bhu Naksha PDF or screenshot.",
    ],
    serviceCharge: 35,
    popularity: 50,
    tags: ["bhu naksha", "cadastral map", "plot map", "land map"],
    online: true,
  },
  {
    id: "property-tax-payment-urban",
    slug: "property-tax-payment-urban",
    name: "Property Tax Payment (Urban)",
    category: "land-property",
    subcategory: "Tax & Civic",
    summary: "Pay annual property / house tax to the municipal corporation online.",
    description:
      "Urban local bodies levy property tax on residential, commercial and industrial properties based on capital value, annual rental value or unit area method. Most municipal corporations now accept online payment through their citizen portals and issue digital receipts.",
    ministry: "Urban Local Bodies / Municipal Corporations",
    officialPortal: "Municipal Citizen Portals",
    officialUrl: "https://mohua.gov.in/",
    eligibility: ["Owner of urban property", "Tenant only where tax is contractually transferred"],
    documentsRequired: ["Property ID / Khata number", "Owner name and address", "Previous receipt (optional)"],
    fee: 5000,
    feeNote: "Tax amount varies widely by city, area, usage & built-up area; example shown is illustrative.",
    processingTime: "Instant (receipt)",
    howToApply: [
      "Visit the municipal corporation portal (e.g. mcdonline.nic.in, bbmp.gov.in, mybmc portal).",
      "Select 'Property Tax' and enter Property ID / Khata number.",
      "Verify owner and property details auto-fetched.",
      "Choose financial year and mode (annual / half-yearly).",
      "Compute tax, pay online and download the receipt.",
    ],
    serviceCharge: 50,
    popularity: 72,
    tags: ["property tax", "house tax", "municipal", "urban"],
    online: true,
  },
  {
    id: "building-plan-approval",
    slug: "building-plan-approval",
    name: "Building Plan Approval",
    category: "land-property",
    subcategory: "Approvals",
    summary: "Apply for sanction of building plan from the municipal authority.",
    description:
      "Construction of any building requires prior sanction of the building plan from the local municipal authority / development authority under the applicable building bye-laws. The Single Window / Online Building Permission System (OBPS) enables auto-DCR scrutiny and time-bound approvals in most cities.",
    ministry: "Urban Local Bodies / Development Authorities",
    officialPortal: "Municipal OBPS Portals",
    officialUrl: "https://mohua.gov.in/",
    eligibility: ["Landowner or licensed developer / architect", "Plot must have clear title & valid land use"],
    documentsRequired: [
      "Title document / sale deed",
      "Latest tax paid receipt",
      "Boundaries & dimensions of plot",
      "Architectural drawings (architect stamped)",
      "Structural stability certificate",
      "NOC from fire / airport / others if applicable",
    ],
    fee: 25000,
    feeNote: "Scrutiny fee ₹15–₹75 per sq.m + processing fee; example shown for a mid-size residential building.",
    processingTime: "15–30 days (auto-DCR states)",
    howToApply: [
      "Register on the municipal OBPS portal.",
      "Upload plot documents and apply for scrutiny.",
      "Submit architectural drawings in the prescribed XML / PDF format.",
      "Auto-DCR scrutinises drawings against building bye-laws.",
      "Pay scrutiny & sanction fee online.",
      "Receive sanctioned plan & building permission letter.",
    ],
    serviceCharge: 150,
    popularity: 48,
    tags: ["building plan", "approval", "obps", "municipal", "construction"],
    online: true,
  },
  {
    id: "occupancy-certificate",
    slug: "occupancy-certificate",
    name: "Occupancy Certificate",
    category: "land-property",
    subcategory: "Approvals",
    summary: "Obtain Occupancy Certificate (OC) confirming building completion as per sanctioned plan.",
    description:
      "An Occupancy Certificate is issued by the local authority after construction is complete and inspected, confirming that the building complies with the sanctioned plan and is fit for occupation. It is mandatory for obtaining water, electricity and sewerage connections and for resale.",
    ministry: "Urban Local Bodies / Development Authorities",
    officialPortal: "Municipal Citizen Portals",
    officialUrl: "https://mohua.gov.in/",
    eligibility: ["Builder / owner with sanctioned building plan", "Construction completed as per plan"],
    documentsRequired: [
      "Building permission / sanctioned plan",
      "Completion report by architect / engineer",
      "Photographs of completed building",
      "Property tax paid receipt",
      "Fire NOC (if applicable)",
    ],
    fee: 1000,
    feeNote: "OC fee ₹500–₹5,000 depending on municipality and built-up area.",
    processingTime: "15–30 days",
    howToApply: [
      "Login to the municipal portal and choose 'Occupancy Certificate'.",
      "Upload sanctioned plan and completion report.",
      "Schedule inspection by the municipal engineer.",
      "Pay OC fee online.",
      "Receive digitally signed Occupancy Certificate after inspection.",
    ],
    serviceCharge: 100,
    popularity: 42,
    tags: ["occupancy certificate", "oc", "completion", "building"],
    online: true,
  },
  {
    id: "land-use-conversion",
    slug: "land-use-conversion",
    name: "Land Use Conversion",
    category: "land-property",
    subcategory: "Approvals",
    summary: "Convert agricultural land to non-agricultural (residential / commercial) use.",
    description:
      "Change of land use from agricultural to non-agricultural requires prior permission from the competent revenue authority under state land revenue laws. The application must demonstrate that the proposed use conforms to the master plan and pay conversion charges based on the market value.",
    ministry: "State Revenue / Town Planning Departments",
    officialPortal: "State Revenue Portals",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: ["Landowner with clear title", "Proposed use must conform to local master plan / zoning"],
    documentsRequired: [
      "Title deed / mutation extract",
      "Latest Khatauni / Khata",
      "Property tax paid receipt",
      "Master plan / zoning extract",
      "Site plan and proposed use",
    ],
    fee: 20000,
    feeNote: "Conversion charge per sq.m varies by zone and market value; example shown for a typical plot.",
    processingTime: "30–90 days",
    howToApply: [
      "Apply on the state revenue / town planning portal.",
      "Attach title deed, Khatauni and site plan.",
      "Pay conversion charges and scrutiny fee.",
      "Field inspection by Revenue Officer / Town Planner.",
      "Receive conversion order; thereafter mutation with new use is recorded.",
    ],
    serviceCharge: 150,
    popularity: 40,
    tags: ["land use conversion", "agricultural to non agricultural", "conversion", "revenue"],
    online: true,
  },
  {
    id: "mutation-municipal-records",
    slug: "mutation-municipal-records",
    name: "Mutation in Municipal Records",
    category: "land-property",
    subcategory: "Mutation",
    summary: "Update ownership in municipal / property tax records after sale or inheritance.",
    description:
      "Mutation in municipal records updates the name of the owner in the property tax register of the urban local body. This is independent of revenue mutation and is required to receive future property tax bills, water connections and other municipal services in the new owner's name.",
    ministry: "Urban Local Bodies",
    officialPortal: "Municipal Citizen Portals",
    officialUrl: "https://mohua.gov.in/",
    eligibility: ["New owner after registered transfer", "Legal heir with succession documents"],
    documentsRequired: [
      "Registered sale deed / gift deed / will",
      "Previous property tax receipt",
      "Aadhaar & PAN of applicant",
      "NOC from society if applicable",
    ],
    fee: 200,
    feeNote: "Mutation fee ₹100–₹500 depending on municipality.",
    processingTime: "7–30 days",
    howToApply: [
      "Login to the municipal citizen portal.",
      "Choose 'Mutation of Property Records' / 'Name Transfer'.",
      "Enter property ID and owner details.",
      "Upload registered deed and supporting documents.",
      "Pay mutation fee and track application status.",
    ],
    serviceCharge: 70,
    popularity: 60,
    tags: ["municipal mutation", "name transfer", "property tax records"],
    online: true,
  },
  {
    id: "e-stamp-payment",
    slug: "e-stamp-payment",
    name: "Stamp Duty Payment (e-Stamp)",
    category: "land-property",
    subcategory: "Stamp & Registration",
    summary: "Purchase e-Stamp paper online for agreements, affidavits and property registration.",
    description:
      "e-Stamp is a computerised stamp paper issued by Stock Holding Corporation of India (SHCIL) under the Central Record Keeping Agency (CRA) of the government. It is a secure, tamper-proof alternative to physical stamp paper and is mandatory for many high-value transactions in most states.",
    ministry: "State Registration & Stamps Department (SHCIL as CRA)",
    officialPortal: "SHCIL e-Stamping",
    officialUrl: "https://www.shcilestamp.com/",
    eligibility: ["Any citizen / organisation requiring stamp paper", "Authorised agents for bulk stamping"],
    documentsRequired: ["Purpose of stamping", "Parties' details", "Transaction value"],
    fee: 100,
    feeNote: "Stamp value depends on the transaction type and state Schedule of Stamp Duties.",
    processingTime: "Instant (digital) / same day (printed)",
    howToApply: [
      "Visit shcilestamp.com and select 'Buy e-Stamp'.",
      "Choose state and stamp duty article / purpose.",
      "Fill parties' details and stamp value.",
      "Pay online via net banking / UPI / card.",
      "Download the e-Stamp certificate with unique CRC / QR code.",
    ],
    serviceCharge: 50,
    popularity: 65,
    tags: ["e-stamp", "stamp duty", "shcil", "stamp paper"],
    online: true,
  },
  {
    id: "property-valuation",
    slug: "property-valuation",
    name: "Property Valuation (Guideline Value)",
    category: "land-property",
    subcategory: "Valuation",
    summary: "Check the guideline / circle rate of any property for stamp duty computation.",
    description:
      "The State Registration & Stamps Department publishes guideline (circle) values for every survey number / street, which form the minimum value for stamp duty and registration charges. Citizens can search the value online before executing a deed to estimate the duty payable.",
    ministry: "State Registration & Stamps Department",
    officialPortal: "State IGR Valuation Portals",
    officialUrl: "https://igrs.gov.in/",
    eligibility: ["Any citizen", "Property buyer or seller"],
    documentsRequired: ["Survey / plot number or street name", "Village / municipal ward"],
    fee: 0,
    feeNote: "Free online guideline value search.",
    processingTime: "Instant",
    howToApply: [
      "Visit the state IGR / Registration portal.",
      "Open 'Guideline Value' / 'Market Value' search.",
      "Enter district, SRO, village / street and survey number.",
      "View per sq.yard / sq.m guideline value.",
      "Use the stamp duty calculator to compute payable duty.",
    ],
    serviceCharge: 30,
    popularity: 58,
    tags: ["property valuation", "guideline value", "circle rate", "stamp duty"],
    online: true,
  },
  {
    id: "land-mutation-rural-agricultural",
    slug: "land-mutation-rural-agricultural",
    name: "Land Mutation (Rural Agricultural)",
    category: "land-property",
    subcategory: "Mutation",
    summary: "Mutate rural agricultural land in revenue records after purchase or inheritance.",
    description:
      "Mutation of rural agricultural land is carried out by the Patwari and sanctioned by the Tehsildar / Revenue Officer under state land revenue laws. The process updates the Khatauni and Khasra to reflect the new cultivator / owner, which is essential for availing PM-KISAN, crop loans and agricultural subsidies.",
    ministry: "State Revenue Departments",
    officialPortal: "State Revenue / e-District Portals",
    officialUrl: "https://edistrict.gov.in/",
    eligibility: [
      "Purchaser / donee of agricultural land",
      "Legal heir of deceased landowner",
      "Co-operative society member with allotted land",
    ],
    documentsRequired: [
      "Registered sale deed / gift deed / partition deed",
      "Original Khatauni / Jamabandi",
      "Death certificate (for inheritance mutation)",
      "Legal heir / succession certificate",
      "Aadhaar of applicant",
      "Affidavit & indemnity bond",
    ],
    fee: 200,
    feeNote: "Mutation fee ₹50–₹500 depending on state; copying and publication charges extra.",
    processingTime: "30–60 days",
    howToApply: [
      "Apply at the Patwari office or state e-District portal.",
      "Submit mutation application (Form 6 / P-6) with Khasra details.",
      "Attach registered deed, Khatauni and affidavit.",
      "Patwari issues notice to adjoining landowners for objections.",
      "After verification, Tehsildar passes the mutation order.",
      "Updated Khatauni is generated on Bhulekh with new owner entry.",
    ],
    serviceCharge: 100,
    popularity: 67,
    tags: ["rural mutation", "agricultural land", "patwari", "tehsildar", "dakhil kharij"],
    online: true,
  },
];
