import type { GovernmentService } from "../types";

export const pensions: GovernmentService[] = [
  {
    id: "ignoaps-old-age-pension",
    slug: "ignoaps-old-age-pension",
    name: "IGNOAPS Old Age Pension Application",
    category: "pensions",
    subcategory: "National Social Assistance",
    summary: "Monthly pension for BPL persons aged 60 years and above.",
    description:
      "The Indira Gandhi National Old Age Pension Scheme (IGNOAPS) is a non-contributory pension under the National Social Assistance Programme (NSAP) of the Ministry of Rural Development. It provides a monthly central pension of ₹200 to BPL persons aged 60-79 years, with most states adding a top-up that takes the total pension to ₹500-₹2,000 depending on the state.",
    ministry: "Ministry of Rural Development (NSAP Division)",
    officialPortal: "NSAP — National Social Assistance Programme",
    officialUrl: "https://nsap.nic.in/",
    eligibility: [
      "Indian citizen, age 60 years or above",
      "Belongs to a Below Poverty Line (BPL) household as per BPL survey",
      "Name appears in the BPL list prepared by the state",
      "Not receiving any other pension from Central/State government",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Age proof (Voter ID, birth certificate, PAN, or school certificate)",
      "BPL ration card / BPL certificate",
      "Bank or post office passbook copy (DBT enabled)",
      "Residence proof",
      "Recent passport-size photograph",
    ],
    fee: 0,
    feeNote: "Free. Pension is credited directly to the bank/post office account via DBT.",
    processingTime: "30-60 days after submission and Gram Sabha verification",
    howToApply: [
      "Collect the IGNOAPS application form from the Gram Panchayat / Municipality office or download from the state social welfare portal.",
      "Fill in applicant details, BPL ration card number, Aadhaar, and bank account particulars.",
      "Attach age proof, BPL certificate, residence proof and bank passbook copy.",
      "Submit to the BDO / Municipal Commissioner; the application is verified at the Gram Panchayat level.",
      "On approval by the District Level Sanctioning Committee, pension is sanctioned and credited monthly via DBT.",
    ],
    serviceCharge: 75,
    popularity: 76,
    tags: ["pension", "old age", "nsap", "bpl", "senior citizen", "dbt"],
    online: false,
  },
  {
    id: "ignoaps-80-plus-enhanced-pension",
    slug: "ignoaps-80-plus-enhanced-pension",
    name: "IGNOAPS Enhanced Pension (80+ Years)",
    category: "pensions",
    subcategory: "National Social Assistance",
    summary: "Enhanced central pension of ₹500/month for BPL beneficiaries aged 80 years and above.",
    description:
      "Under IGNOAPS, beneficiaries who complete 80 years of age receive an enhanced central pension of ₹500 per month (up from the standard ₹200). The state top-up continues to apply on top of the enhanced central share, so the total monthly pension can be significantly higher in states like Delhi, Haryana, Andhra Pradesh and Telangana.",
    ministry: "Ministry of Rural Development (NSAP Division)",
    officialPortal: "NSAP — National Social Assistance Programme",
    officialUrl: "https://nsap.nic.in/",
    eligibility: [
      "Existing IGNOAPS beneficiary completing 80 years of age",
      "Or new BPL applicant aged 80+ years",
      "Continues to be on the BPL list",
      "Aadhaar seeded with bank account for DBT",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Age proof establishing 80+ years (Voter ID, birth certificate, PAN)",
      "Existing IGNOAPS sanction order (if already a beneficiary)",
      "Bank passbook copy",
      "BPL ration card",
      "Medical/age affirmation if no documentary proof",
    ],
    fee: 0,
    feeNote: "Free. Enhanced ₹500 central share is auto-upgraded on age verification.",
    processingTime: "30-45 days after age verification",
    howToApply: [
      "Approach the Gram Panchayat / Municipality office with age proof of 80+ years.",
      "Submit a written request for enhancement of pension citing completion of 80 years.",
      "Attach Aadhaar, age proof, existing sanction order and bank passbook.",
      "The BDO / Municipal Commissioner verifies age and forwards to the District Level Sanctioning Committee.",
      "On approval, the central share is revised to ₹500/month and credited along with the state top-up via DBT.",
    ],
    serviceCharge: 60,
    popularity: 65,
    tags: ["pension", "old age", "nsap", "80 plus", "enhanced pension", "bpl"],
    online: false,
  },
  {
    id: "state-old-age-pension-application",
    slug: "state-old-age-pension-application",
    name: "State Old Age Pension Scheme Application",
    category: "pensions",
    subcategory: "State Pension Schemes",
    summary: "Generic application for state-specific old age pension schemes run by Social Welfare Departments.",
    description:
      "Most Indian states run their own old age pension schemes (e.g. Delhi LAadli, Haryana Old Age Samman Allowance, Tamil Nadu Dr. Muthulakshmi Reddy Maternity Benefit, West Bengal Old Age Pension, Andhra Pradesh YSR Pension Kanuka). The eligibility age varies (55-65 years), income criteria apply, and the pension amount ranges from ₹500 to ₹2,500/month. Beneficiaries receive the union IGNOAPS share plus the state top-up through a single application in most states.",
    ministry: "State Department of Social Welfare / Women & Child Development",
    officialPortal: "State Social Welfare / e-District portal",
    officialUrl: "https://socialjustice.delhi.gov.in/old-age-pension",
    eligibility: [
      "State resident, age as per state scheme (typically 55-65 years)",
      "Annual family income within state-prescribed limit (usually ₹1,00,000 or below)",
      "Not receiving any other pension from Central/State government",
      "Aadhaar and bank account mandatory",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Age proof (Voter ID, PAN, birth certificate)",
      "Residence proof of the state",
      "Income certificate / affidavit",
      "Bank passbook copy",
      "Recent photograph",
    ],
    fee: 0,
    feeNote: "Free to apply. Pension credited via DBT to bank/post office account.",
    processingTime: "45-90 days from submission",
    howToApply: [
      "Visit the state e-District portal or Social Welfare Department office to access the old age pension form.",
      "Register on the state portal using mobile number and Aadhaar OTP.",
      "Fill the application with personal, income, and bank details.",
      "Upload documents and submit; an acknowledgment with application ID is generated.",
      "Field verification by Social Welfare Officer; sanction by District Officer; first pension credited within 90 days.",
    ],
    serviceCharge: 90,
    popularity: 72,
    tags: ["pension", "old age", "state scheme", "social welfare", "dbt"],
    online: true,
  },
  {
    id: "ignwps-widow-pension",
    slug: "ignwps-widow-pension",
    name: "Indira Gandhi National Widow Pension Scheme (IGNWPS)",
    category: "pensions",
    subcategory: "National Social Assistance",
    summary: "Monthly pension of ₹300 for BPL widows aged 40-79 years.",
    description:
      "IGNWPS is a component of the National Social Assistance Programme providing a monthly central pension of ₹300 to widows from BPL families aged between 40 and 79 years. States add their own top-up, taking the total pension to ₹500-₹2,000 in many states. On reaching 80 years, the beneficiary is migrated to IGNOAPS enhanced pension.",
    ministry: "Ministry of Rural Development (NSAP Division)",
    officialPortal: "NSAP — National Social Assistance Programme",
    officialUrl: "https://nsap.nic.in/",
    eligibility: [
      "Widow woman aged 40-79 years",
      "Belongs to a BPL household",
      "Not remarried",
      "Not receiving any other pension from Central/State government",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Age proof (Voter ID, birth certificate, PAN)",
      "Death certificate of husband",
      "BPL ration card / BPL certificate",
      "Bank passbook copy",
      "Residence proof",
    ],
    fee: 0,
    feeNote: "Free. Pension credited via DBT to bank/post office account.",
    processingTime: "30-60 days after verification",
    howToApply: [
      "Collect the IGNWPS application form from the Gram Panchayat / Municipality office.",
      "Fill in personal details, husband's death particulars and bank account info.",
      "Attach Aadhaar, husband's death certificate, age proof and BPL ration card.",
      "Submit to the BDO / Municipal Commissioner; field verification is conducted by the Panchayat.",
      "On approval by the District Level Sanctioning Committee, ₹300 central share + state top-up is credited monthly.",
    ],
    serviceCharge: 75,
    popularity: 70,
    tags: ["pension", "widow", "nsap", "bpl", "women", "dbt"],
    online: false,
  },
  {
    id: "igndps-disability-pension",
    slug: "igndps-disability-pension",
    name: "Indira Gandhi National Disability Pension Scheme (IGNDPS)",
    category: "pensions",
    subcategory: "National Social Assistance",
    summary: "Monthly pension of ₹300 for BPL persons with severe (80%) disability aged 18-79 years.",
    description:
      "IGNDPS under the National Social Assistance Programme grants a central pension of ₹300 per month to persons with severe (80% or more) disability from BPL families, aged 18 to 79 years. Many states top up this amount. Eligibility requires a valid disability certificate issued by a Medical Board.",
    ministry: "Ministry of Rural Development (NSAP Division)",
    officialPortal: "NSAP — National Social Assistance Programme",
    officialUrl: "https://nsap.nic.in/",
    eligibility: [
      "Person with severe disability (80% or more)",
      "Age between 18 and 79 years",
      "Belongs to a BPL household",
      "Disability certificate from a Medical Board",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Disability certificate (80% or more) from Medical Board",
      "Age proof",
      "BPL ration card / BPL certificate",
      "Bank passbook copy",
      "Two recent photographs",
    ],
    fee: 0,
    feeNote: "Free. Pension credited via DBT.",
    processingTime: "45-60 days after medical verification",
    howToApply: [
      "Obtain a Medical Board disability certificate showing 80% or more disability.",
      "Collect the IGNDPS application form from the Gram Panchayat / Municipality / Social Welfare office.",
      "Attach disability certificate, Aadhaar, age proof, BPL certificate and bank passbook.",
      "Submit to BDO / Municipal Commissioner; the Medical Board certificate is verified.",
      "Sanction by District Level Sanctioning Committee; pension of ₹300 + state top-up credited monthly via DBT.",
    ],
    serviceCharge: 80,
    popularity: 64,
    tags: ["pension", "disability", "nsap", "bpl", "divyang", "dbt"],
    online: false,
  },
  {
    id: "nfbs-family-benefit-scheme",
    slug: "nfbs-family-benefit-scheme",
    name: "National Family Benefit Scheme (NFBS)",
    category: "pensions",
    subcategory: "National Social Assistance",
    summary: "One-time lump sum of ₹20,000 to BPL families on the death of the primary breadwinner (18-60 yrs).",
    description:
      "NFBS under NSAP provides a one-time lump sum assistance of ₹20,000 to a BPL household on the death of the primary breadwinner (aged 18-59 years). The 'primary breadwinner' means the member whose earnings contributed the largest share to the family's total income. The assistance is credited directly to the beneficiary's bank account through DBT.",
    ministry: "Ministry of Rural Development (NSAP Division)",
    officialPortal: "NSAP — National Social Assistance Programme",
    officialUrl: "https://nsap.nic.in/",
    eligibility: [
      "Death of primary breadwinner aged 18-59 years",
      "Family belongs to a BPL household",
      "Death occurred due to natural or unnatural causes",
      "Application within 2 years of death (state-specific extension may apply)",
    ],
    documentsRequired: [
      "Death certificate of the primary breadwinner",
      "Proof of age (18-59 years) of deceased",
      "BPL ration card / BPL certificate",
      "Aadhaar of the applicant family member",
      "Bank passbook copy of applicant",
      "Income proof of the deceased showing primary breadwinner status",
    ],
    fee: 0,
    feeNote: "Free. ₹20,000 lump sum credited via DBT.",
    processingTime: "30-45 days after verification",
    howToApply: [
      "Approach the Gram Panchayat / Municipality office within 2 years of the death.",
      "Fill the NFBS application form with deceased's details and applicant's bank info.",
      "Attach death certificate, age proof of deceased, BPL certificate and Aadhaar.",
      "Submit to BDO / Municipal Commissioner; field verification done at Panchayat level.",
      "On approval by the District Level Sanctioning Committee, ₹20,000 is credited via DBT.",
    ],
    serviceCharge: 100,
    popularity: 60,
    tags: ["pension", "nfbs", "lump sum", "bpl", "death benefit", "dbt"],
    online: false,
  },
  {
    id: "annapurna-scheme-application",
    slug: "annapurna-scheme-application",
    name: "Annapurna Scheme Application (Food Grains for Senior Citizens)",
    category: "pensions",
    subcategory: "National Social Assistance",
    summary: "10 kg of food grains per month free to senior citizens not covered under IGNOAPS.",
    description:
      "The Annapurna Scheme under NSAP provides 10 kg of food grains (wheat/rice) free of cost per month to indigent senior citizens (65+ years) who are eligible for IGNOAPS but have been left out due to the BPL cap. Beneficiaries receive food grains through the Public Distribution System (PDS) fair price shop. The scheme has now been subsumed under the National Food Security Act (NFSA) in most states.",
    ministry: "Ministry of Rural Development (NSAP Division)",
    officialPortal: "NSAP — National Social Assistance Programme",
    officialUrl: "https://nsap.nic.in/",
    eligibility: [
      "Senior citizen aged 65 years or above",
      "Eligible for IGNOAPS but not receiving pension due to BPL cap",
      "No regular family support",
      "Not covered under NFSA Antyodaya / Priority Household category",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Age proof (65+ years)",
      "BPL certificate / eligibility certificate",
      "Ration card",
      "Bank passbook copy",
      "Recent photograph",
    ],
    fee: 0,
    feeNote: "Free. 10 kg food grains per month provided through PDS.",
    processingTime: "30-45 days after verification",
    howToApply: [
      "Approach the Gram Panchayat / Municipality office with age proof and BPL certificate.",
      "Fill the Annapurna Scheme application form.",
      "Attach Aadhaar, age proof (65+), BPL certificate and ration card.",
      "Submit to BDO / Municipal Commissioner; verification by Panchayat.",
      "On approval, beneficiaries are linked to the nearest PDS fair price shop for monthly grain collection.",
    ],
    serviceCharge: 60,
    popularity: 55,
    tags: ["pension", "annapurna", "food security", "senior citizen", "pds", "bpl"],
    online: false,
  },
  {
    id: "eps-95-pension-scheme",
    slug: "eps-95-pension-scheme",
    name: "EPS-95 Pension (Employees' Pension Scheme 1995)",
    category: "pensions",
    subcategory: "EPS Pension",
    summary: "Lifelong monthly pension for EPF members on superannuation at age 58 with 10+ years of service.",
    description:
      "The Employees' Pension Scheme (EPS) 1995, administered by the Employees' Provident Fund Organisation (EPFO), provides a lifelong monthly pension to EPF members who retire on superannuation at 58 years with at least 10 years of pensionable service. The pension is calculated on the pensionable salary and service, and the member's UAN must be KYC-compliant for claim processing.",
    ministry: "Ministry of Labour & Employment (EPFO)",
    officialPortal: "EPFO — Employees' Provident Fund Organisation",
    officialUrl: "https://www.epfindia.gov.in/",
    eligibility: [
      "EPF member with at least 10 years of pensionable service",
      "Attained 58 years of age (superannuation)",
      "UAN active and KYC-seeded",
      "Not availed EPS early pension (Form 10D) earlier",
    ],
    documentsRequired: [
      "UAN (Universal Account Number)",
      "Aadhaar card",
      "PAN card",
      "Bank passbook copy (savings account)",
      "Cancelled cheque with name printed",
      "Form 10D (Pension Claim Form)",
      "Service certificate from employer (if required)",
    ],
    fee: 0,
    feeNote: "No application fee. Pension is funded from employer contributions to EPS.",
    processingTime: "20-30 days from claim submission",
    howToApply: [
      "Activate UAN on the EPFO member portal and complete KYC (Aadhaar, PAN, bank).",
      "Download Composite Claim Form (Aadhaar) or use Form 10D for pension.",
      "Fill in pension details, bank account and nominee particulars.",
      "Submit the form online via the EPFO member portal or to the employer for offline attestation.",
      "EPFO Field Office processes the claim; pension is credited monthly to the bank account from the date of sanction.",
    ],
    serviceCharge: 110,
    popularity: 78,
    tags: ["pension", "eps-95", "epfo", "superannuation", "labour", "retirement"],
    online: true,
  },
  {
    id: "eps-early-pension-claim",
    slug: "eps-early-pension-claim",
    name: "EPS Early Pension (Before 58 Years)",
    category: "pensions",
    subcategory: "EPS Pension",
    summary: "Reduced monthly pension for EPF members who retire between 50 and 58 years of age.",
    description:
      "Under EPS 1995, a member who has completed 10 years of pensionable service may withdraw monthly pension earlier than the superannuation age of 58, between 50 and 58 years. The pension amount is reduced at 4% for every year short of 58. The member must not be in service at the time of claim.",
    ministry: "Ministry of Labour & Employment (EPFO)",
    officialPortal: "EPFO — Employees' Provident Fund Organisation",
    officialUrl: "https://www.epfindia.gov.in/",
    eligibility: [
      "EPF member with 10+ years of pensionable service",
      "Age between 50 and 58 years",
      "Not in employment at the time of application",
      "UAN active with KYC completed",
    ],
    documentsRequired: [
      "UAN",
      "Aadhaar card",
      "PAN card",
      "Bank passbook copy",
      "Cancelled cheque",
      "Form 10D",
      "Age proof",
    ],
    fee: 0,
    feeNote: "No application fee. 4% reduction per year of early withdrawal.",
    processingTime: "20-30 days",
    howToApply: [
      "Login to the EPFO member portal with UAN and password.",
      "Ensure KYC (Aadhaar, PAN, bank) is approved and seeded.",
      "File Form 10D online selecting 'Early Pension' option.",
      "Aadhaar-based OTP e-sign the form; system auto-fetches service history.",
      "EPFO Field Office verifies and sanctions the reduced pension; monthly credit begins post-sanction.",
    ],
    serviceCharge: 100,
    popularity: 70,
    tags: ["pension", "eps", "epfo", "early pension", "labour", "retirement"],
    online: true,
  },
  {
    id: "eps-widow-pension-claim",
    slug: "eps-widow-pension-claim",
    name: "EPS Widow / Widow(er) Pension (Form 10D)",
    category: "pensions",
    subcategory: "EPS Pension",
    summary: "Monthly pension to the surviving spouse of a deceased EPF member.",
    description:
      "Under EPS 1995, on the death of an EPF member who was in pensionable service or already drawing an EPS pension, the surviving spouse is entitled to a monthly widow/widower pension. The pension amount depends on the member's pensionable salary and service. Children receive an additional pension until age 25, and a nominee receives a lump sum if no family member survives.",
    ministry: "Ministry of Labour & Employment (EPFO)",
    officialPortal: "EPFO — Employees' Provident Fund Organisation",
    officialUrl: "https://www.epfindia.gov.in/",
    eligibility: [
      "Spouse of a deceased EPF member",
      "Member was in pensionable service or already drawing EPS pension",
      "Member had completed at least 1 month of service (death while in service)",
      "Widow(er) has not remarried",
    ],
    documentsRequired: [
      "Death certificate of the EPF member",
      "UAN of the deceased member",
      "Aadhaar of the widow(er)",
      "Marriage certificate / proof of relationship",
      "Bank passbook copy of widow(er)",
      "Form 10D (Death Case)",
      "Joint photograph of family members",
    ],
    fee: 0,
    feeNote: "No application fee. Pension credited monthly via DBT.",
    processingTime: "20-30 days",
    howToApply: [
      "Collect Form 10D (Death Case) from EPFO office or download from the member portal.",
      "Fill widow(er) details, deceased member's UAN/PF number and bank account.",
      "Attach death certificate, Aadhaar of widow(er), marriage proof and bank passbook.",
      "Submit to the employer for attestation or directly to the EPFO Field Office.",
      "EPFO verifies and sanctions the widow pension; monthly pension + children pension (if applicable) is credited.",
    ],
    serviceCharge: 110,
    popularity: 68,
    tags: ["pension", "eps", "epfo", "widow pension", "death benefit", "labour"],
    online: true,
  },
  {
    id: "eps-children-pension-claim",
    slug: "eps-children-pension-claim",
    name: "EPS Children Pension (Form 10D)",
    category: "pensions",
    subcategory: "EPS Pension",
    summary: "Monthly pension for up to two children of a deceased EPF member, payable till age 25.",
    description:
      "Under EPS 1995, on the death of an EPF member, children of the deceased receive a monthly pension equal to 25% of the widow's pension, payable to a maximum of two children at a time. The pension continues until each child turns 25. If there is no surviving widow, children receive 75% of the original pension amount.",
    ministry: "Ministry of Labour & Employment (EPFO)",
    officialPortal: "EPFO — Employees' Provident Fund Organisation",
    officialUrl: "https://www.epfindia.gov.in/",
    eligibility: [
      "Child of a deceased EPF member (natural or adopted)",
      "Age below 25 years",
      "Member was eligible for EPS pension or in pensionable service at time of death",
      "Maximum two children at a time receive the pension",
    ],
    documentsRequired: [
      "Birth certificate of the child",
      "Death certificate of EPF member",
      "Aadhaar of child (or guardian if minor)",
      "UAN / PF number of deceased member",
      "Form 10D (Death Case)",
      "Bank account details (joint with guardian if child is minor)",
    ],
    fee: 0,
    feeNote: "No application fee. 25% of widow's pension per child, max two children.",
    processingTime: "20-30 days",
    howToApply: [
      "Submit Form 10D (Death Case) along with the widow pension application.",
      "Provide birth certificates of children claiming pension.",
      "Attach Aadhaar of each child, guardian's Aadhaar (if minor), and bank details.",
      "Submit to employer or EPFO Field Office for verification.",
      "EPFO sanctions children pension; credited monthly till each child turns 25 or marries (whichever earlier).",
    ],
    serviceCharge: 100,
    popularity: 55,
    tags: ["pension", "eps", "epfo", "children pension", "death benefit", "labour"],
    online: true,
  },
  {
    id: "nps-tier-1-account-opening",
    slug: "nps-tier-1-account-opening",
    name: "NPS Tier-I Account Opening (All Citizens)",
    category: "pensions",
    subcategory: "National Pension System",
    summary: "Open a National Pension System Tier-I retirement account with ₹500 minimum contribution.",
    description:
      "The National Pension System (NPS) is a voluntary, defined-contribution retirement savings scheme regulated by the Pension Fund Regulatory and Development Authority (PFRDA). The Tier-I account is the primary pension account with lock-in till age 60, offering tax deduction under Section 80CCE up to ₹1.5 lakh and an additional ₹50,000 under Section 80CCD(1B). Any Indian citizen aged 18-65 years can open an account online via eNPS.",
    ministry: "Ministry of Finance (PFRDA)",
    officialPortal: "eNPS — National Pension System (All Citizens Model)",
    officialUrl: "https://enps.ndml.in/",
    eligibility: [
      "Indian citizen, age 18-65 years",
      "Possess Aadhaar and PAN",
      "Mobile number linked to Aadhaar for OTP",
      "Bank account for auto-debit of contribution",
    ],
    documentsRequired: [
      "Aadhaar card",
      "PAN card",
      "Mobile number linked to Aadhaar",
      "Scanned photograph and signature (auto-fetched from Aadhaar)",
      "Bank account details",
      "Cancelled cheque",
    ],
    fee: 0,
    feeNote: "₹500 minimum initial contribution. Intermediary charges ~₹300-₹400.",
    processingTime: "Instant PRAN generation on online completion",
    howToApply: [
      "Visit the eNPS portal (enps.ndml.in) and click 'Open your NPS Account'.",
      "Select 'Tier I' account type and choose between Aadhaar-based or PAN-based registration.",
      "Enter Aadhaar/PAN, generate OTP and verify personal details auto-fetched from UIDAI/NSDL.",
      "Select Pension Fund Manager (PFM) and asset allocation (Equity, Corporate Bonds, Government Securities).",
      "Pay ₹500 minimum contribution online; PRAN is generated instantly and sent to registered email/mobile.",
    ],
    serviceCharge: 100,
    popularity: 75,
    tags: ["pension", "nps", "pfrda", "retirement", "tax saving", "tier-1"],
    online: true,
  },
  {
    id: "nps-tier-2-account-opening",
    slug: "nps-tier-2-account-opening",
    name: "NPS Tier-II Account Opening",
    category: "pensions",
    subcategory: "National Pension System",
    summary: "Voluntary, withdrawable investment account linked to an existing NPS Tier-I account.",
    description:
      "The NPS Tier-II account is an optional, voluntary savings account that can be opened only if the subscriber already has an active Tier-I account. It offers flexible withdrawal without lock-in, lower fund management charges, and Central Government employees get tax deduction under Section 80C. The minimum initial contribution is ₹1,000 and the minimum per contribution is ₹250.",
    ministry: "Ministry of Finance (PFRDA)",
    officialPortal: "eNPS — National Pension System",
    officialUrl: "https://enps.ndml.in/",
    eligibility: [
      "Existing NPS Tier-I subscriber with active PRAN",
      "KYC verified with Aadhaar/PAN",
      "Indian citizen",
    ],
    documentsRequired: [
      "Active PRAN (Permanent Retirement Account Number)",
      "Aadhaar card",
      "PAN card",
      "Bank account details",
      "IPIN/TPIN credentials for NPS portal",
    ],
    fee: 0,
    feeNote: "₹1,000 minimum initial contribution; ₹250 per subsequent contribution.",
    processingTime: "Same-day activation on contribution payment",
    howToApply: [
      "Login to eNPS portal with PRAN and password.",
      "Select 'Tier-II Account Activation' from the menu.",
      "Confirm personal details, FATCA declaration and bank account.",
      "Choose the same or different Pension Fund Manager and asset allocation as Tier-I.",
      "Pay ₹1,000 initial contribution online; Tier-II is activated within 24 hours.",
    ],
    serviceCharge: 80,
    popularity: 60,
    tags: ["pension", "nps", "pfrda", "investment", "tier-2", "voluntary"],
    online: true,
  },
  {
    id: "nps-partial-withdrawal",
    slug: "nps-partial-withdrawal",
    name: "NPS Partial Withdrawal (Tier-I)",
    category: "pensions",
    subcategory: "National Pension System",
    summary: "Withdraw up to 25% of own contributions for specified needs like illness, higher education or home purchase.",
    description:
      "NPS Tier-I subscribers can make up to three partial withdrawals during the entire tenure, each not exceeding 25% of the subscriber's own contributions (excluding returns/government contribution). Permitted grounds include specified illnesses, children's higher education/marriage, and purchase/construction of a residential house. The withdrawal is allowed only after the subscriber has been in NPS for at least 3 years.",
    ministry: "Ministry of Finance (PFRDA)",
    officialPortal: "NPS Trust",
    officialUrl: "https://www.npstrust.org.in/",
    eligibility: [
      "Active NPS Tier-I subscriber for at least 3 years",
      "Withdrawal ground: specified illness / children's education or marriage / first house purchase",
      "Maximum 3 withdrawals in entire NPS tenure",
      "Cumulative withdrawal ≤ 25% of subscriber's own contributions",
    ],
    documentsRequired: [
      "PRAN and password",
      "Aadhaar card",
      "Bank passbook copy",
      "Supporting documents (medical certificate / admission proof / marriage card / house purchase docs)",
      "Self-declaration of the withdrawal ground",
    ],
    fee: 0,
    feeNote: "Free to apply. Pops/CRA may charge nominal processing fee (~₹125).",
    processingTime: "5-10 working days",
    howToApply: [
      "Login to the NPS CRA portal (Kfintech or NSDL) with PRAN and password.",
      "Navigate to 'Partial Withdrawal' under the Transaction menu.",
      "Select the withdrawal ground and enter the amount (≤25% of own contributions).",
      "Upload supporting documents and self-declaration.",
      "Authenticate with OTP; the amount is credited to the bank account within 5-10 working days.",
    ],
    serviceCharge: 90,
    popularity: 62,
    tags: ["pension", "nps", "pfrda", "withdrawal", "tier-1"],
    online: true,
  },
  {
    id: "nps-exit-superannuation",
    slug: "nps-exit-superannuation",
    name: "NPS Exit & Superannuation Withdrawal",
    category: "pensions",
    subcategory: "National Pension System",
    summary: "Exit from NPS at age 60 with 60% lump sum withdrawal and 40% annuity purchase.",
    description:
      "On attaining 60 years of age, an NPS subscriber can exit the scheme by withdrawing up to 60% of the corpus as a lump sum (tax-free) and using at least 40% to purchase an annuity from a PFRDA-empanelled Annuity Service Provider (ASP). The annuity provides a lifelong monthly pension. Subscribers may continue in NPS till age 75 if they wish.",
    ministry: "Ministry of Finance (PFRDA)",
    officialPortal: "NPS Trust",
    officialUrl: "https://www.npstrust.org.in/",
    eligibility: [
      "NPS subscriber attaining 60 years of age",
      "PRAN active and KYC complete",
      "Minimum corpus of ₹5 lakh (lower corpus: 100% lump sum allowed)",
      "Submit exit request online or through POP",
    ],
    documentsRequired: [
      "PRAN and password",
      "Aadhaar card",
      "PAN card",
      "Bank passbook copy",
      "Cancelled cheque",
      "Annuity Service Provider (ASP) selection form",
      "KYC re-verification documents",
    ],
    fee: 0,
    feeNote: "CRA processing fee ~₹125 + POP charges as applicable.",
    processingTime: "10-20 working days",
    howToApply: [
      "Login to the CRA portal with PRAN and navigate to 'Exit Request'.",
      "Fill the online Exit Form selecting 60% lump sum + 40% annuity (or continue till age 75).",
      "Choose the Annuity Service Provider (ASP) and annuity variant (lifetime / return of purchase price).",
      "Upload KYC, bank passbook and cancelled cheque; OTP-authenticate the request.",
      "Lump sum is credited to bank account within 10-20 days; ASP begins monthly annuity thereafter.",
    ],
    serviceCharge: 130,
    popularity: 68,
    tags: ["pension", "nps", "pfrda", "exit", "superannuation", "annuity", "retirement"],
    online: true,
  },
  {
    id: "apy-account-statement-pran-details",
    slug: "apy-account-statement-pran-details",
    name: "Atal Pension Yojana (APY) Account Statement & PRAN Details",
    category: "pensions",
    subcategory: "National Pension System",
    summary: "View APY PRAN status, contribution statement and scheme details online.",
    description:
      "Atal Pension Yojana (APY) is a guaranteed pension scheme for unorganised sector workers, regulated by PFRDA. Each subscriber has a PRAN (Permanent Retirement Account Number). Subscribers can view their PRAN status, transaction statement, default charges and scheme progress through the NPS Lite / APY portal or by approaching the bank/post office where the account was opened.",
    ministry: "Ministry of Finance (PFRDA)",
    officialPortal: "NPS Lite / Atal Pension Yojana",
    officialUrl: "https://www.npstrust.org.in/atal-pension-yojana",
    eligibility: [
      "Existing APY subscriber with active PRAN",
      "Bank/post office account through which APY was opened",
      "Aadhaar-linked mobile number for OTP",
    ],
    documentsRequired: [
      "PRAN",
      "Aadhaar card",
      "Bank account details",
      "Registered mobile number",
    ],
    fee: 0,
    feeNote: "Free to view. Statement can be downloaded as PDF.",
    processingTime: "Instant access online",
    howToApply: [
      "Visit the NPS Trust APY portal or the bank's internet banking APY section.",
      "Enter PRAN and Aadhaar-linked mobile number; verify with OTP.",
      "Select 'Transaction Statement' or 'PRAN Details' from the menu.",
      "Choose the statement period and download as PDF.",
      "For correction in PRAN/bank details, approach the home branch or POP-SP with KYC documents.",
    ],
    serviceCharge: 50,
    popularity: 70,
    tags: ["pension", "apy", "pfrda", "pran", "statement", "unorganised sector"],
    online: true,
  },
  {
    id: "defence-family-pension",
    slug: "defence-family-pension",
    name: "Defence Family Pension (Next of Kin)",
    category: "pensions",
    subcategory: "Defence Pensions",
    summary: "Lifelong pension to the next of kin of a deceased defence pensioner / serving personnel.",
    description:
      "Under the Liberalised Family Pension rules administered by the Principal Controller of Defence Accounts (Pensions) [PCDA(P)], the surviving spouse and dependent family members of a deceased defence pensioner or serving personnel are entitled to a family pension. The pension is enhanced to 30% of last reckonerable emoluments in case of death in action/harness. Children receive pension until age 25 (or marriage for daughters).",
    ministry: "Ministry of Defence (PCDA Pensions)",
    officialPortal: "PCDA (Pension) — Defence Pension",
    officialUrl: "https://pcdapension.nic.in/",
    eligibility: [
      "Spouse of a deceased defence pensioner / serving personnel",
      "Unmarried daughters below 25 years (or disabled son/daughter for life)",
      "Dependent parents in case of unmarried personnel",
      "Death attributable to service or non-attributable (different rates)",
    ],
    documentsRequired: [
      "Death certificate of the defence personnel",
      "Service Record / Part II Order",
      "PPO (Pension Payment Order) of the deceased",
      "Aadhaar of the claimant",
      "Marriage certificate / proof of relationship",
      "Bank passbook copy",
      "Undertaking of dependency / non-remarriage",
    ],
    fee: 0,
    feeNote: "Free. Pension credited via DPDO / bank / treasury.",
    processingTime: "60-180 days from submission of complete claim",
    howToApply: [
      "Collect the Family Pension claim form (Form 10 / Defence Form) from PCDA(P) portal or Record Office.",
      "Fill in service details of deceased, claimant's particulars and bank account.",
      "Attach death certificate, PPO, marriage proof, Aadhaar of claimant and bank passbook.",
      "Submit through the Record Office / Regimental Centre for verification and forwarding to PCDA(P).",
      "On sanction, a fresh PPO is issued and pension is credited monthly via DPDO / SPARSH / bank.",
    ],
    serviceCharge: 130,
    popularity: 60,
    tags: ["pension", "defence", "family pension", "ex-servicemen", "pcda", "nok"],
    online: true,
  },
  {
    id: "ex-servicemen-special-pension",
    slug: "ex-servicemen-special-pension",
    name: "Ex-Servicemen Special Pension (Service / Disability)",
    category: "pensions",
    subcategory: "Defence Pensions",
    summary: "Pension for ex-servicemen with qualifying service or special/disability category.",
    description:
      "Ex-servicemen with the requisite qualifying service (15 years for PBOR, 20 years for officers) are eligible for service pension. Special pensions are granted for war-disabled, gallantry award winners and reservists. The pension is administered by PCDA(Pensions) and now paid through the SPARSH portal (System for Pension Administration - Raksha). Personnel invalided out on medical grounds receive disability pension.",
    ministry: "Ministry of Defence (PCDA Pensions)",
    officialPortal: "PCDA (Pension) — Defence Pension / SPARSH",
    officialUrl: "https://pcdapension.nic.in/",
    eligibility: [
      "Ex-serviceman with qualifying service (15 yrs PBOR / 20 yrs officers)",
      "Or invalided out on medical grounds (disability attributable to service)",
      "Gallantry award winners receive additional pension for life",
      "Reservists with qualifying embodied service",
    ],
    documentsRequired: [
      "Service Record / Discharge Book",
      "PPO (Pension Payment Order)",
      "Aadhaar card",
      "Bank passbook copy",
      "Disability medical board proceedings (if applicable)",
      "Gallantry award citation (if applicable)",
    ],
    fee: 0,
    feeNote: "Free. Pension credited via SPARSH / bank / DPDO.",
    processingTime: "60-180 days from claim submission",
    howToApply: [
      "Register on the SPARSH portal (sparsh.defencepension.gov.in) using PAN/Aadhaar.",
      "Submit the pension claim through the Record Office / Zila Sainik Board.",
      "Attach Discharge Book, PPO, medical board proceedings (if disability) and bank passbook.",
      "PCDA(P) verifies service records and sanctions the pension.",
      "Pension is credited monthly via SPARSH to the bank account; life certificate to be submitted annually.",
    ],
    serviceCharge: 140,
    popularity: 58,
    tags: ["pension", "ex-servicemen", "defence", "sparsh", "disability pension"],
    online: true,
  },
  {
    id: "defence-disability-pension",
    slug: "defence-disability-pension",
    name: "Defence Disability Pension",
    category: "pensions",
    subcategory: "Defence Pensions",
    summary: "Disability pension for defence personnel invalided out on medical grounds.",
    description:
      "Defence personnel who are invalided out of service on medical grounds due to a disability attributable to or aggravated by service are eligible for disability pension. It has two components — a service element (for those with ≥10 years qualifying service) and a disability element (calculated on the percentage of disability, with broad-bandings for 100%, 75%, 50% etc.). War injury pension is granted separately for battle casualties.",
    ministry: "Ministry of Defence (PCDA Pensions)",
    officialPortal: "PCDA (Pension) — Defence Pension",
    officialUrl: "https://pcdapension.nic.in/",
    eligibility: [
      "Defence personnel invalided out of service on medical grounds",
      "Disability assessed at 20% or more (attributable to / aggravated by service)",
      "Medical Board proceedings confirm attributability",
      "War injury pension for battle casualties with any disability %",
    ],
    documentsRequired: [
      "Invaliding Medical Board proceedings",
      "Service Record / Discharge Book",
      "PPO and Disability Pension Sanction letter",
      "Aadhaar card",
      "Bank passbook copy",
      "PAN card",
    ],
    fee: 0,
    feeNote: "Free. Pension credited via SPARSH / DPDO / bank.",
    processingTime: "90-180 days from sanction",
    howToApply: [
      "Obtain the Invaliding Medical Board proceedings and confirmation of attributability.",
      "Submit the disability pension claim through the Record Office / AHQ / Naval HQ / Air HQ.",
      "Attach Discharge Book, medical board proceedings, Aadhaar, PAN and bank passbook.",
      "PCDA(P) verifies the claim and issues a Disability PPO.",
      "Pension is credited monthly via SPARSH; periodic re-medical-boarding as required.",
    ],
    serviceCharge: 140,
    popularity: 52,
    tags: ["pension", "defence", "disability", "ex-servicemen", "sparsh", "war injury"],
    online: true,
  },
  {
    id: "state-govt-employee-pension-sanction",
    slug: "state-govt-employee-pension-sanction",
    name: "State Government Employee Pension Sanction",
    category: "pensions",
    subcategory: "State Government Pensions",
    summary: "Service pension sanction for retiring state government employees with 20+ years of qualifying service.",
    description:
      "State government employees retiring on superannuation (typically at 60 years) with at least 20 years of qualifying service are eligible for service pension calculated on the basis of last drawn pay and qualifying service. The pension is sanctioned by the Accountant General / State Pension Wing and credited via the State Treasury or designated banks. Family pension follows on the death of the pensioner.",
    ministry: "State Finance Department / Accountant General",
    officialPortal: "State AG / Treasury Portal",
    officialUrl: "https://agae.cag.gov.in/",
    eligibility: [
      "State government employee completing qualifying service of 20+ years",
      "Or retiring on superannuation at the state's prescribed age",
      "Departmental disciplinary proceedings, if any, concluded",
      "Service Book verified and up to date",
    ],
    documentsRequired: [
      "Service Book (verified and updated)",
      "Last Pay Certificate (LPC)",
      "PAN card",
      "Aadhaar card",
      "Bank passbook copy",
      "Form 7-Pension (Service Pension) / Form 8 (Family Pension)",
      "Nomination form for Death-cum-Retirement Gratuity (DCRG)",
    ],
    fee: 0,
    feeNote: "Free. Pension + gratuity credited via State Treasury / bank.",
    processingTime: "30-90 days before/after retirement",
    howToApply: [
      "Submit pension papers (Form 7-Pension, Form 8, LPC) to the Drawing & Disbursing Officer (DDO) at least 6 months before retirement.",
      "Ensure Service Book is updated with all service periods, leave, and increments.",
      "Attach PAN, Aadhaar, bank passbook and nomination for DCRG.",
      "DDO forwards to AG Office / State Pension Wing for verification and sanction.",
      "On sanction, Pension Payment Order (PPO) is issued and pension is credited monthly via Treasury/bank.",
    ],
    serviceCharge: 130,
    popularity: 64,
    tags: ["pension", "state government", "retirement", "ppo", "treasury", "service pension"],
    online: false,
  },
];
