// Tilak E-Seva Portal — Police & Law services catalog.
// Real Indian Government police, citizen-safety, and traffic services.
// Reference portals: state police portals (delhipolice.gov.in, mahapolice.gov.in),
// cybercrime.gov.in, parivahan challan, women/child/senior helplines.

import type { GovernmentService } from "../types";

export const policeLaw: GovernmentService[] = [
  {
    id: "online-fir-filing",
    slug: "online-fir-filing",
    name: "Online FIR Filing",
    category: "police-law",
    subcategory: "FIR & Reports",
    summary: "File a First Information Report (FIR) online for cognizable offences.",
    description:
      "Many state police departments now accept online First Information Reports (FIRs) for cognizable offences such as theft, snatching, and motor vehicle accidents. The complaint is electronically transmitted to the relevant police station and a copy with the FIR number is provided to the complainant.",
    ministry: "Ministry of Home Affairs (State Police)",
    officialPortal: "State Police Portal",
    officialUrl: "https://delhipolice.gov.in/",
    eligibility: [
      "Victim or witness of a cognizable offence",
      "Resident of a state that offers online FIR (most states do)",
    ],
    documentsRequired: [
      "Aadhaar / ID proof of complainant",
      "Mobile number and email",
      "Supporting evidence (photos, documents)",
      "Witness details (if any)",
    ],
    fee: 0,
    feeNote: "Free of cost; no fee for filing an FIR.",
    processingTime: "FIR registered immediately; investigation per law",
    howToApply: [
      "Visit your state police portal (e.g. delhipolice.gov.in).",
      "Register with mobile number and Aadhaar OTP.",
      "Open 'File FIR / e-FIR' and select offence category.",
      "Fill incident details, time, place, and suspect info.",
      "Upload evidence; submit; FIR number and copy emailed.",
    ],
    serviceCharge: 75,
    popularity: 75,
    tags: ["fir", "online fir", "police", "complaint", "cognizable"],
    online: true,
  },
  {
    id: "e-fir-cognizable",
    slug: "e-fir-cognizable",
    name: "e-FIR (Cognizable Offence)",
    category: "police-law",
    subcategory: "FIR & Reports",
    summary: "Register an e-FIR for cognizable crimes like theft, assault, or accident.",
    description:
      "e-FIR is a fully digital route to register a First Information Report for cognizable offences, where police can arrest without warrant. Currently available in states like Delhi, Maharashtra, Karnataka, Tamil Nadu, and UP for crimes such as theft up to ₹5 lakh, snatching, and motor vehicle accidents.",
    ministry: "Ministry of Home Affairs (State Police)",
    officialPortal: "State Police e-FIR Portal",
    officialUrl: "https://mahapolice.gov.in/",
    eligibility: [
      "Offence is cognizable and listed as eligible for e-FIR",
      "Complainant is victim / authorised representative",
      "Incident occurred within the state's jurisdiction",
    ],
    documentsRequired: [
      "Aadhaar / ID proof",
      "Mobile + email",
      "Incident details with date, time, location",
      "Supporting evidence (photos, videos, documents)",
    ],
    fee: 0,
    feeNote: "Free; no fee for e-FIR registration.",
    processingTime: "FIR number issued immediately; investigation as per law",
    howToApply: [
      "Open your state police e-FIR portal.",
      "Register as citizen and verify with OTP.",
      "Select 'e-FIR' and choose offence category.",
      "Fill complainant, victim, and incident details.",
      "Upload evidence; submit; e-FIR copy & FIR number emailed.",
    ],
    serviceCharge: 80,
    popularity: 70,
    tags: ["e-fir", "cognizable", "online fir", "police", "complaint"],
    online: true,
  },
  {
    id: "non-cognizable-report-ncr",
    slug: "non-cognizable-report-ncr",
    name: "Non-Cognizable Report (NCR)",
    category: "police-law",
    subcategory: "FIR & Reports",
    summary: "File a Non-Cognizable Report (NCR) for non-cognizable offences.",
    description:
      "An NCR (Non-Cognizable Report) is registered for offences that are non-cognizable under the BNSS (formerly CrPC), where police cannot arrest without warrant and cannot investigate without magisterial permission. Examples include minor assault, defamation, and simple hurt.",
    ministry: "Ministry of Home Affairs (State Police)",
    officialPortal: "State Police Portal",
    officialUrl: "https://delhipolice.gov.in/",
    eligibility: ["Offence is non-cognizable under BNSS", "Complainant is victim or witness"],
    documentsRequired: [
      "Aadhaar / ID proof",
      "Mobile + email",
      "Incident details",
      "Supporting evidence",
    ],
    fee: 0,
    feeNote: "Free; NCR filing attracts no fee.",
    processingTime: "NCR registered immediately; action on magistrate's order",
    howToApply: [
      "Visit your state police portal or nearest police station.",
      "Register complaint selecting 'Non-Cognizable' category.",
      "Fill incident details and upload evidence.",
      "Submit; NCR number issued.",
      "Police forward NCR to magistrate for permission to investigate.",
    ],
    serviceCharge: 60,
    popularity: 45,
    tags: ["ncr", "non cognizable", "police", "complaint"],
    online: true,
  },
  {
    id: "lost-article-report-lar",
    slug: "lost-article-report-lar",
    name: "Lost Article Report (LAR)",
    category: "police-law",
    subcategory: "FIR & Reports",
    summary: "Report a lost article / document online and get an acknowledgment for re-issue.",
    description:
      "A Lost Article Report (LAR) is a police acknowledgment for lost items such as Aadhaar, PAN, driving license, passport, marksheets, or jewellery. It is not an FIR but is accepted by banks, RTOs, and embassies for re-issue of documents. Most state police portals offer LAR filing online.",
    ministry: "Ministry of Home Affairs (State Police)",
    officialPortal: "Delhi Police Lost Report",
    officialUrl: "https://www.delhipolice.gov.in/lostreport.html",
    eligibility: ["Lost article / document in police jurisdiction", "Complainant has valid ID"],
    documentsRequired: [
      "Aadhaar / ID proof",
      "Mobile number",
      "Details of lost article (description, number, place, time)",
    ],
    fee: 0,
    feeNote: "Free; some states charge ₹10 for a notarised copy.",
    processingTime: "Instant (digital acknowledgment)",
    howToApply: [
      "Open state police 'Lost Article Report' portal.",
      "Register with mobile number and Aadhaar OTP.",
      "Select category and fill lost article details.",
      "Submit; receive acknowledgment with unique report number.",
      "Download and print the LAR for re-issue of documents.",
    ],
    serviceCharge: 40,
    popularity: 80,
    tags: ["lost article", "lar", "lost report", "police", "document lost"],
    online: true,
  },
  {
    id: "police-clearance-certificate-pcc",
    slug: "police-clearance-certificate-pcc",
    name: "Police Clearance Certificate (PCC)",
    category: "police-law",
    subcategory: "Verification & Clearance",
    summary: "Get a PCC from police — required for visa, employment abroad, and certain jobs.",
    description:
      "A Police Clearance Certificate (PCC) is issued by police verifying that the applicant has no criminal record. It is mandatory for Indian citizens emigrating, seeking employment abroad, or applying for long-term visas. PCC is applied through the Passport Seva portal and verified by local police.",
    ministry: "Ministry of Home Affairs / Ministry of External Affairs",
    officialPortal: "Passport Seva / State Police",
    officialUrl: "https://www.passportindia.gov.in/",
    eligibility: [
      "Indian citizen with valid passport",
      "Applying for visa / emigration / foreign employment",
      "No criminal record",
    ],
    documentsRequired: [
      "Valid passport",
      "Aadhaar card",
      "Proof of address",
      "Visa / employment offer letter (if any)",
      "Passport-size photo",
    ],
    fee: 500,
    feeNote: "₹500 PCC fee through Passport Seva; police verification charges included.",
    processingTime: "3–30 days (after police verification)",
    howToApply: [
      "Register on passportindia.gov.in → 'Apply for PCC'.",
      "Fill application form and pay ₹500 fee.",
      "Book appointment at Passport Seva Kendra.",
      "Visit PSK for document verification.",
      "Police verification at address; PCC issued and dispatched.",
    ],
    serviceCharge: 110,
    popularity: 78,
    tags: ["pcc", "police clearance", "visa", "passport", "emigration"],
    online: true,
  },
  {
    id: "police-verification-job",
    slug: "police-verification-job",
    name: "Police Verification for Job",
    category: "police-law",
    subcategory: "Verification & Clearance",
    summary: "Get police verification for new employment — common for govt, banking, and security jobs.",
    description:
      "Police verification for employment is conducted to confirm the antecedents of a candidate before joining government, PSU, banking, or security-sensitive roles. The verification covers address, criminal record, and character references, and is initiated by the employer with the local police station.",
    ministry: "Ministry of Home Affairs (State Police)",
    officialPortal: "State Police Verification Portal",
    officialUrl: "https://mahapolice.gov.in/",
    eligibility: ["Candidate offered employment requiring verification", "Resident of the verification address"],
    documentsRequired: [
      "Aadhaar card",
      "Address proof",
      "Employer's verification request letter",
      "Educational certificates",
      "Passport-size photos",
    ],
    fee: 100,
    feeNote: "₹100–₹500 per verification; employer may bear the cost.",
    processingTime: "15–45 days",
    howToApply: [
      "Employer initiates request to local police station.",
      "Candidate submits Form 22 / antecedent verification form.",
      "Upload KYC and address proof on state police portal.",
      "Pay verification fee (if any).",
      "Police visit address; report submitted to employer.",
    ],
    serviceCharge: 100,
    popularity: 65,
    tags: ["police verification", "job", "antecedent", "employment"],
    online: true,
  },
  {
    id: "police-verification-tenant",
    slug: "police-verification-tenant",
    name: "Police Verification for Tenant",
    category: "police-law",
    subcategory: "Verification & Clearance",
    summary: "Register and verify your tenant with the local police — mandatory in most metros.",
    description:
      "Landlords are legally required to register tenants with the local police in metros like Delhi, Mumbai, Bengaluru, and Pune. The verification captures tenant's ID, permanent address, and employer details to prevent misuse of rented premises.",
    ministry: "Ministry of Home Affairs (State Police)",
    officialPortal: "State Police Tenant Verification",
    officialUrl: "https://delhipolice.gov.in/tenant.html",
    eligibility: ["Landlord renting out residential / commercial premises", "Tenant with valid ID and address proof"],
    documentsRequired: [
      "Tenant's Aadhaar / PAN / passport",
      "Tenant's permanent address proof",
      "Tenant's photograph",
      "Rent agreement",
      "Landlord's ID proof",
    ],
    fee: 0,
    feeNote: "Free on most state police portals; notarised rent agreement ₹300–₹500 extra.",
    processingTime: "Instant acknowledgment; verification 7–30 days",
    howToApply: [
      "Visit state police 'Tenant Verification' portal.",
      "Register landlord and tenant details.",
      "Upload tenant's KYC and rent agreement.",
      "Submit; receive acknowledgment number.",
      "Beat officer may visit premises; final report shared with landlord.",
    ],
    serviceCharge: 70,
    popularity: 72,
    tags: ["tenant verification", "rental", "police", "landlord"],
    online: true,
  },
  {
    id: "police-verification-domestic-help",
    slug: "police-verification-domestic-help",
    name: "Police Verification for Domestic Help",
    category: "police-law",
    subcategory: "Verification & Clearance",
    summary: "Verify antecedents of domestic helps, drivers, and security guards before hiring.",
    description:
      "Police verification of domestic helps, drivers, and security guards helps safeguard households from fraud and crime. State police portals (e.g. Delhi Police Sahyog) offer free online submission of helper details for antecedent verification.",
    ministry: "Ministry of Home Affairs (State Police)",
    officialPortal: "State Police Sahyog / Domestic Help Verification",
    officialUrl: "https://delhipolice.gov.in/",
    eligibility: ["Household hiring domestic help, driver, or guard", "Helper has valid ID proof"],
    documentsRequired: [
      "Helper's Aadhaar / voter ID",
      "Helper's photograph",
      "Helper's permanent address",
      "Two references / previous employer details",
      "Employer's ID",
    ],
    fee: 0,
    feeNote: "Free on most state police portals; agency commission may apply.",
    processingTime: "7–30 days",
    howToApply: [
      "Open state police 'Domestic Help Verification' portal.",
      "Register employer and helper details.",
      "Upload helper's KYC and references.",
      "Submit; acknowledgment number generated.",
      "Police verify at helper's permanent address; report shared with employer.",
    ],
    serviceCharge: 70,
    popularity: 60,
    tags: ["domestic help", "servant verification", "police", "antecedent"],
    online: true,
  },
  {
    id: "character-certificate",
    slug: "character-certificate",
    name: "Character Certificate",
    category: "police-law",
    subcategory: "Verification & Clearance",
    summary: "Get a character / antecedent certificate from police for jobs, education, or licenses.",
    description:
      "A Character Certificate (also called Antecedent Certificate) is issued by police certifying that the holder has no adverse criminal record. It is required for private/government jobs, professional licences, and overseas education. Online applications are accepted on state police portals.",
    ministry: "Ministry of Home Affairs (State Police)",
    officialPortal: "State Police Character Certificate",
    officialUrl: "https://mahapolice.gov.in/",
    eligibility: [
      "Indian citizen aged 18+",
      "Resident of the state for at least 1 year",
      "No criminal record",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Address proof",
      "Educational qualification proof",
      "Passport-size photos",
      "Two references (neighbours)",
    ],
    fee: 50,
    feeNote: "₹50–₹200 fee; varies by state.",
    processingTime: "15–45 days",
    howToApply: [
      "Open state police 'Character Certificate' portal.",
      "Register with Aadhaar OTP.",
      "Fill personal details and references.",
      "Upload documents and pay fee.",
      "Police verification at address; certificate issued.",
    ],
    serviceCharge: 90,
    popularity: 68,
    tags: ["character certificate", "antecedent", "police", "verification"],
    online: true,
  },
  {
    id: "antecedent-verification",
    slug: "antecedent-verification",
    name: "Antecedent Verification",
    category: "police-law",
    subcategory: "Verification & Clearance",
    summary: "Comprehensive background verification for sensitive appointments & marriages.",
    description:
      "Antecedent Verification is a deep police background check on an individual's criminal record, address history, and references. It is used for sensitive appointments, matrimonial verification, and adoption cases. Initiated through SP office or state police citizen portal.",
    ministry: "Ministry of Home Affairs (State Police)",
    officialPortal: "State Police SP Office",
    officialUrl: "https://www.mha.gov.in/",
    eligibility: ["Applicant with valid address in jurisdiction", "Specific use case (marriage / employment)"],
    documentsRequired: [
      "Aadhaar card",
      "Address proof",
      "Reason for verification (offer letter / marriage invitation)",
      "References (3+)",
      "Photographs",
    ],
    fee: 200,
    feeNote: "₹200–₹500 fee; notarised affidavit may be required.",
    processingTime: "30–90 days",
    howToApply: [
      "Submit application to SP office or state police portal.",
      "Fill antecedent form with personal and address history.",
      "Upload KYC and reason documents.",
      "Pay fee; verification conducted by local PS.",
      "Detailed report shared with applicant.",
    ],
    serviceCharge: 120,
    popularity: 42,
    tags: ["antecedent verification", "background check", "police", "marriage verification"],
    online: false,
  },
  {
    id: "cyber-crime-complaint-1930",
    slug: "cyber-crime-complaint-1930",
    name: "Cyber Crime Complaint (Helpline 1930)",
    category: "police-law",
    subcategory: "Cyber Crime & Helplines",
    summary: "Report cyber fraud / online crimes via the National Cyber Crime Helpline 1930.",
    description:
      "The National Cyber Crime Reporting Portal (cybercrime.gov.in) and helpline 1930 let citizens report cyber crimes such as UPI fraud, online cheating, phishing, and social media abuse. Early reporting within the 'golden hour' enables banks to freeze fraudulent transactions.",
    ministry: "Ministry of Home Affairs (Indian Cyber Crime Coordination Centre - I4C)",
    officialPortal: "National Cyber Crime Reporting Portal",
    officialUrl: "https://cybercrime.gov.in/",
    eligibility: ["Victim of cyber crime", "Witness of online fraud / abuse"],
    documentsRequired: [
      "Aadhaar / ID proof",
      "Mobile number and email",
      "Screenshots / chat transcripts",
      "Bank statement / UPI transaction ID",
      "Suspect details (number, account, URL)",
    ],
    fee: 0,
    feeNote: "Free; helpline 1930 operates 24x7.",
    processingTime: "Report registered instantly; action in 24–72 hours",
    howToApply: [
      "Call 1930 immediately for live fraud; or visit cybercrime.gov.in.",
      "Register with mobile number and Aadhaar OTP.",
      "Select 'Report Cyber Crime' → Women/Child or Other.",
      "Fill incident details and upload evidence.",
      "Receive complaint ID; track status on portal.",
    ],
    serviceCharge: 60,
    popularity: 70,
    tags: ["cyber crime", "1930", "online fraud", "upi fraud", "i4c"],
    online: true,
  },
  {
    id: "women-helpline-181",
    slug: "women-helpline-181",
    name: "Women Helpline (181)",
    category: "police-law",
    subcategory: "Cyber Crime & Helplines",
    summary: "24x7 women's helpline for domestic violence, harassment, and abuse complaints.",
    description:
      "The Universal Women Helpline 181 (UWH) provides 24x7 emergency response and support to women facing violence, harassment, or abuse. Calls are routed to district One Stop Centres (OSC) and local police. The service is free and operates across all states.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "Women Helpline 181",
    officialUrl: "https://wcd.nic.in/women-helpline-181",
    eligibility: ["Any woman in distress or someone calling on her behalf"],
    documentsRequired: ["Caller ID / mobile number", "Location details"],
    fee: 0,
    feeNote: "Free 24x7 service; calls from any network.",
    processingTime: "Immediate response",
    howToApply: [
      "Call 181 from any phone (toll-free).",
      "Counsellor records complaint details.",
      "Field team / OSC / police dispatched if required.",
      "Legal, medical, and shelter support arranged.",
      "Case tracked until closure.",
    ],
    serviceCharge: 0,
    popularity: 70,
    tags: ["women helpline", "181", "domestic violence", "harassment", "wcd"],
    online: false,
  },
  {
    id: "child-helpline-1098",
    slug: "child-helpline-1098",
    name: "Child Helpline (1098)",
    category: "police-law",
    subcategory: "Cyber Crime & Helplines",
    summary: "24x7 emergency helpline for children in distress, abuse, or exploitation.",
    description:
      "Childline 1098 is India's 24x7 emergency phone outreach for children in need of care and protection, including those facing abuse, child labour, trafficking, or missing cases. It is run by the Ministry of Women & Child Development in partnership with NGOs and CHILDLINE India Foundation.",
    ministry: "Ministry of Women & Child Development (CHILDLINE India Foundation)",
    officialPortal: "CHILDLINE 1098",
    officialUrl: "https://www.childlineindia.org.in/",
    eligibility: ["Children in distress, or adults reporting child abuse"],
    documentsRequired: ["Caller contact", "Child / location details"],
    fee: 0,
    feeNote: "Free 24x7 service; toll-free from any number.",
    processingTime: "Immediate response",
    howToApply: [
      "Call 1098 from any phone.",
      "Counsellor records complaint and location.",
      "Local CHILDLINE team / CWC / police alerted.",
      "Rescue, medical, and legal aid arranged.",
      "Case handed over to Child Welfare Committee for further action.",
    ],
    serviceCharge: 0,
    popularity: 65,
    tags: ["child helpline", "1098", "childline", "child abuse", "wcd"],
    online: false,
  },
  {
    id: "senior-citizen-helpline-14567",
    slug: "senior-citizen-helpline-14567",
    name: "Senior Citizen Helpline (14567)",
    category: "police-law",
    subcategory: "Cyber Crime & Helplines",
    summary: "Toll-free helpline for senior citizens facing abuse, neglect, or financial fraud.",
    description:
      "The Senior Citizen Helpline 14567 (formerly 1090 / 1290 in some states) provides assistance to elders facing physical abuse, neglect by family, financial fraud, or healthcare emergencies. Calls are routed to local police, NGOs, and the Maintenance & Welfare of Parents & Senior Citizens authorities.",
    ministry: "Ministry of Social Justice & Empowerment (in coordination with State Police)",
    officialPortal: "Senior Citizen Helpline 14567",
    officialUrl: "https://socialjustice.gov.in/",
    eligibility: ["Senior citizens (60+) in distress", "Anyone calling on behalf of an elder"],
    documentsRequired: ["Caller contact", "Senior citizen / location details"],
    fee: 0,
    feeNote: "Free 24x7 service; toll-free.",
    processingTime: "Immediate response",
    howToApply: [
      "Call 14567 from any phone.",
      "Counsellor records complaint details.",
      "Local police / maintenance tribunal / NGO alerted.",
      "Field visit and intervention arranged.",
      "Case tracked until resolution.",
    ],
    serviceCharge: 0,
    popularity: 55,
    tags: ["senior citizen", "14567", "elder helpline", "elder abuse", "social justice"],
    online: false,
  },
  {
    id: "traffic-challan-payment",
    slug: "traffic-challan-payment",
    name: "Traffic Challan Payment",
    category: "police-law",
    subcategory: "Traffic",
    summary: "Pay traffic e-challans issued by state police or RTO online.",
    description:
      "Traffic e-challans captured by CCTV or handheld devices are payable online via the Parivihan echallan portal or state police portals. Payment within the stipulated period attracts a discount in some states; unpaid challans may attract additional fines or court summons.",
    ministry: "Ministry of Road Transport & Highways / State Police",
    officialPortal: "Parivahan e-Challan",
    officialUrl: "https://echallan.parivahan.gov.in/",
    eligibility: ["Vehicle owner with pending e-challan", "Vehicle number / challan number"],
    documentsRequired: ["Vehicle registration number", "Mobile number for OTP"],
    fee: 0,
    feeNote: "Application free; challan amount as per MV Act (₹500–₹25000).",
    processingTime: "Instant payment confirmation",
    howToApply: [
      "Visit echallan.parivahan.gov.in or your state police challan portal.",
      "Enter vehicle number; fetch pending challans.",
      "Select challan(s) to pay.",
      "Pay via UPI / cards / net banking.",
      "Receipt generated instantly; challan marked paid.",
    ],
    serviceCharge: 40,
    popularity: 82,
    tags: ["challan", "traffic challan", "echallan", "parivahan", "fine"],
    online: true,
  },
  {
    id: "missing-person-report",
    slug: "missing-person-report",
    name: "Missing Person Report",
    category: "police-law",
    subcategory: "FIR & Reports",
    summary: "File a missing person report — mandatory to be registered as FIR immediately.",
    description:
      "As per Supreme Court directives, every missing person complaint must be registered as an FIR immediately — no waiting period is allowed. The report is filed at the local police station and synced with the state Crime Criminal Tracking Network (CCTNS) and the Track Child portal for inter-state coordination.",
    ministry: "Ministry of Home Affairs (State Police / NCPCR)",
    officialPortal: "State Police / Track Child Portal",
    officialUrl: "https://trackthemissingchild.gov.in/",
    eligibility: ["Relative / guardian of missing person", "Missing person is Indian resident"],
    documentsRequired: [
      "Complainant's Aadhaar / ID proof",
      "Recent photograph of missing person",
      "Missing person's Aadhaar / ID",
      "Description (height, clothes, identifying marks)",
      "Last seen location and time",
    ],
    fee: 0,
    feeNote: "Free; no fee can be charged for filing a missing person FIR.",
    processingTime: "FIR registered immediately; investigation per BNSS",
    howToApply: [
      "Visit nearest police station or state police portal.",
      "File missing person complaint — insist on FIR registration.",
      "Provide photograph, ID, and description details.",
      "Police enter details in CCTNS and Track Child portal.",
      "Investigation begins; complainant receives daily progress updates.",
    ],
    serviceCharge: 80,
    popularity: 50,
    tags: ["missing person", "track child", "cctns", "police", "missing"],
    online: true,
  },
];
