import type { GovernmentService } from "../types";

export const seniorCitizens: GovernmentService[] = [
  {
    id: "senior-citizen-id-card-state",
    slug: "senior-citizen-id-card-state",
    name: "Senior Citizen Identity Card (State)",
    category: "senior-citizens",
    subcategory: "Identity & Recognition",
    summary: "State-issued photo identity card for residents aged 60+ enabling various concessions.",
    description:
      "Most state governments issue a Senior Citizen Identity Card to residents aged 60 years and above. The card is the primary document for availing concessions in travel, hospitals, taxes, banks, and courts. The card typically carries the holder's name, photograph, age, address, and unique ID number, and is issued by the Social Welfare Department of the state through the e-District portal.",
    ministry: "State Department of Social Welfare / Senior Citizens Welfare",
    officialPortal: "State e-District / Social Welfare Portal",
    officialUrl: "https://socialjustice.delhi.gov.in/senior-citizen-id-card",
    eligibility: [
      "Indian citizen aged 60 years or above",
      "Resident of the issuing state",
      "Holds a valid Aadhaar",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Age proof (Voter ID, PAN, birth certificate)",
      "Residence proof of the state",
      "Recent passport-size photograph",
      "Mobile number for OTP",
    ],
    fee: 10,
    feeNote: "₹10-₹50 application fee depending on state; free for BPL.",
    processingTime: "15-30 days",
    howToApply: [
      "Visit the state e-District portal or the Social Welfare Department office.",
      "Register/login with mobile number and OTP.",
      "Select 'Senior Citizen ID Card' service and fill the application form.",
      "Upload Aadhaar, age proof, address proof and photograph; pay the fee online.",
      "Submit; the card is dispatched by post or can be collected from the office.",
    ],
    serviceCharge: 70,
    popularity: 75,
    tags: ["senior citizen", "identity card", "state", "concession"],
    online: true,
  },
  {
    id: "senior-citizen-pension-status",
    slug: "senior-citizen-pension-status",
    name: "Senior Citizen Pension Status Check (NSAP / State)",
    category: "senior-citizens",
    subcategory: "Pension Status",
    summary: "Check disbursement status of IGNOAPS / state old age pension online.",
    description:
      "Beneficiaries of IGNOAPS or state old age pension schemes can verify their pension sanction and disbursement status through the NSAP Beneficiary Status portal or the state's social welfare portal. The lookup requires the NSAP ID, bank account number or Aadhaar number, and shows the latest credit month, amount, and any pending issues.",
    ministry: "Ministry of Rural Development (NSAP Division)",
    officialPortal: "NSAP — National Social Assistance Programme",
    officialUrl: "https://nsap.nic.in/",
    eligibility: [
      "Existing IGNOAPS or state old age pension beneficiary",
      "Has NSAP ID, Aadhaar, or bank account number",
    ],
    documentsRequired: [
      "NSAP ID / Aadhaar / Bank account number",
      "Registered mobile number",
    ],
    fee: 0,
    feeNote: "Free lookup.",
    processingTime: "Instant",
    howToApply: [
      "Visit nsap.nic.in and click 'Beneficiary Status'.",
      "Select state, district and enter NSAP ID or Aadhaar or bank account.",
      "Complete the captcha and submit.",
      "View sanction order, monthly disbursement history and bank credit status.",
      "For state top-up status, visit the state social welfare portal with state pension ID.",
    ],
    serviceCharge: 35,
    popularity: 72,
    tags: ["senior citizen", "pension status", "nsap", "ignoaps", "old age pension"],
    online: true,
  },
  {
    id: "state-senior-citizen-pension-application",
    slug: "state-senior-citizen-pension-application",
    name: "State Senior Citizen Pension Application",
    category: "senior-citizens",
    subcategory: "Pension Application",
    summary: "Apply for state-specific senior citizen pension schemes (separate from IGNOAPS central share).",
    description:
      "Many states operate their own senior citizen pension schemes parallel to IGNOAPS, with relaxed income criteria or lower age thresholds (55+ years in some states). Examples include the Indira Gandhi Old Age Pension (Delhi), Old Age Samman Allowance (Haryana), Mukhyamantri Vriddha Pension Yojana (Bihar), and YSR Pension Kanuka (Andhra Pradesh). The application is filed through the state e-District or Social Welfare portal.",
    ministry: "State Department of Social Welfare",
    officialPortal: "State e-District / Social Welfare Portal",
    officialUrl: "https://eds.delhi.gov.in/",
    eligibility: [
      "Resident of the state, age as per scheme (typically 55-65 years)",
      "Annual family income within state-prescribed limit (₹1,00,000 to ₹3,00,000)",
      "Not receiving any other pension",
      "Aadhaar and bank account mandatory",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Age proof (Voter ID, PAN, birth certificate)",
      "Residence proof of the state",
      "Income certificate / affidavit",
      "Bank passbook copy",
      "Recent photograph",
    ],
    fee: 0,
    feeNote: "Free to apply. Pension ₹500-₹2,500/month via DBT.",
    processingTime: "45-90 days",
    howToApply: [
      "Register on the state e-District or Social Welfare portal.",
      "Select 'Old Age Pension' / 'Senior Citizen Pension' service.",
      "Fill in personal, address, income and bank details.",
      "Upload documents (Aadhaar, age proof, income proof, photo, bank passbook).",
      "Submit and note the application ID; field verification by Social Welfare Officer before sanction.",
    ],
    serviceCharge: 95,
    popularity: 70,
    tags: ["senior citizen", "state pension", "old age", "social welfare", "dbt"],
    online: true,
  },
  {
    id: "railway-senior-citizen-concession",
    slug: "railway-senior-citizen-concession",
    name: "Railway Travel Concession for Senior Citizens",
    category: "senior-citizens",
    subcategory: "Travel Concession",
    summary: "Avail 40% (men) / 50% (women) fare concession in reserved train classes (subject to current policy).",
    description:
      "Indian Railways provides fare concession to senior citizens (men aged 60+, women aged 58+) in reserved classes — historically 40% for men and 50% for women in AC I/II/III, AC Chair Car and Sleeper. From March 2020, the concession was temporarily suspended as a COVID-19 measure; partial restoration is being considered. Passengers must carry valid age proof during travel.",
    ministry: "Ministry of Railways (Indian Railways)",
    officialPortal: "Indian Railways — Passenger Concession",
    officialUrl: "https://www.indianrailways.gov.in/",
    eligibility: [
      "Senior citizen male aged 60+ years (40% concession)",
      "Senior citizen female aged 58+ years (50% concession)",
      "Travelling in reserved classes (AC I/II/III, AC Chair Car, Sleeper)",
      "Valid age proof (Voter ID, Driving Licence, PAN, Senior Citizen ID)",
    ],
    documentsRequired: [
      "Age proof (Voter ID, PAN, Driving Licence, Senior Citizen ID)",
      "Aadhaar card (if booking online via IRCTC)",
      "IRCTC account (for online booking)",
    ],
    fee: 0,
    feeNote: "Free to avail. Concession applied at booking time when age is verified.",
    processingTime: "Instant at booking",
    howToApply: [
      "Book your ticket on IRCTC (irctc.co.in) or at PRS counter.",
      "Tick the 'Senior Citizen' concession checkbox during passenger details entry.",
      "Enter the date of birth and ID card number; IRCTC validates age.",
      "Concession is auto-applied on the fare; ticket is issued with 'SRCTZN' marking.",
      "Carry the original age-proof ID during travel; TTE may verify.",
    ],
    serviceCharge: 40,
    popularity: 78,
    tags: ["senior citizen", "railway", "concession", "train", "irctc", "travel"],
    online: true,
  },
  {
    id: "air-india-senior-citizen-concession",
    slug: "air-india-senior-citizen-concession",
    name: "Air India Senior Citizen Concession",
    category: "senior-citizens",
    subcategory: "Travel Concession",
    summary: "25% discount on Economy class base fare for senior citizens aged 60+ on Air India domestic flights.",
    description:
      "Air India offers a 25% concession on the base fare of Economy class for domestic flights to senior citizens aged 60 years and above. The concession is available only on Air India-operated flights (not code-shares), and is auto-applied on the website when the passenger's date of birth indicates 60+ years. Valid photo ID with date of birth is mandatory at check-in.",
    ministry: "Ministry of Civil Aviation (Air India)",
    officialPortal: "Air India",
    officialUrl: "https://www.airindia.in/",
    eligibility: [
      "Age 60 years or above on the date of travel",
      "Indian citizen or OCI",
      "Travel on Air India-operated domestic flights only",
      "Economy class booking",
    ],
    documentsRequired: [
      "Photo ID with date of birth (Passport / Driving Licence / Voter ID / PAN)",
      "Aadhaar card",
      "Air India booking reference (PNR)",
    ],
    fee: 0,
    feeNote: "Concession auto-applied at booking. Government taxes payable at full rate.",
    processingTime: "Instant at booking",
    howToApply: [
      "Visit airindia.in and select flight search with travel dates.",
      "Enter passenger details; provide date of birth (60+ years).",
      "Select 'Senior Citizen' fare type; the system auto-applies 25% discount on base fare.",
      "Complete payment; receive e-ticket with 'SRCTZN' marking.",
      "Carry valid photo ID with DOB at check-in and boarding.",
    ],
    serviceCharge: 50,
    popularity: 60,
    tags: ["senior citizen", "air india", "concession", "flight", "civil aviation"],
    online: true,
  },
  {
    id: "income-tax-80ddb-senior-citizen-filing",
    slug: "income-tax-80ddb-senior-citizen-filing",
    name: "Income Tax 80DDB Deduction Filing (Senior / Super Senior)",
    category: "senior-citizens",
    subcategory: "Tax Benefits",
    summary: "Assisted filing for ₹40,000-₹1,00,000 deduction under Section 80DDB for medical treatment of specified diseases.",
    description:
      "Section 80DDB of the Income Tax Act allows a deduction for medical treatment of specified diseases (cancer, AIDS, neurological disorders, chronic renal failure, haematological disorders, etc.) for the assessee or a dependent. For senior citizens (60-80 years) the deduction is ₹1,00,000; for super senior citizens (80+) the limit is also ₹1,00,000. A medical certificate in Form 10-I from a specialist is required.",
    ministry: "Ministry of Finance (Central Board of Direct Taxes)",
    officialPortal: "Income Tax Department",
    officialUrl: "https://www.incometax.gov.in/",
    eligibility: [
      "Senior citizen (60+) or super senior (80+) assessee",
      "Self or dependent suffers from a specified disease under Rule 11DD",
      "Medical certificate in Form 10-I from a specialist in a Government hospital",
      "Actual medical expense incurred ( reimbursement reduces the deduction)",
    ],
    documentsRequired: [
      "Form 10-I medical certificate from a specialist (Government hospital)",
      "Hospital bills and pharmacy invoices",
      "PAN card of assessee and dependent",
      "Aadhaar card",
      "Bank account details",
      "ITR form (ITR-1 / ITR-2)",
    ],
    fee: 0,
    feeNote: "Free to file ITR. Tilak assisted filing fee ₹499.",
    processingTime: "Same day (e-filing); refund in 30-90 days",
    howToApply: [
      "Obtain Form 10-I from a specialist in a Government hospital confirming the specified disease.",
      "Collect all hospital bills, pharmacy invoices and payment receipts.",
      "Login to incometax.gov.in with PAN and password; navigate to e-File → Income Tax Returns.",
      "Choose ITR-1 or ITR-2; under Schedule 80DDB enter the deduction amount (up to ₹1,00,000).",
      "Upload Form 10-I if requested, e-verify return with Aadhaar OTP; refund is processed in 30-90 days.",
    ],
    serviceCharge: 150,
    popularity: 55,
    tags: ["senior citizen", "income tax", "80ddb", "medical deduction", "tax filing"],
    online: true,
  },
  {
    id: "income-tax-80d-senior-citizen-filing",
    slug: "income-tax-80d-senior-citizen-filing",
    name: "Income Tax 80D Health Insurance Deduction (Senior)",
    category: "senior-citizens",
    subcategory: "Tax Benefits",
    summary: "Assisted filing for ₹50,000-₹1,00,000 deduction under Section 80D for senior citizens' health insurance/premium.",
    description:
      "Section 80D allows deduction for health insurance premium and preventive health check-up. For senior citizens (60+), the deduction limit is ₹50,000 for self/spouse/dependent children and an additional ₹50,000 for parents (₹1,00,000 if parents are also senior citizens). Medical expenses for senior citizen parents without insurance are also deductible up to ₹50,000.",
    ministry: "Ministry of Finance (Central Board of Direct Taxes)",
    officialPortal: "Income Tax Department",
    officialUrl: "https://www.incometax.gov.in/",
    eligibility: [
      "Senior citizen (60+) assessee paying health insurance premium",
      "Or paying medical expenses for self/spouse/dependent children who are senior citizens",
      "Premium paid by any mode other than cash",
      "Policy from IRDAI-registered insurer",
    ],
    documentsRequired: [
      "Health insurance premium certificate (Form 80D) from insurer",
      "Medical expense bills and prescriptions (if no insurance)",
      "Preventive health check-up receipts (up to ₹5,000)",
      "PAN card",
      "Aadhaar card",
      "Bank account details",
    ],
    fee: 0,
    feeNote: "Free to file ITR. Tilak assisted filing fee ₹499.",
    processingTime: "Same day (e-filing); refund in 30-90 days",
    howToApply: [
      "Collect the 80D certificate from your insurer and medical bills for uninsured expenses.",
      "Login to incometax.gov.in and start a new ITR (ITR-1 or ITR-2).",
      "Under Schedule 80D, enter premium paid for self/spouse/children (₹50,000 cap for senior citizen).",
      "Enter premium or medical expenses for parents (₹50,000 / ₹1,00,000 cap based on parent age).",
      "Submit, e-verify with Aadhaar OTP; refund processed in 30-90 days.",
    ],
    serviceCharge: 120,
    popularity: 65,
    tags: ["senior citizen", "income tax", "80d", "health insurance", "tax deduction"],
    online: true,
  },
  {
    id: "maintenance-tribunal-senior-citizen-complaint",
    slug: "maintenance-tribunal-senior-citizen-complaint",
    name: "Maintenance Tribunal Complaint (Senior Citizens Act)",
    category: "senior-citizens",
    subcategory: "Legal Protection",
    summary: "File complaint at Maintenance Tribunal for monthly maintenance from children/heirs under the Maintenance and Welfare of Parents and Senior Citizens Act, 2007.",
    description:
      "The Maintenance and Welfare of Parents and Senior Citizens Act, 2007 empowers senior citizens (60+) and parents (any age) to claim monthly maintenance from their children or legal heirs. Application is filed before the Maintenance Tribunal (Sub-Divisional Officer / SDM) which has powers of a civil court. The maximum maintenance is ₹10,000/month and the order must be passed within 90 days.",
    ministry: "Ministry of Social Justice & Empowerment",
    officialPortal: "State Social Welfare / Maintenance Tribunal",
    officialUrl: "https://socialjustice.gov.in/",
    eligibility: [
      "Senior citizen (60+) or parent unable to maintain self",
      "Children/heirs have sufficient means but refuse to maintain",
      "Property transferred by senior citizen can be reclaimed if maintenance denied",
    ],
    documentsRequired: [
      "Aadhaar card / Age proof (60+)",
      "Application in prescribed format to Maintenance Tribunal",
      "Details of children/heirs (name, address, occupation)",
      "Proof of income and property of children/heirs (if available)",
      "Medical bills / expense proof",
      "Affidavit of dependency",
    ],
    fee: 0,
    feeNote: "Free to file. No court fee prescribed.",
    processingTime: "Order within 90 days of application",
    howToApply: [
      "Approach the Office of the Maintenance Tribunal (usually at SDM office) with application.",
      "Fill the maintenance application in the prescribed format with details of children/heirs.",
      "Attach age proof, medical bills, affidavit of dependency and any proof of children's income.",
      "Submit to the Tribunal; notice is issued to respondents.",
      "Tribunal conducts hearing and passes order within 90 days; monthly maintenance is paid via bank transfer.",
    ],
    serviceCharge: 140,
    popularity: 50,
    tags: ["senior citizen", "maintenance", "tribunal", "legal", "parents"],
    online: false,
  },
  {
    id: "reverse-mortgage-loan-senior",
    slug: "reverse-mortgage-loan-senior",
    name: "Reverse Mortgage Loan for Senior Citizens",
    category: "senior-citizens",
    subcategory: "Financial Products",
    summary: "Convert self-owned residential property into a monthly income stream without selling it.",
    description:
      "The Reverse Mortgage scheme, introduced by RBI/NHB in 2007, allows senior citizens (60+) who own a self-occupied house to pledge it to a bank and receive monthly income (loan) for up to 20 years while continuing to live in it. The loan is repayable only after the death of both spouses or on permanent vacating of the house. No income tax is payable on the monthly payments.",
    ministry: "Ministry of Finance (National Housing Bank / RBI)",
    officialPortal: "National Housing Bank",
    officialUrl: "https://www.nhb.org.in/",
    eligibility: [
      "Senior citizen aged 60+ years (spouse can be 55+ as co-borrower)",
      "Owns a self-occupied residential property with clear title",
      "Property is the permanent residence",
      "No outstanding loan on the property",
    ],
    documentsRequired: [
      "Aadhaar card / PAN card",
      "Age proof (60+)",
      "Property title deeds (sale deed, encumbrance certificate)",
      "Property tax receipts",
      "Approved building plan",
      "Bank passbook copy",
      "Spouse's KYC (if co-borrower)",
    ],
    fee: 0,
    feeNote: "Processing fee ~0.5% of loan amount. Interest 9.5-11.5% p.a.",
    processingTime: "30-60 days",
    howToApply: [
      "Approach a bank offering reverse mortgage (SBI, PNB, Central Bank, etc.).",
      "Submit KYC, property documents and age proof along with loan application.",
      "Bank conducts property valuation and legal verification of title.",
      "On approval, monthly payments (loan) start within 30-60 days; borrower continues to live in the house.",
      "Loan is repayable on death of both spouses / permanent vacating / sale; balance to heirs after settlement.",
    ],
    serviceCharge: 140,
    popularity: 45,
    tags: ["senior citizen", "reverse mortgage", "loan", "property", "income"],
    online: false,
  },
  {
    id: "rashtriya-vayoshri-yojana",
    slug: "rashtriya-vayoshri-yojana",
    name: "Rashtriya Vayoshri Yojana (Aids for BPL Seniors)",
    category: "senior-citizens",
    subcategory: "Welfare Schemes",
    summary: "Free physical aids and assistive devices to BPL senior citizens with age-related disabilities.",
    description:
      "Rashtriya Vayoshri Yojana (RVY) is a Central Sector scheme of the Ministry of Social Justice & Empowerment, implemented through ALIMCO. It provides free physical aids and assistive devices (walking sticks, elbow crutches, hearing aids, wheelchairs, spectacles, dentures, etc.) to BPL senior citizens aged 60+ suffering from age-related infirmities. Camps are organised at district level for distribution.",
    ministry: "Ministry of Social Justice & Empowerment (DEPwD)",
    officialPortal: "Department of Empowerment of Persons with Disabilities",
    officialUrl: "https://socialjustice.gov.in/",
    eligibility: [
      "Indian senior citizen aged 60+ years",
      "Belongs to BPL family",
      "Suffering from age-related disability/infirmity",
      "Holds a BPL ration card",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Age proof (60+ years)",
      "BPL ration card / BPL certificate",
      "Disability / medical certificate (if available)",
      "Recent photograph",
    ],
    fee: 0,
    feeNote: "Free. Aids and devices distributed in camps organised by ALIMCO.",
    processingTime: "Same day at distribution camp",
    howToApply: [
      "Watch for RVY camp announcements at the District Social Welfare Office or panchayat notice board.",
      "Register at the camp site with Aadhaar, age proof and BPL ration card.",
      "ALIMCO officials assess the assistive device requirement (walking stick, hearing aid, wheelchair, etc.).",
      "On-the-spot distribution of aids; training on usage provided.",
      "Beneficiary receives a distribution slip and warranty card for the aids.",
    ],
    serviceCharge: 60,
    popularity: 50,
    tags: ["senior citizen", "vayoshri", "bpl", "assistive devices", "alimco", "disability"],
    online: false,
  },
  {
    id: "senior-citizen-savings-scheme-scss",
    slug: "senior-citizen-savings-scheme-scss",
    name: "Senior Citizen Savings Scheme (SCSS) Account",
    category: "senior-citizens",
    subcategory: "Savings Schemes",
    summary: "5-year Government of India savings scheme offering 8.2% interest for senior citizens.",
    description:
      "The Senior Citizen Savings Scheme (SCSS) is a Government of India savings instrument available at post offices and designated banks for individuals aged 60+ (55+ for retirees under VRS, 50+ for defence retirees). It offers a quarterly payable interest rate (currently 8.2% p.a. for Q1 FY 2024-25), has a 5-year tenure (extendable by 3 years), and the maximum investment is ₹30 lakh. Tax deduction under Section 80C up to ₹1.5 lakh.",
    ministry: "Ministry of Finance (Department of Economic Affairs)",
    officialPortal: "India Post / Designated Banks",
    officialUrl: "https://www.indiapost.gov.in/",
    eligibility: [
      "Indian citizen aged 60 years or above",
      "Or retiree aged 55+ under VRS (within 1 month of retirement)",
      "Or defence retiree aged 50+ (within 1 month of retirement)",
      "Single or joint account with spouse only",
    ],
    documentsRequired: [
      "Aadhaar card",
      "PAN card",
      "Age proof (Voter ID, PAN, birth certificate)",
      "Recent passport-size photographs (2)",
      "Address proof",
      "Cheque / DD for the deposit amount (₹1,000 to ₹30 lakh)",
      "Form A (SCSS account opening form)",
    ],
    fee: 1000,
    feeNote: "Minimum deposit ₹1,000; maximum ₹30 lakh. Deposit in multiples of ₹1,000.",
    processingTime: "Same day account opening",
    howToApply: [
      "Visit a post office or designated bank (SBI, PNB, BOI, Canara, etc.) offering SCSS.",
      "Collect Form A (SCSS account opening form) and fill in personal and nomination details.",
      "Submit KYC documents, age proof and a cheque/DD for the deposit amount.",
      "Pay the deposit; account is opened same day and passbook issued.",
      "Interest is credited quarterly (March/June/Sep/Dec) to the linked savings account.",
    ],
    serviceCharge: 90,
    popularity: 78,
    tags: ["senior citizen", "scss", "savings", "post office", "tax saving", "interest"],
    online: false,
  },
  {
    id: "pradhan-mantri-vaya-vandana-yojana",
    slug: "pradhan-mantri-vaya-vandana-yojana",
    name: "Pradhan Mantri Vaya Vandana Yojana (PMVVY)",
    category: "senior-citizens",
    subcategory: "Pension Schemes",
    summary: "LIC-administered 10-year pension scheme for senior citizens offering 7.40% p.a. guaranteed payout.",
    description:
      "PMVVY is a pension scheme administered by Life Insurance Corporation (LIC) of India on behalf of the Government of India. It is open to senior citizens aged 60+ years for a 10-year policy term. The scheme offers a guaranteed pension payout at 7.40% p.a. (payable monthly/quarterly/half-yearly/yearly) on a maximum purchase price of ₹15 lakh. The policy can be prematurely surrendered in case of critical illness.",
    ministry: "Ministry of Finance (LIC of India)",
    officialPortal: "LIC India — PMVVY",
    officialUrl: "https://www.licindia.in/",
    eligibility: [
      "Indian citizen aged 60 years or above",
      "No upper age limit",
      "Maximum purchase price ₹15 lakh per senior citizen",
      "Pension payout option: monthly/quarterly/half-yearly/yearly",
    ],
    documentsRequired: [
      "Aadhaar card",
      "PAN card",
      "Age proof (60+)",
      "Address proof",
      "Recent passport-size photograph",
      "Cancelled cheque / bank passbook copy",
      "PMVVY proposal form",
    ],
    fee: 0,
    feeNote: "Purchase price ₹1,62,162 to ₹15,00,000. No premium allocation charge.",
    processingTime: "Same day policy issuance (online); 7-10 days offline",
    howToApply: [
      "Visit the LIC India website (licindia.in) or nearest LIC branch.",
      "Select PMVVY plan; fill the online proposal form with personal and bank details.",
      "Choose pension mode (monthly/quarterly/half-yearly/yearly) and purchase price (up to ₹15 lakh).",
      "Upload KYC documents (Aadhaar, PAN, age proof, photo) and pay the purchase price online.",
      "Policy is issued instantly; pension begins from the chosen date and is credited to the bank account.",
    ],
    serviceCharge: 110,
    popularity: 70,
    tags: ["senior citizen", "pmvvy", "pension", "lic", "guaranteed return"],
    online: true,
  },
  {
    id: "varishtha-pension-bima-yojana",
    slug: "varishtha-pension-bima-yojana",
    name: "Varishtha Pension Bima Yojana (VPBY)",
    category: "senior-citizens",
    subcategory: "Pension Schemes",
    summary: "Government-subsidised pension scheme for seniors offering guaranteed returns (closed for new sale).",
    description:
      "Varishtha Pension Bima Yojana (VPBY) was a pension scheme for senior citizens aged 60+ administered by LIC of India, offering a guaranteed annual return of 9% (effectively 8.30% taxable) on the purchase price. The scheme had a 15-year term with pension payable monthly/quarterly/half-yearly/yearly. New subscriptions are closed but existing policies continue till maturity. The Government provides the differential return subsidy to LIC.",
    ministry: "Ministry of Finance (LIC of India)",
    officialPortal: "LIC India",
    officialUrl: "https://www.licindia.in/",
    eligibility: [
      "Existing VPBY policyholder aged 60+ at the time of purchase",
      "Pension continues till 15-year term completion",
      "Premature exit allowed on critical illness with 98% surrender value",
      "Loan available up to 75% of purchase price after 3 years",
    ],
    documentsRequired: [
      "VPBY policy bond",
      "Aadhaar card / PAN card",
      "Bank passbook copy",
      "Life certificate (annually in November)",
      "Surrender form (if surrendering)",
    ],
    fee: 0,
    feeNote: "Closed for new subscriptions. Existing policies serviced by LIC.",
    processingTime: "Pension credit on chosen frequency; life certificate annually",
    howToApply: [
      "Existing policyholders receive pension automatically on chosen frequency.",
      "Submit Annual Life Certificate (Jeevan Pramaan) in November at any LIC branch or via JeevanPramaan.gov.in.",
      "For surrender due to critical illness, submit Form for Surrender with medical certificate and policy bond.",
      "For loan, approach the servicing LIC branch with policy bond and KYC.",
      "On maturity (15 years), the purchase price is returned to the policyholder/nominee.",
    ],
    serviceCharge: 70,
    popularity: 45,
    tags: ["senior citizen", "vpby", "pension", "lic", "varishtha"],
    online: false,
  },
  {
    id: "antyodaya-senior-citizen-scheme",
    slug: "antyodaya-senior-citizen-scheme",
    name: "Antyodaya Senior Citizen Scheme (State Subsidised Food & Health)",
    category: "senior-citizens",
    subcategory: "Welfare Schemes",
    summary: "Subsidised food grains and health check-ups for destitute / BPL senior citizens through state programmes.",
    description:
      "Several states run Antyodaya-style schemes specifically for destitute and BPL senior citizens — combining highly subsidised food grains via PDS, free health check-ups, and pension top-ups. Examples include the Andhra Pradesh NTR Bharosa, Telangana Aasara, Odisha Madhu Babu Pension Yojana, and Tamil Nadu Destitute Old Age Pension. The application is routed through the Gram Panchayat / Municipality.",
    ministry: "State Department of Social Welfare / Civil Supplies",
    officialPortal: "State Civil Supplies / Social Welfare Portal",
    officialUrl: "https://nfsa.gov.in/",
    eligibility: [
      "Destitute or BPL senior citizen (60+)",
      "No earning family member",
      "Resident of the implementing state",
      "Not receiving any other similar benefit",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Age proof (60+ years)",
      "BPL / Antyodaya ration card",
      "Residence proof",
      "Income certificate / destitute certificate from Tehsildar",
      "Bank passbook copy",
    ],
    fee: 0,
    feeNote: "Free to apply. Benefits via DBT and PDS.",
    processingTime: "30-60 days",
    howToApply: [
      "Approach the Gram Panchayat / Municipality office with BPL and age proof.",
      "Collect the application form for the Antyodaya Senior Citizen scheme of the state.",
      "Fill in personal, income and bank details; attach Aadhaar, age proof, BPL card.",
      "Submit to BDO / Municipal Commissioner; verification by Panchayat and Social Welfare Officer.",
      "On sanction, beneficiary gets subsidised food grains via PDS + monthly pension via DBT.",
    ],
    serviceCharge: 70,
    popularity: 55,
    tags: ["senior citizen", "antyodaya", "bpl", "food security", "pension", "welfare"],
    online: false,
  },
];
