// Tilak E-Seva Portal — Transport & Vehicles services catalog.
// Real Indian Government services under the Ministry of Road Transport & Highways (MoRTH).
// Reference portals: parivahan.gov.in, sarathi.parivahan.gov.in, vahan.parivahan.gov.in,
// fastag.ihmcl.co.in, parivahan.gov.in/puc.

import type { GovernmentService } from "../types";

export const transportVehicles: GovernmentService[] = [
  {
    id: "learners-driving-license",
    slug: "learners-driving-license",
    name: "Learner's Driving License",
    category: "transport-vehicles",
    subcategory: "Driving License",
    summary: "Apply for a learner's license to start driving legally in India.",
    description:
      "A learner's license is a provisional permit issued by the RTO allowing a person to learn driving under supervision. It is valid for 6 months and mandatory before applying for a permanent driving license. The process is fully online through the Parivahan Sarathi portal with Aadhaar e-KYC.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Sarathi",
    officialUrl: "https://sarathi.parivahan.gov.in/",
    eligibility: [
      "Age 16+ for 50cc gearless two-wheeler (with guardian consent)",
      "Age 18+ for light motor vehicle",
      "Age 20+ for transport vehicle",
      "Must pass the learner's license online test",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Proof of address",
      "Proof of age",
      "Passport-size photograph",
      "Medical certificate Form 1 (for transport/age 40+)",
    ],
    fee: 200,
    feeNote: "₹200 per class of vehicle; ₹50 per additional class; ₹50 for re-test.",
    processingTime: "Same day (after passing online test)",
    howToApply: [
      "Visit parivahan.gov.in → Sarathi portal and select your state.",
      "Click 'Apply for Learner License' and fill the application form.",
      "Upload documents and complete Aadhaar e-KYC.",
      "Pay the fee online and book a slot for the learner's test.",
      "Appear for the online test at the RTO; on passing, LL is issued instantly.",
    ],
    serviceCharge: 60,
    popularity: 88,
    tags: ["driving license", "learner", "rto", "sarathi", "parivahan"],
    online: true,
  },
  {
    id: "permanent-driving-license",
    slug: "permanent-driving-license",
    name: "Permanent Driving License",
    category: "transport-vehicles",
    subcategory: "Driving License",
    summary: "Get a permanent driving license after holding a learner's license for 30 days.",
    description:
      "A permanent driving license authorises a person to drive a motor vehicle of the class for which it is granted. It is issued after a practical driving test conducted by the RTO. Applicants must hold a valid learner's license for at least 30 days before applying.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Sarathi",
    officialUrl: "https://sarathi.parivahan.gov.in/",
    eligibility: [
      "Holds a valid learner's license for at least 30 days",
      "Age 18+ for LMV, 20+ for transport vehicle",
      "Has not failed the driving test in the last 7 days",
    ],
    documentsRequired: [
      "Learner's license",
      "Aadhaar card",
      "Proof of address",
      "Passport-size photographs",
      "Form 4 (application for DL)",
      "Medical certificate Form 1A (for transport/age 40+)",
    ],
    fee: 400,
    feeNote: "₹400 for DL; ₹1000 for International DL; ₹50 per additional class of vehicle.",
    processingTime: "7–30 days (after passing driving test)",
    howToApply: [
      "Log in to Sarathi portal → 'Apply for Driving License'.",
      "Fill Form 4 and upload required documents.",
      "Pay the test fee online and book a slot.",
      "Appear for the driving test at the RTO on the scheduled date.",
      "On passing, the DL is printed and dispatched / available as mParivahan DL.",
    ],
    serviceCharge: 80,
    popularity: 90,
    tags: ["driving license", "permanent dl", "rto", "sarathi"],
    online: true,
  },
  {
    id: "driving-license-renewal",
    slug: "driving-license-renewal",
    name: "Driving License Renewal",
    category: "transport-vehicles",
    subcategory: "Driving License",
    summary: "Renew a driving license before or within 5 years of expiry.",
    description:
      "A driving license is valid for 20 years or until age 50, whichever is earlier, for non-transport vehicles. Renewal can be done up to 1 month before expiry; a grace period of 5 years is allowed after expiry without re-test. Applications are filed through Sarathi portal.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Sarathi",
    officialUrl: "https://sarathi.parivahan.gov.in/",
    eligibility: [
      "Holds a valid or recently expired (within 5 years) driving license",
      "For transport license, age below 50 (renewable every 3 years)",
    ],
    documentsRequired: [
      "Original driving license",
      "Aadhaar card",
      "Proof of address",
      "Passport-size photograph",
      "Medical certificate Form 1A",
    ],
    fee: 200,
    feeNote: "₹200 renewal; ₹1000 late fee if expired beyond grace; ₹50 smart card fee.",
    processingTime: "Same day to 7 days",
    howToApply: [
      "Open Sarathi portal → 'Apply for DL Renewal'.",
      "Enter your DL number to fetch existing records.",
      "Upload medical certificate and recent photograph.",
      "Pay renewal fee online.",
      "Visit RTO with original DL; renewed license issued / dispatched.",
    ],
    serviceCharge: 75,
    popularity: 78,
    tags: ["dl renewal", "driving license", "sarathi", "rto"],
    online: true,
  },
  {
    id: "duplicate-driving-license",
    slug: "duplicate-driving-license",
    name: "Duplicate Driving License",
    category: "transport-vehicles",
    subcategory: "Driving License",
    summary: "Apply for a duplicate DL if the original is lost, damaged, or mutilated.",
    description:
      "A duplicate driving license is issued when the original is lost, destroyed, torn, or becomes illegible. The application must be made to the same RTO that issued the original license. An FIR or NCR copy is required if the license was lost.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Sarathi",
    officialUrl: "https://sarathi.parivahan.gov.in/",
    eligibility: [
      "Original DL was issued by an Indian RTO",
      "Lost, destroyed, or mutilated original license",
    ],
    documentsRequired: [
      "LL/DL number and details",
      "Aadhaar card",
      "FIR or NCR copy (if lost)",
      "Mutilated original (if damaged)",
      "Passport-size photograph",
    ],
    fee: 200,
    feeNote: "₹200 duplicate + ₹200 smart card fee (where applicable).",
    processingTime: "7–15 days",
    howToApply: [
      "Log in to Sarathi → 'Services on DL' → 'Issue Duplicate'.",
      "Enter DL number and select reason for duplicate.",
      "Upload FIR/NCR or damaged DL as evidence.",
      "Pay fee online.",
      "Collect duplicate DL from RTO or via post.",
    ],
    serviceCharge: 70,
    popularity: 62,
    tags: ["duplicate dl", "lost license", "sarathi", "rto"],
    online: true,
  },
  {
    id: "international-driving-permit",
    slug: "international-driving-permit",
    name: "International Driving Permit (IDP)",
    category: "transport-vehicles",
    subcategory: "Driving License",
    summary: "Get an IDP to drive a motor vehicle legally in foreign countries.",
    description:
      "The International Driving Permit (IDP) is an official document issued by RTOs that allows Indian citizens to drive in over 150 countries that are signatories to the Geneva Convention. It is valid for 1 year or until the underlying Indian DL expires, whichever is earlier.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Sarathi",
    officialUrl: "https://sarathi.parivahan.gov.in/",
    eligibility: [
      "Indian citizen with valid permanent driving license",
      "DL should be valid for at least 1 more year",
      "Valid Indian passport",
      "Visa / air ticket for travel abroad",
    ],
    documentsRequired: [
      "Valid Indian driving license",
      "Valid passport",
      "Visa / air ticket",
      "Passport-size photographs (5 copies)",
      "Proof of address",
    ],
    fee: 1000,
    feeNote: "₹1000 IDP fee; ₹200 per additional class.",
    processingTime: "1–7 days",
    howToApply: [
      "Open Sarathi portal → 'Apply for International Driving Permit'.",
      "Enter DL number and passport details.",
      "Upload visa, air ticket, and photograph.",
      "Pay ₹1000 fee online.",
      "Visit RTO for document verification; IDP booklet issued.",
    ],
    serviceCharge: 110,
    popularity: 55,
    tags: ["idp", "international license", "sarathi", "foreign driving"],
    online: true,
  },
  {
    id: "driving-license-correction",
    slug: "driving-license-correction",
    name: "Driving License Correction",
    category: "transport-vehicles",
    subcategory: "Driving License",
    summary: "Correct name, address, date of birth, or other details on your DL.",
    description:
      "DL correction service allows holders to rectify errors in name, address, date of birth, blood group, or other personal details printed on the driving license. Documentary proof must be submitted for the corrected information.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Sarathi",
    officialUrl: "https://sarathi.parivahan.gov.in/",
    eligibility: ["Holds a valid driving license", "Has documentary proof for the corrected detail"],
    documentsRequired: [
      "Original driving license",
      "Aadhaar card",
      "Documentary proof for the change (e.g. Aadhaar/PAN/SSLC for name, voter ID for address)",
      "Passport-size photograph",
    ],
    fee: 200,
    feeNote: "₹200 correction fee + ₹200 smart card fee.",
    processingTime: "7–15 days",
    howToApply: [
      "Open Sarathi → 'Services on DL' → 'Change of Address/Other details'.",
      "Enter DL number and select field to correct.",
      "Upload supporting document for the correction.",
      "Pay fee online.",
      "Visit RTO with original DL; corrected DL issued.",
    ],
    serviceCharge: 60,
    popularity: 50,
    tags: ["dl correction", "address change", "sarathi"],
    online: true,
  },
  {
    id: "commercial-driving-license-badge",
    slug: "commercial-driving-license-badge",
    name: "Commercial Driving License Badge",
    category: "transport-vehicles",
    subcategory: "Driving License",
    summary: "Get a transport badge authorising driving of commercial passenger/goods vehicles.",
    description:
      "The commercial badge is an endorsement on a driving license that permits the holder to drive transport vehicles such as taxis, autos, buses, and goods carriers. It requires a separate application, medical fitness, and additional fee over the standard DL.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Sarathi",
    officialUrl: "https://sarathi.parivahan.gov.in/",
    eligibility: [
      "Age 20+ (sometimes 24+ for HMV)",
      "Holds valid LMV DL for at least 1 year",
      "Education: 8th pass (varies by state)",
      "Medical fitness certificate Form 1A",
    ],
    documentsRequired: [
      "Existing driving license",
      "Educational qualification certificate",
      "Medical certificate Form 1A",
      "Aadhaar card",
      "Three passport-size photographs",
    ],
    fee: 500,
    feeNote: "₹500 badge fee; ₹200 per additional class; state taxes extra.",
    processingTime: "7–30 days",
    howToApply: [
      "Apply on Sarathi portal → 'Add Class of Vehicle / Badge'.",
      "Submit educational and medical certificates.",
      "Pay badge fee online.",
      "Appear for driving test for the transport class.",
      "Badge endorsed on DL on passing.",
    ],
    serviceCharge: 100,
    popularity: 58,
    tags: ["badge", "commercial license", "transport dl", "sarathi"],
    online: true,
  },
  {
    id: "add-class-of-vehicle-to-dl",
    slug: "add-class-of-vehicle-to-dl",
    name: "Add Class of Vehicle to DL",
    category: "transport-vehicles",
    subcategory: "Driving License",
    summary: "Endorse an additional vehicle class (e.g. MCWG, LMV, HMV) on your existing DL.",
    description:
      "This service allows a DL holder to add another class of vehicle (motorcycle, light motor vehicle, heavy motor vehicle, etc.) to their existing driving license. A driving test for the new class is mandatory unless exempted.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Sarathi",
    officialUrl: "https://sarathi.parivahan.gov.in/",
    eligibility: [
      "Holds a valid permanent driving license",
      "Minimum age for the class of vehicle being added",
      "For transport class: holds LMV for at least 1 year",
    ],
    documentsRequired: [
      "Existing driving license",
      "Aadhaar card",
      "Passport-size photograph",
      "Medical certificate Form 1A (for transport/age 40+)",
    ],
    fee: 200,
    feeNote: "₹200 per additional class of vehicle + ₹50 test fee.",
    processingTime: "7–15 days",
    howToApply: [
      "Open Sarathi → 'Services on DL' → 'Add Class of Vehicle'.",
      "Select the new class to be added.",
      "Upload required documents.",
      "Pay fee and book test slot.",
      "Appear for test; on passing, new class endorsed on DL.",
    ],
    serviceCharge: 70,
    popularity: 52,
    tags: ["add class", "mcwg", "lmv", "dl endorsement", "sarathi"],
    online: true,
  },
  {
    id: "rc-registration-certificate-new",
    slug: "rc-registration-certificate-new",
    name: "New Vehicle Registration Certificate (RC)",
    category: "transport-vehicles",
    subcategory: "Vehicle Registration",
    summary: "Register a newly purchased vehicle and get the RC book/smart card.",
    description:
      "Every motor vehicle in India must be registered with the RTO within 7 days of purchase. The Registration Certificate (RC) is the official document establishing ownership. Dealers can also register vehicles on behalf of buyers via the dealer point registration system.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: [
      "Owner of a new vehicle purchased from an authorised dealer",
      "Vehicle has valid insurance and roadworthiness",
    ],
    documentsRequired: [
      "Sale certificate (Form 21) from dealer",
      "Vehicle invoice",
      "Insurance certificate",
      "Pollution Under Control (PUC) certificate",
      "Road tax payment receipt",
      "Aadhaar / PAN / Form 60",
      "Temporary registration (if any)",
    ],
    fee: 600,
    feeNote: "₹600 two-wheeler / ₹1200 LMV / ₹1500+ for others; state registration fees extra.",
    processingTime: "1–7 days",
    howToApply: [
      "Visit Vahan portal → 'New Registration'.",
      "Submit Form 20 with dealer-issued documents.",
      "Pay registration fee and road tax.",
      "RTO inspector verifies chassis number.",
      "RC smart card issued and dispatched.",
    ],
    serviceCharge: 110,
    popularity: 86,
    tags: ["rc", "registration", "new vehicle", "vahan", "rto"],
    online: true,
  },
  {
    id: "rc-transfer-of-ownership",
    slug: "rc-transfer-of-ownership",
    name: "RC Transfer of Ownership",
    category: "transport-vehicles",
    subcategory: "Vehicle Registration",
    summary: "Transfer RC ownership to a new buyer when selling a used vehicle.",
    description:
      "On sale/purchase of a used vehicle, ownership must be transferred to the new owner within 14 days (30 days if inter-state). Both buyer and seller must report the transfer; failure to do so makes the original owner liable for offences committed by the buyer.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: [
      "Vehicle has a valid RC",
      "Both buyer and seller available for digital signature / Aadhaar OTP",
      "No outstanding loan / hypothecation (or NOC from financer)",
    ],
    documentsRequired: [
      "Original RC",
      "Form 29 (seller) and Form 30 (buyer)",
      "Sale agreement / affidavit",
      "Insurance and PUC",
      "Buyer's Aadhaar / PAN / address proof",
    ],
    fee: 300,
    feeNote: "₹300 two-wheeler / ₹500 LMV + state transfer fee; ₹500 smart card.",
    processingTime: "7–30 days",
    howToApply: [
      "Open Vahan portal → 'Transfer of Ownership'.",
      "Enter RC number; both parties e-sign via Aadhaar.",
      "Upload Form 29/30 and supporting documents.",
      "Pay transfer fee online.",
      "RTO verifies; new RC in buyer's name dispatched.",
    ],
    serviceCharge: 110,
    popularity: 82,
    tags: ["rc transfer", "ownership transfer", "used vehicle", "vahan"],
    online: true,
  },
  {
    id: "rc-hypothecation-addition",
    slug: "rc-hypothecation-addition",
    name: "RC Hypothecation Addition",
    category: "transport-vehicles",
    subcategory: "Vehicle Registration",
    summary: "Add a bank/financer's hypothecation to RC when buying vehicle on loan.",
    description:
      "When a vehicle is purchased with a loan, the financer's name is endorsed on the RC as hypothecation until the loan is repaid. This service is mandatory within 14 days of vehicle registration or loan disbursement.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: [
      "Vehicle is financed by a bank or NBFC",
      "RC is issued or being issued in owner's name",
    ],
    documentsRequired: [
      "Original RC",
      "Loan sanction letter",
      "Hypothecation agreement",
      "Form 34",
      "Aadhaar of owner",
    ],
    fee: 200,
    feeNote: "₹200 fee + ₹500 smart card fee (if re-printed).",
    processingTime: "7–15 days",
    howToApply: [
      "Open Vahan portal → 'Add Hypothecation'.",
      "Enter RC and loan details.",
      "Upload Form 34 and loan sanction letter.",
      "Pay fee online.",
      "RTO endorses financer on RC.",
    ],
    serviceCharge: 75,
    popularity: 60,
    tags: ["hypothecation", "loan", "rc", "vahan"],
    online: true,
  },
  {
    id: "rc-hypothecation-cancellation",
    slug: "rc-hypothecation-cancellation",
    name: "RC Hypothecation Cancellation",
    category: "transport-vehicles",
    subcategory: "Vehicle Registration",
    summary: "Remove bank's hypothecation from RC after full loan repayment.",
    description:
      "Once a vehicle loan is fully repaid, the owner must apply to cancel the hypothecation entry on the RC. The bank issues an NOC and Form 35; the RTO then reissues the RC without the financer's name.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: ["Vehicle loan fully repaid", "NOC obtained from the financer"],
    documentsRequired: [
      "Original RC",
      "Form 35 (signed by bank)",
      "Bank NOC",
      "Loan closure letter",
      "Aadhaar of owner",
    ],
    fee: 200,
    feeNote: "₹200 fee + ₹500 smart card reprint fee.",
    processingTime: "7–15 days",
    howToApply: [
      "Obtain NOC and Form 35 from your bank after loan closure.",
      "Open Vahan portal → 'Cancel Hypothecation'.",
      "Upload Form 35 and NOC.",
      "Pay fee online.",
      "Submit original RC at RTO; fresh RC issued without hypothecation.",
    ],
    serviceCharge: 90,
    popularity: 65,
    tags: ["hypothecation cancellation", "loan closure", "rc", "vahan"],
    online: true,
  },
  {
    id: "rc-address-change",
    slug: "rc-address-change",
    name: "RC Address Change",
    category: "transport-vehicles",
    subcategory: "Vehicle Registration",
    summary: "Update the address on your vehicle's RC after relocating.",
    description:
      "When an owner relocates permanently, the address on the RC must be updated within 14 days. For inter-state moves, a fresh assignment of new registration mark may be required after obtaining NOC from the original RTO.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: ["Holds a valid RC", "New address proof in owner's name"],
    documentsRequired: [
      "Original RC",
      "Form 33",
      "Proof of new address (Aadhaar, utility bill, etc.)",
      "Insurance certificate",
      "Aadhaar of owner",
    ],
    fee: 200,
    feeNote: "₹200 fee + ₹500 smart card reprint; state taxes extra.",
    processingTime: "7–15 days",
    howToApply: [
      "Open Vahan portal → 'Change of Address in RC'.",
      "Enter RC number and new address.",
      "Upload Form 33 and address proof.",
      "Pay fee online.",
      "Submit original RC; fresh RC with new address issued.",
    ],
    serviceCharge: 80,
    popularity: 55,
    tags: ["rc address change", "address update", "vahan"],
    online: true,
  },
  {
    id: "duplicate-rc",
    slug: "duplicate-rc",
    name: "Duplicate RC (Registration Certificate)",
    category: "transport-vehicles",
    subcategory: "Vehicle Registration",
    summary: "Apply for a duplicate RC if the original is lost, stolen, or damaged.",
    description:
      "A duplicate RC is issued when the original registration certificate is lost, destroyed, or mutilated. An FIR/NCR is required if the RC is lost or stolen. The application is made to the original registering RTO.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: ["Owner of a registered vehicle", "Original RC lost/destroyed/mutilated"],
    documentsRequired: [
      "RC number and details",
      "FIR / NCR copy (if lost)",
      "Mutilated original (if damaged)",
      "Form 26",
      "Insurance and PUC",
      "Aadhaar of owner",
    ],
    fee: 300,
    feeNote: "₹300 fee + ₹500 smart card; ₹200 for two-wheelers.",
    processingTime: "7–15 days",
    howToApply: [
      "Open Vahan portal → 'Issue of Duplicate RC'.",
      "Enter RC number and reason for duplicate.",
      "Upload FIR/NCR and Form 26.",
      "Pay fee online.",
      "Submit original (if mutilated); duplicate RC dispatched.",
    ],
    serviceCharge: 90,
    popularity: 68,
    tags: ["duplicate rc", "lost rc", "vahan", "rto"],
    online: true,
  },
  {
    id: "vehicle-fitness-certificate",
    slug: "vehicle-fitness-certificate",
    name: "Vehicle Fitness Certificate",
    category: "transport-vehicles",
    subcategory: "Vehicle Registration",
    summary: "Get a fitness certificate for commercial vehicles (mandatory every 2 years).",
    description:
      "Commercial vehicles (goods/passenger) require a fitness certificate from the RTO, renewable every 2 years for the first 8 years and annually thereafter. A vehicle failing the fitness test cannot be used as a transport vehicle until rectified.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: [
      "Vehicle is registered as a transport vehicle",
      "Vehicle is roadworthy and complies with emission norms",
    ],
    documentsRequired: [
      "Original RC",
      "Insurance certificate",
      "PUC certificate",
      "Tax clearance receipt",
      "Form CFA / fitness application",
    ],
    fee: 600,
    feeNote: "₹600 fee (varies by vehicle type); ₹200 fitness test fee.",
    processingTime: "Same day to 7 days",
    howToApply: [
      "Open Vahan portal → 'Vehicle Fitness'.",
      "Enter RC number and book a fitness test slot.",
      "Pay fee online.",
      "Present vehicle at Automated Testing Station / RTO.",
      "On passing, fitness certificate issued.",
    ],
    serviceCharge: 110,
    popularity: 50,
    tags: ["fitness certificate", "commercial vehicle", "vahan", "rto"],
    online: true,
  },
  {
    id: "vehicle-tax-payment",
    slug: "vehicle-tax-payment",
    name: "Vehicle Tax Payment (Road Tax)",
    category: "transport-vehicles",
    subcategory: "Vehicle Registration",
    summary: "Pay one-time or annual road tax for your vehicle online.",
    description:
      "Every vehicle owner must pay road tax — either one-time lifetime tax (LTT) or annual tax — to the state RTO. Most states now offer online tax payment via the Vahan portal or state transport websites.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: ["Owner of a registered motor vehicle", "Tax due for payment"],
    documentsRequired: [
      "RC number",
      "Previous tax receipt",
      "Insurance certificate",
    ],
    fee: 0,
    feeNote: "Tax varies by state and vehicle type — typically 7–12% of vehicle cost for LTT.",
    processingTime: "Instant (receipt generated immediately)",
    howToApply: [
      "Open Vahan portal → 'Pay Vehicle Tax'.",
      "Enter RC number to fetch outstanding tax.",
      "Verify computed tax amount.",
      "Pay online via net banking / UPI.",
      "Download tax receipt instantly.",
    ],
    serviceCharge: 50,
    popularity: 75,
    tags: ["road tax", "vehicle tax", "vahan", "ltt"],
    online: true,
  },
  {
    id: "puc-pollution-under-control-certificate",
    slug: "puc-pollution-under-control-certificate",
    name: "PUC (Pollution Under Control) Certificate",
    category: "transport-vehicles",
    subcategory: "Compliance",
    summary: "Get a PUC certificate — mandatory emission check for all motor vehicles.",
    description:
      "The Pollution Under Control (PUC) certificate confirms that a vehicle's emissions are within prescribed limits. It is mandatory for all vehicles and must be renewed every 6 months (1 year for new vehicles). Checks are done at authorised PUC centres across India.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan PUC",
    officialUrl: "https://parivahan.gov.in/puc",
    eligibility: ["Owner of any registered motor vehicle", "Vehicle in roadworthy condition"],
    documentsRequired: ["RC number", "Vehicle at the PUC centre"],
    fee: 60,
    feeNote: "₹60 for two/three-wheelers; ₹100 for four-wheelers; ₹150 for diesel/commercial.",
    processingTime: "Instant (5–10 minutes at the PUC centre)",
    howToApply: [
      "Locate a nearby authorised PUC centre via parivahan.gov.in/puc.",
      "Take your vehicle to the centre for emission test.",
      "Pay the prescribed fee; emission reading is captured.",
      "If within limits, PUC certificate is generated and uploaded to Parivahan.",
      "Download digital PUC from the portal.",
    ],
    serviceCharge: 30,
    popularity: 85,
    tags: ["puc", "pollution certificate", "emission", "parivahan"],
    online: false,
  },
  {
    id: "nhai-fastag",
    slug: "nhai-fastag",
    name: "NHAI FASTag",
    category: "transport-vehicles",
    subcategory: "Toll & FASTag",
    summary: "Buy a FASTag RFID sticker for cashless electronic toll payment across India.",
    description:
      "FASTag is a reloadable RFID tag affixed to a vehicle's windshield that enables automatic deduction of toll charges at NHAI and state highway plazas. It is mandatory for all four-wheelers and is issued by 24+ banks certified by IHMCL/NPCI.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "IHMCL FASTag",
    officialUrl: "https://fastag.ihmcl.co.in/",
    eligibility: [
      "Owner of a four-wheeler (mandatory)",
      "Vehicle has valid RC",
      " KYC documents of owner",
    ],
    documentsRequired: [
      "RC copy",
      "Aadhaar / PAN of owner",
      "Passport-size photo",
      "Active bank account / wallet for linking",
    ],
    fee: 100,
    feeNote: "₹100 issuance (sometimes free under offers) + ₹200 refundable security deposit.",
    processingTime: "5–7 working days (delivery to address)",
    howToApply: [
      "Visit fastag.ihmcl.co.in → 'Buy FASTag'.",
      "Choose issuing bank / payment app.",
      "Enter RC and KYC details; upload documents.",
      "Pay issuance fee + security deposit online.",
      "FASTag delivered to address; activate via bank app.",
    ],
    serviceCharge: 50,
    popularity: 88,
    tags: ["fastag", "toll", "ihmcl", "rfid", "electronic toll"],
    online: true,
  },
  {
    id: "fastag-recharge-replacement",
    slug: "fastag-recharge-replacement",
    name: "FASTag Recharge / Replacement",
    category: "transport-vehicles",
    subcategory: "Toll & FASTag",
    summary: "Recharge your FASTag wallet or replace a damaged/dysfunctional tag.",
    description:
      "FASTag wallets can be recharged online via UPI, net banking, or the issuing bank's app. If the tag is damaged, lost, or stops working, a replacement can be requested from the issuing bank; the old tag is deactivated and balance transferred.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "IHMCL FASTag",
    officialUrl: "https://fastag.ihmcl.co.in/",
    eligibility: ["Active FASTag account", "Valid KYC on record"],
    documentsRequired: ["FASTag account / wallet ID", "RC number", "Aadhaar of owner (for replacement)"],
    fee: 100,
    feeNote: "Recharge free; ₹100 replacement tag + ₹200 refundable security deposit.",
    processingTime: "Recharge instant; replacement 5–7 days",
    howToApply: [
      "Open your FASTag issuing bank's app or UPI app.",
      "Select FASTag recharge and enter vehicle number / wallet ID.",
      "Pay via UPI / cards / net banking — instant credit.",
      "For replacement: raise request on bank portal with reason.",
      "Old tag deactivated; new tag dispatched; balance carried forward.",
    ],
    serviceCharge: 30,
    popularity: 80,
    tags: ["fastag recharge", "fastag replacement", "ihmcl", "toll"],
    online: true,
  },
  {
    id: "rto-noc-inter-state-transfer",
    slug: "rto-noc-inter-state-transfer",
    name: "RTO NOC (Inter-state Vehicle Transfer)",
    category: "transport-vehicles",
    subcategory: "Vehicle Registration",
    summary: "Get NOC from current RTO to re-register your vehicle in another state.",
    description:
      "An NOC from the original RTO is required when a vehicle is moved to another state for more than 12 months. The NOC confirms no dues, theft, or hypothecation pending, and enables fresh registration in the new state.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: [
      "Vehicle registered in current state for at least 6 months",
      "No pending tax, challan, or hypothecation (or NOC from financer)",
      "Vehicle not involved in any criminal case",
    ],
    documentsRequired: [
      "Original RC",
      "Form 28 (3 copies)",
      "Insurance and PUC",
      "Address proof of new state",
      "Aadhaar of owner",
      "Crime report clearance (printed at RTO)",
    ],
    fee: 100,
    feeNote: "₹100 NOC fee; state charges for verification may apply.",
    processingTime: "7–30 days",
    howToApply: [
      "Open Vahan portal → 'Issue of NOC'.",
      "Enter RC number and destination state.",
      "Upload Form 28 and documents.",
      "Pay fee online.",
      "Visit RTO for crime branch verification; NOC issued.",
    ],
    serviceCharge: 110,
    popularity: 58,
    tags: ["noc", "inter-state transfer", "vehicle transfer", "vahan"],
    online: true,
  },
  {
    id: "contract-carriage-permit",
    slug: "contract-carriage-permit",
    name: "Contract Carriage Permit",
    category: "transport-vehicles",
    subcategory: "Permits",
    summary: "Get a permit to operate taxis, autos, and contract carriages commercially.",
    description:
      "A contract carriage permit authorises a vehicle to carry passengers on a contractual basis (taxis, autos, app-based cabs). Permits are issued by the State Transport Authority (STA) or Regional Transport Authority (RTA) and are valid for 5 years.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: [
      "Vehicle registered as commercial / transport vehicle",
      "Holds commercial DL with badge",
      "Vehicle has valid fitness, insurance, PUC",
    ],
    documentsRequired: [
      "RC of commercial vehicle",
      "Commercial DL with badge",
      "Fitness certificate",
      "Insurance and PUC",
      "Form P.C.P.S.",
      "Tax clearance",
    ],
    fee: 500,
    feeNote: "₹500–₹5000 depending on vehicle type and state; annual renewal fee extra.",
    processingTime: "15–45 days",
    howToApply: [
      "Open Vahan portal → 'Permit' → 'Contract Carriage'.",
      "Fill Form P.C.P.S. and upload vehicle and driver documents.",
      "Pay permit fee online.",
      "Attend STA/RTA hearing if listed.",
      "Permit issued; printed and dispatched.",
    ],
    serviceCharge: 130,
    popularity: 45,
    tags: ["contract carriage", "taxi permit", "auto permit", "vahan"],
    online: true,
  },
  {
    id: "goods-carriage-permit",
    slug: "goods-carriage-permit",
    name: "Goods Carriage Permit",
    category: "transport-vehicles",
    subcategory: "Permits",
    summary: "Get a permit to operate a goods/commercial vehicle for freight transport.",
    description:
      "A goods carriage permit authorises use of a motor vehicle for transporting goods for hire or reward. It is issued by the State Transport Authority and is mandatory for trucks, tempos, and other freight vehicles operating commercially.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: [
      "Vehicle registered as goods carrier",
      "Commercial DL holder",
      "Valid fitness, insurance, PUC",
    ],
    documentsRequired: [
      "RC of goods vehicle",
      "Commercial DL",
      "Fitness certificate",
      "Insurance and PUC",
      "Form P.C.P.S.",
      "Tax clearance",
    ],
    fee: 1000,
    feeNote: "₹1000–₹5000 state fee; Goods Carriage Agreement stamp paper ₹100.",
    processingTime: "15–45 days",
    howToApply: [
      "Open Vahan portal → 'Permit' → 'Goods Carriage'.",
      "Fill Form P.C.P.S. and upload vehicle documents.",
      "Pay permit fee online.",
      "Attend STA hearing if required.",
      "Permit issued on approval.",
    ],
    serviceCharge: 130,
    popularity: 42,
    tags: ["goods carriage", "truck permit", "freight permit", "vahan"],
    online: true,
  },
  {
    id: "tourist-permit",
    slug: "tourist-permit",
    name: "Tourist Permit",
    category: "transport-vehicles",
    subcategory: "Permits",
    summary: "Get an All India Tourist Permit to operate tourist vehicles across India.",
    description:
      "An All India Tourist Permit (AITP) allows a vehicle to carry tourists across all states without requiring separate state permits. The vehicle must meet tourism-vehicle specifications including colour scheme, fitness, and driver badge.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "Parivahan Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: [
      "Vehicle is a tourist vehicle as per MV Act",
      "White number plate with 'Tourist' marking",
      "Commercial DL with badge",
      "Empanelled with a tourism operator (preferred)",
    ],
    documentsRequired: [
      "RC of vehicle",
      "Commercial DL",
      "Fitness certificate",
      "Insurance (comprehensive)",
      "PUC certificate",
      "Form P.T.A.",
      "Tax clearance certificate",
    ],
    fee: 1000,
    feeNote: "₹1000 AITP fee + ₹500 per seat tax (state-wise additional fees apply).",
    processingTime: "15–45 days",
    howToApply: [
      "Open Vahan portal → 'Permit' → 'Tourist Permit'.",
      "Fill Form P.T.A. and upload vehicle documents.",
      "Pay AITP fee online.",
      "STA verifies documents and vehicle specifications.",
      "All India Tourist Permit issued.",
    ],
    serviceCharge: 140,
    popularity: 38,
    tags: ["tourist permit", "aitp", "tourist vehicle", "vahan"],
    online: true,
  },
  {
    id: "vehicle-insurance-e-vahan-bima",
    slug: "vehicle-insurance-e-vahan-bima",
    name: "Vehicle Insurance (e-Vahan Bima)",
    category: "transport-vehicles",
    subcategory: "Insurance",
    summary: "Buy third-party / comprehensive motor insurance with digital e-Vahan Bima.",
    description:
      "Third-party motor insurance is mandatory for all vehicles in India under the MV Act. The e-Vahan Bima is a digital insurance certificate linked to the Vahan database, instantly verifiable by traffic police. Comprehensive covers are offered by IRDAI-licensed insurers.",
    ministry: "Ministry of Road Transport & Highways (MoRTH)",
    officialPortal: "IRDAI / Vahan",
    officialUrl: "https://vahan.parivahan.gov.in/",
    eligibility: [
      "Owner of a registered motor vehicle",
      "Vehicle has valid RC",
    ],
    documentsRequired: [
      "RC copy",
      "Previous insurance policy (for renewal)",
      "Aadhaar / PAN of owner",
    ],
    fee: 0,
    feeNote: "Premium varies by vehicle type — typically ₹500–₹3000 for third-party; comprehensive higher.",
    processingTime: "Instant (digital policy)",
    howToApply: [
      "Visit insurer website or Vahan 'Insurance' tab.",
      "Enter RC number; vehicle details fetched automatically.",
      "Choose third-party or comprehensive plan.",
      "Pay premium online.",
      "Digital e-Vahan Bima issued and synced to Vahan database.",
    ],
    serviceCharge: 50,
    popularity: 84,
    tags: ["vehicle insurance", "e-vahan bima", "third party", "motor insurance"],
    online: true,
  },
];
