// Tilak E-Seva Portal — Utilities services catalog.
// Real Indian Government / PSU services covering electricity, water, gas, and telecom.
// Reference portals: state DISCOM websites, mybsnl.in, bharatgas.in, indane.co.in,
// hpgas.in, iglonline.net, mypgclonline.org, mymglonline.in.

import type { GovernmentService } from "../types";

export const utilities: GovernmentService[] = [
  {
    id: "electricity-new-connection-urban",
    slug: "electricity-new-connection-urban",
    name: "Electricity New Connection (Urban DISCOM)",
    category: "utilities",
    subcategory: "Electricity",
    summary: "Apply for a new domestic electricity connection from your city DISCOM.",
    description:
      "An urban electricity connection is provided by the distribution company (DISCOM) for your area — e.g. BSES / TPDDL (Delhi), Adani Electricity (Mumbai), TANGEDCO (Chennai), CESC (Kolkata). Online applications are accepted via the DISCOM website or the state's single-window portal.",
    ministry: "Ministry of Power (through state DISCOMs)",
    officialPortal: "State DISCOM Website",
    officialUrl: "https://www.powermin.gov.in/",
    eligibility: [
      "Owner or tenant of a premises needing supply",
      "Premises has a valid address and wiring completion report",
      "No outstanding dues on the premises",
    ],
    documentsRequired: [
      "Proof of ownership / rent agreement",
      "Address proof (Aadhaar, voter ID)",
      "Identity proof (Aadhaar / PAN)",
      "Electrical wiring completion certificate (licensed electrician)",
      "NOC from owner (if tenant)",
      "Passport-size photo",
    ],
    fee: 500,
    feeNote: "₹500 application + security deposit (₹1000–₹5000 by load); extra for single/three-phase.",
    processingTime: "7–30 days",
    howToApply: [
      "Visit your DISCOM's website (e.g. tpddl.com, adanielectricity.com).",
      "Register / log in and open 'New Connection' application.",
      "Fill premises, load, and applicant details.",
      "Upload address proof and wiring certificate.",
      "Pay application fee + security deposit online.",
      "Field inspection scheduled; meter installed on approval.",
    ],
    serviceCharge: 120,
    popularity: 88,
    tags: ["electricity", "new connection", "discom", "urban", "power"],
    online: true,
  },
  {
    id: "electricity-name-change",
    slug: "electricity-name-change",
    name: "Electricity Name Change",
    category: "utilities",
    subcategory: "Electricity",
    summary: "Transfer the electricity connection to a new owner or tenant after sale/lease.",
    description:
      "When ownership of a premises changes (sale, inheritance, or new tenant), the electricity connection must be transferred to the new consumer's name. The DISCOM issues a fresh consumer number; pending dues of the previous consumer must be cleared.",
    ministry: "Ministry of Power (through state DISCOMs)",
    officialPortal: "State DISCOM Website",
    officialUrl: "https://www.powermin.gov.in/",
    eligibility: ["New legal owner or tenant of the premises", "No outstanding dues on the connection"],
    documentsRequired: [
      "Sale deed / gift deed / rent agreement",
      "Previous consumer's NOC",
      "Address proof",
      "Aadhaar / PAN of new applicant",
      "Latest electricity bill",
      "Indemnity bond (if required)",
    ],
    fee: 100,
    feeNote: "₹100–₹500 name-change fee; security deposit adjustment may apply.",
    processingTime: "7–30 days",
    howToApply: [
      "Open your DISCOM portal → 'Name Change'.",
      "Enter existing consumer number.",
      "Upload ownership proof and KYC.",
      "Pay name-change fee online.",
      "Field verification done; new consumer number issued.",
    ],
    serviceCharge: 80,
    popularity: 70,
    tags: ["electricity", "name change", "discom", "transfer"],
    online: true,
  },
  {
    id: "electricity-load-enhancement",
    slug: "electricity-load-enhancement",
    name: "Electricity Load Enhancement",
    category: "utilities",
    subcategory: "Electricity",
    summary: "Increase the sanctioned load of your electricity connection (e.g. 2 kW to 5 kW).",
    description:
      "Load enhancement is required when adding high-wattage appliances like ACs, geysers, or EV chargers that exceed the sanctioned load. The DISCOM inspects the wiring and issues a revised sanction letter; an additional security deposit is charged pro-rata.",
    ministry: "Ministry of Power (through state DISCOMs)",
    officialPortal: "State DISCOM Website",
    officialUrl: "https://www.powermin.gov.in/",
    eligibility: ["Existing consumer with valid connection", "Wiring supports the requested higher load"],
    documentsRequired: [
      "Latest electricity bill",
      "Aadhaar / PAN",
      "Revised wiring completion certificate",
      "Sanction letter of existing load",
    ],
    fee: 100,
    feeNote: "₹100 application + additional security deposit proportional to added load.",
    processingTime: "7–21 days",
    howToApply: [
      "Open DISCOM portal → 'Load Enhancement'.",
      "Enter consumer number and requested new load.",
      "Upload revised wiring certificate.",
      "Pay additional security deposit online.",
      "Field inspection and revised sanction letter issued.",
    ],
    serviceCharge: 90,
    popularity: 55,
    tags: ["electricity", "load enhancement", "load increase", "discom"],
    online: true,
  },
  {
    id: "electricity-bill-payment",
    slug: "electricity-bill-payment",
    name: "Electricity Bill Payment",
    category: "utilities",
    subcategory: "Electricity",
    summary: "Pay your monthly electricity bill online instantly via UPI, cards, or net banking.",
    description:
      "Electricity bills can be paid online through DISCOM websites, BBPS-enabled apps (BHIM, PhonePe, Google Pay, Paytm), and the Umang app. Payments are reflected instantly and digital receipts are issued, avoiding late-payment surcharges.",
    ministry: "Ministry of Power (through state DISCOMs)",
    officialPortal: "DISCOM / Bharat BillPay (BBPS)",
    officialUrl: "https://www.bharatbillpay.net/",
    eligibility: ["Active electricity connection", "Consumer number / billing unit details"],
    documentsRequired: ["Electricity bill / consumer number"],
    fee: 0,
    feeNote: "No convenience fee on DISCOM website; apps may charge ₹0–₹5.",
    processingTime: "Instant",
    howToApply: [
      "Open DISCOM website or BBPS-enabled UPI app.",
      "Select 'Electricity' and your DISCOM.",
      "Enter consumer number and fetch bill.",
      "Verify amount and pay via UPI / card / net banking.",
      "Download digital receipt.",
    ],
    serviceCharge: 25,
    popularity: 92,
    tags: ["electricity bill", "bill payment", "bbps", "discom"],
    online: true,
  },
  {
    id: "solar-rooftop-net-metering",
    slug: "solar-rooftop-net-metering",
    name: "Solar Rooftop Net-Metering",
    category: "utilities",
    subcategory: "Electricity",
    summary: "Install rooftop solar panels and feed surplus power back to the grid via net-metering.",
    description:
      "Under the PM Surya Ghar: Muft Bijli Yojana, residential consumers can install rooftop solar (1–10 kW) and export surplus power to the grid. The DISCOM installs a bi-directional meter and credits the exported units against future consumption. Central financial assistance up to ₹78,000 is available.",
    ministry: "Ministry of New and Renewable Energy (MNRE)",
    officialPortal: "PM Surya Ghar Portal",
    officialUrl: "https://pmsuryaghar.gov.in/",
    eligibility: [
      "Residential consumer with valid electricity connection",
      "Rooftop area suitable for solar (10 m² per kW)",
      "Aadhaar-linked bank account for subsidy",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Latest electricity bill / consumer number",
      "Rooftop ownership proof",
      "Bank account details",
      "Passport-size photo",
    ],
    fee: 0,
    feeNote: "No application fee; subsidy ₹30,000–₹78,000 for 1–3 kW; consumer pays balance after subsidy.",
    processingTime: "30–90 days (post-installation & net-metering approval)",
    howToApply: [
      "Register on pmsuryaghar.gov.in with Aadhaar and consumer number.",
      "Apply for rooftop solar; choose DISCOM-empanelled vendor.",
      "Vendor installs panels and bi-directional meter.",
      "DISCOM inspects and approves net-metering.",
      "Subsidy credited to your bank account within 30 days of commissioning.",
    ],
    serviceCharge: 150,
    popularity: 72,
    tags: ["solar", "rooftop", "net metering", "pm surya ghar", "mnre"],
    online: true,
  },
  {
    id: "water-connection-urban",
    slug: "water-connection-urban",
    name: "Water Connection (Urban)",
    category: "utilities",
    subcategory: "Water",
    summary: "Apply for a new domestic water connection from your city Jal Board / municipal water authority.",
    description:
      "An urban water connection is provided by the local water utility (e.g. DJB Delhi, BMC Mumbai, HMWSSB Hyderabad, BWSSB Bengaluru). Online applications are accepted on the respective utility's website with document upload and fee payment.",
    ministry: "Ministry of Housing & Urban Affairs (through local bodies)",
    officialPortal: "City Jal Board / Water Utility",
    officialUrl: "https://jalboard.delhi.gov.in/",
    eligibility: [
      "Owner or tenant of premises within the utility's jurisdiction",
      "Property has valid address and internal plumbing",
      "No outstanding water tax dues",
    ],
    documentsRequired: [
      "Property ownership proof / rent agreement",
      "Address proof",
      "Aadhaar / PAN",
      "Indemnity bond (for tenants)",
      "Plumbing completion certificate",
    ],
    fee: 500,
    feeNote: "₹500–₹5000 connection fee + ₹1000–₹5000 refundable security deposit.",
    processingTime: "15–45 days",
    howToApply: [
      "Visit your city water utility's website (e.g. delhijalboard.delhi.gov.in).",
      "Register and apply for 'New Water Connection'.",
      "Fill property and applicant details.",
      "Upload documents and pay connection fee + security deposit.",
      "Field inspection; water meter installed on approval.",
    ],
    serviceCharge: 110,
    popularity: 80,
    tags: ["water", "new connection", "jal board", "urban", "municipal"],
    online: true,
  },
  {
    id: "water-connection-rural",
    slug: "water-connection-rural",
    name: "Water Connection (Rural)",
    category: "utilities",
    subcategory: "Water",
    summary: "Apply for a household tap water connection under Jal Jeevan Mission in rural areas.",
    description:
      "Under the Jal Jeevan Mission (JJM), every rural household is provided a Functional Household Tap Connection (FHTC) supplying 55 litres per capita per day. Applications are made through the Gram Panchayat or state's JJM portal free of cost for BPL families.",
    ministry: "Ministry of Jal Shakti (Department of Drinking Water & Sanitation)",
    officialPortal: "Jal Jeevan Mission / State Water & Sanitation Mission",
    officialUrl: "https://jaljeevanmission.gov.in/",
    eligibility: ["Rural household with a valid address", "Listed in the Gram Panchayat records"],
    documentsRequired: [
      "Aadhaar of household head",
      "Ration card",
      "Bank account details (for any DBT)",
      "Property / Khasra details",
    ],
    fee: 0,
    feeNote: "Free for BPL households; APL families may pay a nominal ₹100–₹500 depending on state.",
    processingTime: "30–90 days",
    howToApply: [
      "Approach the Gram Panchayat / Village Water & Sanitation Committee.",
      "Submit JJM application with Aadhaar and ration card.",
      "VWSC verifies and approves.",
      "PHE department lays pipeline and installs tap.",
      "Connection activated; test report updated on JJM IMIS.",
    ],
    serviceCharge: 60,
    popularity: 68,
    tags: ["jal jeevan mission", "rural water", "fhtc", "jal shakti"],
    online: false,
  },
  {
    id: "water-bill-payment",
    slug: "water-bill-payment",
    name: "Water Bill Payment",
    category: "utilities",
    subcategory: "Water",
    summary: "Pay your monthly / quarterly water bill online instantly.",
    description:
      "Water bills can be paid online via the city Jal Board's website or BBPS-enabled apps. Most utilities (DJB, BWSSB, HMWSSB) accept UPI, cards, and net banking with instant receipt generation; some offer 5–10% rebate for online payment.",
    ministry: "Ministry of Housing & Urban Affairs (through local bodies)",
    officialPortal: "City Jal Board / BBPS",
    officialUrl: "https://www.bharatbillpay.net/",
    eligibility: ["Active water connection", "Consumer number / billing details"],
    documentsRequired: ["Water bill / consumer number"],
    fee: 0,
    feeNote: "Free on utility website; apps may charge ₹0–₹5.",
    processingTime: "Instant",
    howToApply: [
      "Open your city Jal Board website or BBPS UPI app.",
      "Select 'Water' and choose your utility.",
      "Enter consumer number and fetch bill.",
      "Pay via UPI / cards / net banking.",
      "Download digital receipt.",
    ],
    serviceCharge: 25,
    popularity: 84,
    tags: ["water bill", "bill payment", "bbps", "jal board"],
    online: true,
  },
  {
    id: "water-sewerage-connection",
    slug: "water-sewerage-connection",
    name: "Water Sewerage Connection",
    category: "utilities",
    subcategory: "Water",
    summary: "Apply for a domestic sewerage connection to the city's underground drainage network.",
    description:
      "A sewerage connection links a household's wastewater outlet to the city's underground drainage network, managed by the local Jal Board or sewerage board (e.g. DJB, Chennai Metro Water). Mandatory for properties in areas where the sewer network is available.",
    ministry: "Ministry of Housing & Urban Affairs (through local bodies)",
    officialPortal: "City Jal / Sewerage Board",
    officialUrl: "https://jalboard.delhi.gov.in/",
    eligibility: [
      "Property within the sewerage network coverage area",
      "Property has internal plumbing and a septic / inspection chamber",
      "Valid water connection (in most cities)",
    ],
    documentsRequired: [
      "Property ownership proof",
      "Address proof",
      "Aadhaar / PAN",
      "Water connection details / bill",
      "Plumbing diagram",
    ],
    fee: 1000,
    feeNote: "₹1000–₹5000 sewerage connection fee; refundable security deposit varies.",
    processingTime: "15–60 days",
    howToApply: [
      "Visit your city Jal / Sewerage Board portal.",
      "Apply for 'New Sewerage Connection'.",
      "Fill property and applicant details.",
      "Upload ownership proof and plumbing diagram.",
      "Pay connection fee; field inspection & connection done.",
    ],
    serviceCharge: 110,
    popularity: 55,
    tags: ["sewerage", "drainage", "jal board", "sewer connection"],
    online: true,
  },
  {
    id: "png-gas-connection",
    slug: "png-gas-connection",
    name: "PNG Gas Connection (IGL / MGL)",
    category: "utilities",
    subcategory: "Gas",
    summary: "Apply for a Piped Natural Gas (PNG) domestic connection from IGL, MGL, or your city CGD.",
    description:
      "Piped Natural Gas (PNG) is supplied to households through a city gas distribution (CGD) network — e.g. Indraprastha Gas (IGL, Delhi NCR), Mahanagar Gas (MGL, Mumbai), Adani Gas, GAIL Gas. PNG is cheaper and safer than LPG cylinders for cooking.",
    ministry: "Ministry of Petroleum & Natural Gas (through PNGRB-licensed CGDs)",
    officialPortal: "City Gas Distribution Company",
    officialUrl: "https://www.iglonline.com/",
    eligibility: [
      "Residence in a CGD network coverage area",
      "Society / RWA has obtained bulk connection approval",
      "Owner or tenant with valid address proof",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Address proof",
      "Property ownership / NOC from owner",
      "Passport-size photo",
      "Society NOC (for flats)",
    ],
    fee: 6000,
    feeNote: "₹6000 one-time (refundable ₹4000 + non-refundable ₹2000); stove & pipe extra.",
    processingTime: "30–90 days",
    howToApply: [
      "Visit your CGD website (e.g. iglonline.com, mahanagargas.com).",
      "Register and apply for 'New Domestic PNG Connection'.",
      "Fill premises and applicant details; upload KYC.",
      "Pay ₹6000 connection charges online.",
      "CGD inspects premises; pipeline laid & meter installed; connection activated.",
    ],
    serviceCharge: 120,
    popularity: 62,
    tags: ["png", "piped gas", "igl", "mgl", "cgd"],
    online: true,
  },
  {
    id: "lpg-new-connection-indane",
    slug: "lpg-new-connection-indane",
    name: "LPG New Connection (Indane)",
    category: "utilities",
    subcategory: "Gas",
    summary: "Book a new Indane LPG domestic cylinder connection from Indian Oil.",
    description:
      "Indane, marketed by Indian Oil Corporation (IOCL), is one of India's largest LPG brands. New connections are booked through the SAHAJ portal or Indane mobile app; KYC, deposit, and an optional hotplate (stove) purchase are required at the time of release.",
    ministry: "Ministry of Petroleum & Natural Gas (IOCL)",
    officialPortal: "Indane / SAHAJ e-SV",
    officialUrl: "https://indane.co.in/",
    eligibility: ["Indian citizen aged 18+", "No existing LPG connection in the household (PAHAL rules)"],
    documentsRequired: [
      "Aadhaar card",
      "Proof of address",
      "Passport-size photograph",
      "Bank account details (for PAHAL subsidy)",
      "Optional: hotplate / regulator purchase receipt",
    ],
    fee: 1450,
    feeNote: "₹1450 security deposit for 2 cylinders + regulator; stove cost extra (₹1500–₹2500).",
    processingTime: "1–7 days",
    howToApply: [
      "Visit indane.co.in → 'Apply for New Connection'.",
      "Locate nearest distributor via PIN code.",
      "Register with Aadhaar and upload KYC.",
      "Pay security deposit + stove cost online.",
      "Visit distributor with originals; SV (subscription voucher) issued; first cylinder delivered.",
    ],
    serviceCharge: 100,
    popularity: 90,
    tags: ["lpg", "indane", "ioc", "cooking gas", "new connection"],
    online: true,
  },
  {
    id: "lpg-new-connection-bharat-gas",
    slug: "lpg-new-connection-bharat-gas",
    name: "LPG New Connection (Bharat Gas)",
    category: "utilities",
    subcategory: "Gas",
    summary: "Book a new Bharat Gas LPG domestic cylinder connection from BPCL.",
    description:
      "Bharat Gas is the LPG brand of Bharat Petroleum Corporation Limited (BPCL). New domestic connections can be booked online via the Bharat Gas website or mobile app. KYC and security deposit are required; the first cylinder and DIN (Distributor Initiated Number) are issued at the time of release.",
    ministry: "Ministry of Petroleum & Natural Gas (BPCL)",
    officialPortal: "Bharat Gas",
    officialUrl: "https://www.bharatgas.com/",
    eligibility: ["Indian citizen aged 18+", "No existing LPG connection in the household"],
    documentsRequired: [
      "Aadhaar card",
      "Proof of address",
      "Passport-size photograph",
      "Bank passbook / account details",
      "Hotplate purchase receipt (optional)",
    ],
    fee: 1450,
    feeNote: "₹1450 security deposit for 2 cylinders + regulator; stove cost extra.",
    processingTime: "1–7 days",
    howToApply: [
      "Visit bharatgas.com → 'Book New Connection'.",
      "Enter PIN code and select nearest distributor.",
      "Register with Aadhaar; upload KYC documents.",
      "Pay security deposit + optional stove online.",
      "Visit distributor with originals; SV issued; cylinder delivered.",
    ],
    serviceCharge: 100,
    popularity: 90,
    tags: ["lpg", "bharat gas", "bpcl", "cooking gas", "new connection"],
    online: true,
  },
  {
    id: "lpg-new-connection-hp-gas",
    slug: "lpg-new-connection-hp-gas",
    name: "LPG New Connection (HP Gas)",
    category: "utilities",
    subcategory: "Gas",
    summary: "Book a new HP Gas LPG domestic cylinder connection from Hindustan Petroleum.",
    description:
      "HP Gas is the LPG brand of Hindustan Petroleum Corporation Limited (HPCL). New domestic connections are booked online through the HP Gas portal; KYC verification and security deposit are required. The first refill is delivered after SV (subscription voucher) issuance.",
    ministry: "Ministry of Petroleum & Natural Gas (HPCL)",
    officialPortal: "HP Gas",
    officialUrl: "https://www.hpgas.com/",
    eligibility: ["Indian citizen aged 18+", "No existing LPG connection in the household"],
    documentsRequired: [
      "Aadhaar card",
      "Proof of address",
      "Passport-size photograph",
      "Bank account details",
      "Hotplate receipt (optional)",
    ],
    fee: 1450,
    feeNote: "₹1450 security deposit + regulator; stove cost extra (₹1500–₹2500).",
    processingTime: "1–7 days",
    howToApply: [
      "Visit hpgas.com → 'New Connection'.",
      "Locate nearest distributor by PIN code.",
      "Register with Aadhaar; upload KYC.",
      "Pay security deposit + stove (optional) online.",
      "Visit distributor with originals; SV issued; cylinder delivered.",
    ],
    serviceCharge: 100,
    popularity: 88,
    tags: ["lpg", "hp gas", "hpcl", "cooking gas", "new connection"],
    online: true,
  },
  {
    id: "lpg-pahal-subsidy-registration",
    slug: "lpg-pahal-subsidy-registration",
    name: "LPG Subsidy (PAHAL) Registration",
    category: "utilities",
    subcategory: "Gas",
    summary: "Link your Aadhaar / bank account to receive PAHAL LPG subsidy directly.",
    description:
      "PAHAL (DBTL) is the world's largest direct benefit transfer scheme. LPG consumers receive the subsidy on each refill directly into their bank account after linking Aadhaar (or bank account) to the LPG consumer number. Currently the subsidy is credited for eligible consumers (small ring-keeps may apply).",
    ministry: "Ministry of Petroleum & Natural Gas (PPAC)",
    officialPortal: "PAHAL / MyLPG.in",
    officialUrl: "https://mylpg.in/",
    eligibility: [
      "Active domestic LPG connection (Indane/Bharat/HP)",
      "Aadhaar linked to LPG consumer number",
      "Bank account linked to Aadhaar",
    ],
    documentsRequired: [
      "Aadhaar card",
      "LPG consumer number / SV",
      "Bank account details",
      "Mobile number linked with Aadhaar",
    ],
    fee: 0,
    feeNote: "Free registration; subsidy credited per cylinder (variable, government-notified).",
    processingTime: "1–7 days for linking; subsidy credit per refill within 2–3 days",
    howToApply: [
      "Visit mylpg.in → select your distributor & brand.",
      "Choose 'Link Aadhaar to LPG' or 'Link Bank to LPG'.",
      "Fill Aadhaar, consumer number, and bank details.",
      "Submit; OTP verification via SMS.",
      "Confirmation SMS on successful linking; subsidy auto-credited on each refill.",
    ],
    serviceCharge: 50,
    popularity: 85,
    tags: ["pahal", "lpg subsidy", "dbtl", "subsidy", "aadhaar link"],
    online: true,
  },
  {
    id: "lpg-cylinder-booking",
    slug: "lpg-cylinder-booking",
    name: "LPG Cylinder Booking / Refill",
    category: "utilities",
    subcategory: "Gas",
    summary: "Book an LPG refill online, via SMS, IVRS, WhatsApp, or UPI app.",
    description:
      "LPG refill bookings can be made through multiple channels — the brand's app/website, SMS to designated number, IVRS call, WhatsApp, or via UPI apps under BBPS. Delivery is generally made within 2–7 days; bookings are tracked via a 9-digit DIN (Distributor Initiated Number).",
    ministry: "Ministry of Petroleum & Natural Gas (IOCL / BPCL / HPCL)",
    officialPortal: "MyLPG.in / Brand App",
    officialUrl: "https://mylpg.in/",
    eligibility: ["Active domestic LPG connection", "Bookings must respect the 15-day cooling-off gap"],
    documentsRequired: ["LPG consumer number / mobile number"],
    fee: 0,
    feeNote: "Refill price ₹800–₹1200 (varies monthly); subsidy credited if eligible.",
    processingTime: "2–7 days",
    howToApply: [
      "Visit your LPG brand app/website or use SMS/IVRS.",
      "Enter consumer number and authenticate via OTP.",
      "Confirm refill booking; DIN generated.",
      "Track delivery via app or distributor SMS.",
      "Make payment to delivery person or via online mode.",
    ],
    serviceCharge: 25,
    popularity: 92,
    tags: ["lpg refill", "cylinder booking", "indane", "bharat gas", "hp gas"],
    online: true,
  },
  {
    id: "lpg-surrender-connection",
    slug: "lpg-surrender-connection",
    name: "LPG Surrender Connection",
    category: "utilities",
    subcategory: "Gas",
    summary: "Surrender your LPG connection and claim refund of the security deposit.",
    description:
      "When a consumer no longer needs an LPG connection (relocated abroad, switched to PNG, or duplicate connection detected), the connection can be surrendered at the distributor. The security deposit is refunded via NEFT/cheque after deducting cylinder and regulator condition-based charges.",
    ministry: "Ministry of Petroleum & Natural Gas (IOCL / BPCL / HPCL)",
    officialPortal: "MyLPG.in",
    officialUrl: "https://mylpg.in/",
    eligibility: ["Active LPG connection in your name", "No outstanding dues or refills pending"],
    documentsRequired: [
      "Original SV / subscription voucher",
      "Cylinder and regulator (in good condition)",
      "Aadhaar card",
      "Bank account details for refund",
    ],
    fee: 0,
    feeNote: "Refund ₹1450 per cylinder + ₹150 regulator (deductions for damage may apply).",
    processingTime: "Same day at distributor; refund credit 7–15 days",
    howToApply: [
      "Visit your LPG distributor with SV, cylinder, and regulator.",
      "Submit surrender request form.",
      "Distributor inspects equipment; deductions noted if any.",
      "Termination voucher issued; refund initiated to bank.",
      "Connection closed in petroleum ministry records.",
    ],
    serviceCharge: 50,
    popularity: 40,
    tags: ["lpg surrender", "lpg termination", "connection closure"],
    online: false,
  },
  {
    id: "bsnl-new-landline",
    slug: "bsnl-new-landline",
    name: "BSNL New Landline Connection",
    category: "utilities",
    subcategory: "Telecom",
    summary: "Apply for a new BSNL landline telephone connection.",
    description:
      "Bharat Sanchar Nigam Limited (BSNL) provides landline telephone connections across India (except Delhi & Mumbai, served by MTNL). New connections can be booked online via BSNL's self-care portal with free installation in many circles; combined landline+broadband plans are popular.",
    ministry: "Ministry of Communications (BSNL)",
    officialPortal: "BSNL Self-Care",
    officialUrl: "https://selfcare.bsnl.co.in/",
    eligibility: ["Resident / business in a BSNL-served area", "Address proof of premises"],
    documentsRequired: [
      "Aadhaar card",
      "Address proof",
      "Passport-size photo",
      "Demand draft / online payment receipt",
    ],
    fee: 500,
    feeNote: "₹500 installation; refundable security deposit ₹1000–₹2000; plan rental monthly.",
    processingTime: "7–30 days",
    howToApply: [
      "Visit selfcare.bsnl.co.in → 'New Connection'.",
      "Choose 'Landline' and select plan.",
      "Fill applicant and premises details.",
      "Upload KYC and pay installation + security deposit.",
      "BSNL field team installs line & instrument; number allotted.",
    ],
    serviceCharge: 90,
    popularity: 48,
    tags: ["bsnl", "landline", "new connection", "telecom"],
    online: true,
  },
  {
    id: "bsnl-new-mobile-connection",
    slug: "bsnl-new-mobile-connection",
    name: "BSNL New Mobile Connection",
    category: "utilities",
    subcategory: "Telecom",
    summary: "Get a new BSNL prepaid or postpaid mobile SIM with free home delivery.",
    description:
      "BSNL offers new prepaid and postpaid mobile connections with free SIM home delivery in most circles. The process is fully digital via Aadhaar e-KYC; activation typically takes 24–72 hours after biometric verification at the doorstep.",
    ministry: "Ministry of Communications (BSNL)",
    officialPortal: "BSNL Self-Care",
    officialUrl: "https://selfcare.bsnl.co.in/",
    eligibility: ["Indian citizen aged 18+", "Aadhaar for e-KYC", "Address in BSNL service area"],
    documentsRequired: [
      "Aadhaar card (for e-KYC)",
      "Passport-size photo",
      "Alternate mobile number",
    ],
    fee: 100,
    feeNote: "₹100 SIM cost; first recharge ₹100–₹200; security deposit ₹500 for postpaid.",
    processingTime: "24–72 hours after e-KYC",
    howToApply: [
      "Visit selfcare.bsnl.co.in or BSNL app → 'New SIM'.",
      "Choose prepaid / postpaid and circle.",
      "Fill Aadhaar details and book home delivery.",
      "Delivery agent completes biometric e-KYC.",
      "SIM activated in 24–72 hours after tele-verification.",
    ],
    serviceCharge: 60,
    popularity: 65,
    tags: ["bsnl", "mobile", "sim", "prepaid", "postpaid", "ekyc"],
    online: true,
  },
  {
    id: "bsnl-broadband-connection",
    slug: "bsnl-broadband-connection",
    name: "BSNL Broadband Connection (Bharat Fiber / DSL)",
    category: "utilities",
    subcategory: "Telecom",
    summary: "Apply for BSNL Bharat Fiber (FTTH) or DSL broadband at your home or office.",
    description:
      "BSNL provides Bharat Fiber (FTTH) gigabit broadband and VDSL/copper broadband across India. New connections can be booked online via the BSNL self-care portal; plans start from ₹449/month. A landline is bundled on copper, while FTTH offers voice calling over fiber.",
    ministry: "Ministry of Communications (BSNL)",
    officialPortal: "BSNL Self-Care / Bharat Fiber",
    officialUrl: "https://bharatfiber.bsnl.co.in/",
    eligibility: ["Resident / business in a BSNL-served area", "Existing BSNL landline (for DSL) or fiber feasibility (FTTH)"],
    documentsRequired: [
      "Aadhaar card",
      "Address proof",
      "Passport-size photo",
      "Existing landline number (for DSL)",
    ],
    fee: 500,
    feeNote: "₹500 installation; ONT/router ₹1000–₹2000 (refundable); plan rental monthly.",
    processingTime: "7–21 days",
    howToApply: [
      "Visit bharatfiber.bsnl.co.in → 'Book New Connection'.",
      "Select plan and feasibility check by PIN code.",
      "Fill applicant and premises details.",
      "Upload KYC and pay installation + plan rental.",
      "BSNL technician installs ONT / modem; connection activated.",
    ],
    serviceCharge: 100,
    popularity: 70,
    tags: ["bsnl", "broadband", "bharat fiber", "ftth", "internet"],
    online: true,
  },
  {
    id: "bsnl-bill-payment",
    slug: "bsnl-bill-payment",
    name: "BSNL Bill Payment",
    category: "utilities",
    subcategory: "Telecom",
    summary: "Pay your BSNL landline, mobile, or broadband bill online instantly.",
    description:
      "BSNL bills for landline, mobile (postpaid), and broadband can be paid online via the BSNL self-care portal, BSNL app, BBPS-enabled UPI apps, or third-party apps. Payments are reflected instantly and digital receipts are issued; auto-pay can also be set up.",
    ministry: "Ministry of Communications (BSNL)",
    officialPortal: "BSNL Self-Care / BBPS",
    officialUrl: "https://selfcare.bsnl.co.in/",
    eligibility: ["Active BSNL connection", "Consumer / mobile number for billing"],
    documentsRequired: ["BSNL phone / account number"],
    fee: 0,
    feeNote: "Free on BSNL portal; apps may charge ₹0–₹5.",
    processingTime: "Instant",
    howToApply: [
      "Open selfcare.bsnl.co.in or BSNL app / BBPS app.",
      "Select 'Landline / Mobile / Broadband' bill payment.",
      "Enter phone number and fetch bill.",
      "Pay via UPI / cards / net banking.",
      "Download digital receipt.",
    ],
    serviceCharge: 25,
    popularity: 78,
    tags: ["bsnl", "bill payment", "landline", "broadband", "mobile"],
    online: true,
  },
  {
    id: "mobile-number-portability",
    slug: "mobile-number-portability",
    name: "Mobile Number Portability (MNP)",
    category: "utilities",
    subcategory: "Telecom",
    summary: "Switch your mobile operator without changing your number via MNP.",
    description:
      "Mobile Number Portability (MNP) lets a subscriber switch between mobile operators (or between prepaid and postpaid within same operator) while retaining the existing 10-digit number. The process is fully digital via UPC (Unique Porting Code) generated by SMS to 1900.",
    ministry: "Ministry of Communications (TRAI)",
    officialPortal: "TRAI MNP / Operator Portals",
    officialUrl: "https://www.trai.gov.in/",
    eligibility: [
      "Completed 90 days with current operator since activation",
      "No outstanding dues (postpaid)",
      "Number not under contractual lock-in",
    ],
    documentsRequired: [
      "Aadhaar card (for e-KYC)",
      "Last bill (postpaid)",
      "UPC generated via SMS to 1900",
    ],
    fee: 0,
    feeNote: "MNP itself free; new SIM cost ₹10–₹50; first recharge as per new plan.",
    processingTime: "2–7 working days (within circle); up to 15 days inter-circle",
    howToApply: [
      "SMS 'PORT <10-digit mobile>' to 1900 to get 8-digit UPC (valid 4 days).",
      "Visit new operator's store / app with UPC and Aadhaar.",
      "Complete e-KYC biometric verification.",
      "New SIM issued; insert after porting SMS received.",
      "Number activates on new network within 2–7 days.",
    ],
    serviceCharge: 60,
    popularity: 75,
    tags: ["mnp", "mobile portability", "switch operator", "trai"],
    online: true,
  },
  {
    id: "aadhaar-mobile-re-verification",
    slug: "aadhaar-mobile-re-verification",
    name: "Aadhaar-Mobile Re-verification",
    category: "utilities",
    subcategory: "Telecom",
    summary: "Re-verify your mobile number with Aadhaar as mandated by DoT.",
    description:
      "The Department of Telecommunications (DoT) mandates all mobile subscribers to link their mobile number with Aadhaar for re-verification (periodic, especially for out-of-circle numbers or flagged SIMs). The process uses biometric OTP-based e-KYC at operator stores or via OTP SMS.",
    ministry: "Ministry of Communications (DoT)",
    officialPortal: "Operator Store / TAFCOP",
    officialUrl: "https://tafcop.dgtelecom.gov.in/",
    eligibility: ["Active mobile connection", "Aadhaar linked to a mobile number"],
    documentsRequired: ["Aadhaar card", "Mobile number to be re-verified"],
    fee: 0,
    feeNote: "Free of cost at operator stores.",
    processingTime: "Instant (24–72 hours for full activation)",
    howToApply: [
      "Visit your mobile operator's nearest store.",
      "Provide mobile number and Aadhaar number.",
      "Authenticate via biometric or OTP e-KYC.",
      "Receive confirmation SMS on successful re-verification.",
      "Connection continues without disruption.",
    ],
    serviceCharge: 40,
    popularity: 50,
    tags: ["aadhaar mobile link", "re-verification", "dot", "ekyc", "telecom"],
    online: false,
  },
];
