import type { GovernmentService } from "../types";

export const welfareSchemes: GovernmentService[] = [
  {
    id: "pm-kisan-registration",
    slug: "pm-kisan-registration",
    name: "PM-KISAN Samman Nidhi Registration",
    category: "welfare-schemes",
    subcategory: "Farmer Welfare",
    summary: "Register for ₹6,000 per year income support under PM-KISAN scheme.",
    description:
      "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) provides an income support of ₹6,000 per year to all landholding farmer families in three equal instalments. Eligible farmers can self-register on the PM-KISAN portal or visit Common Service Centres for assistance.",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    officialPortal: "PM-KISAN Portal",
    officialUrl: "https://pmkisan.gov.in/",
    eligibility: [
      "Indian citizen with cultivable landholding",
      "Family holds land in own name",
      "Excluded: institutional farmers, present/former public servants, income-tax payers, professionals",
    ],
    documentsRequired: ["Aadhaar", "Land record (khata/khatauni/patta)", "Bank account details", "Mobile number"],
    fee: 0,
    feeNote: "Free scheme. No fee for registration.",
    processingTime: "30 to 90 days for first instalment",
    howToApply: [
      "Visit the PM-KISAN portal.",
      "Click 'New Farmer Registration' under Farmers Corner.",
      "Enter Aadhaar, mobile and captcha for OTP verification.",
      "Fill personal, land and bank details as per land records.",
      "Submit and save the acknowledgement reference.",
    ],
    serviceCharge: 50,
    popularity: 95,
    tags: ["pm-kisan", "farmer", "samman nidhi", "subsidy", "agriculture"],
    online: true,
  },
  {
    id: "pm-kisan-beneficiary-status",
    slug: "pm-kisan-beneficiary-status",
    name: "PM-KISAN Beneficiary Status Check",
    category: "welfare-schemes",
    subcategory: "Farmer Welfare",
    summary: "Check instalment status and payment credit of PM-KISAN benefit.",
    description:
      "Registered farmers can verify their beneficiary status and track all instalments paid under PM-KISAN using Aadhaar, mobile number or account number. The portal also shows reasons for rejection if a payment is held up.",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    officialPortal: "PM-KISAN Portal",
    officialUrl: "https://pmkisan.gov.in/BeneficiaryStatus.aspx",
    eligibility: ["Registered PM-KISAN farmer", "Aadhaar or bank account or mobile number available"],
    documentsRequired: ["Aadhaar / Account number / Mobile number"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Visit the PM-KISAN portal 'Beneficiary Status' page.",
      "Select Aadhaar / Account / Mobile number option.",
      "Enter the selected identifier with captcha.",
      "View instalment-wise payment status and reference ID.",
      "If rejected, correct land or KYC details via edit facility.",
    ],
    serviceCharge: 30,
    popularity: 90,
    tags: ["pm-kisan", "beneficiary status", "installment", "farmer"],
    online: true,
  },
  {
    id: "pm-kisan-self-registration-correction",
    slug: "pm-kisan-self-registration-correction",
    name: "PM-KISAN Self Registration Correction",
    category: "welfare-schemes",
    subcategory: "Farmer Welfare",
    summary: "Edit name, Aadhaar, bank or land details in your PM-KISAN record.",
    description:
      "Farmers who have errors in name, Aadhaar number, mobile, bank account or land details in their PM-KISAN record can self-correct them through the 'Edit Aadhaar Details' / 'Updation of Land Records' facility on the PM-KISAN portal.",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    officialPortal: "PM-KISAN Portal",
    officialUrl: "https://pmkisan.gov.in/EditAadharDetail.aspx",
    eligibility: ["Already registered under PM-KISAN", "Aadhaar-linked mobile active for OTP"],
    documentsRequired: ["Aadhaar", "Registered mobile", "Corrected bank passbook / land record"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "30 to 45 days for re-verification",
    howToApply: [
      "Open 'Updation of Self Registered Farmer Details' on PM-KISAN portal.",
      "Enter Aadhaar and captcha to fetch record.",
      "Verify with OTP on Aadhaar-linked mobile.",
      "Edit the required fields (name, bank, land, mobile).",
      "Submit for state nodal officer approval.",
    ],
    serviceCharge: 50,
    popularity: 85,
    tags: ["pm-kisan", "correction", "edit", "farmer", "aadhaar"],
    online: true,
  },
  {
    id: "pmay-gramin-application",
    slug: "pmay-gramin-application",
    name: "PMAY-Gramin (PMAY-G) Housing Application",
    category: "welfare-schemes",
    subcategory: "Housing",
    summary: "Apply for a pucca house with financial assistance under PMAY-Gramin.",
    description:
      "Pradhan Mantri Awas Yojana - Gramin provides a pucca house with basic amenities to houseless households and those living in kutcha houses in rural areas. The unit assistance is ₹1.20 lakh in plain areas and ₹1.30 lakh in hilly/NE states/IAP districts.",
    ministry: "Ministry of Rural Development",
    officialPortal: "PMAY-G AwaasSoft Portal",
    officialUrl: "https://pmayg.nic.in/",
    eligibility: [
      "Rural household without pucca house",
      "Listed in SECC 2011 or added through Gram Sabha verification",
      "Not an income-tax payer or government employee",
    ],
    documentsRequired: ["Aadhaar", "Bank account", "Land availability proof (own/patta)", "Caste / income certificate (if applicable)", "Photograph"],
    fee: 0,
    feeNote: "Free scheme.",
    processingTime: "60 to 120 days (after verification & waitlist allotment)",
    howToApply: [
      "Visit the nearest Gram Panchayat or CSC with Aadhaar and bank details.",
      "Submit the PMAY-G application form to the Gram Sabha.",
      "Village verification by VLO / Panchayat Secretary.",
      "Eligibility approved at Block level and name entered in AwaasSoft.",
      "First instalment credited to bank on geo-tagged foundation stage.",
    ],
    serviceCharge: 100,
    popularity: 88,
    tags: ["pmay-g", "housing", "rural", "gramin", "subsidy"],
    online: true,
  },
  {
    id: "pmay-urban-application",
    slug: "pmay-urban-application",
    name: "PMAY-Urban (PMAY-U) Housing Application",
    category: "welfare-schemes",
    subcategory: "Housing",
    summary: "Apply for affordable housing under PMAY-Urban components.",
    description:
      "Pradhan Mantri Awas Yojana - Urban provides central assistance for affordable housing in 4 verticals: In-Situ Slum Redevelopment (ISSR), Affordable Housing in Partnership (AHP), Beneficiary Led Construction (BLC) and Credit Linked Subsidy Scheme (CLSS).",
    ministry: "Ministry of Housing and Urban Affairs (MoHUA)",
    officialPortal: "PMAY-U Web Portal",
    officialUrl: "https://pmaymis.gov.in/",
    eligibility: [
      "Annual family income up to ₹6 lakh (EWS/LIG for CLSS up to ₹6 lakh)",
      "Should not own a pucca house in own / family name",
      "Not availed central housing scheme assistance before",
    ],
    documentsRequired: ["Aadhaar of all family members", "Income certificate / salary slip", "Bank details", "Caste / category certificate (if applicable)", "Property / land document (for BLC)"],
    fee: 0,
    feeNote: "Free scheme.",
    processingTime: "30 to 90 days (state SLNA approval)",
    howToApply: [
      "Visit the PMAY-U portal and click 'Citizen Assessment'.",
      "Apply for PMAY-U under AHP / BLC / CLSS vertical.",
      "Fill Aadhaar, income and family details.",
      "Upload income proof, caste certificate and bank details.",
      "Application routed to state Urban Development Department.",
    ],
    serviceCharge: 100,
    popularity: 87,
    tags: ["pmay-u", "urban housing", "subsidy", "clss", "affordable housing"],
    online: true,
  },
  {
    id: "pmay-beneficiary-status",
    slug: "pmay-beneficiary-status",
    name: "PMAY Beneficiary Status & Tranche Check",
    category: "welfare-schemes",
    subcategory: "Housing",
    summary: "Track PMAY-G/PMAY-U instalment status and geo-tagged stages.",
    description:
      "Beneficiaries of PMAY (G & U) can check the status of their application, geo-tagging stages (foundation, lintel, roof, completion) and tranche-wise fund credit using their Aadhaar or application ID.",
    ministry: "Ministry of Rural Development / MoHUA",
    officialPortal: "PMAY AwaasSoft / PMAY-MIS Portal",
    officialUrl: "https://pmaymis.gov.in/Search/BeneficiaryDetails.aspx",
    eligibility: ["Registered PMAY-G or PMAY-U beneficiary"],
    documentsRequired: ["Aadhaar / Application ID / Mobile number"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant",
    howToApply: [
      "Open the PMAY-MIS 'Beneficiary Details' page.",
      "Select search by Aadhaar / Application ID / Mobile.",
      "Enter the identifier and submit.",
      "View stage-wise status (foundation / lintel / roof / completion).",
      "Check bank credit and reject reasons if any.",
    ],
    serviceCharge: 30,
    popularity: 82,
    tags: ["pmay", "beneficiary status", "housing", "tranche"],
    online: true,
  },
  {
    id: "pm-ujjwala-new-connection",
    slug: "pm-ujjwala-new-connection",
    name: "PM Ujjwala Yojana — New LPG Connection",
    category: "welfare-schemes",
    subcategory: "Cooking Fuel",
    summary: "Get a free LPG cooking gas connection under PMUY.",
    description:
      "Pradhan Mantri Ujjwala Yojana (PMUY) provides a deposit-free LPG connection to adult women of BPL households with financial assistance of ₹1,600 per connection. PMUY 2.0 also provides the first refill and stove free of cost.",
    ministry: "Ministry of Petroleum & Natural Gas",
    officialPortal: "PMUY Portal / OMC portals",
    officialUrl: "https://www.pmuy.gov.in/",
    eligibility: [
      "Adult woman from BPL household",
      "Adult woman from SC/ST, PMJDY account holder, Antyodaya, forest dwellers etc.",
      "Should not have an existing LPG connection in household",
    ],
    documentsRequired: ["Aadhaar of woman", "BPL / ration card / SECC-2011 list", "Bank account", "Recent photograph"],
    fee: 0,
    feeNote: "Free connection (subsidy of ₹1,600 + first refill + stove under PMUY 2.0).",
    processingTime: "3 to 7 working days",
    howToApply: [
      "Visit a nearby LPG distributor (IOC/HPCL/BPCL) or apply via PMUY portal.",
      "Submit KYC form with Aadhaar, BPL proof and bank details.",
      "Choose the distributor and cylinder size (14.2kg / 5kg).",
      "Distributor issues connection with SV (Subscription Voucher).",
      "First refill delivered with stove within 7 days.",
    ],
    serviceCharge: 75,
    popularity: 88,
    tags: ["ujjwala", "lpg", "gas", "cooking fuel", "bpl"],
    online: true,
  },
  {
    id: "pm-ujjwala-refill-subsidy",
    slug: "pm-ujjwala-refill-subsidy",
    name: "PM Ujjwala Yojana — Refill Subsidy / DBT",
    category: "welfare-schemes",
    subcategory: "Cooking Fuel",
    summary: "Get refill subsidy credited to your bank account under PMUY DBT.",
    description:
      "PMUY beneficiaries receive subsidy for LPG refills directly into their bank account under the Direct Benefit Transfer (DBT) scheme. The subsidy amount is the difference between market price and subsidised price as notified by the government from time to time.",
    ministry: "Ministry of Petroleum & Natural Gas",
    officialPortal: "PMUY / PAHAL Portal",
    officialUrl: "https://www.pmuy.gov.in/",
    eligibility: [
      "Active PMUY connection with SV and first refill",
      "Aadhaar seeded with bank and LPG ID",
      "Aadhaar linked to LPG consumer number",
    ],
    documentsRequired: ["Aadhaar", "LPG consumer number (17 digit)", "Bank account", "PMUY connection ID"],
    fee: 0,
    feeNote: "Free enrolment. Subsidy credited per refill.",
    processingTime: "2 to 5 days after refill purchase",
    howToApply: [
      "Visit your LPG distributor with Aadhaar and bank passbook.",
      "Submit Form 4 (Aadhaar linking) for DBT.",
      "Link Aadhaar with bank through bank branch / NPCI mapper.",
      "Purchase refill at non-subsidised rate.",
      "Subsidy credited to bank within 2-5 days.",
    ],
    serviceCharge: 50,
    popularity: 75,
    tags: ["ujjwala", "subsidy", "dbt", "lpg", "refill"],
    online: true,
  },
  {
    id: "pm-jan-dhan-account-opening",
    slug: "pm-jan-dhan-account-opening",
    name: "PM Jan Dhan Yojana (PMJDY) Account Opening",
    category: "welfare-schemes",
    subcategory: "Financial Inclusion",
    summary: "Open a zero-balance bank account with RuPay debit card and accident cover.",
    description:
      "Pradhan Mantri Jan Dhan Yojana (PMJDY) provides a zero-balance savings account with RuPay debit card, ₹2 lakh accident insurance (PMSBY), ₹10,000 overdraft facility and access to Direct Benefit Transfer. Accounts can be opened at any bank branch or BC outlet.",
    ministry: "Ministry of Finance — Department of Financial Services",
    officialPortal: "PMJDY / Bank Branch",
    officialUrl: "https://pmjdy.gov.in/",
    eligibility: [
      "Indian citizen aged 10 years and above",
      "No existing bank account (to get additional benefits)",
      "Address proof if available; otherwise self-attested photograph",
    ],
    documentsRequired: ["Aadhaar (preferred)", "One passport-size photograph", "NREGA job card / voter ID / any official document"],
    fee: 0,
    feeNote: "Zero minimum balance. No account opening fee.",
    processingTime: "Instant account opening",
    howToApply: [
      "Visit any bank branch or Business Correspondent outlet.",
      "Request account opening under PMJDY.",
      "Submit Aadhaar and one photograph.",
      "Account opened instantly with RuPay card.",
      "Passbook and cheque book issued on demand.",
    ],
    serviceCharge: 50,
    popularity: 90,
    tags: ["jan dhan", "pmjdy", "bank account", "zero balance", "rupay"],
    online: false,
  },
  {
    id: "pm-mudra-shishu-loan",
    slug: "pm-mudra-shishu-loan",
    name: "PM Mudra Yojana Loan — Shishu (up to ₹50,000)",
    category: "welfare-schemes",
    subcategory: "Micro Credit",
    summary: "Get a loan up to ₹50,000 for a new micro business under Mudra Shishu.",
    description:
      "Pradhan Mantri Mudra Yojana (PMMY) offers collateral-free loans to non-corporate, non-farm small/micro entrepreneurs. The Shishu category covers loans up to ₹50,000 for starting a new business or scaling an existing micro unit. Loans are routed through banks, NBFCs, MFIs and SFBs.",
    ministry: "Ministry of Finance",
    officialPortal: "Mudra / UdyamMitra Portal",
    officialUrl: "https://www.mudra.org.in/",
    eligibility: [
      "Indian citizen aged 18 and above",
      "Engaged in non-farm income-generating activity",
      "Loan amount required up to ₹50,000",
    ],
    documentsRequired: ["Mudra Loan Application Form", "Aadhaar", "PAN (mandatory above ₹50,000 / voluntary below)", "Bank statement (3 months)", "Business plan / quotation"],
    fee: 0,
    feeNote: "Processing fee varies by lender (usually NIL for Shishu).",
    processingTime: "7 to 15 working days",
    howToApply: [
      "Approach any commercial bank, RRB, NBFC or MFI branch.",
      "Submit Mudra Loan Application Form with business plan.",
      "Provide Aadhaar, PAN, photograph and bank statement.",
      "Lender assesses creditworthiness and visits business location.",
      "On approval, loan disbursed to bank account; MUDRA card issued.",
    ],
    serviceCharge: 100,
    popularity: 80,
    tags: ["mudra", "shishu", "loan", "micro business", "pmmmy"],
    online: true,
  },
  {
    id: "pm-mudra-kishore-loan",
    slug: "pm-mudra-kishore-loan",
    name: "PM Mudra Yojana Loan — Kishore (₹50,001 to ₹5 lakh)",
    category: "welfare-schemes",
    subcategory: "Micro Credit",
    summary: "Loan between ₹50,001 and ₹5 lakh for an existing micro business under Mudra Kishore.",
    description:
      "The Kishore category under PMMY provides loans above ₹50,000 and up to ₹5 lakh for business expansion, working capital or capital expenditure of micro units. Credit history, business vintage and turnover are evaluated by the lender before sanction.",
    ministry: "Ministry of Finance",
    officialPortal: "Mudra / UdyamMitra Portal",
    officialUrl: "https://www.mudra.org.in/",
    eligibility: [
      "Existing micro business or startup",
      "Loan requirement ₹50,001 to ₹5,00,000",
      "Satisfactory credit / business track record",
    ],
    documentsRequired: ["Mudra Loan Application Form", "Aadhaar & PAN of applicant", "Last 1-2 years financials / IT return", "Bank statement (12 months)", "Business registration (Udyam if available)"],
    fee: 0,
    feeNote: "Processing fee usually 0.50% to 1% of loan amount.",
    processingTime: "15 to 30 working days",
    howToApply: [
      "Apply at any bank, NBFC, MFI or Small Finance Bank.",
      "Submit Mudra Kishore form with financial statements.",
      "Provide Udyam / shop act registration if available.",
      "Lender conducts credit appraisal and site visit.",
      "On sanction, loan disbursed with MUDRA card.",
    ],
    serviceCharge: 120,
    popularity: 75,
    tags: ["mudra", "kishore", "loan", "msme", "pmmmy"],
    online: true,
  },
  {
    id: "pm-mudra-tarun-loan",
    slug: "pm-mudra-tarun-loan",
    name: "PM Mudra Yojana Loan — Tarun (₹5 lakh to ₹10 lakh)",
    category: "welfare-schemes",
    subcategory: "Micro Credit",
    summary: "Loan between ₹5 lakh and ₹10 lakh for scaling your micro enterprise under Mudra Tarun.",
    description:
      "The Tarun category under PMMY covers loans above ₹5 lakh and up to ₹10 lakh for established micro enterprises looking to scale. Lenders may require collateral for higher amounts, but PMMY loans up to ₹10 lakh to micro units are covered under Credit Guarantee Fund Scheme for Micro Units (CGFMU).",
    ministry: "Ministry of Finance",
    officialPortal: "Mudra / UdyamMitra Portal",
    officialUrl: "https://www.mudra.org.in/",
    eligibility: [
      "Established micro enterprise with track record",
      "Loan requirement above ₹5 lakh and up to ₹10 lakh",
      "Satisfactory financial & credit history",
    ],
    documentsRequired: ["Mudra Loan Application Form", "Aadhaar & PAN", "Last 2-3 years IT returns & financials", "Bank statements (12 months)", "Udyam registration & GST registration"],
    fee: 0,
    feeNote: "Processing fee 0.50% to 1.50% of loan amount.",
    processingTime: "20 to 45 working days",
    howToApply: [
      "Apply at scheduled commercial bank, RRB or NBFC.",
      "Submit application with 2-3 years financials and IT returns.",
      "Provide GST returns and Udyam certificate.",
      "Lender conducts detailed credit appraisal and site visit.",
      "On sanction, loan disbursed; CGFMU cover applied.",
    ],
    serviceCharge: 150,
    popularity: 70,
    tags: ["mudra", "tarun", "loan", "msme", "pmmmy"],
    online: true,
  },
  {
    id: "pm-svanidhi-loan",
    slug: "pm-svanidhi-loan",
    name: "PM SVANidhi — Street Vendor Loan",
    category: "welfare-schemes",
    subcategory: "Micro Credit",
    summary: "Get a working capital loan up to ₹50,000 as a street vendor under PM SVANidhi.",
    description:
      "Pradhan Mantri Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi) provides collateral-free working capital loan up to ₹10,000 in the first cycle, ₹20,000 in second and ₹50,000 in third to street vendors. Vendors also get interest subsidy (7%) and cashback on digital transactions.",
    ministry: "Ministry of Housing and Urban Affairs (MoHUA)",
    officialPortal: "PM SVANidhi Portal",
    officialUrl: "https://pmsvanidhi.mohua.gov.in/",
    eligibility: [
      "Street vendor vending in urban / peri-urban areas",
      "Holds Certificate of Vending / Identity Card from ULB",
      "Vending on or before March 24, 2020 (extended under 2.0)",
    ],
    documentsRequired: ["Aadhaar", "Certificate of Vending / Letter of Recommendation from ULB", "Bank account details", "Mobile number"],
    fee: 0,
    feeNote: "Interest subsidy of 7% credited quarterly.",
    processingTime: "15 to 30 working days",
    howToApply: [
      "Apply through PM SVANidhi portal or via ULB / CSC.",
      "Authenticate Aadhaar with OTP.",
      "Choose lending institution (bank / NBFC / SFB).",
      "Submit vending certificate and bank details.",
      "Loan disbursed to bank; subsidy credited quarterly.",
    ],
    serviceCharge: 75,
    popularity: 78,
    tags: ["svanidhi", "street vendor", "loan", "urban", "working capital"],
    online: true,
  },
  {
    id: "pm-vishwakarma-yojana",
    slug: "pm-vishwakarma-yojana",
    name: "PM Vishwakarma Yojana",
    category: "welfare-schemes",
    subcategory: "Artisan Welfare",
    summary: "Skill, toolkit & loan support for 18 traditional artisan trades.",
    description:
      "PM Vishwakarma Yojana provides recognition, skill upgradation, toolkit incentive of ₹15,000, collateral-free loan up to ₹3 lakh (1st tranche ₹1 lakh, 2nd ₹2 lakh) at 5% interest and digital transaction incentive to traditional artisans and craftspeople across 18 trades.",
    ministry: "Ministry of Skill Development and Entrepreneurship",
    officialPortal: "PM Vishwakarma Portal",
    officialUrl: "https://pmvishwakarma.gov.in/",
    eligibility: [
      "Practising one of 18 traditional trades (carpenter, blacksmith, goldsmith, potter etc.)",
      "Self-employed in informal / unorganised sector",
      "Aged 18+ with Aadhaar & mobile",
    ],
    documentsRequired: ["Aadhaar", "Mobile number", "Bank account", "Trade / caste certificate (if applicable)"],
    fee: 0,
    feeNote: "Free registration; loan at 5% interest.",
    processingTime: "30 to 60 days for loan disbursement",
    howToApply: [
      "Visit the PM Vishwakarma portal.",
      "Register with Aadhaar and mobile OTP.",
      "Fill trade, bank and family details.",
      "Visit CSC / village level Entrepreneur for biometric authentication.",
      "On approval, recognition certificate, toolkit and loan sanctioned.",
    ],
    serviceCharge: 75,
    popularity: 80,
    tags: ["vishwakarma", "artisan", "toolkit", "loan", "traditional trade"],
    online: true,
  },
  {
    id: "pm-kisan-samman-installment-receipt",
    slug: "pm-kisan-samman-installment-receipt",
    name: "PM Kisan Samman Nidhi Installment Receipt Download",
    category: "welfare-schemes",
    subcategory: "Farmer Welfare",
    summary: "Download official receipt of each PM-KISAN instalment credited to your account.",
    description:
      "PM Kisan Samman Nidhi beneficiaries can download the official instalment-wise receipt (UTR / PFMS reference) from the beneficiary dashboard. This receipt is useful for bank reconciliation, loans and any grievances related to non-credit of instalment.",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    officialPortal: "PM-KISAN Beneficiary Dashboard",
    officialUrl: "https://pmkisan.gov.in/BeneficiaryStatus.aspx",
    eligibility: ["Active PM-KISAN beneficiary with at least one instalment released"],
    documentsRequired: ["Aadhaar / Mobile / Account number"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant download",
    howToApply: [
      "Visit the PM-KISAN 'Beneficiary Status' page.",
      "Search using Aadhaar / Account / Mobile number.",
      "View instalment list with dates and reference IDs.",
      "Click 'Download Receipt' for the required instalment.",
      "Save the PDF for records or grievance follow-up.",
    ],
    serviceCharge: 30,
    popularity: 82,
    tags: ["pm-kisan", "samman nidhi", "receipt", "installment", "farmer"],
    online: true,
  },
  {
    id: "pmay-beneficiary-list",
    slug: "pmay-beneficiary-list",
    name: "PMAY Permanent Wait List / Beneficiary List",
    category: "welfare-schemes",
    subcategory: "Housing",
    summary: "Check if your name appears in the PMAY-G permanent waitlist.",
    description:
      "After the Awaas+ survey, MoRD publishes a permanent waitlist of eligible PMAY-G beneficiaries. Citizens can search their name in the waitlist by state, district, block, Gram Panchayat and name on the AwaasSoft portal.",
    ministry: "Ministry of Rural Development",
    officialPortal: "AwaasSoft PMAY-G Portal",
    officialUrl: "https://pmayg.nic.in/netiayGrihaApp/BeneficiaryListToUserGriha.aspx",
    eligibility: ["Surveyed under Awaas+ / SECC-2011", "Rural household without pucca house"],
    documentsRequired: ["Aadhaar / Name / Father or Husband name"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant search",
    howToApply: [
      "Visit AwaasSoft PMAY-G portal.",
      "Open the 'Beneficiary List to User' page.",
      "Select state, district, block and Gram Panchayat.",
      "Enter your name and search.",
      "If listed, approach Gram Panchayat for activation.",
    ],
    serviceCharge: 30,
    popularity: 78,
    tags: ["pmay-g", "waitlist", "beneficiary list", "housing"],
    online: true,
  },
  {
    id: "nfsa-ration-card-application",
    slug: "nfsa-ration-card-application",
    name: "NFSA Ration Card Application",
    category: "welfare-schemes",
    subcategory: "Food Security",
    summary: "Apply for a new ration card under the National Food Security Act.",
    description:
      "The National Food Security Act (NFSA) 2013 entitles up to 75% rural and 50% urban population to receive subsidised food grains (5 kg per person per month) through the PDS. Households apply for new ration cards at state food / civil supplies portals.",
    ministry: "Ministry of Consumer Affairs, Food & Public Distribution",
    officialPortal: "State Food / Civil Supplies Department Portal",
    officialUrl: "https://nfsa.gov.in/",
    eligibility: [
      "Indian citizen household not holding a ration card",
      "Not covered as AAY/BPL in any other state",
      "Meets state-specific income criteria",
    ],
    documentsRequired: ["Aadhaar of all members", "Address proof", "Income certificate", "Bank passbook", "Photograph"],
    fee: 5,
    feeNote: "Application fee ₹5 to ₹25 (varies by state).",
    processingTime: "30 days",
    howToApply: [
      "Visit the state Food / Civil Supplies portal or e-District.",
      "Create login with mobile and Aadhaar OTP.",
      "Fill new ration card application with family details.",
      "Upload Aadhaar of all members, address proof and bank details.",
      "Field verification by Food Supply Officer before issuance.",
    ],
    serviceCharge: 100,
    popularity: 90,
    tags: ["nfsa", "ration card", "food security", "pds", "subsidy"],
    online: true,
  },
  {
    id: "antyodaya-anna-yojana-card",
    slug: "antyodaya-anna-yojana-card",
    name: "Antyodaya Anna Yojana (AAY) Card",
    category: "welfare-schemes",
    subcategory: "Food Security",
    summary: "Get an AAY ration card with 35 kg foodgrains per family at subsidised rates.",
    description:
      "Antyodaya Anna Yojana (AAY) covers the poorest of the poor households. Each AAY family is entitled to 35 kg of foodgrains per month (rice ₹3/kg, wheat ₹2/kg, coarse grains ₹1/kg). The card is issued by the state food department on identification by Gram Sabha / ULB.",
    ministry: "Ministry of Consumer Affairs, Food & Public Distribution",
    officialPortal: "State Food / Civil Supplies Department Portal",
    officialUrl: "https://nfsa.gov.in/",
    eligibility: [
      "Poorest of poor households (landless labourers, marginal farmers, etc.)",
      "No regular income source",
      "Recommended by Gram Sabha / ULB",
    ],
    documentsRequired: ["Aadhaar of all members", "Income / caste certificate", "Address proof", "Photograph", "Recommendation from Gram Sabha / ULB"],
    fee: 5,
    feeNote: "Application fee ₹5 to ₹25 (varies by state).",
    processingTime: "30 to 45 days",
    howToApply: [
      "Approach Gram Panchayat / ULB for AAY identification.",
      "Obtain Gram Sabha / ward committee recommendation.",
      "Apply on state Food Supplies portal with recommendation letter.",
      "Upload Aadhaar of all members and income proof.",
      "Inspection & card issued by Food Supply Officer.",
    ],
    serviceCharge: 100,
    popularity: 82,
    tags: ["aay", "antyodaya", "ration card", "food security", "poorest"],
    online: true,
  },
  {
    id: "bpl-ration-card",
    slug: "bpl-ration-card",
    name: "BPL Ration Card Application",
    category: "welfare-schemes",
    subcategory: "Food Security",
    summary: "Apply for a Below Poverty Line (BPL) ration card with subsidised foodgrain entitlement.",
    description:
      "BPL ration cards are issued to households identified as below poverty line under NFSA (Priority Households - PHH). They receive 5 kg foodgrain per person per month at subsidised rates. Each state issues its own BPL/PHH card with state-specific colour coding.",
    ministry: "Ministry of Consumer Affairs, Food & Public Distribution",
    officialPortal: "State Food / Civil Supplies Department Portal",
    officialUrl: "https://nfsa.gov.in/",
    eligibility: [
      "Listed in SECC 2011 as BPL household",
      "Income within state BPL limit",
      "Not covered under AAY",
    ],
    documentsRequired: ["Aadhaar of all members", "Income certificate", "Address proof", "Bank passbook", "Photograph"],
    fee: 5,
    feeNote: "Application fee ₹5 to ₹25 (varies by state).",
    processingTime: "30 to 45 days",
    howToApply: [
      "Visit the state Food / Civil Supplies portal.",
      "Apply for BPL / PHH ration card.",
      "Enter Aadhaar of all family members.",
      "Upload income certificate and address proof.",
      "Verification & card issued by FSO.",
    ],
    serviceCharge: 100,
    popularity: 85,
    tags: ["bpl", "ration card", "food security", "pds", "phh"],
    online: true,
  },
  {
    id: "sukanya-samriddhi-yojana-account",
    slug: "sukanya-samriddhi-yojana-account",
    name: "Sukanya Samriddhi Yojana Account",
    category: "welfare-schemes",
    subcategory: "Savings",
    summary: "Open a small savings account for your girl child with 8.2% interest.",
    description:
      "Sukanya Samriddhi Yojana (SSY) is a small savings scheme for girl children below 10 years, offering one of the highest interest rates (8.2% for FY 2024-25). Deposits qualify for Section 80C deduction up to ₹1.5 lakh; maturity after 21 years with tax-free interest.",
    ministry: "Ministry of Finance — Department of Economic Affairs",
    officialPortal: "India Post / Banks",
    officialUrl: "https://www.india.gov.in/sukanya-samriddhi-yojna",
    eligibility: [
      "Girl child below 10 years of age",
      "Indian citizen",
      "Only one account per girl child (max two in a family, three for twins/triplets)",
    ],
    documentsRequired: ["Girl child's birth certificate", "Parent's Aadhaar / PAN / ID", "Address proof", "Photograph of guardian"],
    fee: 0,
    feeNote: "No account opening fee. Min ₹250 / year; Max ₹1.5 lakh / year.",
    processingTime: "Instant account opening",
    howToApply: [
      "Visit any post office or authorised bank branch.",
      "Fill SSY Account Opening Form (SSY-1).",
      "Submit birth certificate of girl child & parent KYC.",
      "Deposit minimum ₹250 to activate the account.",
      "Receive SSY passbook with account number.",
    ],
    serviceCharge: 50,
    popularity: 78,
    tags: ["sukanya", "girl child", "savings", "80c", "tax"],
    online: false,
  },
  {
    id: "atal-pension-yojana-enrollment",
    slug: "atal-pension-yojana-enrollment",
    name: "Atal Pension Yojana (APY) Enrollment",
    category: "welfare-schemes",
    subcategory: "Pension",
    summary: "Enroll for guaranteed monthly pension of ₹1,000 to ₹5,000 from age 60.",
    description:
      "Atal Pension Yojana (APY) is a pension scheme for unorganised sector workers aged 18-40. The subscriber contributes monthly until age 60 and gets a guaranteed pension of ₹1,000-₹5,000. Government co-contributes 50% of total contribution or ₹1,000 per year (whichever is lower) for eligible subscribers.",
    ministry: "Ministry of Finance — PFRDA",
    officialPortal: "Bank Branch / NPS Trust",
    officialUrl: "https://www.npstrust.org.in/scheme/atal-pension-yojana",
    eligibility: [
      "Indian citizen aged 18-40 years",
      "Possesses a savings bank account",
      "Not an income-tax payer",
    ],
    documentsRequired: ["Aadhaar", "Savings bank account number", "Mobile number", "Photograph (if KYC pending)"],
    fee: 0,
    feeNote: "No enrolment fee. Contribution auto-debited monthly.",
    processingTime: "Instant enrolment",
    howToApply: [
      "Approach your bank branch where you have savings account.",
      "Submit APY Registration Form with Aadhaar and bank details.",
      "Choose pension amount (₹1,000 to ₹5,000) and contribution mode.",
      "Bank auto-debits monthly contribution.",
      "Receive PRAN (Permanent Retirement Account Number).",
    ],
    serviceCharge: 50,
    popularity: 76,
    tags: ["apY", "atal pension", "pension", "pfrda", "unorganised"],
    online: false,
  },
  {
    id: "pmjjby-life-insurance-enrollment",
    slug: "pmjjby-life-insurance-enrollment",
    name: "PMJJBY Life Insurance Enrollment",
    category: "welfare-schemes",
    subcategory: "Insurance",
    summary: "Get ₹2 lakh life cover for ₹436 per year under PM Jeevan Jyoti Bima Yojana.",
    description:
      "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY) is a one-year term life insurance offering ₹2 lakh cover for an annual premium of ₹436. It is available to all savings bank account holders aged 18-50 years. The cover auto-renews each year and the premium is auto-debited.",
    ministry: "Ministry of Finance — Department of Financial Services",
    officialPortal: "Bank Branch / Jansuraksha Portal",
    officialUrl: "https://www.jansuraksha.gov.in/",
    eligibility: [
      "Savings bank account holder",
      "Aged 18-50 years",
      "Aadhaar linked with bank account",
    ],
    documentsRequired: ["Aadhaar", "Savings bank account details", "Nominee details", "Mobile number"],
    fee: 436,
    feeNote: "Annual premium ₹436 (GST extra).",
    processingTime: "Instant enrollment",
    howToApply: [
      "Approach the bank branch where you have savings account.",
      "Submit PMJJBY enrollment form with nominee details.",
      "Premium ₹436 auto-debited from savings account.",
      "Cover starts on 1st June of scheme year.",
      "Confirmation SMS sent; auto-renews each year.",
    ],
    serviceCharge: 30,
    popularity: 80,
    tags: ["pmjjby", "life insurance", "jansuraksha", "term cover", "insurance"],
    online: false,
  },
  {
    id: "pmsby-accident-insurance-enrollment",
    slug: "pmsby-accident-insurance-enrollment",
    name: "PMSBY Accident Insurance Enrollment",
    category: "welfare-schemes",
    subcategory: "Insurance",
    summary: "Get ₹2 lakh accident cover for ₹20 per year under PM Suraksha Bima Yojana.",
    description:
      "Pradhan Mantri Suraksha Bima Yojana (PMSBY) provides accidental death and full disability cover of ₹2 lakh and partial disability cover of ₹1 lakh for an annual premium of ₹20. Available to all savings bank account holders aged 18-70 years.",
    ministry: "Ministry of Finance — Department of Financial Services",
    officialPortal: "Bank Branch / Jansuraksha Portal",
    officialUrl: "https://www.jansuraksha.gov.in/",
    eligibility: [
      "Savings bank account holder",
      "Aged 18-70 years",
      "Aadhaar linked with bank account",
    ],
    documentsRequired: ["Aadhaar", "Savings bank account details", "Nominee details", "Mobile number"],
    fee: 20,
    feeNote: "Annual premium ₹20 (GST extra).",
    processingTime: "Instant enrollment",
    howToApply: [
      "Approach the bank branch where you have savings account.",
      "Submit PMSBY enrollment form with nominee details.",
      "Premium ₹20 auto-debited from savings account.",
      "Cover starts on 1st June of scheme year.",
      "Confirmation SMS sent; auto-renews each year.",
    ],
    serviceCharge: 30,
    popularity: 80,
    tags: ["pmsby", "accident insurance", "jansuraksha", "disability cover", "insurance"],
    online: false,
  },
  {
    id: "stand-up-india-loan",
    slug: "stand-up-india-loan",
    name: "Stand-Up India Loan",
    category: "welfare-schemes",
    subcategory: "Entrepreneurship",
    summary: "Bank loans between ₹10 lakh and ₹1 crore for SC/ST & women entrepreneurs.",
    description:
      "Stand-Up India facilitates bank loans between ₹10 lakh and ₹1 crore to at least one Scheduled Caste (SC) or Scheduled Tribe (ST) borrower and at least one woman borrower per bank branch for setting up a greenfield enterprise in manufacturing, services or trading.",
    ministry: "Department of Financial Services, Ministry of Finance",
    officialPortal: "Stand-Up India Portal",
    officialUrl: "https://www.standupmitra.in/",
    eligibility: [
      "SC/ST or woman entrepreneur aged 18+",
      "Setting up greenfield enterprise (first time in manufacturing/services/trading)",
      "Borrower not in default with any bank",
    ],
    documentsRequired: ["Aadhaar & PAN", "Caste / category certificate (if SC/ST)", "Business plan / project report", "Bank statement", "Collateral documents (if any)"],
    fee: 0,
    feeNote: "Processing fee as per bank norms; 7% interest rate (subsidised).",
    processingTime: "30 to 60 working days",
    howToApply: [
      "Register on the Stand-Up India Mitra portal.",
      "Choose the category (SC/ST/Woman).",
      "Fill in business plan and loan requirement.",
      "Upload KYC and project report.",
      "Application forwarded to a bank branch for sanction.",
    ],
    serviceCharge: 150,
    popularity: 65,
    tags: ["stand up india", "sc st", "women", "loan", "entrepreneur"],
    online: true,
  },
  {
    id: "startup-india-recognition",
    slug: "startup-india-recognition",
    name: "Startup India Recognition (DPIIT)",
    category: "welfare-schemes",
    subcategory: "Entrepreneurship",
    summary: "Get DPIIT recognition for tax benefits and incentives under Startup India.",
    description:
      "DPIIT recognition under the Startup India initiative enables startups to avail tax benefits under Section 80-IAC, self-certification under labour & environment laws, easier compliance, IP fast-tracking and access to Fund of Funds. Recognition is valid for 10 years from incorporation.",
    ministry: "Department for Promotion of Industry and Internal Trade (DPIIT)",
    officialPortal: "Startup India Portal",
    officialUrl: "https://www.startupindia.gov.in/",
    eligibility: [
      "Entity incorporated as Pvt Ltd / LLP / Partnership",
      "Incorporated within last 10 years",
      "Annual turnover below ₹100 crore",
      "Working towards innovation / improvement of products or processes",
    ],
    documentsRequired: ["Certificate of Incorporation / Registration", "PAN", "Pitch deck / business plan", "Website / mobile app link", "Patent / trademark (if any)"],
    fee: 0,
    feeNote: "Free recognition.",
    processingTime: "10 to 20 working days",
    howToApply: [
      "Register on the Startup India portal.",
      "Click 'Get Recognised' and fill the recognition form.",
      "Upload incorporation certificate, pitch deck and details.",
      "Submit for DPIIT review.",
      "Recognition Certificate generated on approval.",
    ],
    serviceCharge: 100,
    popularity: 75,
    tags: ["startup india", "dpiit", "recognition", "tax benefit", "80-iac"],
    online: true,
  },
  {
    id: "pmegp-khadi-loan",
    slug: "pmegp-khadi-loan",
    name: "PMEGP (Khadi & Village Industries Loan)",
    category: "welfare-schemes",
    subcategory: "Entrepreneurship",
    summary: "Get margin money subsidy up to 35% for micro enterprise under PMEGP.",
    description:
      "Prime Minister's Employment Generation Programme (PMEGP) provides margin money subsidy of 15-35% on project cost (up to ₹50 lakh manufacturing / ₹20 lakh services) for setting up micro enterprises in rural and urban areas. Implemented by KVIC, KVIB and DICs.",
    ministry: "Ministry of Micro, Small & Medium Enterprises (KVIC)",
    officialPortal: "PMEGP e-Portal",
    officialUrl: "https://www.kviconline.gov.in/pmegp/",
    eligibility: [
      "Indian citizen aged 18+ (VIII pass for >₹10 lakh manufacturing / >₹5 lakh services)",
      "Project cost up to ₹50 lakh (manufacturing) / ₹20 lakh (services)",
      "Not received any subsidy from Govt earlier for same project",
    ],
    documentsRequired: ["Aadhaar & PAN", "Project report", "Cast / category certificate", "Educational qualification proof", "Photos & bank details"],
    fee: 0,
    feeNote: "Free application. Margin money subsidy up to 25-35% (rural) / 15-25% (urban).",
    processingTime: "60 to 90 days",
    howToApply: [
      "Register on the PMEGP online portal of KVIC.",
      "Fill online PMEGP application with project report.",
      "Upload Aadhaar, PAN and caste certificate.",
      "Submit to concerned implementing agency (KVIC / KVIB / DIC).",
      "Attend interview; subsidy credited to bank on loan sanction.",
    ],
    serviceCharge: 150,
    popularity: 72,
    tags: ["pmegp", "khadi", "kvic", "subsidy", "msme"],
    online: true,
  },
  {
    id: "nsap-old-age-pension",
    slug: "nsap-old-age-pension",
    name: "NSAP Old Age Pension (IGNOAPS)",
    category: "welfare-schemes",
    subcategory: "Pension",
    summary: "Get ₹200 monthly pension under National Social Assistance Programme.",
    description:
      "Indira Gandhi National Old Age Pension Scheme (IGNOAPS) under NSAP provides ₹200 per month to BPL persons aged 60-79 and ₹500 per month to those aged 80+ (the state may add a top-up). Eligible beneficiaries can apply at the state social welfare department.",
    ministry: "Ministry of Rural Development",
    officialPortal: "NSAP Portal",
    officialUrl: "https://nsap.nic.in/",
    eligibility: [
      "BPL household as per criteria",
      "Aged 60 years and above",
      "Not availing any other pension from Centre / State",
    ],
    documentsRequired: ["Aadhaar", "Age proof", "BPL certificate / Ration card", "Bank / Post office account", "Photograph"],
    fee: 0,
    feeNote: "Free application.",
    processingTime: "30 to 60 days",
    howToApply: [
      "Visit the NSAP portal or nearby Gram Panchayat / Block office.",
      "Fill NSAP application form (A) for old age pension.",
      "Upload Aadhaar, age proof and BPL certificate.",
      "Verification by Gram Sabha / Block officer.",
      "Pension credited to bank / post office account monthly.",
    ],
    serviceCharge: 75,
    popularity: 80,
    tags: ["nsap", "ignoaps", "old age pension", "bpl", "pension"],
    online: true,
  },
  {
    id: "indira-gandhi-national-old-age-pension",
    slug: "indira-gandhi-national-old-age-pension",
    name: "Indira Gandhi National Old Age Pension (State Top-Up)",
    category: "welfare-schemes",
    subcategory: "Pension",
    summary: "Apply for state top-up on IGNOAPS giving pension up to ₹1,000-₹2,000 per month.",
    description:
      "Most states add a top-up to the central IGNOAPS amount taking the total pension to ₹1,000-₹2,000 per month. The state top-up is administered by state Social Welfare Departments; beneficiaries already receiving IGNOAPS get the top-up automatically.",
    ministry: "State Social Welfare Departments",
    officialPortal: "State Social Welfare Portal",
    officialUrl: "https://nsap.nic.in/",
    eligibility: [
      "Already receiving IGNOAPS central pension",
      "Meets state-specific age / income criteria",
      "Aadhaar linked bank account",
    ],
    documentsRequired: ["IGNOAPS beneficiary ID", "Aadhaar", "Bank / Post office account", "Age proof"],
    fee: 0,
    feeNote: "Free application.",
    processingTime: "30 to 45 days",
    howToApply: [
      "Visit the state Social Welfare / Pension portal.",
      "Login with existing IGNOAPS beneficiary ID.",
      "Verify personal and bank details.",
      "Submit for state top-up review.",
      "Top-up amount credited monthly with central pension.",
    ],
    serviceCharge: 75,
    popularity: 75,
    tags: ["ignoaps", "old age pension", "state pension", "top up", "nsap"],
    online: true,
  },
  {
    id: "garib-kalyan-anna-yojana",
    slug: "garib-kalyan-anna-yojana",
    name: "PM Garib Kalyan Anna Yojana (PMGKAY)",
    category: "welfare-schemes",
    subcategory: "Food Security",
    summary: "Free 5 kg foodgrains per person per month under PMGKAY for 5 years.",
    description:
      "PM Garib Kalyan Anna Yojana (PMGKAY) provides free foodgrains (rice, wheat, coarse grains) to over 80 crore NFSA beneficiaries for 5 years (Jan 2024 to Dec 2028). 5 kg per person per month is given free over and above the regular NFSA entitlement.",
    ministry: "Ministry of Consumer Affairs, Food & Public Distribution",
    officialPortal: "State Food / Civil Supplies Department Portal",
    officialUrl: "https://nfsa.gov.in/",
    eligibility: [
      "Holds valid AAY / PHH ration card",
      "Listed in NFSA beneficiary database",
      "Aadhaar seeded with ration card",
    ],
    documentsRequired: ["Ration card", "Aadhaar of members", "Mobile number"],
    fee: 0,
    feeNote: "Free foodgrain — no charge to beneficiary.",
    processingTime: "Monthly distribution at Fair Price Shop",
    howToApply: [
      "Verify NFSA / AAY / PHH beneficiary status with ration card.",
      "Ensure Aadhaar of all members seeded with ration card.",
      "Visit Fair Price Shop with ration card / e-PDS app.",
      "Authenticate via ePOS / biometric.",
      "Collect free foodgrains (5 kg per person).",
    ],
    serviceCharge: 30,
    popularity: 88,
    tags: ["pmgkay", "garib kalyan", "free food", "nfsa", "pds"],
    online: false,
  },
  {
    id: "one-nation-one-ration-card",
    slug: "one-nation-one-ration-card",
    name: "One Nation One Ration Card (ONORC) Portability",
    category: "welfare-schemes",
    subcategory: "Food Security",
    summary: "Lift subsidised foodgrains from any FPS in India using ONORC portability.",
    description:
      "One Nation One Ration Card (ONORC) enables NFSA beneficiaries to lift their entitled foodgrains from any Fair Price Shop (FPS) anywhere in India using Aadhaar-based authentication on the ePoS device. Migrant workers benefit the most.",
    ministry: "Ministry of Consumer Affairs, Food & Public Distribution",
    officialPortal: "ONORC / PDS Portal",
    officialUrl: "https://nfsa.gov.in/onorc",
    eligibility: [
      "Active NFSA (AAY/PHH) ration card",
      "Aadhaar seeded for all members",
      "eKYC completed on PDS",
    ],
    documentsRequired: ["Ration card", "Aadhaar of lifting member"],
    fee: 0,
    feeNote: "Free service.",
    processingTime: "Instant authentication at FPS",
    howToApply: [
      "Confirm Aadhaar seeding with your ration card.",
      "Complete eKYC at any FPS or state PDS portal.",
      "Visit any FPS in any state with your ration card / Aadhaar.",
      "Authenticate on ePoS device with fingerprint / OTP.",
      "Lift your entitlement; SMS confirmation sent.",
    ],
    serviceCharge: 30,
    popularity: 82,
    tags: ["onorc", "portability", "ration card", "migrant", "pds"],
    online: false,
  },
  {
    id: "annapurna-scheme",
    slug: "annapurna-scheme",
    name: "Annapurna Scheme",
    category: "welfare-schemes",
    subcategory: "Food Security",
    summary: "10 kg free foodgrains per month for senior citizens not covered under IGNOAPS.",
    description:
      "The Annapurna Scheme provides 10 kg of free foodgrains per month to indigent senior citizens aged 65+ who are not receiving pension under IGNOAPS. The scheme is implemented by state food & civil supplies departments with allocation from the central pool.",
    ministry: "Ministry of Rural Development",
    officialPortal: "NSAP / State Food Portal",
    officialUrl: "https://nsap.nic.in/",
    eligibility: [
      "Aged 65 years and above",
      "BPL / destitute without IGNOAPS pension",
      "Not covered under any other food scheme",
    ],
    documentsRequired: ["Aadhaar", "Age proof", "BPL / income certificate", "Photograph"],
    fee: 0,
    feeNote: "Free foodgrains.",
    processingTime: "30 to 60 days",
    howToApply: [
      "Approach Gram Panchayat / ULB for Annapurna Scheme application.",
      "Submit form with age proof, BPL certificate and Aadhaar.",
      "Verification by Panchayat / Municipal officer.",
      "Beneficiary added to Annapurna list at Food Department.",
      "Collect 10 kg foodgrains from designated FPS monthly.",
    ],
    serviceCharge: 75,
    popularity: 60,
    tags: ["annapurna", "senior citizen", "foodgrains", "bpl", "rural development"],
    online: false,
  },
  {
    id: "pm-garib-kalyan-yojana",
    slug: "pm-garib-kalyan-yojana",
    name: "PM Garib Kalyan Yojana (Subsidised Cylinder)",
    category: "welfare-schemes",
    subcategory: "Cooking Fuel",
    summary: "Get up to 12 LPG refills per year at subsidised rate under PMGKY.",
    description:
      "Under PM Garib Kalyan Yojana (PMGKY), beneficiaries of PMUY get up to 12 LPG refills per year at subsidised rate. During 2020-22 free cylinders were provided under PMGKY-CYL; the scheme continues with subsidised refill support for Ujjwala beneficiaries.",
    ministry: "Ministry of Petroleum & Natural Gas",
    officialPortal: "PMUY / OMC Portals",
    officialUrl: "https://www.pmuy.gov.in/",
    eligibility: [
      "Active PMUY beneficiary",
      "Aadhaar linked with LPG consumer number",
      "DBT-enabled bank account",
    ],
    documentsRequired: ["PMUY SV number", "Aadhaar", "Bank account", "LPG ID"],
    fee: 0,
    feeNote: "Subsidy credited to bank per refill (varies by market price).",
    processingTime: "2 to 5 days per refill (DBT)",
    howToApply: [
      "Confirm PMUY beneficiary status and Aadhaar linking.",
      "Visit OMC portal (IOC/HPCL/BPCL) or distributor.",
      "Verify LPG ID and DBT status.",
      "Purchase refill at non-subsidised rate.",
      "Subsidy credited to bank within 2-5 days.",
    ],
    serviceCharge: 50,
    popularity: 80,
    tags: ["pmgky", "garib kalyan", "lpg subsidy", "ujjwala", "cooking fuel"],
    online: true,
  },
];
