import type { GovernmentService } from "../types";

export const womenChild: GovernmentService[] = [
  {
    id: "ssy-account-transfer-closure",
    slug: "ssy-account-transfer-closure",
    name: "Sukanya Samriddhi Yojana Account Transfer / Closure",
    category: "women-child",
    subcategory: "Girl Child Savings",
    summary: "Transfer SSY account to a new post office / bank, or close prematurely on maturity / marriage.",
    description:
      "Sukanya Samriddhi Yojana (SSY) is a small savings scheme for girl children under 10, opened at post offices or designated banks. An existing SSY account can be transferred from one post office/bank to another when the family relocates. Premature closure is normally allowed only on the girl's marriage after age 18, or for higher education with conditions. Normal maturity is 21 years from opening.",
    ministry: "Ministry of Finance (Department of Posts)",
    officialPortal: "India Post — Sukanya Samriddhi Yojana",
    officialUrl: "https://www.indiapost.gov.in/",
    eligibility: [
      "Existing SSY account holder (girl child under 21 years)",
      "For transfer: parent / guardian applies with reason for transfer",
      "For closure on marriage: girl has attained 18 years and marriage is being solemnised",
      "For closure for higher education: girl has attained 18 years and is in 10th standard or above",
    ],
    documentsRequired: [
      "SSY passbook",
      "Birth certificate of the girl child",
      "Aadhaar card of parent / guardian and girl child",
      "For marriage closure: marriage invitation / affidavit",
      "For education closure: admission proof / fee receipt",
      "Transfer application form",
    ],
    fee: 0,
    feeNote: "Free for transfer. Closure proceeds credited to account.",
    processingTime: "7-15 days for transfer; 7-30 days for closure",
    howToApply: [
      "Visit the current post office / bank where the SSY account is held.",
      "Submit the SSY transfer / closure application form with the passbook.",
      "Attach Aadhaar, birth certificate of the girl, and supporting documents (marriage/education proof).",
      "For transfer, the receiving office opens a new account with same number and balance; for closure, proceeds are credited to the bank account.",
      "Updated passbook or closure receipt is provided after processing.",
    ],
    serviceCharge: 80,
    popularity: 70,
    tags: ["ssy", "sukanya samriddhi", "girl child", "transfer", "closure", "post office"],
    online: false,
  },
  {
    id: "beti-bachao-beti-padhao-cac-registration",
    slug: "beti-bachao-beti-padhao-cac-registration",
    name: "Beti Bachao Beti Padhao — CAC Registration & Awareness",
    category: "women-child",
    subcategory: "Awareness & Empowerment",
    summary: "Register district-level CACs (Cumulative Action Committees) and access BBBP awareness campaigns.",
    description:
      "Beti Bachao Beti Padhao (BBBP) is a flagship awareness campaign of the Ministry of Women & Child Development to address the declining child sex ratio and promote education of the girl child. District-level Cumulative Action Committees (CACs) implement the scheme at the ground level. The scheme focuses on awareness, advocacy and capacity building, with disbursements to districts based on performance. A CMO/DM chairs the CAC.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "Beti Bachao Beti Padhao",
    officialUrl: "https://wcd.nic.in/bbbp-schemes",
    eligibility: [
      "Districts with low child sex ratio (CSR < 918)",
      "Or any district implementing BBBP activities",
      "NGOs / educational institutions / Self Help Groups can partner with CAC",
    ],
    documentsRequired: [
      "Society / Trust registration certificate (for NGOs)",
      "PAN card of the organisation",
      "Audited financial statements of last 3 years",
      "Activity proposal and budget",
      "Aadhaar of authorised signatory",
      "CAC membership form (for individual members)",
    ],
    fee: 0,
    feeNote: "Free to register. Funding via district-level BBBP budget.",
    processingTime: "30-60 days for CAC partnership approval",
    howToApply: [
      "Visit the District Magistrate / District WCD Office for CAC membership or NGO partnership.",
      "Submit the proposal for BBBP activities (workshops, awareness drives, scholarship, etc.).",
      "Attach organisation registration, PAN, audit reports and Aadhaar of signatory.",
      "District CAC reviews and approves; funding released via PFMS.",
      "Implement activities and submit utilisation certificate; report outcomes quarterly.",
    ],
    serviceCharge: 90,
    popularity: 60,
    tags: ["bbb", "beti bachao", "beti padhao", "cac", "awareness", "girl child"],
    online: false,
  },
  {
    id: "pm-matru-vandana-yojana-application",
    slug: "pm-matru-vandana-yojana-application",
    name: "PM Matru Vandana Yojana (PMMVY) Application",
    category: "women-child",
    subcategory: "Maternity Benefit",
    summary: "Cash benefit of ₹5,000 to pregnant and lactating mothers for the first living child.",
    description:
      "Pradhan Mantri Matru Vandana Yojana (PMMVY) is a centrally sponsored maternity benefit scheme providing a cash incentive of ₹5,000 to pregnant and lactating mothers (18+) for the birth of the first living child, paid in three instalments. The benefit is in addition to the Janani Suraksha Yojana wage compensation. Application is filed at the Anganwadi Centre or through the PMMVY-CAS mobile app.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "PMMVY — Pradhan Mantri Matru Vandana Yojana",
    officialUrl: "https://wcd.nic.in/schemes/pradhan-mantri-matru-vandana-yojana",
    eligibility: [
      "Pregnant and lactating mother aged 19+ years",
      "First living child (since 2021 amendment: second child if girl, in some states)",
      "Aadhaar and bank/post office account mandatory",
      "Not availed similar benefit from employer (Central/State govt employees not eligible)",
    ],
    documentsRequired: [
      "Aadhaar card of mother",
      "MCP (Mother and Child Protection) card",
      "Bank / post office account details",
      "Husband's Aadhaar (optional)",
      "Anganwadi registration slip",
      "Photograph of mother",
    ],
    fee: 0,
    feeNote: "Free. ₹5,000 cash benefit in 3 instalments via DBT.",
    processingTime: "30-60 days per instalment",
    howToApply: [
      "Register at the local Anganwadi Centre with Aadhaar, MCP card and bank passbook.",
      "Fill the PMMVY Form A (registration) at the Anganwadi or via PMMVY-CAS app.",
      "Submit Form A — first instalment ₹1,000 on pregnancy registration within 150 days of LMP.",
      "Submit Form B — second instalment ₹2,000 after at least one ANC check-up in 6th month.",
      "Submit Form C — third instalment ₹2,000 after child birth is registered and first immunisation done.",
    ],
    serviceCharge: 80,
    popularity: 78,
    tags: ["pmmvy", "maternity", "pregnancy", "women", "dbt", "wcd"],
    online: true,
  },
  {
    id: "pmvy-second-child-benefit",
    slug: "pmvy-second-child-benefit",
    name: "PMMVY Second Child Benefit (Girl Child)",
    category: "women-child",
    subcategory: "Maternity Benefit",
    summary: "Additional ₹6,000 cash benefit for second child if it is a girl, under revised PMMVY norms.",
    description:
      "Under the revised PMMVY guidelines (effective 2021-22 in select states), a mother who has received PMMVY benefit for the first child becomes eligible for an additional cash incentive of ₹6,000 for the second child, provided the second child is a girl. The objective is to promote girl child birth and address the skewed sex ratio. Application is filed at the Anganwadi Centre.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "PMMVY — Pradhan Mantri Matru Vandana Yojana",
    officialUrl: "https://wcd.nic.in/schemes/pradhan-mantri-matru-vandana-yojana",
    eligibility: [
      "Mother who has received PMMVY first-child benefit",
      "Second child born is a girl",
      "Birth registered within 1 year",
      "Aadhaar and bank account active",
    ],
    documentsRequired: [
      "Aadhaar card of mother",
      "Birth certificate of second child showing girl gender",
      "MCP card",
      "First child's birth certificate (showing prior PMMVY benefit)",
      "Bank passbook copy",
      "Anganwadi registration",
    ],
    fee: 0,
    feeNote: "Free. ₹6,000 cash benefit via DBT.",
    processingTime: "30-60 days",
    howToApply: [
      "Register the second childbirth at the Anganwadi Centre within 1 year of birth.",
      "Fill PMMVY Form for second child benefit with birth certificate showing girl gender.",
      "Attach Aadhaar of mother, MCP card, first child's birth certificate, bank passbook.",
      "Submit to Anganwadi worker; verification by Supervisor and CDPO.",
      "On approval, ₹6,000 is credited to the mother's bank account via DBT.",
    ],
    serviceCharge: 80,
    popularity: 60,
    tags: ["pmmvy", "second child", "girl child", "maternity", "dbt", "wcd"],
    online: true,
  },
  {
    id: "mahila-shakti-kendra",
    slug: "mahila-shakti-kendra",
    name: "Mahila Shakti Kendra (MSK)",
    category: "women-child",
    subcategory: "Women Empowerment",
    summary: "Block-level convergence centre for women's welfare schemes, awareness and student volunteer engagement.",
    description:
      "Mahila Shakti Kendra (MSK) is a centrally sponsored scheme of the Ministry of Women & Child Development, set up at block level to empower rural women through awareness, convergence of welfare schemes and student volunteer engagement. District and State Level Centres for Women (SLCW) provide domain support. College-going girl students are engaged as volunteers for community outreach.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "Mahila Shakti Kendra",
    officialUrl: "https://wcd.nic.in/schemes",
    eligibility: [
      "Women in rural areas of implementing blocks",
      "College-going girls (18-25 years) for volunteer engagement",
      "Block / District administration for MSK setup",
    ],
    documentsRequired: [
      "For volunteers: College ID and Aadhaar",
      "For MSK setup: Block/District administration proposal",
      "For beneficiary registration: Aadhaar and family details",
      "Bank passbook copy",
    ],
    fee: 0,
    feeNote: "Free. Volunteers receive an honorarium (₹1,000/month).",
    processingTime: "30-45 days for registration",
    howToApply: [
      "Approach the Block MSK or District Level Centre for Women (DLCW) with Aadhaar and family details.",
      "Register as a beneficiary for awareness about schemes (PMMVY, BBBP, BJG, OSC, WHL).",
      "For volunteer engagement, college girls apply through their college NSS/NCC cell or DLCW.",
      "Selected volunteers undergo training and conduct community outreach.",
      "Beneficiaries get convergence support to access schemes from various departments.",
    ],
    serviceCharge: 60,
    popularity: 50,
    tags: ["mahila shakti kendra", "women empowerment", "volunteer", "wcd", "rural"],
    online: false,
  },
  {
    id: "step-support-training-employment-programme",
    slug: "step-support-training-employment-programme",
    name: "STEP — Support to Training & Employment Programme for Women",
    category: "women-child",
    subcategory: "Women Empowerment",
    summary: "Government grant for skill training and employment of women in sectors like agriculture, handlooms, IT.",
    description:
      "STEP (Support to Training and Employment Programme for Women) is a Central Sector scheme of the Ministry of Women & Child Development that provides grants to NGOs and institutions for imparting skill training to women aged 16+ in sectors such as agriculture, horticulture, handlooms, handicrafts, computer applications, electronics and home-based work. Training includes a stipend and placement support.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "Ministry of Women & Child Development — STEP",
    officialUrl: "https://wcd.nic.in/schemes",
    eligibility: [
      "Women aged 16+ years",
      "Below poverty line or from marginalised sections",
      "Not availed similar training under any other government scheme",
      "Implementing agency: registered NGO/institution with 3 years' experience",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Age proof",
      "Income certificate / BPL certificate",
      "Educational qualification certificates",
      "Bank passbook copy",
      "Photograph",
    ],
    fee: 0,
    feeNote: "Free training. Stipend ₹500-₹1,000/month during training.",
    processingTime: "30-60 days for selection",
    howToApply: [
      "Identify the STEP-implementing NGO/institution in your district (list available at WCD website).",
      "Approach the NGO with Aadhaar, age proof, income certificate and educational certificates.",
      "Fill the trainee registration form; the NGO conducts screening.",
      "On selection, undergo 6-12 months training; receive a monthly stipend.",
      "On completion, receive a certificate and placement support from the NGO.",
    ],
    serviceCharge: 70,
    popularity: 45,
    tags: ["step", "skill training", "employment", "women", "wcd", "ngo"],
    online: false,
  },
  {
    id: "widow-remarriage-scheme-state",
    slug: "widow-remarriage-scheme-state",
    name: "Widow Remarriage Scheme (State)",
    category: "women-child",
    subcategory: "Widow Welfare",
    summary: "Cash incentive for remarriage of widows, ranging from ₹25,000 to ₹2,00,000 depending on state.",
    description:
      "Several state governments offer a cash incentive to widows who remarry, to encourage social rehabilitation and reduce stigma. Examples include West Bengal (₹30,000), Andhra Pradesh (₹50,000), Haryana (₹51,000), Telangana (₹1,00,000) and Tamil Nadu (₹50,000+ gold coin). The application is filed at the District Social Welfare Office within a specified period after marriage registration.",
    ministry: "State Department of Social Welfare",
    officialPortal: "State Social Welfare Portal",
    officialUrl: "https://wcd.nic.in/",
    eligibility: [
      "Widow woman of any age who has remarried",
      "Resident of the implementing state",
      "Marriage registered under the Hindu Marriage Act or Special Marriage Act",
      "Application within 1-2 years of remarriage (state-specific)",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Death certificate of first husband",
      "Marriage registration certificate of remarriage",
      "Age proof",
      "Residence proof of the state",
      "Bank passbook copy",
      "Husband's Aadhaar (new spouse)",
    ],
    fee: 0,
    feeNote: "Free to apply. Cash incentive credited via DBT.",
    processingTime: "60-90 days",
    howToApply: [
      "Register the remarriage under the Hindu Marriage Act / Special Marriage Act at the Sub-Registrar office.",
      "Approach the District Social Welfare Office with the application form.",
      "Attach Aadhaar, first husband's death certificate, remarriage certificate and bank passbook.",
      "Submit; verification by Social Welfare Officer and Gram Panchayat/Municipality.",
      "On approval, the cash incentive is credited via DBT to the widow's bank account.",
    ],
    serviceCharge: 90,
    popularity: 40,
    tags: ["widow", "remarriage", "state scheme", "social welfare", "dbt"],
    online: false,
  },
  {
    id: "working-women-hostel-registration",
    slug: "working-women-hostel-registration",
    name: "Working Women Hostel Registration",
    category: "women-child",
    subcategory: "Working Women Support",
    summary: "Apply for accommodation in Government-subsidised Working Women Hostels with daycare for children.",
    description:
      "The Working Women Hostel (WWH) scheme of the Ministry of Women & Child Development provides safe, affordable accommodation with daycare facilities for working women (single, married, widowed, divorced, separated) and their children up to 6-8 years of age. Hostels are run by NGOs, universities, PSUs and state governments with Central assistance. Rent is subsidised based on income.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "Working Women Hostel Scheme",
    officialUrl: "https://wwh-wcd.nic.in/",
    eligibility: [
      "Working woman aged 18+ years (single, married, widowed, divorced, separated)",
      "Monthly income up to ₹50,000 in cities with population > 12.5 lakh (varies by city)",
      "Trainees and students with valid proof",
      "Children up to 6 years for daycare (boys); up to 8 years in hostel",
    ],
    documentsRequired: [
      "Aadhaar card",
      "Age proof",
      "Employment proof / offer letter / payslip",
      "Income certificate / latest payslip",
      "Residence proof (previous)",
      "Police verification certificate",
      "Medical fitness certificate",
      "Recent photograph",
    ],
    fee: 0,
    feeNote: "Security deposit + monthly rent based on income slab (₹300-₹3,500/month).",
    processingTime: "15-30 days",
    howToApply: [
      "Identify the nearest Working Women Hostel via wwh-wcd.nic.in or District WCD office.",
      "Obtain the WWH admission form from the hostel office.",
      "Fill in personal, employment, income details; attach Aadhaar, payslip, police verification.",
      "Submit the form with security deposit; hostel committee conducts interview/verification.",
      "On selection, allotment letter is issued; monthly rent is deducted via bank mandate.",
    ],
    serviceCharge: 70,
    popularity: 55,
    tags: ["working women hostel", "wwh", "women", "hostel", "daycare", "wcd"],
    online: false,
  },
  {
    id: "one-stop-centre-sakhi-service",
    slug: "one-stop-centre-sakhi-service",
    name: "One Stop Centre (Sakhi) — OSC Service",
    category: "women-child",
    subcategory: "Women in Distress",
    summary: "Integrated support (medical, legal, police, counselling, shelter) for women affected by violence.",
    description:
      "One Stop Centres (OSCs), also called Sakhi Centres, are set up by the Ministry of Women & Child Development across all districts to support women affected by violence — in public or private spaces, family, community, or workplace. OSCs provide integrated services including medical aid, police assistance, legal counselling, psycho-social counselling, video conferencing with courts, and short-stay shelter (up to 5 days). Services are free.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "One Stop Centre Scheme",
    officialUrl: "https://wcd.nic.in/one-stop-centre-scheme",
    eligibility: [
      "Any woman facing violence (domestic, sexual, workplace, cyber, etc.)",
      "Girl children below 18 (with guardian or referred through CWC)",
      "No income / residence restriction",
      "Services available 24x7",
    ],
    documentsRequired: [
      "Aadhaar card (if available; not mandatory in emergencies)",
      "Photo identification (any government ID)",
      "Medical report / FIR copy (if filed)",
      "No documentation needed for emergency shelter",
    ],
    fee: 0,
    feeNote: "All services completely free. 24x7 helpline linked to 181.",
    processingTime: "Immediate assistance",
    howToApply: [
      "Walk into the nearest One Stop Centre (location at District Hospital / WCD office) or call 181.",
      "Centre staff (Centre Administrator, case worker, medical officer) receives the woman.",
      "Immediate medical aid, police intimation (if FIR to be filed), and psycho-social counselling.",
      "Short-stay shelter (up to 5 days) provided if needed; video conferencing facility for court hearings.",
      "Follow-up services and referral to legal services authority, shelter home, or skill training.",
    ],
    serviceCharge: 50,
    popularity: 70,
    tags: ["one stop centre", "osc", "sakhi", "women distress", "violence", "wcd"],
    online: false,
  },
  {
    id: "women-helpline-181-osc-referral",
    slug: "women-helpline-181-osc-referral",
    name: "Women Helpline 181 — OSC / Scheme Referral",
    category: "women-child",
    subcategory: "Women in Distress",
    summary: "Toll-free 24x7 helpline for women in distress, providing referral to OSC, police, legal aid and schemes.",
    description:
      "The Women Helpline (WHL) 181 is a 24x7 toll-free telephonic helpline for women in distress, linked to One Stop Centres (OSC) and the police. Operated by the Ministry of Women & Child Development through state-level empanelled agencies, it provides emergency response, information on women welfare schemes, and referral to OSCs, police, legal services, medical services and shelter homes. The service is available in multiple Indian languages.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "Women Helpline 181",
    officialUrl: "https://wcd.nic.in/women-helpline-181",
    eligibility: [
      "Any woman in distress or someone calling on her behalf",
      "Available across all states and UTs",
      "Available 24x7",
    ],
    documentsRequired: [
      "No documents required for distress calls",
      "Location details of the caller (for emergency response)",
      "Optional: caller's Aadhaar / mobile number for follow-up",
    ],
    fee: 0,
    feeNote: "Toll-free from any mobile or landline in India.",
    processingTime: "Immediate response",
    howToApply: [
      "Dial 181 from any mobile or landline (toll-free) — 24x7.",
      "Brief the counsellor on the type of distress (violence, abuse, harassment, scheme info).",
      "Counsellor dispatches emergency response (police / OSC / ambulance) as needed.",
      "Caller receives information on schemes and referral to nearest OSC, legal services or shelter.",
      "Follow-up call within 24-48 hours to confirm action and offer further support.",
    ],
    serviceCharge: 25,
    popularity: 75,
    tags: ["women helpline", "181", "osc referral", "distress", "wcd", "toll-free"],
    online: false,
  },
  {
    id: "icds-anganwadi-enrollment",
    slug: "icds-anganwadi-enrollment",
    name: "ICDS Anganwadi Enrollment (Children 0-6, Pregnant & Lactating Mothers)",
    category: "women-child",
    subcategory: "Child Development",
    summary: "Enroll children 0-6 years and pregnant/lactating mothers at Anganwadi for nutrition, health & pre-school.",
    description:
      "The Integrated Child Development Services (ICDS) scheme provides supplementary nutrition, immunisation, health check-up, referral services, pre-school non-formal education, and nutrition & health education through Anganwadi Centres. Beneficiaries are children aged 0-6 years, pregnant women, and lactating mothers. Enrollment is free at the nearest Anganwadi Centre in the village or urban ward.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "ICDS — Anganwadi Services",
    officialUrl: "https://icds-wcd.nic.in/",
    eligibility: [
      "Children aged 6 months to 6 years",
      "Pregnant women",
      "Lactating mothers (up to child's age 6 months)",
      "Adolescent girls 11-14 years (under Scheme for Adolescent Girls in some states)",
    ],
    documentsRequired: [
      "Aadhaar card of child and mother (if available)",
      "Birth certificate of child (for age verification)",
      "Mother's MCP card",
      "Residence proof (ration card)",
      "BPL / Antyodaya card (if applicable)",
      "Photograph of mother and child",
    ],
    fee: 0,
    feeNote: "Free enrollment. Take-home ration and hot cooked meal provided.",
    processingTime: "Same-day enrollment",
    howToApply: [
      "Identify the nearest Anganwadi Centre in your village / urban ward.",
      "Visit the Anganwadi with the child and mother's MCP card, Aadhaar and birth certificate.",
      "Fill the ICDS enrollment form with child and family details.",
      "Anganwadi worker enters the data into the POSHAN Tracker / RRS portal.",
      "Beneficiary begins receiving supplementary nutrition, immunisation and pre-school education.",
    ],
    serviceCharge: 40,
    popularity: 75,
    tags: ["icds", "anganwadi", "child nutrition", "pregnant women", "poshan", "wcd"],
    online: false,
  },
  {
    id: "poshan-abhiyan-tracking",
    slug: "poshan-abhiyan-tracking",
    name: "POSHAN Abhiyan Tracking & Beneficiary Status",
    category: "women-child",
    subcategory: "Child Development",
    summary: "Track ICDS services, nutrition status and POSHAN Abhiyan benefits via the POSHAN Tracker app.",
    description:
      "POSHAN Abhiyan (National Nutrition Mission) is the flagship programme for improving nutritional outcomes for children, pregnant women and lactating mothers. The POSHAN Tracker mobile app launched in 2021 captures real-time data on beneficiary enrollment, growth measurement, supplementary nutrition distribution, and Anganwadi infrastructure. Beneficiaries and AWCs can track service delivery through the app.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "POSHAN Abhiyan",
    officialUrl: "https://poshanabhiyaan.gov.in/",
    eligibility: [
      "All enrolled ICDS beneficiaries (children 0-6, pregnant/lactating mothers)",
      "Anganwadi workers and supervisors for data entry",
      "CDPOs and District Program Officers for monitoring",
    ],
    documentsRequired: [
      "Aadhaar card of beneficiary",
      "ICDS enrollment ID / Anganwadi ID",
      "MCP card",
      "Mobile number registered with Anganwadi",
    ],
    fee: 0,
    feeNote: "Free app and service.",
    processingTime: "Real-time data",
    howToApply: [
      "Download the POSHAN Tracker app from Google Play Store.",
      "Login as a beneficiary with mobile number OTP (or Anganwadi worker with employee ID).",
      "Enter beneficiary ID / Aadhaar to fetch enrollment details.",
      "View service delivery status — supplementary nutrition, growth monitoring, immunisation, ANC check-ups.",
      "For grievance, raise a ticket through the app or call the WCD toll-free number 14416.",
    ],
    serviceCharge: 35,
    popularity: 65,
    tags: ["poshan", "nutrition", "icds", "anganwadi", "tracker", "wcd"],
    online: true,
  },
  {
    id: "cara-adoption-domestic",
    slug: "cara-adoption-domestic",
    name: "CARA Adoption — Domestic (Indian Parents)",
    category: "women-child",
    subcategory: "Adoption",
    summary: "Adopt a child in India through CARA-regulated process; matching via Central Adoption Resource Authority.",
    description:
      "The Central Adoption Resource Authority (CARA), a statutory body under the Ministry of Women & Child Development, regulates domestic and inter-country adoption of orphaned, abandoned and surrendered children. Prospective Adoptive Parents (PAPs) register on the CARA portal (CARINGS), upload documents, and are matched with a child through seniority-based referral. The process takes 1-3 years depending on preference and child availability.",
    ministry: "Ministry of Women & Child Development (CARA)",
    officialPortal: "CARA — Central Adoption Resource Authority",
    officialUrl: "https://cara.wcd.gov.in/",
    eligibility: [
      "Indian citizen, NRI, OCI or foreign national (married couples, single persons)",
      "Couple: 2 years of stable marriage; both 25-50 years (one ≤ 55)",
      "Single: aged 25-50 years (single male cannot adopt a girl child)",
      "Age difference between PAP and child should be ≥ 25 years",
      "Combined income ≥ ₹3,00,000 per annum; net worth ≥ ₹10,00,000",
      "Medical fitness certificate",
    ],
    documentsRequired: [
      "Aadhaar card of both PAPs",
      "PAN card",
      "Marriage certificate",
      "Medical fitness certificate from a Government hospital",
      "Income proof (last 3 years ITR, salary slips)",
      "Bank statement (last 1 year)",
      "Property / asset declaration",
      "Two reference letters",
      "Recent photographs",
    ],
    fee: 0,
    feeNote: "₹1,000 registration; ₹40,000 CARA fee on referral (adoption agency charges extra).",
    processingTime: "1-3 years for matching + 6-12 months legal process",
    howToApply: [
      "Register on the CARA portal (carings.wcd.gov.in) with Aadhaar OTP.",
      "Complete online registration; upload documents and pay ₹1,000 fee.",
      "Home Study Report (HSR) by SAA — physical visit and interview within 30 days.",
      "PAPs appear in the seniority list; child referral shared as per availability.",
      "PAPs reserve the child within 48 hours; acceptance → foster care → court order → adoption deed.",
    ],
    serviceCharge: 150,
    popularity: 55,
    tags: ["cara", "adoption", "domestic", "child", "wcd"],
    online: true,
  },
  {
    id: "cara-adoption-intercountry",
    slug: "cara-adoption-intercountry",
    name: "CARA Adoption — Inter-Country (NRI / OCI / Foreign)",
    category: "women-child",
    subcategory: "Adoption",
    summary: "Adopt an Indian child from abroad as NRI / OCI / foreign national via Hague-accredited process.",
    description:
      "Inter-country adoption of Indian children is regulated by CARA under the Hague Convention on Inter-Country Adoption, 1993. NRI / OCI PAPs and foreign nationals apply through their country's Central Authority (CA) or Authorised Foreign Adoption Agency (AFAA), which forwards the dossier to CARA. NRI/OCI PAPs are given priority in referral over non-Indian foreigners. The process is governed by the JJ Act 2015 and Adoption Regulations 2017.",
    ministry: "Ministry of Women & Child Development (CARA)",
    officialPortal: "CARA — Inter-Country Adoption",
    officialUrl: "https://cara.wcd.gov.in/",
    eligibility: [
      "NRI / OCI / Foreign national",
      "Couple: 2 years stable marriage; both 25-50 years (one ≤ 55)",
      "Single: 25-50 years (single male cannot adopt a girl)",
      "Resident in a Hague Convention signatory country",
      "Income and medical fitness as per CARA guidelines",
    ],
    documentsRequired: [
      "Passport and OCI/PIO card (for NRI/OCI)",
      "Aadhaar if Indian-origin",
      "Home Study Report from CA / AFAA in the resident country",
      "Medical fitness certificate",
      "Financial proof (income, bank statement, tax returns)",
      "Police clearance certificate from resident country",
      "Marriage certificate",
      "No-objection from CA/AFAA",
      "Photographs",
    ],
    fee: 0,
    feeNote: "CARA fee $5,000 (NRI/OCI) / $6,000 (foreigners); plus agency and legal charges.",
    processingTime: "1.5-3 years",
    howToApply: [
      "Approach the Central Authority / Authorised Foreign Adoption Agency in your resident country.",
      "Submit dossier (HSR, medical, financials, PCC); CA/AFAA forwards to CARA via the Hague channel.",
      "CARA issues No Objection Certificate (NOC) and refers a child through CARINGS portal.",
      "PAPs travel to India for foster care; court issues adoption order.",
      "Post-adoption, CARA issues Conformity Certificate; child's passport and visa processed for travel.",
    ],
    serviceCharge: 150,
    popularity: 35,
    tags: ["cara", "intercountry adoption", "nri", "oci", "foreign", "hague", "wcd"],
    online: true,
  },
  {
    id: "child-helpline-1098-rescue-restoration",
    slug: "child-helpline-1098-rescue-restoration",
    name: "CHILDLINE 1098 — Rescue & Restoration Service",
    category: "women-child",
    subcategory: "Child Protection",
    summary: "24x7 rescue, shelter and restoration service for children in difficult circumstances via CHILDLINE 1098.",
    description:
      "CHILDLINE 1098 is India's first 24-hour emergency phone outreach service for children in need of care and protection, operated by the CHILDLINE India Foundation under the Ministry of Women & Child Development. The helpline receives calls regarding missing children, child labour, abuse, runaway children, school dropouts, and child marriage. Rescue teams coordinate with police, CWC, DCPU and shelter homes for immediate intervention and restoration.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "CHILDLINE India Foundation",
    officialUrl: "https://www.childlineindia.org.in/",
    eligibility: [
      "Any child (0-18 years) in difficult circumstances",
      "Or an adult reporting on behalf of a child",
      "Available 24x7 across India (in 600+ cities/districts)",
    ],
    documentsRequired: [
      "No documents required for emergency calls",
      "Child's Aadhaar (if available) for restoration",
      "CWC order for shelter placement",
    ],
    fee: 0,
    feeNote: "Free service. All rescue and shelter services are free.",
    processingTime: "Immediate intervention",
    howToApply: [
      "Dial 1098 from any mobile or landline (toll-free) — available 24x7.",
      "Brief the CHILDLINE team on the child's situation (abuse, missing, child labour, etc.).",
      "Rescue team dispatches to the location; coordinates with police if needed.",
      "Child is produced before Child Welfare Committee (CWC) within 24 hours.",
      "CWC orders shelter placement or family restoration; follow-up for rehabilitation.",
    ],
    serviceCharge: 25,
    popularity: 70,
    tags: ["childline", "1098", "rescue", "child protection", "cwc", "wcd"],
    online: false,
  },
  {
    id: "balika-samriddhi-yojana",
    slug: "balika-samriddhi-yojana",
    name: "Balika Samriddhi Yojana (BSY)",
    category: "women-child",
    subcategory: "Girl Child Welfare",
    summary: "Post-birth cash grant + annual scholarships to girls born in BPL families after 15 August 1997.",
    description:
      "Balika Samriddhi Yojana (BSY), launched by the Government of India in 1997, aims at changing negative community attitudes towards the girl child. Under BSY, a post-birth grant of ₹2,500 is given to a mother of a girl child born in a BPL family after 15 August 1997. The girl receives annual scholarships from Class I to Class X (₹300-₹1,000), credited as a fixed deposit, with maturity amount on attaining 18 years and completion of Class X.",
    ministry: "Ministry of Women & Child Development",
    officialPortal: "Balika Samriddhi Yojana",
    officialUrl: "https://wcd.nic.in/schemes/balika-samriddhi-yojana",
    eligibility: [
      "Girl child born in a BPL family on or after 15 August 1997",
      "Both rural and urban BPL families",
      "Girl child continues schooling",
      "Maximum two girls per family",
    ],
    documentsRequired: [
      "Birth certificate of the girl child",
      "BPL ration card",
      "Aadhaar card of mother and girl child",
      "Mother's MCP card",
      "Bank passbook copy of mother/girl child",
      "School enrollment proof (for scholarship)",
    ],
    fee: 0,
    feeNote: "Free. ₹2,500 birth grant + annual scholarships ₹300-₹1,000.",
    processingTime: "30-60 days for birth grant; yearly for scholarships",
    howToApply: [
      "Approach the Anganwadi worker or Municipality office within 1 year of the girl's birth.",
      "Submit BSY application form with birth certificate, BPL ration card and Aadhaar.",
      "Verification by Anganwadi worker and Gram Panchayat / Municipality.",
      "On approval, ₹2,500 birth grant credited to mother's bank account.",
      "Annual scholarship credited when girl child enrolls in school; renew yearly with school certificate.",
    ],
    serviceCharge: 70,
    popularity: 50,
    tags: ["balika samriddhi", "bsy", "girl child", "bpl", "scholarship", "wcd"],
    online: false,
  },
];
